### ISSUE TITLE
arg_max documentation should mention v2 vs v3 null handling differences

### ISSUE THREAD

**Issue by MisterFlask** [MicrosoftDocs/dataexplorer-docs#1001]
In V2 of the kusto engine, this documentation is incorrect (or at least incomplete).  Specifically, if the value being maximized is ever null in the input set, then *every* column not in the summarized-by set of columns gets converted to null in the result set.

The documentation should reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b51337-2793-f005-6f37-31f383ff7f02
* Version Independent ID: 4659f959-2e71-f6fb-5e2c-bba6271dd2cd
* Content: [arg_max() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-max-aggfunction)
* Content Source: [data-explorer/kusto/query/arg-max-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/arg-max-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@MisterFlask Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by ShaikMaheer-MSFT** [comment]
@orspod could you please validate feedback and enhance document as appropriate.

**Comment by shsagir** [comment]
@MisterFlask Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

**Comment by shsagir** [comment]
@MisterFlask Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
