### ISSUE TITLE
Unclear about what if Right-hand-side (RHS) of `has` operator is not a pure alphanumeric word

### ISSUE THREAD

**Issue by jiasli** [MicrosoftDocs/dataexplorer-docs#1005]
I checked these 2 docs but it is unclear what will happen if Right-hand-side (RHS) of `has` operator is not a pure alphanumeric word:

- https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators
- https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/has-operator

```
print("https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/test.rg000001?api-version=2021-04-01" has "resourcegroups/test.rg000001")
true

print("https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/test.rg000001?api-version=2021-04-01" has "/resourcegroups/test.rg000001?")
true

print("North America" has "North America")
true
```

The tests show that if Right-hand-side (RHS) of `has` operator is not a pure alphanumeric word and contains several parts like `resourcegroups/test.rg000001` or `/resourcegroups/test.rg000001?`, the `has` operator can still do a word match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54a3e89-5278-6712-42b8-146c4f6c57dd
* Version Independent ID: 6d773e2a-596d-5c8f-28d1-9b61389f1089
* Content: [The case-insensitive has string operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/has-operator)
* Content Source: [data-explorer/kusto/query/has-operator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/has-operator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by KranthiPakala-MSFT** [comment]
We have assigned the issue to the content author. They will evaluate and update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
@orspod - Could you please help loop relevant product owner who can clarify on this ask. Thank you

**Comment by shsagir** [comment]
@jiasli Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

**Comment by shsagir** [comment]
@jiasli Thanks again for your feedback. The RHS can be *any* scalar or literal expression as mentioned in the arguments section. I'm closing this issue, but we'll continue to monitor if there is a need to update the descriptions.

#please-close
