### ISSUE TITLE
IngestionMapping might not exist

### ISSUE THREAD

**Issue by zzgzy** [MicrosoftDocs/dataexplorer-docs#101]
It seems like `IngestionMapping` is no longer a valid property. What would be the new way to define `IngestionMappingReference`? Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a2c619-a306-8f10-0106-5a6a34f6ef9f
* Version Independent ID: a4825509-e03c-6825-9d6e-37da0d08bd89
* Content: [Data ingestion with Kusto.Ingest library - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-queued-ingest-sample)
* Content Source: [data-explorer/kusto/api/netfx/kusto-ingest-queued-ingest-sample.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/netfx/kusto-ingest-queued-ingest-sample.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by zzgzy** [comment]
Resolved by replacing

```
ingestProps.IngestionMapping = new IngestionMapping()
{
  IngestionMappingReference = mappingName
};
```

with    `ingestProps.SetAppropriateMappingReference(mappingName, DataSourceFormat.json);`

**Comment by KranthiPakala-MSFT** [comment]
@zzgzy Thanks for sharing the resolution details here. It will be beneficial for others who reads this thread.
