### ISSUE TITLE
Make the warning on column type rename more clear

### ISSUE THREAD

**Issue by baselsalam** [MicrosoftDocs/dataexplorer-docs#1010]
The wording here 'When altering the data type of a column, any pre-existing data in that column which is not of the new data type will be ignored in future queries and will be replaced by a null value. ' is very misleading.

It should simply state that any pre-existing data in that column will be replaced by a null value.
"any pre-existing data in that column which is not of the new data type" could be misconstrued as to mean that if pre-existing data can casts to the new type itll be preserved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d59e3acb-91e5-9a8d-bbdb-e51d7f26c342
* Version Independent ID: 96090d79-2742-9b59-399f-96b7f7cab792
* Content: [.alter column - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-column)
* Content Source: [data-explorer/kusto/management/alter-column.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/alter-column.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@baselsalam Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@baselsalam Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

**Comment by AnnuKumari-MSFT** [comment]
Hi @orspod / @shsagir
Requesting to validate customer feedback and update the document accordingly as appropriate. Thankyou

**Comment by shsagir** [comment]
@baselsalam Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
