### ISSUE TITLE
No longer exists

### ISSUE THREAD

**Issue by ajs794** [MicrosoftDocs/dataexplorer-docs#1014]
Page is no longer relevant, it appears the "real" function does not exists.

![image](https://user-images.githubusercontent.com/78363586/151973280-52c9a3df-5d85-4916-bfa5-dc902d303ce0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a093fa47-a7fe-9f2a-3069-c1a87edcf517
* Version Independent ID: e13c2621-b98e-be79-3e11-337af8050b6f
* Content: [The real data type - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/real)
* Content Source: [data-explorer/kusto/query/scalar-data-types/real.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/scalar-data-types/real.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by shsagir** [comment]
@ajs794 Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ajs794 After investigating with the product team, the real type does exist and shows up in IntelliSense wherever an expression is expected. For example:

![image](https://user-images.githubusercontent.com/51323195/152301671-82a81e44-0531-4977-b6ac-09ddd67958bb.png)

Thanks again for contacting us with feedback. Since there is no change required, I am closing this issue.

#please-close
