### ISSUE TITLE
Client-side export is defined but how do you learn how to do it?

### ISSUE THREAD

**Issue by edburns** [MicrosoftDocs/dataexplorer-docs#102]
I would like to know how to perform client side export as defined above, however, none of the linked documents cover that topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad10bb6-4b40-d27e-c988-630c8e4e28be
* Version Independent ID: 30902ba1-ea77-0f75-e9bd-e20b1d4e1fd5
* Content: [Data export - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-export/#feedback)
* Content Source: [data-explorer/kusto/management/data-export/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-export/index.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@edburns  Thanks for the feedback!  Your feedback  has been shared with the content owner for further review.

**Comment by spektom** [comment]
Hi @edburns ,

The reason client-side export is not explained well, is because there are variety of ways to do so.
The idea is to use you client application (Kusto Explorer, SDK, etc.) to retrieve the data, then saving it manually. For example, in Kusto Explorer there's an option to save query results to CSV file (File -> To CSV), which implements client-side export.

Sincerely.
Michael

**Comment by edburns** [comment]
Hello @spektom , thanks for your response.  Is there a way to do it in the Web UI?

**Comment by spektom** [comment]
Hi @edburns ,

Yes, there's an option:

![image](https://user-images.githubusercontent.com/158011/82863541-169cb400-9f2b-11ea-9e89-ed14603146cc.png)

**Comment by edburns** [comment]
Proposed fix in https://github.com/MicrosoftDocs/dataexplorer-docs/pull/107

**Comment by orspod** [comment]
@edburns thanks for your proposed fix. LMK when that PR #107 is ready to merge. Moving to close this issue
