### ISSUE TITLE
Automated Routes to the Internet

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1025]
Are the Azure Data Explorer management IP addresses and Health Monitoring IP address on this page up to date. I recently deployed an VNET injected Data Explorer in Australia East and a route table with the following IP addresses with a next hop of Internet were automatically configured. As far as I can tell none of the IP addresses that was configured in my environment appear on this page.  

![image](https://user-images.githubusercontent.com/7891408/152919481-e76715e9-b8b3-43d4-bbfa-20bad48d45bf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501c33cd-0ac0-685b-0da1-03a269616d08
* Version Independent ID: 67e7428d-9b35-cb0c-7af9-6fc402848b8d
* Content: [Deploy Azure Data Explorer into your Virtual Network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment#securing-outbound-traffic-with-a-firewall)
* Content Source: [data-explorer/vnet-deployment.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/vnet-deployment.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
Fixed by https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2732
