### ISSUE TITLE
Data Explorer CMK and Description

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1030]
If we enable this feature to encrypt all data in the storage account used by Data Explorer with a CMK, will the CMK also be used to encrypt the OS and data disks of the cluster VMs in the Data Explorer cluster when the "disk encryption" feature documented [here](https://docs.microsoft.com/en-us/azure/data-explorer/cluster-disk-encryption) is enabled?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f61000f3-9e92-bd3d-18b3-4ea518dc8646
* Version Independent ID: f26cdeba-20d7-7e06-92d0-55a15e1dc650
* Content: [Configure customer-managed-keys in Azure Data Explorer using the Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/data-explorer/customer-managed-keys-resource-manager)
* Content Source: [data-explorer/customer-managed-keys-resource-manager.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/customer-managed-keys-resource-manager.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thanks for the question. GitHub forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilize Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html)

**Comment by pnarsi** [comment]
@ShaikMaheer-MSFT - I was using my question to highlight an issue/gap with the docs - it is not clear which specific components are encrypted at rest via the CMK feature mentioned on this page. I would have thought this would be something that would be articulated on this page more clearly.

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by Gabilehner** [comment]
Using Customer Managed Key (CMK) for encryption the data is done on the storage level (cold data), while Disk Encryption today is enabled on the compute (OS and data disks). Therefore the 2 features are unrelated and do not have any impact on one another.

**Comment by shsagir** [comment]
@pnarsi Thanks so much for taking the time to leave us your comment on our documentation. The information you request is in the previous comment. We're still looking into whether the docs need updating. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
