### ISSUE TITLE
CSV file not available

### ISSUE THREAD

**Issue by karstenulferts** [MicrosoftDocs/dataexplorer-docs#1032]
https://kustosamplefiles.blob.core.windows.net/samplefiles/StormEvents.csv seems unavailable.

**Comment by ShaikMaheer-MSFT** [comment]
@karstenulferts Could you please share link of the documentation page for which you are providing feedback? Thank you.

**Comment by karstenulferts** [comment]
Here you can find the peage with a dead link:
https://docs.microsoft.com/en-us/azure/data-explorer/ingest-sample-data?tabs=ingest-comand

See step 4 (dead URL and typo/syntax error)
.ingest into table StormEvents 'https://kustosamplefiles.blob.core.windows.net/samplefiles/StormEvents.csv with (ignoreFirstRecord=true)

This link is the new/correct link to csv file.
https://kustosamples.blob.core.windows.net/samplefiles/StormEvents.csv

Correct version of data ingestion query
.ingest into table StormEvents 'https://kustosamples.blob.core.windows.net/samplefiles/StormEvents.csv' with (ignoreFirstRecord=true)

**Comment by shsagir** [comment]
@karstenulferts Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.
