### ISSUE TITLE
Cannot download Kusto Explorer

### ISSUE THREAD

**Issue by kerbelp** [MicrosoftDocs/dataexplorer-docs#1035]
Links in the docs are broken for me.
https://aka.ms/ke (CDN location)
https://aka.ms/ke-mirror (Non-CDN location)

This is the error I see in developer tools:
`       
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://browser.events.data.microsoft.com/OneCollector/1.0/?cors=true&content-type=application/x-json-stream&client-id=NO_AUTH&client-version=1DS-Web-JS-3.1.10&apikey=c6c27850c9c24cbfae921778d2465031-4c28c161-db47-426b-9d28-733d45d05dd9-7278&upload-time=1644918261922&ext.intweb.msfpc=GUID%3D8c7758d23be74ff497485d5c150227d1%26HASH%3D8c77%26LV%3D202112%26V%3D4%26LU%3D1639301601682&time-delta-to-apply-millis=526&w=0 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
`---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba96a1-65dd-5320-6d36-47de50b8403f
* Version Independent ID: deee5b70-9bd5-2bf9-f7b7-12c40200693d
* Content: [Kusto.Explorer installation and user interface](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer)
* Content Source: [data-explorer/kusto/tools/kusto-explorer.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/tools/kusto-explorer.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by MartinJaffer-MSFT** [comment]
Hello @kerbelp .  I just finished conferring with my colleague.  The CORS / CORB error you received is something implemented by your browser or company IT.  It is not cause by a broken link per se.  Please try looking at
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

**Comment by kerbelp** [comment]
Maybe the issue was in Edge browser. `aka.ms/ke` in edge got me this CORS errors, but it did work using the Chrome browser.
