### ISSUE TITLE
pack_all() demo query does not match results

### ISSUE THREAD

**Issue by dudu-markovitz** [MicrosoftDocs/dataexplorer-docs#1039]
The following query does not match the given results:

datatable(SourceNumber:string,TargetNumber:string,CharsCount:long)
[
'555-555-1234','555-555-1212',46,
'555-555-1234','555-555-1213',50,
'555-555-1313','',42, 
'','555-555-3456',74 
]
| extend Packed=pack_all()
| extend PackedIgnoreNullEmpty=pack_all(true)

It should actually be as following (a single 'extend' clause with 2 pack_all() operations):

datatable(SourceNumber:string,TargetNumber:string,CharsCount:long)
[
'555-555-1234','555-555-1212',46,
'555-555-1234','555-555-1213',50,
'555-555-1313','',42, 
'','555-555-3456',74 
]
| extend Packed=pack_all(), PackedIgnoreNullEmpty=pack_all(true)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d19e22d9-4cf0-c2dc-36fc-55424a68e417
* Version Independent ID: ea33783a-f666-0542-0dc0-a62aa18eadda
* Content: [pack_all() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/packallfunction)
* Content Source: [data-explorer/kusto/query/packallfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/packallfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@dudu-markovitz 
Thanks for the feedback and bringing this to our notice. At this time, we are reviewing the feedback and will update the document as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
