### ISSUE TITLE
Docs indicate that Power BI connector would still be in beta

### ISSUE THREAD

**Issue by vjrantal** [MicrosoftDocs/dataexplorer-docs#104]
The page at https://docs.microsoft.com/en-us/azure/data-explorer/visualize-power-bi has text:

> Search for Azure Data Explorer, select Azure Data Explorer (Beta), then Connect.

Below that, there is a screenshot that has the `(Beta)`-label.

These imply that the connector is still in beta even though I believe it is GA (ref: https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-june-2019-feature-summary/#azureDataExplorer).

**Comment by Mike-Ubezzi-MSFT** [comment]
@vjrantal Thank you for making us aware of this issue. This is an update that needs to take place in PowerBI and not necessarily with the documentation itself but understand there is no effective way to report this except for this channel.

**Comment by vjrantal** [comment]
@Mike-Ubezzi-MSFT In the Power BI, the `(Beta)`-label is already gone and there are other parts in the same docs that a newer screenshot such as this image:

https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/media/power-bi-connector/search-get-data.png

Above is referenced from https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/power-bi-connector.md#get-data-from-azure-data-explorer.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@vjrantal Thanks for bringing this to our attention. Your feedback  has been shared with the content owner for further review.

@orspod Could you please update the content and the screenshot in the document?

Screenshot needs to be updated.

![image](https://user-images.githubusercontent.com/44426401/82863140-f840b380-9f3e-11ea-9325-d000f21e5ee9.png)

Latest screenshot:

![image](https://user-images.githubusercontent.com/44426401/82863177-1ad2cc80-9f3f-11ea-8498-28d57495a72b.png)

**Comment by orspod** [comment]
@vjrantal thanks for the feedback. The doc was updated with updated image: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/355. I am now closing this issue.

**Comment by vjrantal** [comment]
@orspod As mentioned in the issue, the old info is also in the text (not just screenshot):

The page at https://docs.microsoft.com/en-us/azure/data-explorer/visualize-power-bi has text:

> Search for Azure Data Explorer, select Azure Data Explorer (Beta), then Connect.

**Comment by orspod** [comment]
@vjrantal - Appreciate your additional feedback. Sorry I missed that change. 
Note: an updated PowerBI topic can be found here: https://docs.microsoft.com/en-us/azure/data-explorer/power-bi-connector along with other Power BI topics.
Created PR to fix the text: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/358
