### ISSUE TITLE
Example on python is outdated

### ISSUE THREAD

**Issue by james-tn** [MicrosoftDocs/dataexplorer-docs#1040]
[Enter feedback here]

It should be updated to the following to run.
use azure.identity and method begin_create_or_update

```
from azure.mgmt.kusto import KustoManagementClient
from azure.mgmt.kusto.models import EventHubDataConnection
from azure.identity import ClientSecretCredential

#Directory (tenant) ID
tenant_id = ""
#Application ID
client_id = ""
#Client Secret
client_secret = ""
subscription_id = ""

credentials = ClientSecretCredential(
        client_id=client_id,
        client_secret=client_secret,
        tenant_id=tenant_id
    )
kusto_management_client = KustoManagementClient(credentials, subscription_id)

resource_group_name = "databackend"
#The cluster and database that are created as part of the Prerequisites
cluster_name = ""
database_name = ""
data_connection_name = ""
#The event hub that is created as part of the Prerequisites
event_hub_resource_id = ""
consumer_group = "$Default"
location = ""
#The table and column mapping that are created as part of the Prerequisites
table_name = ""
mapping_rule_name = ""
data_format = ""
#Returns an instance of LROPoller, check https://docs.microsoft.com/python/api/msrest/msrest.polling.lropoller?view=azure-python
poller = kusto_management_client.data_connections.begin_create_or_update(resource_group_name=resource_group_name, cluster_name=cluster_name, database_name=database_name, data_connection_name=data_connection_name,
                                        parameters=EventHubDataConnection(event_hub_resource_id=event_hub_resource_id, consumer_group=consumer_group, location=location,
                                                                            table_name=table_name, mapping_rule_name=mapping_rule_name, data_format=data_format))
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09ec755-8b8b-c3ae-c41c-e46e150b9296
* Version Independent ID: 139476a1-e5f9-181e-ee7f-ab466d65d54d
* Content: [Create an event hub data connection for Azure Data Explorer by using Python](https://docs.microsoft.com/en-us/azure/data-explorer/data-connection-event-hub-python)
* Content Source: [data-explorer/data-connection-event-hub-python.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/data-connection-event-hub-python.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

@orspod Could you please review the above feedback and loop in the relevant owner to validate and update the document as needed. Thank you

**Comment by shsagir** [comment]
@james-tn Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@james-tn Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish. We are tracking the request in [work item](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1924707).

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close

**Comment by Aviv-Yaniv** [comment]
Thank you @james-tn for notifying us and for the vigilance! 
We are updating the docs accordingly
