### ISSUE TITLE
Outbound FQDN Dependencies

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1044]
For securing outbound traffic with Firewall this page gives a list of FQDN including some very broad wildcard subdomain rules for *.core.windows.net (any storage account) and *.servicebus.windows.net (any eventhub/servicebus/relay)

![image](https://user-images.githubusercontent.com/7891408/154595540-f15ca9f9-8ab6-48c7-ac39-f62d5bdab08b.png)

The next section of the page talks about retrieving the outbound dependencies automatically via a REST API. The list of FQDN obtained via this method is a bit different to what is published in the previous section. Specifically when I tested this out the API returns (among other things) a list of Storage Endpoints FQDN (24 in total). From their names they seem to be Microsoft owned storage accounts created specifically for a DXP instance. Furthermore there no dependency for *.servicebus.windows.net (event hub ?) is listed via the REST API. 

It is unclear from the docs how these two lists of dependencies should be should in the context of an actual solution. Can/should readers ignore the first list and just use the specific dependencies obtained via REST API for their specific DXP instance in their  Firewall configuration? As the Storage endpoints dependencies obtained via the REST API seem to be specific for a DXP instance would I be correct assuming there is no risk of these storage dependencies changing over time for a specific DXP deployment?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501c33cd-0ac0-685b-0da1-03a269616d08
* Version Independent ID: 67e7428d-9b35-cb0c-7af9-6fc402848b8d
* Content: [Deploy Azure Data Explorer into your Virtual Network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment)
* Content Source: [data-explorer/vnet-deployment.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/vnet-deployment.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by ShaikMaheer-MSFT** [comment]
@orspod Could you please validate customer feedback and enhance doc as appropriate to get clear about from two lists of dependencies which should be in the context of an actual solution?

**Comment by cosh** [comment]
> For securing outbound traffic with Firewall this page gives a list of FQDN including some very broad wildcard subdomain rules for *.core.windows.net (any storage account) and *.servicebus.windows.net (any eventhub/servicebus/relay)

that's correct. kusto needs to access a variable list of storage accounts which might grow or shrink. That's why we are using a wildcard for *.core.windows.net. Same is true for servicebus.

> The next section of the page talks about retrieving the outbound dependencies automatically via a REST API. The list of FQDN obtained via this method is a bit different to what is published in the previous section. Specifically when I tested this out the API returns (among other things) a list of Storage Endpoints FQDN (24 in total). From their names they seem to be Microsoft owned storage accounts created specifically for a DXP instance. Furthermore there no dependency for *.servicebus.windows.net (event hub ?) is listed via the REST API.
 
we'll fix the doc. thx for bringing it up

**Comment by shsagir** [comment]
@pnarsi  Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish. We are tracking the request in this [work item](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1925226).

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
