### ISSUE TITLE
Materialized View with backfill property vs idempotency with IaC

### ISSUE THREAD

**Issue by dariuszdbr** [MicrosoftDocs/dataexplorer-docs#1052]
Hi, not sure if that's the correct area to place question regarding materialized views and IaC, but will give a try.

We are working on solution that is using ADX. We have created some arm templates responsible for creating ADX Cluster, and then we have *.csl scripts used by [Adx Azure DevOps Tasks](https://docs.microsoft.com/en-us/azure/data-explorer/devops) to create tables, functions, policies etc with the use of the tip: 
![image](https://user-images.githubusercontent.com/27953502/155131956-f7ff7cd5-f2e4-451e-ab79-19f618bfb2e3.png)

Right now we have a lot of data in our adx, and we wanted to add materialized-view which is using `backfill=true` property in order to make sure that the existing data will be included in this view. 

Let's say that this is the example query that we want to use:

```
.create-or-alter materialized-view with (backfill=true) ArgMax on table T
{
    T | summarize arg_max(Timestamp, *) by User
}
```

when we ran this command for the very first time it will create the materialized view, and everything is ok, but if we will ran it again it will return error 

```
 Unsupported propery in materialized view alter command. Supported properties: DimensionTables,Lookback,Folder,DocString,AutoUpdateSchema.
```

So it seems that idempotency cannot be maintained within IaC with materialized views.

[.create-or-alter materialized-view documentation](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-create-or-alter) says that:
![image](https://user-images.githubusercontent.com/27953502/155131536-563d7095-5c9d-4349-b4ea-50dfc981896c.png)

> The backfill property isn't supported if the materialized view already exists. If the materialized view already exists, it cannot be backfilled.

Our case is that we have `backfilled` materialized view, and we cannot ran command that in the end is not changing anything. 

We are wondering if that's correct behaviour, appreciate any thoughts or ideas how to achieved idempotency with materialized views

**Comment by SaurabhSharma-MSFT** [comment]
@dariuszdbr To assist you better on your query could you provide us with the link to the document you are referring to ?
In case your query in not related to document content, open a new forum thread either [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) or StackOverflow as it could be better place to get help on your scenario where the community members could provide their expert guidance to you based on their experience.

**Comment by dariuszdbr** [comment]
There is no such example in the docs (with `create-or-alter + backfill property`), although there are examples with `.create async ... ` like the second one [here](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-create#examples), 
```
.create async materialized-view with (backfill=true, docString="Customer telemetry") CustomerUsage on table T
{
    T 
    | extend Day = bin(Timestamp, 1d)
    | summarize count(), dcount(User), max(Duration) by Customer, Day 
}
```
but this is not exactly what I was asking, so I have placed a question on [stackoverflow](https://stackoverflow.com/questions/71228326/adx-materialized-views-with-backfill-property-vs-idempotency-with-iac-in-adx-azu)

**Comment by SaurabhSharma-MSFT** [comment]
@dariuszdbr Closing this one as it looks like you have got your answer over Stackoverflow.
