### ISSUE TITLE
Need examples of usage in context

### ISSUE THREAD

**Issue by ghogen** [MicrosoftDocs/dataexplorer-docs#1056]
OK, so I have a table in Kusto that has a query string that is ideal input for parse_urlquery() but what do I need to do with the output of parse_urlquery to extract useful information like the value of a particular parameter. This article just gives the result in a JSON format and I guess we need to go through the article on dynamic types that are property bags to go further, but that topic is very terse as well and doesn't really give any examples relevant to this case.

What I'm looking for is something like 

let monikerValue = (querystring: string)
{
   let params = parse_urlquery(querystring);
   tostring(params["Query Parameters"].view) 
};

If one passes is querystring like "view=vs-2019&preserve-view=true" how do I get the value of the "view" parameter? The above code works but it would be nice if an example was given.

I would also mention that if the input string contains the initial "?" that this function doesn't work. It's expecting input starting from just after the "?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d29facf2-c56d-5db6-3acd-831800d04349
* Version Independent ID: 8b033240-8e2d-3f58-dd21-bf7bb41860a2
* Content: [parse_urlquery() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parseurlqueryfunction#feedback)
* Content Source: [data-explorer/kusto/query/parseurlqueryfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/parseurlqueryfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@ghogen Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@ghogen Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by sloutsky** [comment]
Here is a working example, we will add something like this to the docs.


```kusto
let monikerValue = (querystring: string)
{
    let params = parse_urlquery(querystring);
    tostring(params["Query Parameters"].['view'])
};
print UrlQuery = 'view=vs-2019&preserve-view=true'
| extend Moniker = monikerValue(UrlQuery)
```

|UrlQuery|Moniker|
|---|---|
|view=vs-2019&preserve-view=true|vs-2019|

**Comment by shsagir** [comment]
@ghogen Thanks for your feedback. We've submitted a [documentation change](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2864) based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
