### ISSUE TITLE
Missing dash in instruction for ".alter materialized view"

### ISSUE THREAD

**Issue by marcolisi** [MicrosoftDocs/dataexplorer-docs#1057]
The instructions are missing a dash for materialized view: .alter materialized view

Both in the definition and in the code.

It should be .alter **materialized-view**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c105250e-9bb6-4ef6-0f20-1e84158b57c2
* Version Independent ID: 17b0eee7-a0c3-02a2-5281-ea10a21f9e7b
* Content: [.alter materialized view retention policy command- Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-materialized-view-retention-policy-command)
* Content Source: [data-explorer/kusto/management/alter-materialized-view-retention-policy-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/alter-materialized-view-retention-policy-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback and bringing this to our notice. At this time, we are reviewing the feedback and will update the document as appropriate.

**Comment by shsagir** [comment]
@marcolisi Thanks for your feedback. @KranthiPakala-MSFT (Thanks!) submitted a documentation change based on your feedback, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
