### ISSUE TITLE
These examples *really* need to show the output.

### ISSUE THREAD

**Issue by stowen-msft** [MicrosoftDocs/dataexplorer-docs#1065]
Since so many Microsoft services use Kusto for querying, a lot of folk's will be viewing these help documents.  It would really be beneficial to show the expected output from the command.

The output of these commands demonstrates the value of using the commands.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66c8f1ca-58d1-ea24-9423-30fc46a4a276
* Version Independent ID: 3a0759be-fb2e-385b-24d5-4b1b59b7670e
* Content: [facet operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/facetoperator)
* Content Source: [data-explorer/kusto/query/facetoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/facetoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback. We have assigned the issue to the content author. They will evaluate and update the document as appropriate.

**Comment by shsagir** [comment]
@stowen-msft Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.
