### ISSUE TITLE
This article needs troubleshooting steps

### ISSUE THREAD

**Issue by JasonFreeberg** [MicrosoftDocs/dataexplorer-docs#1067]
Followed the instructions but it fails with this:

![image](https://user-images.githubusercontent.com/18747768/156680045-d3ae3603-75a4-4d3f-a859-9da5b05cb8fc.png)

_Now what do I do?_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4aa15b-5f33-b4f8-f3cd-f5f2434f3836
* Version Independent ID: ac42a985-65b3-4671-5c8e-de32dd876025
* Content: [Visualize data with Azure Data Explorer connector for Power BI](https://docs.microsoft.com/en-us/azure/data-explorer/power-bi-connector)
* Content Source: [data-explorer/power-bi-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/power-bi-connector.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@JasonFreeberg Thank you for sharing feedback. We will validate and share updates soon.

**Comment by ShaikMaheer-MSFT** [comment]
@orspod Could you please validate customer feedback and check if this doc can include few trouble shooting tips and enhance document as appropriate?

@JasonFreeberg Thank you for question. GitHub forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilize Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html).

**Comment by shsagir** [comment]
@JasonFreeberg Thanks for your feedback. After investigating, we've discovered the documented steps work as expected. If the problem persists, please use the support channel suggested by @ShaikMaheer-MSFT.

@ShaikMaheer-MSFT Thanks for the suggestion. At this time the steps have been verified.

#please-close
