### ISSUE TITLE
No helptext for user defined functions

### ISSUE THREAD

**Issue by ringerc** [MicrosoftDocs/dataexplorer-docs#1068]
The documentation at https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/functions/user-defined-functions does not describe any way to add help-text, parameter documentation etc to user-defined functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5958aeff-6cae-d186-b3b4-47925c42f4dd
* Version Independent ID: ba7d8197-6ec5-e730-9b1a-4fba51680289
* Content: [User-defined functions - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/functions/user-defined-functions)
* Content Source: [data-explorer/kusto/query/functions/user-defined-functions.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/functions/user-defined-functions.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MonikaReddy-MSFT** [comment]
@ringerc  - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can review and update the document accordingly.

**Comment by shsagir** [comment]
@ringerc Thanks for your feedback. Please can you provide more detail or an example of the issue you raised?

**Comment by shsagir** [comment]
@ringerc Apologies for the delay in responding.

Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ringerc Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're tracking the change request on [Work Item 1932537](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1932537) and closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
