### ISSUE TITLE
Are more authentication methods possible than the GET parameter?

### ISSUE THREAD

**Issue by m-terlinde** [MicrosoftDocs/dataexplorer-docs#1069]
Hey guys,

we have the issue, that for MS Defender advanced hunting, we need to access 3rd-party data behind authentication. Unfortunately, the GET parameter does not work on that endpoint like in the example.

We tried something like that:
`let data= (externaldata(md5_hash:string ) [h@"https://user:password@domain.tld/path/to/file.txt"]`

Looking at the logs of the 3rd-party werbserver, username and password was not send.

So, is there any other method to authenticate?

Thanks,
Matthias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c78088-4289-15ef-3111-8116976124bb
* Version Independent ID: 3c8d8be2-2841-df0a-6c8b-b5a6893bbd1d
* Content: [externaldata operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/externaldata-operator)
* Content Source: [data-explorer/kusto/query/externaldata-operator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/externaldata-operator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for reaching out! We have assigned the issue to the content author to further review this and provide an update as appropriate.

**Comment by shsagir** [comment]
@m-terlinde Thanks for your question. You can use the [authentication methods](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/storage-authentication-methods) topic for supported ways to authenticate.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close

**Comment by m-terlinde** [comment]
Thanks a lot for the link, @shsagir! 
The linked documentation only mentions authentication against a Azure storage product. Are the same methods also possible against 3rd-party sites like a basic auth protected webserver or so?

In our tests, the SAS was not passed to our Apache web server, which left us kind of puzzled.
