### ISSUE TITLE
Typo "deletes" should be "displays" in show stream ingestion policy articles

### ISSUE THREAD

**Issue by vmhenard** [MicrosoftDocs/dataexplorer-docs#1073]
Hello,

Looks like there is a typo, it should be "displays" not "deletes" in :
"The following command deletes the streaming ingestion policy:"

Same issue for the .show database streaming ingestion policy article.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c753d363-f7eb-4681-ae61-84cf5e1173d3
* Version Independent ID: 0433d936-a61a-b162-297e-819e9423399c
* Content: [.show table streaming ingestion policy command - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-table-streaming-ingestion-policy-command)
* Content Source: [data-explorer/kusto/management/show-table-streaming-ingestion-policy-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/show-table-streaming-ingestion-policy-command.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
