### ISSUE TITLE
Page needs a new title/TOC-title

### ISSUE THREAD

**Issue by zivcaspi** [MicrosoftDocs/dataexplorer-docs#1082]
It's very hard to find this page based on its title and/or its TOC-title.
Suggest we rename both to something like "Referencing security principals"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b075a2bc-27ff-ad1f-b155-42f8486f7688
* Version Independent ID: 90dd764e-d81d-76ec-0da0-e4b9d14e0018
* Content: [Principals and Identity Providers - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/principals-and-identity-providers?source=docs)
* Content Source: [data-explorer/kusto/management/access-control/principals-and-identity-providers.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/access-control/principals-and-identity-providers.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@zivcaspi Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by ShaikMaheer-MSFT** [comment]
@shsagir Could you please validate customer feedback and enhance document as appropriate? Thank you

**Comment by shsagir** [comment]
@zivcaspi Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're tracking this in [work item 1932547](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1932547) and  closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
