### ISSUE TITLE
Exception mapping

### ISSUE THREAD

**Issue by meanin** [MicrosoftDocs/dataexplorer-docs#1083]
Hi, it would be cool to have somewhere documented http response code mappings into C#/.NET exceptions as it is not so easy to replicate all of scenarios from [here](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/response).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b0560f-8a4c-c829-7307-c18a7710f0fc
* Version Independent ID: 61dcd20a-7a61-88af-ca40-e9922fbb86a1
* Content: [Kusto client library - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/about-kusto-data)
* Content Source: [data-explorer/kusto/api/netfx/about-kusto-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/netfx/about-kusto-data.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by meanin** [comment]
Which Microsoft.Azure.Kusto.Data exceptions map to which ADX http response codes. In example, we do know, that 400 is being mapped to KustoRequestException with ErrorReason property set to "BadRequest", or 413 is being mapped to KustoServicePartialQueryFailureException. Please provide a way to distinguish each http response code returned from ADX based on mentioned nuget.

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@meanin Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@meanin Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

You can track progress on work item: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1936737

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
