### ISSUE TITLE
Need to update the limitation of externaldata operator in documentation

### ISSUE THREAD

**Issue by lujinlou** [MicrosoftDocs/dataexplorer-docs#1084]
When we use externaldata operator to execute Azure DevOps Rest API, it will shows the error message: message":"Partial query failure: 0x80131500 (message: 'The remote server returned an error: (405) Method Not Allowed in the Browser Developer Network Tool.

For example: Rest API: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-file-contents?view=azure-devops-rest-6.0
Sample:

externaldata(IPAddress:string) [@"https://aa:PAT@dev.azure.com/Organization/project/_apis/sourceProviders/TfsGit/filecontents?repository=Repo4&commitOrBranch=main&path=/test1.csv"] with (format="csv", ignoreFirstRecord=True);

![image](https://user-images.githubusercontent.com/52313100/157872602-01beb752-a6e4-473e-b7ea-d713e659aa3d.png)

Discuss with engineer from Azure Log Analytics workspace team, this error means that externaldata does not support executing Rest API.

But in the documentation, it doesn't show clearly.

Please check the situation and update the doc to state this limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c78088-4289-15ef-3111-8116976124bb
* Version Independent ID: 3c8d8be2-2841-df0a-6c8b-b5a6893bbd1d
* Content: [externaldata operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/externaldata-operator?pivots=azuremonitor)
* Content Source: [data-explorer/kusto/query/externaldata-operator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/externaldata-operator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@lujinlou Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@lujinlou Thanks for your feedback. We've submitted a documentation change based on your query, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
