### ISSUE TITLE
Possible new reserved word?

### ISSUE THREAD

**Issue by rafamerlin** [MicrosoftDocs/dataexplorer-docs#109]
So. I saw that I have one query that stopped working a while ago, I can't pinpoint when though.

Looks like `blocked` is now a reserved word in the project operator.

This works fine for example:
```
traces
| project x = itemCount
```

If I do this though:
```
traces
| project blocked = itemCount
```

I get this error now:
```
Syntax Error
Query could not be parsed at 'blocked' on line [2,10]

Token: blocked
Line: 2
Position: 10

If issue persists, please open a support ticket.
Request id: 9df7dd5a-37f4-486e-910f-620dd1542df5   
```

If this expected now or should I open a support ticket? 
In case of being expected, is there a page in the docs with all the reserved words?

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d21a5c6-ae80-52d0-7d06-43191081b656
* Version Independent ID: 799a41ab-2353-1bbc-8132-69eeb4678154
* Content: [Project operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/projectoperator)
* Content Source: [data-explorer/kusto/query/projectoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/projectoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@rafamerlin Thank you for reaching out and bringing this to our notice. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by rafamerlin** [comment]
Hey @KranthiPakala-MSFT , I may have asked this question on the wrong place. I am having this issue on log analytics query. I didn't realise I was looking at the project operator on the Data Explorer instead. The query looks the same and testing it on the provided test environment in this docs page I could confirm it doesn't work:

https://dataexplorer.azure.com/clusters/help/databases/Samples
```
StormEvents 
| where StartTime >= datetime(2007-11-01) and StartTime < datetime(2007-12-01)
| where State == "FLORIDA"  
| project blocked = State
```

The difference from here and Log Analytics is that in here there's a squiggly line under the blocked when you type it and not on Log Analytics. I'll ask this on the Log Analytics page.
