### ISSUE TITLE
Chinese version misses the latest download link

### ISSUE THREAD

**Issue by jasonhumsft** [MicrosoftDocs/dataexplorer-docs#1094]
In the English version, there are two download links and the one for .NET is latest:
![image](https://user-images.githubusercontent.com/91578501/158541485-ed213ce6-1a84-4e51-8e19-36aa3b84d8b1.png)

But in the Chinese version, there is only one download link for the depreciated .NETCore version, but the link for the latest .NET version is missing:

![image](https://user-images.githubusercontent.com/91578501/158541323-119d3451-0e7b-49af-9077-8f92037e2819.png)

Doc English version: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-cli#get-the-tool
Doc Chinese version: https://docs.microsoft.com/zh-cn/azure/data-explorer/kusto/tools/kusto-cli#get-the-tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93861526-36d2-0a0c-7c05-b3ebdd22a80a
* Version Independent ID: 4e5c3ed9-3009-f064-ad1e-079388e189d1
* Content: [Kusto CLI - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-cli#command-line-arguments)
* Content Source: [data-explorer/kusto/tools/kusto-cli.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/tools/kusto-cli.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@jasonhumsft Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by AnnuKumari-MSFT** [comment]
@shsagir , 
Requesting to validate customer feedback and update the document accordingly as appropriate. Thankyou

**Comment by shsagir** [comment]
#assign: @SunnyDeng
