### ISSUE TITLE
Default value for CachingPoliciesModificationKind

### ISSUE THREAD

**Issue by jasonhumsft** [MicrosoftDocs/dataexplorer-docs#1097]
As per my testing, when a DB is attached to a follower cluster, the default CachingPoliciesModificationKind is "union", not the "none" described in this document.
![image](https://user-images.githubusercontent.com/91578501/158763624-856f1e3b-8778-452e-ab84-8359851228b9.png)
![image](https://user-images.githubusercontent.com/91578501/158763794-c23a11e1-0cfd-4085-9077-e8803d0d7e9c.png)

Could you check and update this section https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/cluster-follower#caching-policy accordingly?

Also, the description in another page is inaccurate: https://docs.microsoft.com/en-us/azure/data-explorer/follower?tabs=csharp#configure-caching-policy
![image](https://user-images.githubusercontent.com/91578501/158764033-2ddcf627-a3d5-440e-94f7-5f715fd85220.png)

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88173fa-6370-7d0c-5b56-53a81b0b07d5
* Version Independent ID: f1c313ec-3cbd-ca9a-bdc6-b56d765e55b4
* Content: [Cluster follower commands - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/cluster-follower)
* Content Source: [data-explorer/kusto/management/cluster-follower.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/cluster-follower.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@jasonhumsft  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by shsagir** [comment]
@jasonhumsft Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

You can track progress on work item: https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1934643

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
