### ISSUE TITLE
Telegraf is still not mentioned on the plugin list

### ISSUE THREAD

**Issue by KhaoticMind** [MicrosoftDocs/dataexplorer-docs#1099]
Telegraf received an output plugin to ADX november last year (https://techcommunity.microsoft.com/t5/azure-data-explorer-blog/new-azure-data-explorer-output-plugin-for-telegraf-enables-sql/ba-p/2829444) but there's no mention of it on the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c758ab8-a66a-0d9d-af7a-a0fbe43ec6f4
* Version Independent ID: 62e4d091-8261-eb79-0f50-92a302487dd0
* Content: [Azure Data Explorer data ingestion overview](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-overview)
* Content Source: [data-explorer/ingest-data-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/ingest-data-overview.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@KhaoticMind  Thanks for the feedback! We are investigating and will update you shortly.

**Comment by shsagir** [comment]
@KhaoticMind Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@KhaoticMind Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue and will be updating the page based on your suggestions. Changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
