### ISSUE TITLE
Page referring to Kusto Explorer

### ISSUE THREAD

**Issue by Marco-Santoni** [MicrosoftDocs/dataexplorer-docs#110]
This page and the images inside it are not up to date with Data Explorer and latest AAD App Registration. Would it be possible to update it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb65164-6a92-2013-fda7-786690851a1d
* Version Independent ID: 10011da2-ec90-c6d1-5324-07fbb990e974
* Content: [HowTo -  Creating an AAD application - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/how-to-provision-aad-app)
* Content Source: [data-explorer/kusto/management/access-control/how-to-provision-aad-app.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/access-control/how-to-provision-aad-app.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Marco-Santoni** [comment]
Found https://docs.microsoft.com/en-us/azure/data-explorer/provision-azure-ad-app 😄

**Comment by KranthiPakala-MSFT** [comment]
@Marco-Santoni Thanks for sharing the latest link here. It will be helpful others who reads this thread. 
Feel free to comment or open new issue if you further queries.
