### ISSUE TITLE
How to use identity mapping for Event Hub data connection? Docs should lead to greater success here

### ISSUE THREAD

**Issue by sandersaares** [MicrosoftDocs/dataexplorer-docs#1101]
The [mapping docs](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings#identity-mapping) say that identity mappings are supported.

However the Event Hub page does not explain how to tell it to use it - when I created such a data connection in the Azure Portal, it says the mapping is required. If this is something that can only be accomplished in a different way (e.g. manually invoking some command), this (the fact that the portal is limited feature set) should be made clear in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5808ed2-5d09-4c56-dc0b-4e3650f8fc16
* Version Independent ID: ba034a8d-d5bb-6ea4-e61b-74ea3a5eb2be
* Content: [Ingest data from event hub into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub)
* Content Source: [data-explorer/ingest-data-event-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/ingest-data-event-hub.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@sandersaares Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by LeaShallev** [comment]
Thanks @sandersaares for the feedback.
Indeed we not support automatic identity mapping for JSON, MULTIJSON and AVRO in Event Hub ingestion.
As mentioned [here](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub#target-table) and as you can see in the portal, specifing mapping for these formats is required.
We will update docs so it clearer.

**Comment by shsagir** [comment]
@sandersaares Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @MicrosoftDocs/build_service_account 
#please-close

**Comment by LeaShallev** [comment]
@sandersaares - we recently added a support for identity mapping for all formats in Event Hub, Event Grid and IoT hub ingestion so you can now use it.
Thanks for your feedback!
