### ISSUE TITLE
Wrong parameter on query example

### ISSUE THREAD

**Issue by KhaoticMind** [MicrosoftDocs/dataexplorer-docs#1104]
The query example of section "Evaluate resource usage" is probably wrong.

The script calls "MyFunction" in the end, but this is never defined. This probably refers to the second let that reads

```
let MySourceTable = 
    MySourceTable
    | where ingestion_time() > ago(10m) and extent_id() == _extentId;

```
but should probably be

```
let MyFunction = 
    MySourceTable
    | where ingestion_time() > ago(10m) and extent_id() == _extentId;

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26bac25c-c168-fadc-2491-651d35361512
* Version Independent ID: 608aa328-7799-1597-0940-4edec0b93e08
* Content: [Kusto update policy - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/updatepolicy)
* Content Source: [data-explorer/kusto/management/updatepolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/updatepolicy.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@KhaoticMind  Thanks for the feedback! We are investigating and will update you shortly.

**Comment by shsagir** [comment]
#please-close
