### ISSUE TITLE
Undocumented hint: hint.progressive_top

### ISSUE THREAD

**Issue by dudu-markovitz** [MicrosoftDocs/dataexplorer-docs#1108]
There seems to be an undocumented hint (hint.progressive_top) for the top operator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4829b5ee-46fa-3d2d-af51-4a5c28803b79
* Version Independent ID: 7dcb3bc9-4a10-97e1-ed40-a5ed989e1b9e
* Content: [top operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/topoperator?source=docs)
* Content Source: [data-explorer/kusto/query/topoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/topoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by amitof** [comment]
This is a debugging flag meant to be used by Kusto developer
We will hide it from intellisense

**Comment by shsagir** [comment]
@amitof Thanks for your feedback. Per @amitof's comment, this is not a supported feature and hence not relevant for docs. Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue.

#please-close
