### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by sergeigirshev** [MicrosoftDocs/dataexplorer-docs#1109]
Every data value **(such as the value of an expression,** or the parameter to a function, **or the value of an expression**)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 303e5f6b-e267-4c5d-36ae-b82999a9ebf2
* Version Independent ID: e41a87d8-e321-1fe3-8854-384eaf2030a2
* Content: [Scalar data types - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/#feedback)
* Content Source: [data-explorer/kusto/query/scalar-data-types/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/scalar-data-types/index.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
