### ISSUE TITLE
Not sustainable design for Adx proxy URL

### ISSUE THREAD

**Issue by faizgouri** [MicrosoftDocs/dataexplorer-docs#1112]
The URL for Azure Monitor data using Azure Data Explorer contains "Resource Group Name" and "Workspace Name" which is not an ideal case because these values may change in the future and any application with that URL will fail.
Why using Resource Group ID and Workspace ID is not supported here just like Subscription ID in the URL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6c8fe3-d9a3-f11b-cfe7-f0f67f44b0d5
* Version Independent ID: 418e6ed4-24b4-689b-50fc-490441dc393c
* Content: [Query data in Azure Monitor with Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/query-monitor-data)
* Content Source: [data-explorer/query-monitor-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/query-monitor-data.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@faizgouri Thank you for sharing feedback. We are actively validating it. We will share updates soon.
