### ISSUE TITLE
Not clear on partial sucess/failure

### ISSUE THREAD

**Issue by shacharoronm** [MicrosoftDocs/dataexplorer-docs#1113]
Hi.
thank you for the documentation. 

some details that I am missing in order to use the .lear table [name] data command in my code:

this page does not state what will happen in case of partial success or failure of the command.
will there be an exception thrown? 
will there be an indicator if a retry is required? 
what details will be available?

thanks, 
Shachar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5cbc919-f643-9a6e-cdbc-dd5b6e224946
* Version Independent ID: 33fb698f-075e-ec52-898f-be5e180a5b01
* Content: [.clear table data - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/clear-table-data-command)
* Content Source: [data-explorer/kusto/management/clear-table-data-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/clear-table-data-command.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@shacharoronm Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
Fixes https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/3006

**Comment by shsagir** [comment]
@shacharoronm Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
