### ISSUE TITLE
When is Azure Data Explorer Dashboards out of preview? 

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/dataexplorer-docs#1115]
When is the dashboard feature coming out of preview?  

What is the expected cost of using the dashboard feature? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1640-3699-8fdf-07a2-c9b922499c90
* Version Independent ID: 55027537-6af4-541d-da8d-e2cdc2b5fa92
* Content: [Visualize data with the Azure Data Explorer dashboard](https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards)
* Content Source: [data-explorer/azure-data-explorer-dashboards.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/azure-data-explorer-dashboards.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.
