### ISSUE TITLE
Incorrect default/max values

### ISSUE THREAD

**Issue by liranms** [MicrosoftDocs/dataexplorer-docs#1118]
Several issues with this documentation:
1) The default value for max number of items appears to be 500 rather than 1000
2) For raw data size the default is 1024 which is larger than 1000 that you consider max
3) setting values larger than the max works, is this a bug or a feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d4d614-63d3-d2d2-b7a1-cce41cd43335
* Version Independent ID: f324df02-c6e3-ecca-3ee7-806633089d3a
* Content: [.alter database ingestion batching policy command - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-database-ingestion-batching-policy)
* Content Source: [data-explorer/kusto/management/alter-database-ingestion-batching-policy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/alter-database-ingestion-batching-policy.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@liranms Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@liranms Thanks again for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

Progress is tracked on work item: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1937666

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close

**Comment by yahavx-ms** [comment]
Default values are indeed outdated, will fix that. 
Upper bounds are not set at the moment, will be removed from the docs.
Thanks.
