### ISSUE TITLE
Provide download link for the .jar files needed

### ISSUE THREAD

**Issue by KhaoticMind** [MicrosoftDocs/dataexplorer-docs#1121]
Please provide a link for the .jar that are needed to be download to connect to ADX, or at least a list of the sources, the way it is is hard to figure where each .jar should be dowloaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6149ce-1c3c-d2a2-79a9-cb181240ce90
* Version Independent ID: 372e6191-af44-ba93-bf59-c3bcc236c270
* Content: [MS-TDS clients and Kusto - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/tds/clients)
* Content Source: [data-explorer/kusto/api/tds/clients.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/tds/clients.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@KhaoticMind Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@name Thanks again for your feedback. After investigating with the product dev team, we've discovered the list of jar files is provided for example purposes only. It's not jar files we provide. As such, we cannot change the referenced page to include the information and functionality that you're asking for and we're closing this issue.

#please-close
