### ISSUE TITLE
Examples should use HH not hh for hour

### ISSUE THREAD

**Issue by kganjam** [MicrosoftDocs/dataexplorer-docs#1124]
// Using hh incorrectly cuts of the hours
print format_timespan(time(29.23:59:59.12345), "d.hh:mm:ss"); // 29.11:59:59
print format_timespan(time(29.23:59:59.12345), "d.HH:mm:ss"); // 29.23:59:59

// Using HH is better when for example subtracting two times 
print format_timespan(time(29.23:59:59.12345) - time(1.2:30:59.12345), "d.HH:mm:ss"); // 28.21:29:00 (Correct)
print format_timespan(time(29.23:59:59.12345) - time(1.2:30:59.12345), "d.hh:mm:ss"); // 28.09:29:00 (Wrong)

I had copied the doc example blindly and had to rerun an expensive query because of this issue. And I almost didn't even notice the bug. 
Note that there are 3 places with hh in the doc page that need updating.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f256e73-523b-eb7e-8499-935cad4f681d
* Version Independent ID: 25deec0b-850f-f067-6809-cff0de381b74
* Content: [format_timespan() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/format-timespanfunction)
* Content Source: [data-explorer/kusto/query/format-timespanfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/format-timespanfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@kganjam Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by shsagir** [comment]
@kganjam Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@kganjam Thanks for your feedback. We've submitted a code bug fix based on your suggestion that will be released at the earliest opportunity, most likely in the coming months. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
