### ISSUE TITLE
Include escaping of quotes in verbatim string literals

### ISSUE THREAD

**Issue by acalarch** [MicrosoftDocs/dataexplorer-docs#1127]
[There should be a section that describes how to escape " in verbatim string literals (via double-double quotes]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525bbc5a-0b79-0609-3637-2af59995c55d
* Version Independent ID: 9d1ec307-cf2d-a41d-bacc-cd7615c85212
* Content: [The string data type - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/string)
* Content Source: [data-explorer/kusto/query/scalar-data-types/string.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/scalar-data-types/string.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.
