### ISSUE TITLE
Drop query doesn't work

### ISSUE THREAD

**Issue by CIPop** [MicrosoftDocs/dataexplorer-docs#113]
Should be `mapping` (singular) and lowercase `json`. 

.drop table TableName ingestion json mapping "JsonMapping1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece17ed4-922c-fad6-8063-f6ba4988bd03
* Version Independent ID: 332cfe88-df27-b4e2-6556-d482b5f7fca2
* Content: [.drop ingestion mapping - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/drop-ingestion-mapping-command)
* Content Source: [data-explorer/kusto/management/drop-ingestion-mapping-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/drop-ingestion-mapping-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@CIPop   Thanks for bringing this to our attention. Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@CIPop - thanks for the feedback. the doc has been updated with your changes. https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/356.
I am now closing this issue.
