### ISSUE TITLE
Example 4 - Case Sensitive match in quotes

### ISSUE THREAD

**Issue by brianmatusz** [MicrosoftDocs/dataexplorer-docs#1136]
We setup exercises to train our team on KQL. And there was some confusion regarding the documentation. It appears that `search` does not permit in-quote sensitivity as mentioned in example 4 *OR* is there an additional configuration item to enable this scenario?

For our classroom exercise we found:
```
let bob=search "bob" | count | extend searchterm="search 'bob'";
let Bob=search "Bob" | count | extend searchterm="search 'Bob'";
let bob_cs=search kind=case_sensitive "bob" | count | extend searchterm="search kind=case_sensitive 'bob'";
let Bob_cs=search kind=case_sensitive "Bob" | count | extend searchterm="search kind=case_sensitive 'Bob'";
union bob, Bob, bob_cs, Bob_cs
| sort by searchterm asc
```

| **Count** | **searchterm** |
|--|--|
1,916 | search 'Bob' |
1,916 | search 'bob' |
1,866 | search kind=case_sensitive 'Bob' |
42 | search kind=case_sensitive 'bob' |

See the ***Examples*** section, example number 4:
```
// 4. Like (2), but performing a case-sensitive match of all terms
search "BillB" and ("SteveB" or "SatyaN")
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b54882e-831a-64d3-a2e1-9dc8f689ff53
* Version Independent ID: 755ac9e9-796c-bf0c-6f29-c8810cbeca98
* Content: [search operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/searchoperator?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/searchoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/searchoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @brianmatusz, thanks for bringing this to our attention. I have assigned the issue to the content author to evaluate and update as appropriate

**Comment by shsagir** [comment]
@brianmatusz Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@brianmatusz Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
