### ISSUE TITLE
"Query data ..." shouldn't be a next step for this page.

### ISSUE THREAD

**Issue by mitulmk** [MicrosoftDocs/dataexplorer-docs#114]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1640-3699-8fdf-07a2-c9b922499c90
* Version Independent ID: 55027537-6af4-541d-da8d-e2cdc2b5fa92
* Content: [Visualize data with the Azure Data Explorer dashboard](https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards)
* Content Source: [data-explorer/azure-data-explorer-dashboards.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/azure-data-explorer-dashboards.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by KranthiPakala-MSFT** [comment]
@orspod Could you please have a look at the above feedback. Thank you.

**Comment by orspod** [comment]
@Gabilehner

**Comment by orspod** [comment]
@mitulmk thanks for your feedback. 
Next steps are mandatory for all articles. The query data topic can be both a pre-req and a next steps for this article. Once more dashboard articles are published we will add those as next steps too.
I will now close this issue but feel free to continue discussion if you have additional concerns.
