### ISSUE TITLE
AttributeError: 'ClustersOperations' object has no attribute 'create_or_update'

### ISSUE THREAD

**Issue by rigoita** [MicrosoftDocs/dataexplorer-docs#1141]
Hello,
when I try to run the command provided for creating an Azure Data Explorer cluster and database by using Python (ref. https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-python), I received the following AttributeError:

- 'ClustersOperations' object has no attribute 'create_or_update'.  Did you mean: 'begin_create_or_update'?

Could you please advice?

Thanks
Rigo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a6ac245-2ec4-1f83-6f38-c58197c3afc0
* Version Independent ID: f503e255-b4c5-4c91-2187-977168fcda78
* Content: [Create an Azure Data Explorer cluster & DB using Python](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-python)
* Content Source: [data-explorer/create-cluster-database-python.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/create-cluster-database-python.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by Grace-MacJones-MSFT** [comment]
Thank you for the detailed question. We are currently investigating and will update you when we have accurate information to provide.

**Comment by yihezkel** [comment]
We do not support this SDK, so it's worth confirming with the owners of this repo, but I looked back and see that in https://github.com/Azure/azure-sdk-for-python/commit/b1d8fc67f1831ea276bc73e9f1c7fdae16a825a5 it seems `create_or_update` was indeed changed to `begin_create_or_update`.

I'll update our docs accordingly.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@rigoita  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
