### ISSUE TITLE
Missing documentation on ExecuteQueryV2Async

### ISSUE THREAD

**Issue by ChadNedzlek** [MicrosoftDocs/dataexplorer-docs#1146]
This page references a "ExecuteQueryV2Async" as a way that will fix the problem when making these queries from code. But that method appears to be 100% undocumented anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082142f3-9558-d472-c85b-459b956480a1
* Version Independent ID: 3beb35b6-5885-9367-9fc0-2c4fe6b7b824
* Content: [Query limits - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits)
* Content Source: [data-explorer/kusto/concepts/querylimits.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/concepts/querylimits.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ChadNedzlek** [comment]
It is also a very confusing API, so using it correctly is incredibly difficult.  I've had to just start slapping "notruncation" on a lot of my queries because I don't know how to use the progressive mode, and that's presumably not ideal for my cluster.

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@ChadNedzlek Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
