### ISSUE TITLE
Description of example Kusto code is incorrect

### ISSUE THREAD

**Issue by richard-southworth-pico** [MicrosoftDocs/dataexplorer-docs#1149]
The statement quoted below seems to be referring to a different example than the one it is used to describe.
'The following example binds the name x using the ['name'] notion'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 741d0e14-4a3f-af28-1d6e-e6a6dd3dd414
* Version Independent ID: 731bbd4d-10c6-5cc4-741d-7cba31cb0586
* Content: [Let statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/letstatement)
* Content Source: [data-explorer/kusto/query/letstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/letstatement.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@richard-southworth-pico Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@richard-southworth-pico Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
