### ISSUE TITLE
Please update this page for ADX dashboards.

### ISSUE THREAD

**Issue by mitulmk** [MicrosoftDocs/dataexplorer-docs#115]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f5815d8-3946-1579-14a0-6f1b94f2daf2
* Version Independent ID: 0b9bfbd9-0b00-f27c-0800-cc6a4b8e40d3
* Content: [Azure Data Explorer data visualization](https://docs.microsoft.com/en-us/azure/data-explorer/viz-overview)
* Content Source: [data-explorer/viz-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/viz-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your feedback. This has been assigned to the content owner , @orspod  and will be updated as appropriate.

**Comment by orspod** [comment]
@mitulmk - thanks for your feedback. The following PR was created to add the ADX dashboards to the viz overview page: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/357
Closing this issue.
