### ISSUE TITLE
In step 2 of the On-behalf-of authentication part, what is the accessToken?

### ISSUE THREAD

**Issue by v-weijiexu** [MicrosoftDocs/dataexplorer-docs#1150]
[Enter feedback here]
In step 2 of the On-behalf-of authentication part, what is the accessToken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee89d0d7-becd-83f4-b862-f39b1c1ad6d4
* Version Independent ID: d40d3446-9677-dbdc-faa9-f04a30ffb042
* Content: [Authenticate with Azure AD for access - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad)
* Content Source: [data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by shsagir** [comment]
@v-weijiexu Thanks for your question. As stated in step 2, it's "the access token **acquired in the first step as a proof of identity** to Azure Data Explorer". So it refers to the access token created in step 1c. Hope that answers your question. In the meantime, I'm closing this issue. You can @comment me if you have any further questions relating to this issue. Thanks again.

#please-close
