### ISSUE TITLE
Variable name inconsistent

### ISSUE THREAD

**Issue by iwafula025** [MicrosoftDocs/dataexplorer-docs#1159]
while inconsequential, I believe the second example should to be "AvailableMB" instead of "AvailableMD"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01a9498f-3bba-5479-e7d7-32cc4d96c15a
* Version Independent ID: 198ef7fc-f118-3f0d-0c9b-366d3e008be0
* Content: [extract_json() and extractjson() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractjsonfunction)
* Content Source: [data-explorer/kusto/query/extractjsonfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/extractjsonfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shashishailaj** [comment]
@iwafula025 
Thank you for your feedback . We will investigate and update the thread.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@iwafula025 Thanks for pointing out the issue, I've addressed this issue in PR:[https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/3061](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/3061) 
The changes should be live soon. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.
