### ISSUE TITLE
Please update this page now that we have native ADX dashboards.

### ISSUE THREAD

**Issue by mitulmk** [MicrosoftDocs/dataexplorer-docs#116]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8744d097-8c1f-725a-358b-c39b6db2e5c3
* Version Independent ID: f412568f-e983-12be-3b07-e85bd2385b85
* Content: [Azure Data Explorer tools - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/)
* Content Source: [data-explorer/kusto/tools/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/index.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by orspod** [comment]
@mitulmk - thanks for the feedback. We will be removing this page shortly. I am now closing this issue.
