### ISSUE TITLE
Missing instructions on setting/modifying 'All Databases *' roles

### ISSUE THREAD

**Issue by msftyehong** [MicrosoftDocs/dataexplorer-docs#1160]
Missing references to how one can set/modify 'All Databases admin', 'All Databases viewer' and 'All Databases monitor' roles. Reference below the table https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/security-roles#managing-database-security-roles links to a page that only shows how one can manage security roles at database, table, materialized view and function. But not cluster. Can you link to the proper page or update existing page to show how one can set/modify 'All Databases *' roles view KQL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143622e5-86cc-6eeb-f9b8-c53336867149
* Version Independent ID: ddda3c76-6945-5c73-6acd-c0d8b4a64c75
* Content: [Manage database permissions in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/manage-database-permissions)
* Content Source: [data-explorer/manage-database-permissions.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/manage-database-permissions.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@msftyehong  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by shsagir** [comment]
@msftyehong Thanks for contacting us with feedback about our product documentation. We are looking into your issue. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by orhasban** [comment]
@msftyehong AllDatabases* (Admin, Viewer, Monitor) are all types of Kusto ARM resource which is called clusterPrincipalAssignments. 

This resource can be managed in every form that uses ARM API:

UI – Azure portal.

 
![image](https://user-images.githubusercontent.com/39991747/170479959-dd25209a-2097-4630-8131-3bcd36c9d2ed.png)


Programmatically – all Azure resource manager SDKS:

•	Azure PowerShell 
•	Azure CLI
•	C#
•	Java
•	JS
•	Python
•	Go
•	…

Official docs for cluster principal assignments resource: [Cluster Principal Assignments - REST API (Azure Azure Kusto) | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/azurerekusto/cluster-principal-assignments)

**Comment by msftyehong** [comment]
@orhasban I understand from your response this specific set of permissions cannot be controlled Azure Data Explorer using KQL 
 language (the interface I asked about). Thank you for sharing information regarding other ways to control these permissions. 
 
 Consider updating into docs if you see fit. 
 
 Can close the case as far as I'm concerned.

**Comment by shsagir** [comment]
@msftyehong Thanks again for your feedback. Following on from @orhasban response, we are closing this issue.
#please-close
