### ISSUE TITLE
Calling series-metric-fl() breaks IDE in Azure Log Analytics blade

### ISSUE THREAD

**Issue by FoxSpirit77** [MicrosoftDocs/dataexplorer-docs#1161]
Concerned function/document:
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/functions-library/series-rate-fl

I am using the function in a Azure Log Analytics blade and after calling it, the IDE breaks.
ReferenceError: UnknownIdentifierResolveResult is not defined

After using this in code, none of the IDE functions work, it turns into a basic text editor.

** Added page metadata **

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee77f6d0-fb78-8a66-4be4-6245cea3162f
* Version Independent ID: 18d57170-e9fe-5309-3350-a1fa3092106d
* Content: [series_rate_fl() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/functions-library/series-rate-fl?tabs=adhoc)
* Content Source: [data-explorer/kusto/functions-library/series-rate-fl.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/functions-library/series-rate-fl.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by FoxSpirit77** [comment]
Very sorry for the error, it's series-rate-fl(), not series-mertic-fl(). Metric is fine.

**Comment by ShaikMaheer-MSFT** [comment]
@FoxSpirit77 Yes typo in function name it seems. 

Please Note, GitHub forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilise Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html)

**Comment by FoxSpirit77** [comment]
Okay, did that. Many thanks :-)

**Comment by FoxSpirit77** [comment]
Just to clarify, this is not a query or need for clarification, this is a bug.
