### ISSUE TITLE
this example doesn't work in AI logs query :-(

### ISSUE THREAD

**Issue by diligent176** [MicrosoftDocs/dataexplorer-docs#117]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f88f51d0-abca-00ac-4ab4-bbe18fc984d5
* Version Independent ID: abb505b3-e5b0-31f4-2542-fd5d41b58b0e
* Content: [T-SQL - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/tds/t-sql)
* Content Source: [data-explorer/kusto/api/tds/t-sql.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/tds/t-sql.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by diligent176** [comment]
using "explain" to translate T-SQL to Kusto doesn't work for me

**Comment by Mike-Ubezzi-MSFT** [comment]
@diligent176 Thank you for providing this feedback. Can you provide a screen capture that details how you are attempting this?

![Screenshot (31)](https://user-images.githubusercontent.com/37126106/83216693-bbcbae00-a11e-11ea-905c-dcf33685dc4a.png)

The following:

>explain
select top(10) * from StormEvents order by DamageProperty desc

Outputs the equivalent KQL:

>StormEvents
| project StartTime, EndTime, EpisodeId, EventId, State, EventType, InjuriesDirect, InjuriesIndirect, DeathsDirect, DeathsIndirect, DamageProperty, DamageCrops, Source, BeginLocation, EndLocation, BeginLat, BeginLon, EndLat, EndLon, EpisodeNarrative, EventNarrative, StormSummary
| sort  by DamageProperty desc nulls first
| take int(10)

**Comment by diligent176** [comment]
I'm trying to use this syntax in Azure Portal, in Logs section of Application Insights.
Maybe I'm misunderstanding, is it not part of the Kusto query language? 
![image](https://user-images.githubusercontent.com/7737939/83275264-cb311280-a183-11ea-93a9-7a835e38046e.png)

**Comment by Mike-Ubezzi-MSFT** [comment]
@diligent176 You would need to use the [Kusto.Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer) desktop client. Can you connect to `jb51588awesone` with the Kusto Explorer client as per this document: [Query data in Azure Monitor using Azure Data Explorer (Preview)](https://docs.microsoft.com/en-us/azure/data-explorer/query-monitor-data)
There is some functionality that is specific to Azure Monitor that will not work with Kusto Explorer but if you are looking for the the `explain` functionality, you will need to execute this in the Data Explorer (Kusto) client. Please let me know if you have additional questions.

**Comment by Mike-Ubezzi-MSFT** [comment]
@diligent176 We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
