### ISSUE TITLE
.create function with (docstring = 'Demo function with parameter', folder='Demo')  MyFunction2(myLimit: long)  {StormEvents | limit myLimit}

### ISSUE THREAD

**Issue by g9K5ZTr0** [MicrosoftDocs/dataexplorer-docs#1171]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a1c45a-851f-b06f-9258-412aac797750
* Version Independent ID: 7f8c7702-129c-62b8-2a8f-d893aa96c848
* Content: [repeat() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/repeatfunction)
* Content Source: [data-explorer/kusto/query/repeatfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/repeatfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@g9K5ZTr0 Could you please share more details on your feedback on this document?

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@g9K5ZTr0  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
