### ISSUE TITLE
Cannot add this document to collection at docs.microsoft.com

### ISSUE THREAD

**Issue by yamakenrc5** [MicrosoftDocs/dataexplorer-docs#1176]
It looks like I cannot add this document to my collection. I confirmed this page behavior with my iPhone and Windows 10 PC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb28ce95-83a3-dcb7-5c37-f4efbbff1dc6
* Version Independent ID: d7fd65d3-33d0-7dd4-6c83-6842fa5cc334
* Content: [database() (scope function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/databasefunction?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/databasefunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/databasefunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@yamakenrc5  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

@shsagir As per my repro from my end, we are unable to add this document to my collection and when I click on save it keeps on rotating and it never stops or save it.

Note: We are able to save other docs under the special functions section. 

![image](https://user-images.githubusercontent.com/79183421/167766332-728651b2-a9b8-4123-a7b7-b3a7e47226c4.png)

**Comment by shsagir** [comment]
@yamakenrc5 Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@yamakenrc5  Thanks so much for taking the time to leave us your feedback. We're investigating the issue.
We're closing this issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close

**Comment by shsagir** [comment]
@yamakenrc5 We've investigated and resolved the issue and you should now be able to add the article to your collection. To follow up on this issue, leave us a comment with an @mention.
