### ISSUE TITLE
examples not helpful

### ISSUE THREAD

**Issue by FaronFaulk** [MicrosoftDocs/dataexplorer-docs#1181]
examples not helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c70cf14e-e42f-392b-c7b8-4616574e2f33
* Version Independent ID: 0b04f427-098d-0602-5c02-3d4a71b292c5
* Content: [The timespan data type - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan)
* Content Source: [data-explorer/kusto/query/scalar-data-types/timespan.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/scalar-data-types/timespan.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for your feedback. 
Can you please share what do you think is missing and what can be done to improve the doc?

**Comment by Karishma-Tiwari-MSFT** [comment]
We will now close this issue. Please share the details when you get a chance and tag me in a comment. I will reopen it and we will gladly continue the discussion.
