### ISSUE TITLE
Incorrect link in documentation

### ISSUE THREAD

**Issue by douggarding** [MicrosoftDocs/dataexplorer-docs#1188]
Under the [Retention Policy Control Commands section](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/retentionpolicy#control-commands), the link for ".alter policy retention" takes you to the wrong page. It takes you to the documentation for _showing_ the policy instead of the _altering_ the policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cd49bc5-70be-d992-82c5-5cfa04bda845
* Version Independent ID: 9d54dc33-a902-0b40-e36d-fe272f66a1d4
* Content: [Kusto retention policy controls how data is removed - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/retentionpolicy#control-commands)
* Content Source: [data-explorer/kusto/management/retentionpolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/retentionpolicy.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.
