### ISSUE TITLE
Add more details around clientId mentioned in the code snippets 

### ISSUE THREAD

**Issue by nikhilboreddy** [MicrosoftDocs/dataexplorer-docs#119]
Please add more details around clientId mentioned in the code snippets. What level of perms should it have on the leader ADX cluster, follower ADX cluster? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7eb643f-96fa-ea4b-998c-fbbe012c497d
* Version Independent ID: 83e7ee0a-6376-924d-d777-4c312103bde7
* Content: [Use follower database feature to attach databases in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/follower)
* Content Source: [data-explorer/follower.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/follower.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@nikhilboreddy  Thanks for the feedback!  Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@docohe will you assist with the customer question?

**Comment by docohe** [comment]
In order to to attach a database, you should be a contributor/owner on both follower/leader. 
Will update the docs

**Comment by orspod** [comment]
@docohe thanks for the fix.
@nikhilboreddy thanks for the feedback. Hope this answered your question.
I will now close this issue. Feel free to respond if you have additional questions/concerns. Thanks!

**Comment by nikhilboreddy** [comment]
Thank you! Yes that answered my question.
