### ISSUE TITLE
Typo with word user

### ISSUE THREAD

**Issue by jeremylcarter** [MicrosoftDocs/dataexplorer-docs#1195]
Typo:

Sentence: "The current version of the SDK doesn't support interactive uer authentication on .NET Core. If required, use AAD username/password or application authentication instead."

Word: uer
Should be: user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82ebd2-f7f6-5068-54f2-69c7532b6b38
* Version Independent ID: 4727dbed-4e17-879b-d494-6ee62d78633a
* Content: [Ingest data with Azure Data Explorer .NET SDK](https://docs.microsoft.com/en-us/azure/data-explorer/net-sdk-ingest-data)
* Content Source: [data-explorer/net-sdk-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/net-sdk-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@jeremylcarter Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@jeremylcarter Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
