### ISSUE TITLE
Label the ADX virtual network

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1202]
Can I suggest labelling the "ADX virtual network" in the various diagrams on this page as "ADX managed virtual network" or similar to make it clear that it is not a regular virtual network. 
![image](https://user-images.githubusercontent.com/7891408/170604528-73d2d764-3f15-4c0a-9a29-2232e3b9efc1.png)

Also the statement in the Managed private endpoint section around "when a cluster is created Azure provisions a managed virtual network in the Microsoft backbone infrastructure which is hidden from users " I think needs to be added to the leading section at the top of the manage. Furthermore that leading section needs to mention managed private endpoints as well. At the moment that first section is talking about ingress to ADX only. 

![image](https://user-images.githubusercontent.com/7891408/170604988-29b3c547-0c0e-4871-97f6-4ffc6828eace.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af34f52-e08b-55b0-bfdd-6081b808e585
* Version Independent ID: 4e61b826-27ab-67be-e921-1656ec7f2777
* Content: [Private endpoints for Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/security-network-private-endpoint)
* Content Source: [data-explorer/security-network-private-endpoint.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/security-network-private-endpoint.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@pnarsi  Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
