### ISSUE TITLE
incomplete description of the conditions which start a new session

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#1205]
The paragraph that starts with 
> The condition that determines if the value represents a new session is a logical OR one of the following conditions:  

describes 3 conditions upon which a new session is started.  
It misses a 4th given by the *Restart* parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ced7b0-4d88-798d-b83b-881c06fc9c7e
* Version Independent ID: 10b55046-8597-a047-c980-6ef5b1ae5366
* Content: [row_window_session() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/row-window-session-function)
* Content Source: [data-explorer/kusto/query/row-window-session-function.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/row-window-session-function.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ciufudean Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ciufudean  Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
