### ISSUE TITLE
Mention Managed VNET/Managed Private Endpoint/Callout Policy in Network Security

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1207]
The Network security section of this page talks about VNet Injection only. I think it needs to highlight the Managed VNET + Manage Private Endpoint + callout policies as well as an option and include a link to the overview page: https://docs.microsoft.com/en-us/azure/data-explorer/security-network-private-endpoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4941c2-5157-9da2-83bd-de7541fdec63
* Version Independent ID: e32184c5-13fa-c8e9-04f5-2913b67b9ea8
* Content: [Secure Azure Data Explorer clusters in Azure](https://docs.microsoft.com/en-us/azure/data-explorer/security#network-security)
* Content Source: [data-explorer/security.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/security.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and add the above details.

**Comment by shsagir** [comment]
@pnarsi  Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by cosh** [comment]
fixed it. thx for reporting it

**Comment by pnarsi** [comment]
@cosh @shsagir - that looks better.
