### ISSUE TITLE
additionalProperties are actually supported by the ADF GUI

### ISSUE THREAD

**Issue by dumarkov** [MicrosoftDocs/dataexplorer-docs#1208]
As can be seen in the ADF documentation, additionalProperties are supported for ADX as a sink in a COPY operation, as part of the GUI. No need to manipulate the JSON manually.

https://docs.microsoft.com/en-us/azure/data-factory/connector-azure-data-explorer?tabs=data-factory#azure-data-explorer-as-sink

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03f0356-b30b-b4e9-3413-d0f24a18043b
* Version Independent ID: b138689b-50aa-053a-c3aa-e34a488e3d73
* Content: [Azure Data Explorer integration with Azure Data Factory](https://docs.microsoft.com/en-us/azure/data-explorer/data-factory-integration#specify-additionalproperties-when-copying-to-azure-data-explorer)
* Content Source: [data-explorer/data-factory-integration.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/data-factory-integration.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@dumarkov  Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ Thanks so much for taking the time to leave us your comment on our documentation. We're working on changing the docs based on your feedback that will be added in the next possible publish.

It may take a little while. In the meantime, we're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
