### ISSUE TITLE
the sentence for stored functions doesnt make sense

### ISSUE THREAD

**Issue by jocawtho** [MicrosoftDocs/dataexplorer-docs#1210]
https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/functions/index.md

This phrasing doesnt make sense to me, should it be fixed?
Stored functions, which are user-defined functions **that are stored and managed a one kind of a database's schema entities**. See [Stored functions](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/schema-entities/stored-functions.md).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c43b56-2c34-bc9b-1e29-65be71193b7a
* Version Independent ID: 1ca83fd2-dcde-6ef8-5650-a32b863a9e7e
* Content: [Functions - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/functions/)
* Content Source: [data-explorer/kusto/query/functions/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/functions/index.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by JamesTran-MSFT** [comment]
@jocawtho 
Thanks for your feedback! We will investigate and update as appropriate.
