### ISSUE TITLE
Configuring ZRS for ADX

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1215]
The "Persistent layer" section mentions that the service leverages Azure Storage which by default uses LRS within a data center. However it goes on to mention that ZRS can be configured at additional cost. Is there a link that explains how exactly ZRS can be configured for ADX? Is it automatically enabled if a ADX cluster is configured to deployed across multiple Availability Zones. A link to page that explains this setting in more details would be useful. 

![image](https://user-images.githubusercontent.com/7891408/171769211-3269ffb1-f95e-42b1-806f-17165d28fdd4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c426719b-43df-8702-a573-9b1698439773
* Version Independent ID: d33d9114-7292-8487-a4c3-a3491b23c212
* Content: [Azure Data Explorer and business continuity disaster recovery](https://docs.microsoft.com/en-us/azure/data-explorer/business-continuity-overview#disaster-recovery-configurations)
* Content Source: [data-explorer/business-continuity-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/business-continuity-overview.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
@please-close

**Comment by YaelSchuster** [comment]
#please-close
