### ISSUE TITLE
Specify time interval for automatic stop of inactive ADX cluster

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1220]
The leading sentence of this page mentions that "Azure Data Explorer clusters that have been inactive for a **specified time interval** are automatically stopped". Can we actually specify a time interval for this automatic stop for inactivity or is it fixed at 5 days as per the second sentence? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bf2b6b-be24-51e4-1458-dbbe00e09624
* Version Independent ID: e8901776-7721-7160-0efa-8512904ba87f
* Content: [Automatic stop of inactive clusters in Azure Data Explorer](https://docs.microsoft.com/en-au/azure/data-explorer/auto-stop-clusters)
* Content Source: [data-explorer/auto-stop-clusters.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/auto-stop-clusters.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by shsagir** [comment]
@pnarsi Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
