### ISSUE TITLE
This page should have a link to the aggregation functions types

### ISSUE THREAD

**Issue by ChristopherLeitner** [MicrosoftDocs/dataexplorer-docs#1221]
This page should contain a link to https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/aggregation-functions
As is, the only way to find that page is to manually search for one of the functions used in the programming samples and then go from there.

Also a suggestions: put important, related links at the top of the page. As is, if there are any links, they are always at the very end of the text. Not only have you to scroll down, but it prevents you seeing hints to important further information at a glance whenever you enter a page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cede3d6d-4803-358f-c3b3-11f8c407c878
* Version Independent ID: 9064e163-b02a-6030-dcc4-eddab6fa31cd
* Content: [summarize operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/summarizeoperator#feedback)
* Content Source: [data-explorer/kusto/query/summarizeoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/summarizeoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@ChristopherLeitner Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by ShaikMaheer-MSFT** [comment]
@shsagir Could you please validate customer feedback and update document as appropriate? Thank you.

**Comment by ChristopherLeitner** [comment]
Yes, thank you. Link works great and is in a good place.

**Comment by shsagir** [comment]
@ChristopherLeitner Thanks for your feedback. In the description of the _aggregation_ argument, there is a link to the aggregations' functions page. 

#please-close
