### ISSUE TITLE
Does Tenant Permissions apply for data connections

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1222]
It is not clear from the documentation if the "define tenant permissions" feature documented on this page impacts on the cross tenant data connection feature on this other [page](https://docs.microsoft.com/en-au/azure/data-explorer/ingest-data-cross-tenant). 

For example if the "Define tenant permissions" setting on the UI is set to "My tenant only" as described on this page, will it block users from creating data connections to Event Grid or Event Hubs in other tenants as described in the other page linked above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79b284a-66a1-e13b-f34d-62a728c4863f
* Version Independent ID: d797686f-e457-b5bc-3377-caf77d4e7ae6
* Content: [Allow cross-tenant queries and commands in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/cross-tenant-query-and-commands?tabs=portal)
* Content Source: [data-explorer/cross-tenant-query-and-commands.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/cross-tenant-query-and-commands.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thank you for sharing feedback. We will share updates soon.

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by cosh** [comment]
Thx!! created a PR

**Comment by YaelSchuster** [comment]
Thanks @cosh. Closing the issue at this time.

**Comment by YaelSchuster** [comment]
#please-close
