### ISSUE TITLE
Setting My tenant only via API

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1223]
The documentation shows that via the Portal Interface tab we can set tenant permissions to either my tenant, all tenants or specific tenants. 

![image](https://user-images.githubusercontent.com/7891408/173008063-caccd138-5b5f-44fe-86e9-f02470a04309.png)

However when we switch to the API it talks about settings permissions to all tenants or specific tenants only. There is no mention how how to restrict it to my tenant only. The note in the purple mentions that an empty array isn't supported. So I assume that we need to actually specify the guid of my specific tenancy in order restrict it to my tenant only? If so it would be helpful to include this in the documentation. 

Futhermore it would be helpful to mention in the ARM template documentation as well that by default the **trustedExternalTenants** setting permits trusts all tenants. 

![image](https://user-images.githubusercontent.com/7891408/173009138-942d4080-b917-4e6d-b81c-41292b01a61e.png)

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
#please-close
