### ISSUE TITLE
Cannot save this page to collections

### ISSUE THREAD

**Issue by yamakenrc5** [MicrosoftDocs/dataexplorer-docs#1224]
[Enter feedback here]
Tried to save this document to a collection under docs.microsoft.com, and found I cannot save this page, the round icon just moves around and does not let me save the page to my collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103728d9-415c-551e-ca55-7bd70a0894f0
* Version Independent ID: f88b2b51-a787-585b-708b-6b333fbdfe49
* Content: [substring() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/substringfunction)
* Content Source: [data-explorer/kusto/query/substringfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/substringfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@yamakenrc5 Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by briandunnington** [comment]
This was due to an Akamai WAF configuration issue. It has been resolved and I verified that the content can be added to collections now.
