### ISSUE TITLE
I'm using KQL for almost a year, love it and familiar with the different functions. But I have to say that the Syntax column here is VERY unclear, the different brackets are not clear, for functions I'm using (all of them) - I don't understand the Syntax explanation. Maybe consider providing examples.

### ISSUE THREAD

**Issue by EitanSht** [MicrosoftDocs/dataexplorer-docs#1227]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95c35535-c41f-5fcb-e4a0-2ad29a9f9b9d
* Version Independent ID: d43ad025-70be-142b-9d76-b6f9bacc3768
* Content: [KQL quick reference](https://docs.microsoft.com/en-us/azure/data-explorer/kql-quick-reference)
* Content Source: [data-explorer/kql-quick-reference.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kql-quick-reference.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by MayankBargali-MSFT** [comment]
@EitanSht Thank you for your feedback! We will review and update as appropriate.

**Comment by shsagir** [comment]
@EitanSht Closing as no further information received.
To follow up on this issue, leave us a comment with an @mention.

#please-close
