### ISSUE TITLE
Other FQDN dependencies for clients accessing ADX UI

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1230]
This there a page that documents all of the FQDN dependencies for clients accessing ADX from a private network including those that are **not** exposed as private endpoints?

For example when accessing the ADX UI in addition to the private endpoint FQDN I have also noticed the following FQDN being accessed from my browser which means that I would need to allow my clients to have outbound access to them via the internet as they are not accessible via private endpoint. Are the full list of FQDN dependencies documented somewhere? 

* dc.services.visualstudio.com
* dataexplorer.azure.com
* web.vortex.data.microsoft.com
* graph.microsoft.com
* login.microsoftonline.com
* amcdn.msftauth.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec266648-f748-a305-aaf3-6c0bcc565d62
* Version Independent ID: ed07efae-8508-d32b-dd02-b7fd25943111
* Content: [Create a private endpoint for Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/security-network-private-endpoint-create)
* Content Source: [data-explorer/security-network-private-endpoint-create.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/security-network-private-endpoint-create.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@shsagir Requesting to validate feedback and update document as appropriate. Thank you.

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by cosh** [comment]
to the best of my knowledge: no
reason: those are FQDNs which are needed by the portal to connect to ADX. We documented the FQDNs which are needed to run the service in case of vnet injection

**Comment by YaelSchuster** [comment]
Thanks, @cosh.

At this time, I'm closing the issue. If you have further questions, feel free to @mention myself or @cosh 
Thanks for your contributions!

**Comment by YaelSchuster** [comment]
#please-close

**Comment by pnarsi** [comment]
Thanks @cosh @YaelSchuster - is there a separate page that documents the FQDN required by the portal to connect ADX? e.g. in the context of an end user accessing the ADX UI from a locked down environment where need to whitelist these required FQDN on a corporate Firewall?
