### ISSUE TITLE
Add link to Dashboard Permissions 

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1231]
Neither this page nor any of the other pages in this Access Control section mention the fact that there is also the ability to set permissions on dashboards. Adding a link to this page: https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards#share-dashboards I think would be helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45c884a3-485c-ba99-e387-d35fdfdb5432
* Version Independent ID: 94fefdd0-80a7-5992-5fc6-02e48e713699
* Content: [Role-based Authorization in Kusto - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/role-based-authorization)
* Content Source: [data-explorer/kusto/management/access-control/role-based-authorization.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/access-control/role-based-authorization.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by cosh** [comment]
thx for the feedback. this doc is focused on roles which apply to the data plane. Not related to dashboards.

**Comment by YaelSchuster** [comment]
#please-close
