### ISSUE TITLE
Include Diagram showing how the Storage Account, Event Grid and Event Hub work in this scenario

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1233]
It would be helpful to include a diagram that provides an overview of how the four services mentioned in this scenario (Storage Account, Event Grid, Event Hub, and ADX) work together. 

Something similar to the below: 

![image](https://user-images.githubusercontent.com/7891408/173718147-2ee4a2ec-2b10-46b1-935b-7d4dee903084.png)

A diagram would also make it clear how this integration could be configured in a ADX private endpoint deployment model i.e. there is no direct Event Grid to ADX connectivity, ADX only needs managed private endpoints to be created for Event Hub and Storage Account with callout policies safelisting the specific Event Hub and Storage Accoutn FQDN. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16dc65a-b98e-a872-a5a2-6c0295577827
* Version Independent ID: 40c59405-281f-c945-0a9d-f762a9dbe442
* Content: [Ingest from storage using Event Grid subscription - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-grid-overview)
* Content Source: [data-explorer/ingest-data-event-grid-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/ingest-data-event-grid-overview.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@pnarsi Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

You can track progress on work item: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1964359

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
