### ISSUE TITLE
Authentication Method

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1236]
In addition to authentication methods mentioned in the screenshot below (from this page) there is also an option to use Managed Identity (User or System assigned) as well which is probably the most secure option as there are no credentials involved - https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/tests/sample.py#L48

![image](https://user-images.githubusercontent.com/7891408/174241104-b552c8cd-f3b0-4f3d-84fa-ff33e2cf69ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c010923-e011-6915-e3c4-6265fb997c35
* Version Independent ID: 6b102d99-8aae-bba3-0ddf-d4137c3d6434
* Content: [Ingest data using the Azure Data Explorer Python library](https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data)
* Content Source: [data-explorer/python-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/python-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
This has been updated in the attached PR
#please-close
