### ISSUE TITLE
Missing Ingest Action in Table

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1238]
I believe that the summary of supported actions at the top of this page is missing the [INGEST Action](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/streaming-ingest)

![image](https://user-images.githubusercontent.com/7891408/174509024-3af65382-c422-4611-b29a-0782c0c3aeba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72676865-17c0-16aa-6ff7-3ef2e3b961dc
* Version Independent ID: 80c163bb-3e28-9b67-855c-4ed7eaa272dc
* Content: [RESTful web API overview - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/)
* Content Source: [data-explorer/kusto/api/rest/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/rest/index.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
This missing information has been addressed in the above tagged PR. It will go live over the next 1-2 days. @pnarsi thanks for your contribution!

#please-close
