### ISSUE TITLE
Connectivity to Blob, Table and Queue Endpoints

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1245]
This page mentions that in addition to the query and ingestion endpoints ADX comes with several FQDNs for blob, table, queue endpoints for ingestion scenario. Is there page that goes into how these blob, table and queue endpoints are used for ingestion in more detail? There are many ways to ingest data into ADX (Custom Streaming, Event Grid, Event Hub, IoT Hub, SDK, Event Hub, etc, LightIngest, One click ingestion, etc) - is connectivity to these blob, table and queue FDQN required in all of these scenarios? In a realistic enterprise scenario there would be firewall rules that restrict ingress to private endpoint - having more details around the specific scenarios these FQDNs for blob, table, queue endpoints are used would be helpful in include in the documentation.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af34f52-e08b-55b0-bfdd-6081b808e585
* Version Independent ID: 4e61b826-27ab-67be-e921-1656ec7f2777
* Content: [Private endpoints for Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/security-network-private-endpoint#connect-to-a-private-endpoint)
* Content Source: [data-explorer/security-network-private-endpoint.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/security-network-private-endpoint.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@pnarsi Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close

**Comment by shsagir** [comment]
#please-close
