### ISSUE TITLE
Power Automate with Private Endpoint ADX 

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1246]
Does the Power Automate connector work with private endpoint enabled ADX cluster (i.e where public connectivity is blocked)? I assume that in order to enable this use case we need to setup a [VNET Data Gateway](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-power-platform-dataflows#supported-data-sources) (which is still in preview) or possibly use an on premise data gateway (though it unclear from the on premise data gateway [documentation](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-power-platform-dataflows#supported-data-sources) if this is actually technically possible)

There is no mention on this page around any limitations or additional configuration required if the ADX cluster is **not** publicly accessible. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97d2864-59a3-b492-116e-cb3d34272916
* Version Independent ID: 4e604cdc-c8fb-8f09-f299-d575404f7e66
* Content: [Azure Data Explorer connector for Power Automate](https://docs.microsoft.com/en-au/azure/data-explorer/flow)
* Content Source: [data-explorer/flow.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/flow.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks @cosh for your response.

@pnarsi at this time I'm closing this issue. Feel free to reach out by @mention me for further issues.

#please-close

**Comment by YaelSchuster** [comment]
#please-close
