### ISSUE TITLE
Add Link to Github page for output plugin

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1251]
I believe this page is missing the link to the Logstash Output Plugin for Kusto documentation. It would be helpful to include it in this article. https://github.com/Azure/logstash-output-kusto.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ca34fa-96ef-e2f3-4758-667c8d1c21da
* Version Independent ID: 816b41a3-3fe6-19fd-8194-42d6e96089f2
* Content: [Ingest data from Logstash to Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-logstash)
* Content Source: [data-explorer/ingest-data-logstash.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/ingest-data-logstash.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Link has been added
#please-close

**Comment by YaelSchuster** [comment]
#please-close
