### ISSUE TITLE
Incorrect Link to how to guide to Enable CMK 

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1253]
I believe that while ADX stores data in Azure Storage which is encrypted at rest by default using Microsoft managed keys, enabling ADX to use a CMK to encrypt data stored in the Azure Storage is actually managed via ADX rather than via the Azure Storage (which is hidden to customer). 

Therefore this link to "Use your own customer-managed key" actually makes no sense in the context of ADX as it is currently pointing to the [Azure Storage documentation](https://docs.microsoft.com/en-us/azure/storage/common/customer-managed-keys-overview) on how to enable CMK. It probably should be pointing to this ADX specific CMK page instead: https://docs.microsoft.com/en-us/azure/data-explorer/customer-managed-keys-portal

![image](https://user-images.githubusercontent.com/7891408/175439623-98e89f3f-08b0-4142-9d63-045429e657dd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf4f16b8-0084-0e9e-bf4a-a4aa6ff1ea20
* Version Independent ID: 8229462a-5b32-4a72-eb90-7b7f4b4c867f
* Content: [Secure your cluster with encryption in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/cluster-encryption-overview)
* Content Source: [data-explorer/cluster-encryption-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/cluster-encryption-overview.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Link updated in PR referenced above

**Comment by YaelSchuster** [comment]
#please-close
