### ISSUE TITLE
Are Dashboards and Dashboard-related metadata encrypted at rest via CMK

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1254]
According the note in blue at the top of the page, "Dashboards and dashboard-related metadata about users is encrypted at rest." If our ADX cluster is configured to encrypt data at rest using a CMK as described on this [page](https://docs.microsoft.com/en-us/azure/data-explorer/customer-managed-keys-portal), would this CMK also be used for the Dashboard and related metadata encryption as well? 

It is unclear from the documentation on this page as well as the [cluster encryption overview](https://docs.microsoft.com/en-us/azure/data-explorer/cluster-encryption-overview) page if CMK applies for dashboards and related metadata as well. 

![image](https://user-images.githubusercontent.com/7891408/175440310-b5aa1ca7-ea67-4f0b-9d64-491a426c20c1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1640-3699-8fdf-07a2-c9b922499c90
* Version Independent ID: 55027537-6af4-541d-da8d-e2cdc2b5fa92
* Content: [Visualize data with the Azure Data Explorer dashboard](https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards)
* Content Source: [data-explorer/azure-data-explorer-dashboards.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/azure-data-explorer-dashboards.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Updated in  Pull Request #3267

#please-close
