### ISSUE TITLE
Prereqs for this How to Guide

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1255]
The prerequisites section is missing from this how to guide. Is it the same as what is documented in the excel query pages (screenshot below)? Specifically I assume we need to have an organization email account that is a member of the AAD directory and has permissions on the ADX database that is being connected to? 

![image](https://user-images.githubusercontent.com/7891408/175475506-16a6dbbd-c44a-4e90-a965-816b4b99fadb.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab47fc29-e55f-b6f8-4904-ff531c49feac
* Version Independent ID: c46ee3de-cfdf-4e54-a375-088e389866d0
* Content: [Visualize data using the Azure Data Explorer connector for Microsoft Excel](https://docs.microsoft.com/en-us/azure/data-explorer/excel-connector)
* Content Source: [data-explorer/excel-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/excel-connector.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@pnarsi Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by YaelSchuster** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
hi @pnarsi, This depends on if you are sharing data in a free cluster - in which you only need a MS-linked email address, or using a paid cluster, which will require an organization email account that is a member of the AAD directory and has permissions on the ADX database that is being connected to.

I have opened a work item to update these prereqs

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1964539

#please-close
