### ISSUE TITLE
Outdated path to Kusto.Data.dll.

### ISSUE THREAD

**Issue by centis** [MicrosoftDocs/dataexplorer-docs#1259]
It seems that starting with Microsoft.Azure.Kusto.Tools/6.0.0-preview there are multiple versions of the binaries in the tools directory for different versions of .NET; ie: net5.0, net572, etc.  This change breaks the Add-Type command below.

Add-Type -LiteralPath "path\Kusto.Data.dll"

You might also include instructions for installing the necessary runtime.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2df80c7-1cca-9c8d-0ed5-05b387e1850f
* Version Independent ID: d3f5e3ed-dc62-ca1a-c821-4ca25453fa0f
* Content: [Kusto .NET Client Libraries from PowerShell - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell)
* Content Source: [data-explorer/kusto/api/powershell/powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/powershell/powershell.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Hi @centis, thanks for the input. We are currently working on updating these docs. In the meantime, you can use the following syntax:

$packagesRoot = "C:\Users\salevy\Downloads\microsoft.azure.kusto.tools.6.0.3\tools\<version>\"
[System.Reflection.Assembly]::LoadFrom("$packagesRoot\Kusto.Data.dll")

#please-close
