### ISSUE TITLE
Authentication Error on blob?

### ISSUE THREAD

**Issue by xmorera** [MicrosoftDocs/dataexplorer-docs#126]
The [Ingest JSON formatted sample data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language) page references two JSON files that are hosted within kustosamplefiles.blob.core.windows.net/jsonsamplefiles:  **_simple.json_** and **_multilined.json_**.

However, these links appear not to work to Data Explorer users—authentication issues. These are the two links:

```
https://kustosamplefiles.blob.core.windows.net/jsonsamplefiles/simple.json?st=2018-08-31T22%3A02%3A25Z&se=2020-09-01T22%3A02%3A00Z&sp=r&sv=2018-03-28&sr=b&sig=LQIbomcKI8Ooz425hWtjeq6d61uEaq21UVX7YrM61N4%3D
```
```
https://kustosamplefiles.blob.core.windows.net/jsonsamplefiles/multilined.json?st=2018-08-31T22%3A02%3A25Z&se=2020-09-01T22%3A02%3A00Z&sp=r&sv=2018-03-28&sr=b&sig=LQIbomcKI8Ooz425hWtjeq6d61uEaq21UVX7YrM61N4%3D
```
The error when trying to access them is:
```
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:96fe790f-b01e-010e-71ce-376211000000 Time:2020-06-01T04:37:30.4609123Z
</Message>
<AuthenticationErrorDetail>
Signature did not match. String to sign used was r 2018-08-31T22:02:25Z 2020-09-01T22:02:00Z /blob/kustosamplefiles/jsonsamplefiles/simple.json 2018-03-28
</AuthenticationErrorDetail>
</Error>
```

IMHO it would be really useful to have a blob that is accessible to non-Microsoft users for testing.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d5f8ab-85c7-19bf-d91a-e76e81c76d7b
* Version Independent ID: 161a10d8-fc7f-97e8-b13e-0ddc7dd4f3c6
* Content: [Ingest JSON formatted data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language)
* Content Source: [data-explorer/ingest-json-formats.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-json-formats.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by MartinJaffer-MSFT** [comment]
@xmorera  Thank you for bringing this issue to our attention.  I agree the blobs used for tutorials should be publicly accessible.  I will assign this to the content owner to update.

@orspod  Could you please make the sample data blobs public, and update the hyperlinks?  The current links are using expired SAS.

**Comment by orspod** [comment]
@kerend - can you please assist with this request?

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@kerend  Any update on the issue?

**Comment by orspod** [comment]
@xmorera we have a work item in place to update this doc as requested. Thanks for your feedback.

**Comment by orspod** [comment]
I am closing this issue. Link to [WI](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1736737)

**Comment by orspod** [comment]
Note: docs fixed: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1206
