### ISSUE TITLE
Would be better if there was a mention of the benefit or use case of the operator in summary or seperate section called use case

### ISSUE THREAD

**Issue by AMK2805** [MicrosoftDocs/dataexplorer-docs#1261]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0735a144-ec13-33fe-da6a-37b5f43fd85c
* Version Independent ID: a4d0c043-e081-9d66-792f-2d2464e0f873
* Content: [partition operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/partitionoperator)
* Content Source: [data-explorer/kusto/query/partitionoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/partitionoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YutongTie-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @AMK2805  Thanks for your input. I am updating docs to include further explanation and examples.

Tracking pull request to answer this request:
https://github.com/MicrosoftDocs/dataexplorer-docs/pull/1269

At this time I'm going to close the issue, but please feel free to reach out with further questions through new issues or by @mention myself.

Thanks

#please-close
