### ISSUE TITLE
Permissions to enable assignment of security roles

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1264]
What permissions does a user need to be able to actually assign a role to a user via  **.add database <TestDatabase> users ('aaduser=<user@contoso.com>')** as described on this page?  

Do they need to have Contributor at the Cluster level (via Azure RBAC) or is having admin permissions for the specific ADX secured resource (e.g Database or Table) sufficient?  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4526aa53-827b-abf4-d419-cea51c79c71b
* Version Independent ID: 73682729-2e9a-216f-5fb5-8e887ef93df2
* Content: [Security roles management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/security-roles#managing-database-security-roles)
* Content Source: [data-explorer/kusto/management/security-roles.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/security-roles.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
@pnarsi Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by cosh** [comment]
Azure RBAC and Kusto RBAC are decoupled from each other. You need to be an Admin on the database level or an AllDatabasesAdmin on the cluster level to change the security principals

**Comment by pnarsi** [comment]
Thanks @cosh. Looking into this a bit more, I believe that for a new cluster we also need to have Contributor Azure RBAC permissions (or a custom Azure RBAC role that gives **Microsoft.Kusto/Clusters/PrincipalAssignments/write** permissions) in order to actually first assign AllDatabaseAdmin permissions to a second user https://docs.microsoft.com/en-us/azure/templates/microsoft.kusto/2022-02-01/clusters/principalassignments?tabs=bicep. Subsequent principals assignment can be done by that second user who does not need any other privileged permissions.

**Comment by YaelSchuster** [comment]
@cosh @shsagir would you guys like to update the docs to clarify this?

**Comment by YaelSchuster** [comment]
I have added a note to the doc to clarify this.

#please-close
