### ISSUE TITLE
Wrong date in the example

### ISSUE THREAD

**Issue by noamhalamish90** [MicrosoftDocs/dataexplorer-docs#1265]
[Enter feedback here]

In Backfill a materialized view section, the date in the example is 2019-01-01 while the description says 2020-01-01
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a80bf02-94d1-8ba9-87d5-7eb879b3f193
* Version Independent ID: 775199fd-18a8-c173-27f1-c44d533e4697
* Content: [Create materialized view - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-create#examples)
* Content Source: [data-explorer/kusto/management/materialized-views/materialized-view-create.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/materialized-views/materialized-view-create.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
@noamhalmish90 thanks for noticing that! I've updated the file to correct

#please-close
