### ISSUE TITLE
Immutable callout policies cannot be modified

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1267]
I am a bit confused by some of the commentary on this page. Under the "Types of callout policies" sections it mentions that Immutable callout policies "are standard policies of a cluster. They are preconfigured and **can't be modified.**" which implies that these are baked in policies that cannot be edited or deleted.

![image](https://user-images.githubusercontent.com/7891408/176111670-c68faead-14ee-4a71-8e9d-1304ef8a96db.png). 

However further down there is an entire section that talks about emptying the list of immutable callout policies. So we can actually mutate the immutable callout policies?    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9c5ddd-0e14-1f8b-079a-1781a5213a70
* Version Independent ID: 92f16016-9ad3-5f8e-f664-399a8e93cc2d
* Content: [Restrict outbound access from your Azure Data Explorer cluster](https://docs.microsoft.com/en-us/azure/data-explorer/security-network-restrict-outbound-access#empty-the-list-of-immutable-callout-policies)
* Content Source: [data-explorer/security-network-restrict-outbound-access.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/security-network-restrict-outbound-access.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pnarsi  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
@pnarsi  Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
At this time, I'm closing this issue. Please feel free to reach out with further questions by @mention myself or @cosh 

Thanks!

#please-close
