### ISSUE TITLE
Monitor Role

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/dataexplorer-docs#1271]
This may be a basic question so apologies in advance. With regards to the monitor role which is described as "Can execute .show commands in the context of the database and its child entities." Can a user assigned this role also run queries against the data in a table? 

It is a mentioned in this other [page](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/) that 'Control commands must start with the dot (.) character, and no query may start by that character' which to me implies that having .show execute permissions does not allow the user to query the data if they have the monitor role. I just want be sure that I am interpreting this correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45c884a3-485c-ba99-e387-d35fdfdb5432
* Version Independent ID: 94fefdd0-80a7-5992-5fc6-02e48e713699
* Content: [Role-based Authorization in Kusto - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/role-based-authorization)
* Content Source: [data-explorer/kusto/management/access-control/role-based-authorization.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/access-control/role-based-authorization.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
@pnarsi, yes that is correct. A monitor cannot execute data queries. 

#please-close
