### ISSUE TITLE
Can't use Kusto for beyond 500000 records results?

### ISSUE THREAD

**Issue by CharanCloud** [MicrosoftDocs/dataexplorer-docs#1272]
[Enter feedback here]
So Kusto is not useful for (500000) 5 Lakh+ records resultsets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fb5754b-a061-c650-0d44-40e233dd5f8e
* Version Independent ID: 05aded72-a24a-470d-b976-e8814aeaefc5
* Content: [Kusto query result set exceeds internal limit - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/resulttruncation)
* Content Source: [data-explorer/kusto/concepts/resulttruncation.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/concepts/resulttruncation.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
@CharanCloud - Result truncation is a limit set by default on the result set returned by the query. Kusto limits the number of records returned to the client to 500,000, and the overall data size for those records to 64 MB. When either of these limits is exceeded, the query fails with a "partial query failure". The limits make sure that a single query doesn't disrupt concurrent queries running on the cluster.

But you can still disable `result truncation` by using the `notruncation` command request option. But product team recommend that some form of limitation is still put in place.

`set notruncation;
MyTable | take 1000000`

For more info about query limits please refer to this doc: [Limit on result set size (result truncation)](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits#limit-on-result-set-size-result-truncation)

Hope this info helps.
