### ISSUE TITLE
Callout policies not respected for externaldata and externaltable queries

### ISSUE THREAD

**Issue by webczat** [MicrosoftDocs/dataexplorer-docs#1276]
Documentation talks about the "externaldata" kind of callout policies, which controls access to data on storage/sql using externaldata operator and external tables.
However, I have tested this with "restrict_outbound_access" setting set to "Enabled", which should make all externaldata callouts blocked by default unless whitelisted.
Yet, when there is no externaldata entry in callout policies, I am able to create and query an external table pointed to a storage account, and callout policies are not consulted. More specifically the query succeeds. The same happens with query using externaldata operator. I didn't test the case with externaldata to sql databases.
However, trying to perform data export (with or without an external table) is properly blocked by callout policies, I get an error that operation is denied by callout policy.
I am not sure if this is a service bug and all external table/externaldata usages should consult the callout policy, or if this is a documentation issue, as in if not sure if documentation shouldn't state callouts of type "externaldata" apply only to data export but not for retrieving data from storage...?
Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2e82a7-5c78-bfa2-25d6-c8add6b64271
* Version Independent ID: cb07a81c-e920-97d4-5eeb-f2e385257a3a
* Content: [Callout policy - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/calloutpolicy)
* Content Source: [data-explorer/kusto/management/calloutpolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/calloutpolicy.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
@webczat  Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Hi @webczat thanks for reaching out. I've checked with the engineering teams, and it turns out this is a bug. A fix will be deployed on your clusters within the next few weeks. 

Since there are no docs changes needed, I'm going to close this issue.

#please-close
