### ISSUE TITLE
Typo in Note at bottom of page

### ISSUE THREAD

**Issue by hvoerman** [MicrosoftDocs/dataexplorer-docs#1280]
Note

The daily period that can be also seen in the chart wasn't found **becasue** the sampling is too coarse (12h bin size), so a daily period of 2 bins is below the minimum period size of 4 points, required by the algorithm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4393ed0-5f93-4715-1b12-a7c6885c3a29
* Version Independent ID: 6ff5d7db-4a52-54a4-b99b-afacda4e1e67
* Content: [series_periods_detect() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/series-periods-detectfunction)
* Content Source: [data-explorer/kusto/query/series-periods-detectfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/series-periods-detectfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by VikasPullagura-MSFT** [comment]
@hvoerman Thanks for pointing this out. The document is updated, and changes will go live soon.
