### ISSUE TITLE
Would be great if the page on "union operator" explains how to include columns only from one leg, while retaining their order.

### ISSUE THREAD

**Issue by konrad-jamrozik** [MicrosoftDocs/dataexplorer-docs#1285]
Union operator can be used to simulate performing operations based on condition, as explained by [this StackOverflow answer](https://stackoverflow.com/a/70606783/986533). This is cool, but it gets really messy if the operations (function calls) are to return different sets of columns. You can see two proposed solutions to that problem [here](https://stackoverflow.com/a/72842527/986533) and [here](https://stackoverflow.com/a/67407876/986533).

The solutions are really hacky; they require packing, key set operations, unpacking, and, if one wishes to retain column order, also doing tons of "column_ifexists" and it still is not proper solution as it will result in exception if the result has no rows (for details, see [here](https://stackoverflow.com/a/72842527/986533)).

Here I am asking if there is a better, less complicated way of achieving the goal of "conditionally execute one of the operations, and include columns only from that operation, while retaining their order". I do strongly suspect there is currently no easy way to do it based on my read of this page. 

If there is such way of doing it, I ask to document it here. Even if there isn't, I think it would be great if this page documents the hacky way of doing it.

If the feature doesn't exist, I kindly request a to augment union operator to allow it. Something like: `union kind=evaluated` where it will include columns only from the evaluated leg, retaining their order. This way a call like this `union (funcA() | where flag), (funcB() | where not(flag))` would just work as expected, including only columns from the evaluated function, and requiring no packing or other funny business.

I also filed a my feature ask on the Azure Data Explorer user voice, [here](https://feedback.azure.com/d365community/idea/04af18ca-77fe-ec11-a81b-6045bd8606d4).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdae741d-890b-0d72-8873-1b5be2a72d74
* Version Independent ID: 4845e524-c60d-ebbd-94c7-05c075e5a177
* Content: [union operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/unionoperator)
* Content Source: [data-explorer/kusto/query/unionoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/unionoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@konrad-jamrozik  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
@konrad-jamrozik Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
@konrad-jamrozik Since this is a feature request, and not a documentation update, I'm going to close this Issue. 

#please-close
