### ISSUE TITLE
Return status not documented correctly in case the table already exists on .create

### ISSUE THREAD

**Issue by andreas-deruiter** [MicrosoftDocs/dataexplorer-docs#1288]
According to the .create command documentation:

**If the table already exists, the command will return success.**

This is not true. If you create a table - at least when using 'based-on' - the .create command returns an error message when the table already exists.

```
Error 

Entity 'MyTable' of kind 'Table' already exists.

clientRequestId: KustoWebV2;6c243c61-559d-478d-abda-2fb864b7fae3
```

Note: I would expect this to be a documentation issue, however I find it odd that no .create-or-replace command exists, so perhaps it is a product error. (As a work-around for not having .create-or-replace I could use .set-or-replace as instead, but then my new table wouldn't inherit the policies from the original table)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1839ab41-fb98-e337-df4c-e9ea2cccb471
* Version Independent ID: 3607ff00-6651-4dad-95c5-bb3e99772a5a
* Content: [.create table - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/create-table-command)
* Content Source: [data-explorer/kusto/management/create-table-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/create-table-command.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by VikasPullagura-MSFT** [comment]
@andreas-deruiter 
Thanks for your Question! We are currently investigating and will get back on this.

**Comment by ShaikMaheer-MSFT** [comment]
@andreas-deruiter Documentation actually means, when table already exists and if we try to run create command then you will get true that is table details back. I am not seeing any error when I tried same. So I feel all is good with document here. Kindly check below screenshot.
![image](https://user-images.githubusercontent.com/84302758/179246245-48eb27cb-be9d-4795-b83a-51c98d84e259.png)
Feel free to re-open issue and share more details along with screenshot about error. Thank you.

**Comment by andreas-deruiter** [comment]
OK, I think I figured it out. You only get an error when you use .create table with **based-on**.
