### ISSUE TITLE
range() | limitation on returned result

### ISSUE THREAD

**Issue by dumarkov** [MicrosoftDocs/dataexplorer-docs#1289]
We should add "Returns" section (similar to other function, e.g., round())  and note that the array returned by range()  is limited to 1,048,576 elements (2^20)

Example:

print r = range(1,100000000000, 1)
| mv-expand r
| count

//  Result: 1048576

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95fd7c2-de6d-c3b2-c166-bd8c49ee2192
* Version Independent ID: 1fe03afa-a3d4-6cf8-9a5a-a64871817589
* Content: [range() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/rangefunction)
* Content Source: [data-explorer/kusto/query/rangefunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/rangefunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by SaurabhSharma-MSFT** [comment]
@dumarkov Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @dumarkov - I'm going to contact you on teams about how to contribute to docs for internal MS people

#please-close
