### ISSUE TITLE
Ingesting JSON data - dynamic type size limit not mentioned (nor BigObject/BigObject32)

### ISSUE THREAD

**Issue by williamburns** [MicrosoftDocs/dataexplorer-docs#1291]
I think it would be useful to mention on this page that the `dynamic` field type has a default limit of 1MB. Although this is stated on its own field type page, when ingesting large JSON objects it is not immediately clear why it fails (no error message, just empty data), and this may provide a more obvious link.

It also isn't mentioned that you can apply an encoding policy update to `BigObject` or `BigObject32` type to handle larger ingestion (on either page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d5f8ab-85c7-19bf-d91a-e76e81c76d7b
* Version Independent ID: 161a10d8-fc7f-97e8-b13e-0ddc7dd4f3c6
* Content: [Ingest JSON formatted data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language#ingest-json-records-containing-arrays)
* Content Source: [data-explorer/ingest-json-formats.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/ingest-json-formats.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by MonikaReddy-MSFT** [comment]
@williamburns - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can review and update  accordingly.

**Comment by YaelSchuster** [comment]
Hi @williamburns, thanks for your suggestion. We appreciate your contribution to docs.

At this point, we aren't going to add more information on dynamic fields, as this doc is referenced and outside the scope of the how-to.

#please-close
