### ISSUE TITLE
replace_string() is not working

### ISSUE THREAD

**Issue by RishabhRishuGarg** [MicrosoftDocs/dataexplorer-docs#1296]
[Enter feedback here]
replace_string() is not working:
![image](https://user-images.githubusercontent.com/29625904/178479651-c2499be9-7bd9-46c9-bab3-726d9f022f35.png)

Error message: Please provide below info when asking for support: timestamp = 2022-07-12T11:03:47.2039720Z, correlationId = 11ed149c-25a4-4eb2-856c-bbf2bb1bd36f....: "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying. Unknown function: 'replace_string'. Failed to analyze expression for extended column ["newVISID"]..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fb6f05f-07aa-0c53-7aa3-415b58705647
* Version Independent ID: 991313f3-5fa4-96b1-516f-5c3cbf6fec89
* Content: [replace_string() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/replace-string-function)
* Content Source: [data-explorer/kusto/query/replace-string-function.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/replace-string-function.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by YaelSchuster** [comment]
@KranthiPakala-MSFT This is not a docs bug. @RishabhRishuGarg has been instructed on getting engineering help through internal channels.

#please-close
