### ISSUE TITLE
Ingestion Property Names and Values

### ISSUE THREAD

**Issue by gacurtin** [MicrosoftDocs/dataexplorer-docs#1302]
Can someone add all the Ingestion property names and values to this document?

```
.ingest [async] into table TableName SourceDataLocator [with ( _**IngestionPropertyName**_ = _**IngestionPropertyValue**_ [, ...] )]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8367589f-76cb-1a24-37d0-e4355594fb18
* Version Independent ID: 3455ea4f-4ce4-ee0d-007c-d4ca3b7ec89e
* Content: [Kusto.ingest into command (pull data from storage) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-from-storage)
* Content Source: [data-explorer/kusto/management/data-ingestion/ingest-from-storage.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/data-ingestion/ingest-from-storage.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
PR created to include these properties.

@gacurtin thanks for bringing this up. Your contributions help us improve our docs!
I'm going to close this issue at this time, but please feel free to reach out again with other docs improvements.

#please-close
