### ISSUE TITLE
rename columns does not work as described

### ISSUE THREAD

**Issue by willheineman** [MicrosoftDocs/dataexplorer-docs#1303]
The `.rename columns` function does not swap the name of 2 columns as described in the page.

Using the suggested command for renaming multiple columns results in an error message

**query I am executing**
.rename columns TimeGenerated_archive = myDB.sampleData.TimeGenerated

**expected result**
swap the name of the column `TimeGenerated_archive` and `TimeGenerated`

**error message**
Error during execution of a client request: Argument 'columnsToRename' failed to satisfy condition 'Columns rename supports currently only 2 columns': at .ctor in C:\source\Src\Engine\DataNode\Frontend\ControlCommands\ColumnsRenameCommand.cs: line 37

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43434d43-67a0-331e-9965-64e55fecd02b
* Version Independent ID: a421af93-b3ae-ded2-34cd-f11d0f00dfaf
* Content: [rename column - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/rename-column)
* Content Source: [data-explorer/kusto/management/rename-column.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/rename-column.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and provide an update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Hi @willheineman 
“.rename columns” syntax only supports _Exactly_ 2 columns, and also only works if used to swap the 2

Swap can be done like this:
.rename columns TimeGenerated_archive = myDB.sampleData.TimeGenerated, TimeGenerated = myDB.sampleData.TimeGenerated_archive,


I will update the docs to make this more clear.

At this time I'm closing the issue, please feel free to contact us with further docs questions!

#please-close
