### ISSUE TITLE
No AVRO doc at all??

### ISSUE THREAD

**Issue by appcrawler** [MicrosoftDocs/dataexplorer-docs#1309]
I tried to create an Avro mapping, which is mentioned in the docs as a possible configuration.  I am unable to get a working config, so I would like to request an enhancement to include this.

```
.create table Sales ingestion avro mapping 'Sales_AVRO_Mapping' '[{"Name":"txnid","datatype":"string","Ordinal":0},' 
                                                                 ' {"Name":"ts","datatype":"long","Ordinal":1},'
                                                                 ' {"Name":"sku","datatype":"string","Ordinal":2},'
                                                                 ' {"Name":"quantity","datatype":"int","Ordinal":3},'
                                                                 ' {"Name":"price","datatype":"int","Ordinal":4}]'
```

AvroToCsvMappingReference contains no mappings with both column name and Avro fields/paths.

---

I tried to create a mapping with an Avro schema, and it complained about what is a valid Avro schema.

.create table Sales ingestion avro mapping 'Sales_AVRO_Mapping'
'{'
  '"type": "record",'
  '"name": "value_sales_s",'
  '"namespace": "sales_stream",'
  '"fields": ['
  '  {"name": "txnid","type": "string"},'
  '  {"name": "ts","type": "long"},'
  '  {"name": "sku","type": "string"},'
  '  {"name": "quantity","type": "int"},'
  '  {"name": "price","type": "int"}'
  ']'
'}'

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0013a7e-ee3a-6be5-64eb-a38b5f6c03a8
* Version Independent ID: ddaaa167-ce5c-5296-c403-9d3e354f315a
* Content: [.create ingestion mapping - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/create-ingestion-mapping-command)
* Content Source: [data-explorer/kusto/management/create-ingestion-mapping-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/create-ingestion-mapping-command.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by YaelSchuster** [comment]
Hi @appcrawler, it seems you've tried to create an Avro mapping with CSV mapping format, specifying Ordinals – which is not supported. In the 2nd try, you've tried providing a Avro JSON schema, with an unfamiliar syntax.

Please see (AVRO mapping)[https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings#avro-mapping].

I will update the ingestion doc with a better explanation of what to find in the mapping doc.
#please-close
