### ISSUE TITLE
Legend property invalid error

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/dataexplorer-docs#1312]
I am unable to use legend property in Azure Data Explorer. Not sure what I am doing wrong. The tooltip says it is valid value, but I cannot execute the query.

![image](https://user-images.githubusercontent.com/5035266/179853719-12e60ed1-ccb7-4cdf-8ff8-4092182ee980.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@rajyraman  Thanks for the question! We are investigating and will update you shortly.

**Comment by YaelSchuster** [comment]
Hi @rajyraman, try using the word `visible` without any tick marks or apostrophes surrounding it.

**Comment by YaelSchuster** [comment]
Since the documentation is correct, and this appears to be a misunderstanding arising from the tool tip, I am closing this issue. Following up with the query team to clarify tool tips.

#please-close

**Comment by rajyraman** [comment]
That works. Thank you @YaelSchuster. I thought that I had to give it a string value because of the tooltip.
