### ISSUE TITLE
Module "DataFormat" cannot be impoted from azure.kusto.ingest in python code 

### ISSUE THREAD

**Issue by prateek-narula** [MicrosoftDocs/dataexplorer-docs#1315]
Module DataFormat is not available in `azure.kusto.ingest` anymore rather in `azure.kusto.data`, 
So the document needs correction in [section: Source file Information](https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data#set-source-file-information) from code 
```
from azure.kusto.ingest import QueuedIngestClient, IngestionProperties, FileDescriptor, BlobDescriptor, DataFormat, ReportLevel, ReportMethod

CONTAINER = "samplefiles"
ACCOUNT_NAME = "kustosamples"
SAS_TOKEN = ""  # If relevant add SAS token
FILE_PATH = "StormEvents.csv"
FILE_SIZE = 64158321    # in bytes

BLOB_PATH = "https://" + ACCOUNT_NAME + ".blob.core.windows.net/" + \
    CONTAINER + "/" + FILE_PATH + SAS_TOKEN
```
To code

```
from azure.kusto.data import DataFormat
from azure.kusto.ingest import QueuedIngestClient, IngestionProperties, FileDescriptor, BlobDescriptor, ReportLevel, ReportMethod

CONTAINER = "samplefiles"
ACCOUNT_NAME = "kustosamples"
SAS_TOKEN = ""  # If relevant add SAS token
FILE_PATH = "StormEvents.csv"
FILE_SIZE = 64158321    # in bytes

BLOB_PATH = "https://" + ACCOUNT_NAME + ".blob.core.windows.net/" + \
    CONTAINER + "/" + FILE_PATH + SAS_TOKEN
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c010923-e011-6915-e3c4-6265fb997c35
* Version Independent ID: 6b102d99-8aae-bba3-0ddf-d4137c3d6434
* Content: [Ingest data using the Azure Data Explorer Python library](https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data)
* Content Source: [data-explorer/python-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/python-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by prateek-narula** [comment]
For reference please have a look [here](https://pypi.org/project/azure-kusto-ingest/)

**Comment by ShaikMaheer-MSFT** [comment]
@prateek-narula Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by ShaikMaheer-MSFT** [comment]
@shsagir Could you please validate feedback and update as appropriate? Thank you.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by yihezkel** [comment]
Thanks @prateek-narula !

We updated the docs per your suggestion, which should be published in the coming days.

**Comment by YaelSchuster** [comment]
#please-close
