### ISSUE TITLE
 Syntax is wrong for datatable

### ISSUE THREAD

**Issue by KeroppiTheFrog** [MicrosoftDocs/dataexplorer-docs#1316]
Syntax is wrong for datatable, as it should be 

name:type, not type:name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97de494f-8a36-e9ee-45f8-95c0ef540ae9
* Version Independent ID: 8af2d2f5-1512-1827-3c39-c27683155c18
* Content: [datatable operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatableoperator)
* Content Source: [data-explorer/kusto/query/datatableoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/datatableoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
@KeroppiTheFrog Thanks for reaching out. Looks like the issue was opened and closed immediately. Just wanted to double check if the issue was closed intentionally or do you have any specific feedback on this document?

Thanks
