### ISSUE TITLE
Between operator

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/dataexplorer-docs#1318]
There is between operator in KQL as well. So, query number 6 can be rewritten as 

```
dependencies
| where timestamp between (datetime(2016-10-01) .. datetime(2016-11-01))
```

This would be more aligned with the SQL query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f392719-bd91-a626-7176-a95297e4ca99
* Version Independent ID: 362cb089-c767-ed2c-6c00-16068b68cbbd
* Content: [SQL to Kusto query translation - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/sqlcheatsheet)
* Content Source: [data-explorer/kusto/query/sqlcheatsheet.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/sqlcheatsheet.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@rajyraman  Thanks for the question! We are investigating and will update you shortly.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@shsagir Could you please take a look at the above feedback.

**Comment by YaelSchuster** [comment]
Hi @rajyraman, thanks for your suggestion. You're correct, and that's a more performant way of writing the query. I'll update the doc now to include this method of writing the query.

#please-close
