### ISSUE TITLE
Control the user identity connecting to Power BI

### ISSUE THREAD

**Issue by darivuki** [MicrosoftDocs/dataexplorer-docs#132]
Hello,

I would like to be able to connect to an ADX Cluster located in a specific AAD Tenant using my singed in details (AAD Account). Right now, when I sign in to PowerBI Desktop, I am not able to choose the right Tenant. How can I achieve this? Here is an example on how to do this in Kusto.Explorer. Is there a way to achieve this in Power BI as well? If so, I think that it would be nice to add to this documentation.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4aa15b-5f33-b4f8-f3cd-f5f2434f3836
* Version Independent ID: ac42a985-65b3-4671-5c8e-de32dd876025
* Content: [Visualize data with Azure Data Explorer connector for Power BI](https://docs.microsoft.com/en-us/azure/data-explorer/power-bi-connector)
* Content Source: [data-explorer/power-bi-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/power-bi-connector.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@darivuki  Thanks for the feedback! Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@Gabilehner and @saguiitay - can you please assist the customer with the correct instructions?

**Comment by orspod** [comment]
@darivuki - please contact the Power BI team with this question. Sorry we can't be of further assistance. Moving to close this issue. If you have additional questions on this topic, feel free to open a new issue.
