### ISSUE TITLE
term confusion

### ISSUE THREAD

**Issue by xfgavin** [MicrosoftDocs/dataexplorer-docs#1320]
Is command-then-query AdminTheyQuery?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7273ba66-9fda-51e5-1f6b-46cb610f6c33
* Version Independent ID: 12a79f6f-223f-3940-29dd-69d9dbc9f370
* Content: [Management (control commands) overview - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/#feedback)
* Content Source: [data-explorer/kusto/management/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/index.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by KranthiPakala-MSFT** [comment]
@xfgavin I did double checked with product team and yes, both terms (“command-then-query” and “AdminThenQuery”) refer to the same types of operations.

Product team has noted this feedback to make the documentation clearer. 

Appreciate much for the feedback. 

Hope this info helps.

**Comment by KranthiPakala-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thank you
