### ISSUE TITLE
What is Application Id for Active Directory Integrated

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/dataexplorer-docs#1322]
I try to connect to Dataverse TDS endpoint using sql_request. I always get an error, even though the Managed Identity Application Id of the Azure Data Explorer Cluster is setup as an user in Power Apps with right roles.

![image](https://user-images.githubusercontent.com/5035266/180633683-80553cb0-baf7-43ba-ab3c-76e751cb070b.png)

The can connect with [access token](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/sqlrequestplugin?pivots=azuredataexplorer#azure-ad-access-token) to the same SQL TDS endpoint without any issue (see screenshot below)

![image](https://user-images.githubusercontent.com/5035266/180633724-352880bf-abbd-4ae0-bc4a-75f29c542581.png)

But, Active Directory Integrated does not work at all. What AppId is being used to connect the SQL endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1921551c-5a66-7483-47a7-f8fc497f530e
* Version Independent ID: e1bc5c78-ac3e-fd10-a1cd-407e9626c463
* Content: [sql_request plugin - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/sqlrequestplugin)
* Content Source: [data-explorer/kusto/query/sqlrequestplugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/sqlrequestplugin.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by rajyraman** [comment]
Related to this issue, I tried to use `http_request_post` and so that I can token from Azure AD itself, and then use the token in the `sql_request`. But, I am unable to get that either. Always getting HTTP 400 - bad request.

![image](https://user-images.githubusercontent.com/5035266/182056062-4c70afcb-9e4d-4797-bff0-bffa37387dc0.png)

![image](https://user-images.githubusercontent.com/5035266/182055808-3a926c81-3edc-4ceb-9010-e623ab8e1c0d.png)

Just using AppId and Secret (https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret).

I am able to get the token via PowerShell using the same AppId and Secret without any issues.

**Comment by YaelSchuster** [comment]
This is currently being investigated by the dev team.

**Comment by shanisolomon** [comment]
Hi @rajyraman,

can you confirm you have the correct permissions on your sql server?

**Comment by rajyraman** [comment]
@shanisolomon - This is Dataverse TDS endpoint. https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query

**Comment by shanisolomon** [comment]
@rajyraman could you please specify the port and try again? https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/sqlrequestplugin?pivots=azuredataexplorer#specify-the-network-endpoint

**Comment by YaelSchuster** [comment]
Since this issue has been inactive for over a week, I'm going to close it at this time. Please feel free to @mention myself or @shanisolomon to reach out again.

#please-close

**Comment by rajyraman** [comment]
@shanisolomon I am getting a different error if I use the port number.

![image](https://user-images.githubusercontent.com/5035266/187104316-bfe0fc03-a57b-47a0-b837-73fafaef2fe4.png)

It should work based on the docs. https://docs.microsoft.com/en-us/power-apps/developer/data-platform/dataverse-sql-query#security-and-authentication

@YaelSchuster - I was away on AL, so I could not respond to this earlier. Apologies.

**Comment by rajyraman** [comment]
@shanisolomon - On a side note I cannot connect to the TDS endpoint from Azure Data Studio as well.

![image](https://user-images.githubusercontent.com/5035266/187104721-13ace793-d7d8-4409-b091-d8834cbf6501.png)

I can connect only from SSMS.
