### ISSUE TITLE
There is a Splunk equivalent to project-away!

### ISSUE THREAD

**Issue by tduarte14** [MicrosoftDocs/dataexplorer-docs#1325]
Hi team!

First of all thanks for this map of the 2 languages, it's being very handful.

I noticed you say that there is no splunk equivalent to project-away in KQL.
However, even if there's no equivalent command, you can use "| fields - " to exclude fields.

Kind regards,
Tiago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 490b535f-ad0c-f7b0-516b-32b276deb947
* Version Independent ID: fd01a49b-b735-3bc4-50aa-a8bd7c808584
* Content: [Splunk to Kusto map for Azure Data Explorer and Azure Monitor](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/splunk-cheat-sheet)
* Content Source: [data-explorer/kusto/query/splunk-cheat-sheet.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/splunk-cheat-sheet.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for your feedback, @tduarte14 ! I have created a work item to track this update

**Comment by YaelSchuster** [comment]
#please-close
