### ISSUE TITLE
IoT Hub to Event Hub to Kusto database

### ISSUE THREAD

**Issue by bseaholmAlloyGroup** [MicrosoftDocs/dataexplorer-docs#1329]
I was moving data from a hardware device to IoT Hub via MQTT.  I wanted to get the data into a Kusto database.  I created a IoT endpoint and route to an Event Hub.  Event Hub data all looked good.  Created Azure Data Explorer cluster with database and used One-Click ingestion to drop data into a Table.  One-click ingestion table looked ok with simulated data in the correct columns:
![image](https://user-images.githubusercontent.com/100370811/181106189-aa7e5e0b-c844-464c-b824-1e7300342c18.png)

Let things run for 15min+ and got no data into table.  Contacted Microsoft Support.  Fortunately, person assigned to the issue had seen this exact issue and fixed it in 5 minutes.  The Nested levels control and Data format was the issue.  We set Nested levels to 10 and Data format from JSON to MULTIJSON and now everything works perfectly.
![image](https://user-images.githubusercontent.com/100370811/181106916-b8fa4ea8-df8b-4743-9547-3efa29cbcdcc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90fd48b-27a7-677c-fc01-41557c111ad7
* Version Independent ID: 95f4ff76-7c43-6b8b-67d0-15838ae77437
* Content: [Ingest data from Azure Event Hubs into Azure Data Explorer using the ingestion wizard](https://docs.microsoft.com/en-us/azure/data-explorer/one-click-event-hub)
* Content Source: [data-explorer/one-click-event-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/one-click-event-hub.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@bseaholmAlloyGroup  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by vladikbr** [comment]
We are working on improvements in that specific area right now that would affect the format handling, especially for JSONs.
Thank you for bringing this into our attention.

**Comment by vladikbr** [comment]
please-close
