### ISSUE TITLE
'render linechart' example data is a poor illustration of how-to, as it doesn't use a real table

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/dataexplorer-docs#1335]
The 'render linechart' linked example data uses 'demo_series2', but this isn't really a table, it's just one row of packed data values:

![image](https://user-images.githubusercontent.com/22213780/181660917-d0db4043-8f13-4efe-ad69-f76a10e7b39d.png)

A more useful example would start with an actual table with x and y fields, not a one row table with packed data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@johndog Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by YaelSchuster** [comment]
Thanks, @johndog 
You're absolutely correct. We actually have an open work item for updating the examples in this subject. 

At this time, I'm going to close the issue, but please feel free to reach out with other docs improvements.

#please-close
