### ISSUE TITLE
Please update document with correct PowerShell cmdlet

### ISSUE THREAD

**Issue by RahulSawantMS** [MicrosoftDocs/dataexplorer-docs#1337]
[Enter feedback here]
Could you please update the *example* in this document with correct syntax mentioned in [this link](https://github.com/MicrosoftDocs/dataexplorer-docs/issues/1295)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2df80c7-1cca-9c8d-0ed5-05b387e1850f
* Version Independent ID: d3f5e3ed-dc62-ca1a-c821-4ca25453fa0f
* Content: [Kusto .NET Client Libraries from PowerShell - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell)
* Content Source: [data-explorer/kusto/api/powershell/powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/powershell/powershell.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by samlevy-microsoft** [comment]
ack, we have already pushed a fix to the documentation (under review)

**Comment by YaelSchuster** [comment]
Hi @RahulSawantMS - thanks for reaching out. Docs have been updated here: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/3367 and should go live in a number of hours.

**Comment by YaelSchuster** [comment]
#please-close
