### ISSUE TITLE
External table mapping creation doesn't work

### ISSUE THREAD

**Issue by gkrajuska** [MicrosoftDocs/dataexplorer-docs#134]
Data explorer does not detect ".create external table table_name JSON mapping" as a valid command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3621d01-d6db-5ea1-4ac8-4c84787ef71f
* Version Independent ID: 5a6df5d9-c867-390d-4aa5-c6a899566cfb
* Content: [Create and alter external tables in Azure Storage or Azure Data Lake - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/external-tables-azurestorage-azuredatalake)
* Content Source: [data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Hi @gkrajuska Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by orspod** [comment]
@spektom can you assist with this customer question?

**Comment by spektom** [comment]
Hi @gkrajuska ,

Can you please provide the full command you're using (and the error message you're getting).

Thanks!

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@gkrajuska  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
