### ISSUE TITLE
Subnet delegation is mandatory, not "recommended" or optional

### ISSUE THREAD

**Issue by deyanp** [MicrosoftDocs/dataexplorer-docs#1349]
Hi,

As per ticket 2205040050000216, my cluster was running fine for more than 6 months with daily start/stop so that we do not incur costs during the night. One day, all of a sudden it could not be started and the error message was:

```
{

  "ErrorCode": "MissingSubnetDelegation",

  "ErrorMessage": "Creating cluster in subnet '{0}' requires delegating subnet to '{1}'. Please delegate the subnet and retry operation, see [https://aka.ms/adxvnetportal](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fadxvnetportal&data=05%7C01%7Cankdas%40microsoftsupport.com%7C0ef24fac03da4bb3ad9908da491f9085%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637902697164113055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OJN5KMUZXG9LSAIB3BIWy2XIBaAvdpViwldyUvZhG0c%3D&reserved=0)",

  "ErrorParameters": [

    "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxxx/subnets/xxxxxxx",

    "Microsoft.Kusto/clusters"

  ],

  "HttpStatus": 400

}
```

There was no prior notification from Microsoft that we should change in anyway the configuration of the underlying Vnet so that our cluster can continue working as normal. So under stress I had to configure the subnet delegation, so that the cluster can be started

I would suggest that you change the wording in this article and explicitly state that subnet delegation is mandatory (not recommended etc). 

Br,
Deyan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501c33cd-0ac0-685b-0da1-03a269616d08
* Version Independent ID: 67e7428d-9b35-cb0c-7af9-6fc402848b8d
* Content: [Deploy Azure Data Explorer into your Virtual Network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment#configure-network-security-group-rules-using-subnet-delegation)
* Content Source: [data-explorer/vnet-deployment.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/vnet-deployment.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@deyanp Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by ShaikMaheer-MSFT** [comment]
@shsagir Could you please validate customer feedback and enhance doc as appropriate? Thank you.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by cosh** [comment]
Hi Deyan,

I'm sorry for the inconveniences and hope that your cluster is running fine. Please consider changing to a Private Endpoint based solution (https://docs.microsoft.com/en-us/azure/data-explorer/security-network-private-endpoint). It's feature compatible with way less operational overhead.
I'm going to fix the doc

KR, Henning

**Comment by YaelSchuster** [comment]
#please-close

**Comment by deyanp** [comment]
@cosh how is private endpoint going to help? The ADX instance must be reachable by:
1) Our AKS cluster
2) PowerBI/Excel, web browser https://dataexplorer.azure.com/

Private endpoint may help with 1), but not sure how it helps with 2) ..
