### ISSUE TITLE
Add syntax for '.export'  on Data Export document

### ISSUE THREAD

**Issue by nfgallimore** [MicrosoftDocs/dataexplorer-docs#1355]
Add syntax for '.export'  like this answer on StackOverflow: https://stackoverflow.com/a/73151928

```
.export to tsv (
    h@"https://SANAME.blob.core.windows.net/CONTAINER/PATH;SAKEY"
) with (
    includeHeaders="all"
)
<| simple QUERY | limit 5
```
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad10bb6-4b40-d27e-c988-630c8e4e28be
* Version Independent ID: 30902ba1-ea77-0f75-e9bd-e20b1d4e1fd5
* Content: [Data export - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-export/)
* Content Source: [data-explorer/kusto/management/data-export/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/data-export/index.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by nfgallimore** [comment]
Found .export syntax documentation

https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-export/export-data-to-storage

**Comment by KranthiPakala-MSFT** [comment]
Thanks for sharing the doc link here as it will help others reading this post. 

Thank you
