### ISSUE TITLE
deprecated nuget

### ISSUE THREAD

**Issue by DanielHolth** [MicrosoftDocs/dataexplorer-docs#1356]
using Microsoft.IdentityModel.Clients.ActiveDirectory; is deprecated use 
using Microsoft.IdentityClient; instead.

Might affect more of your code. But thanks for the sample :)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7efb5044-1b89-ab74-187e-81e5751da9a1
* Version Independent ID: 56892ddf-7488-791d-80d6-0385c2cfa442
* Content: [MS-TDS with Azure Active Directory - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/tds/aad)
* Content Source: [data-explorer/kusto/api/tds/aad.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/tds/aad.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by yihezkel** [comment]
Thanks @DanielHolth for bringing this to our attention!

We've rewritten the page to include working examples that use MSAL instead of ADAL. It may take time for the new docs to publish.

**Comment by YaelSchuster** [comment]
@DanielHolth thanks for pointing that out - your contributions make our docs better.
Thanks so much @yihezkel. Closing the issue at this time.
#please-close
