### ISSUE TITLE
Inconsistencies with ! vs. not

### ISSUE THREAD

**Issue by rymusg-msft** [MicrosoftDocs/dataexplorer-docs#1359]
For some commands, not works (e.g. contains, notcontains, !contains), while startswith only supports startswith, !startswith.

This should be consistent - either allowing 'not' for all commands or using ! for all commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9312e60-5709-96b9-f4d6-e0bfb1e618b9
* Version Independent ID: 96f23cb8-5d7e-e301-7845-a2f218c63bd9
* Content: [The case-insensitive startswith string operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/startswith-operator)
* Content Source: [data-explorer/kusto/query/startswith-operator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/startswith-operator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ShaikMaheer-MSFT** [comment]
@rymusg-msft Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by YaelSchuster** [comment]
Please submit all feature requests at https://aka.ms/adx.uservoice? This way it will be easier for the team to track it. Thanks!

Closing this matter, as it's not a docs update.
#please-close
