### ISSUE TITLE
update managed identities authentication note

### ISSUE THREAD

**Issue by xiaoshiyi123** [MicrosoftDocs/dataexplorer-docs#1367]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/36906182/186557664-a0b6f3f0-920d-45a1-899d-6d4f0ca6c81f.png)

Hello, to use managed identities authentication, we should use function with_aad_managed_service_identity_authentication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c010923-e011-6915-e3c4-6265fb997c35
* Version Independent ID: 6b102d99-8aae-bba3-0ddf-d4137c3d6434
* Content: [Ingest data using the Azure Data Explorer Python library](https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data?source=docs#feedback)
* Content Source: [data-explorer/python-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/python-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@shsagir  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @xiaoshiyi123, are you asking if this function should be used? with_aad_managed_service_identity_authentication

**Comment by xiaoshiyi123** [comment]
Yes, I think the code showed in Note is for no authentication, I see the sample in 
https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/tests/sample.py#:~:text=kcsb%20%3D%20KustoConnectionStringBuilder()

**Comment by YaelSchuster** [comment]
Sorry for the delay in response. We're going to remove the comment about managed identities and update the code sample to use user prompt authorization.

#please-close
