### ISSUE TITLE
The name 'ipv4_is_in_any_range' does not refer to any known function.

### ISSUE THREAD

**Issue by JustJordanT** [MicrosoftDocs/dataexplorer-docs#1369]
Using this function results in the following error. 
>The name 'ipv4_is_in_any_range' does not refer to any known function.

The query being used is the same from the docs: 

```sql
let LocalNetworks=dynamic([
    "192.168.1.1/16",
    "127.0.0.1/8",
    "10.0.0.1/8"
]);
let IPs=datatable(IP:string) [
    "10.1.2.3",
    "192.168.1.5",
    "123.1.11.21",
    "1.1.1.1"
];
IPs
| extend IsLocal=ipv4_is_in_any_range(IP, LocalNetworks)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64f3e904-5393-56f3-5dc8-6a4e1d0904f3
* Version Independent ID: ba1448fd-47e1-1406-d9c5-50ed476a7c90
* Content: [ipv4_is_in_any_range() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/ipv4-is-in-any-range-function)
* Content Source: [data-explorer/kusto/query/ipv4-is-in-any-range-function.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/ipv4-is-in-any-range-function.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @JustJordanT; I have just run this query and get the following output: 
![image](https://user-images.githubusercontent.com/62833511/187067770-0f6ad40e-dbc6-4747-a334-dd4329ad2969.png)
Can you please re-check that you're getting a different result?

**Comment by YaelSchuster** [comment]
Hi @JustJordanT, since I haven't heard back I'm going to go ahead and close this issue. If you have further problems, please feel free to reach out by @MicrosoftDocs/build_service_account 
#please-close

**Comment by JustJordanT** [comment]
Sorry about that. Yes looks like it does work, were getting errors from he Azure KQL editor.

**Comment by rstanilewicz** [comment]
The function works, but it is not listed in the command auto-completion window, and it's not recognised by the syntax checker, as of Feb 2023.
