### ISSUE TITLE
Unable to enumerate databases after specifying Cluster Uri in "Add Data source"

### ISSUE THREAD

**Issue by darivuki** [MicrosoftDocs/dataexplorer-docs#137]
Hello,

when I try to add a Data source and enter my Cluster Uri, I do not get any databases back and am not able to configure the Data source. My AAD account has Admin permissions to the Cluster, and I was able to enumerate the databases some days ago. Can it be that this is still not completely working due to the tech still being in Preview, or am I missing something?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1640-3699-8fdf-07a2-c9b922499c90
* Version Independent ID: 55027537-6af4-541d-da8d-e2cdc2b5fa92
* Content: [Visualize data with the Azure Data Explorer dashboard](https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards)
* Content Source: [data-explorer/azure-data-explorer-dashboards.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/azure-data-explorer-dashboards.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by darivuki** [comment]
It seems like that I manually needed to switch to the Tenant where the Cluster is located. After I did that, I was able to enumerate the databases. This is not an issue, but maybe worth mentioning in the documentation.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Thanks for the update.

@orspod Could you look into this issue?

**Comment by orspod** [comment]
@Gabilehner - can you please assist?

**Comment by orspod** [comment]
@Gabilehner - can you please assist?

**Comment by orspod** [comment]
@darivuki - thanks for the feedback. We will look into adding this to the documentation. Moving to close the issue.
