### ISSUE TITLE
Page unclear on which engine version note applies to

### ISSUE THREAD

**Issue by llavalleytw** [MicrosoftDocs/dataexplorer-docs#1371]
In the current version of the page `String Operators` there is a note stating that `In EngineV2, a term consists of four or more characters.`, as opposed to the section above the note which says that a term is 3 or more characters. The note is clear as to what the rules for EngineV2 are, but I don't see anywhere which clarifies whether the larger body of the document applies to EngineV1 or EngineV3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11df65bd-6d46-7a8d-de92-97d933d7f1b1
* Version Independent ID: 51157ab2-6539-8ef8-75aa-89c1ad3026f7
* Content: [String operators - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators)
* Content Source: [data-explorer/kusto/query/datatypes-string-operators.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/datatypes-string-operators.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @llavalleytw, the currently available engine versions are v2 and v3. Only the note is specific to Engine V2; the rest is applicable to both instances.

Hope this answers your question. Please feel free to reach out by @mention me with further clarifications.

#please-close
