### ISSUE TITLE
Error connecting with Sisense and JDBC

### ISSUE THREAD

**Issue by roboyoben** [MicrosoftDocs/dataexplorer-docs#1382]
Hi,

we are currently trying to connect to Azure Data Explorer using JDBC by following the instructions from the documentation:

https://docs.microsoft.com/en-us/azure/data-explorer/sisense
https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/sisense.md

However, when we create the connection string by adding our ```cluster_name.region``` and the ```database_name```, we still get an error saying: ```"Cannot establish connection with provided parameters"```.

jdbc:sqlserver://<cluster_name.region>.kusto.windows.net:1433;database=<database_name>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.kusto.windows.net;loginTimeout=30;authentication=ActiveDirectoryPassword

![image](https://user-images.githubusercontent.com/111729049/188409355-a0f727cb-8162-4ffc-a02e-8ed2bfcf0351.png)

For the jar files, we downloaded the latest versions of the ones listed in the documentation and uploaded them into the ```C:\Program Files\Sisense\DataConnectors\jdbcdrivers\adx``` folder:

![image](https://user-images.githubusercontent.com/111729049/188408568-e86ad355-1e49-4d54-b498-daefab4f288c.png)

Do you know what might be causing the issue here?

**Comment by YaelSchuster** [comment]
Closing this issue at this time. If there is a doc change that is requested, please feel free to reach out.
#please-close
