### ISSUE TITLE
Embed dashboards Not Working For Only Show Dashboard and Select Specific Page

### ISSUE THREAD

**Issue by fazhong-ms** [MicrosoftDocs/dataexplorer-docs#1385]
Embed dashboards Not Working For Only Show Dashboard and Select Specific Page [Enter feedback here]
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/monaco/host-web-ux-in-iframe#embed-dashboards-preview

![image](https://user-images.githubusercontent.com/71804222/188858216-3b67a11c-fabc-4a21-9f4c-e5f07ab1722a.png)

My Code
```
<iframe title="Test" width="1140" height="541.25" src="https://dataexplorer.azure.com/dashboards/65412248-b1dc-411f-a070-a211872bd5c3?p-_startTime=2days&p-_endTime=now&p-Stack=v-PRD#3f376eb9-bf5d-40d6-a2ab-68b217802a46?f-PersistAfterEachRun=true&f-IFrameAuth=true&f-Homepage=false&f-ShowPageHeader=false&f-ShowNavigation=false" frameborder="0" allowFullScreen="true"></iframe>
```
1. It still shows menus(left and top), I want to show only dashboard:
![image](https://user-images.githubusercontent.com/71804222/188858681-c990862a-03fe-401f-92f8-7f5e90fd2b83.png)

2. I specified it to be third page, but it's showing the first page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19a65aa5-0a6b-9916-e201-45fb67154e30
* Version Independent ID: e68aa06e-8811-a52b-8629-ffe7ada9accf
* Content: [Embed the Azure Data Explorer web UI in an **iframe**.](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/monaco/host-web-ux-in-iframe#feedback)
* Content Source: [data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md)
* Service: **data-explorer**
* GitHub Login: @fazhong-ms
* Microsoft Alias: **fazhong**

**Comment by YashikaTyagi-MSFT** [comment]
@fazhong-ms 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by fazhong-ms** [comment]
> 

Hi @YashikaTyagi-MSFT , could you please assign to the right person? Thanks！
![image](https://user-images.githubusercontent.com/71804222/189018108-1c0326ca-3351-43fe-af2c-69bfdf10986b.png)

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Hi,
Since there has been no response to the above question, I'm closing this Issue. Please feel free to reopen or mention us with this information by using @mention.

#please-close
