### ISSUE TITLE
Not enough examples how to add/update/delete permissions

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/dataexplorer-docs#1390]
For example, I'm getting an error trying to drop a principal from a database but getting a syntax error. The doc doesn't help me to achieve what I'm trying to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4526aa53-827b-abf4-d419-cea51c79c71b
* Version Independent ID: 73682729-2e9a-216f-5fb5-8e887ef93df2
* Content: [Security roles management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/security-roles)
* Content Source: [data-explorer/kusto/management/security-roles.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/security-roles.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @abatishchev, can you share the command you're using and the error that was returned?

**Comment by abatishchev** [comment]
hi @YaelSchuster,
Sorry, my computer was rebooted and I've lost the history of closed tabs in ADX.

What I attempted to do was to drop an admin from a db. The article provides only the pattern:

```k
.drop database DatabaseName Role ( Principal [, Principal...] ) [skip-results] [Description]
```

Which makes sense when you know how to read it but less so when you don't. I don't update permissions often enough to remember the syntax so have to re-learn it every several months.

**Comment by YaelSchuster** [comment]
Hi @abatishchev, thanks for your reply. That's definitely a legitimate concern, and I've added a work item to track updating these docs: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1988446

Please feel free to reach out with other concerns/requests.

At this time, I'm closing the issue and will track updates in ADO

#please-close
