### ISSUE TITLE
Unable to connect to source without Authority ID

### ISSUE THREAD

**Issue by sfwatergit** [MicrosoftDocs/dataexplorer-docs#1391]
The code in the documentation for source connection is missing a statement. You need to specify an authority Id in the configuration mapping. So, instead of

```scala
val conf: Map[String, String] = Map(
      KustoSourceOptions.KUSTO_AAD_APP_ID -> appId,
      KustoSourceOptions.KUSTO_AAD_APP_SECRET -> appKey,
    )
```

you need

```scala
val conf: Map[String, String] = Map(
      KustoSourceOptions.KUSTO_AAD_APP_ID -> appId,
      KustoSourceOptions.KUSTO_AAD_APP_SECRET -> appKey,
      KustoSourceOptions.KUSTO_AAD_AUTHORITY_ID -> authorityId
    )
```

where `authorityId`  is the user-specified variable for the appropriate authority ID. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa46bfb-17f8-a18d-50a5-eaad4c85ae19
* Version Independent ID: ac1fc513-55d6-203a-ce2c-bae250d126d4
* Content: [Use the Azure Data Explorer connector for Apache Spark to move data between Azure Data Explorer and Spark clusters.](https://docs.microsoft.com/en-us/azure/data-explorer/spark-connector)
* Content Source: [data-explorer/spark-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/spark-connector.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@sfwatergit  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Hi @sfwatergit Thanks for your feedback. I've added a note that this field is optional and defaults to microsoft.com

Thanks!

#please-close
