### ISSUE TITLE
How to disable "ignoreformaterrors" using python

### ISSUE THREAD

**Issue by akhila31** [MicrosoftDocs/dataexplorer-docs#1400]
Hi Team, I am using https://docs.microsoft.com/en-us/azure/data-explorer/data-connection-event-hub-python#add-an-event-hubs-data-connection to create dataconnections in ADX for eventhub as a source. My input data is in JSON format. Due to some issues I want to disable this option ignoreformaterrors option but unable to find a variable.

I have gone through below link to look at the class for eventhub but did not find any. can you pls suggest or advice how can it be done. Thanks!
https://docs.microsoft.com/en-us/rest/api/azurerekusto/data-connections/create-or-update?tabs=HTTP#eventhubdataconnection

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09ec755-8b8b-c3ae-c41c-e46e150b9296
* Version Independent ID: 139476a1-e5f9-181e-ee7f-ab466d65d54d
* Content: [Create an Event Hubs data connection for Azure Data Explorer by using Python](https://docs.microsoft.com/en-us/azure/data-explorer/data-connection-event-hub-python#add-an-event-hubs-data-connection)
* Content Source: [data-explorer/data-connection-event-hub-python.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/data-connection-event-hub-python.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by AjayBathini-MSFT** [comment]
@akhila31 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@akhila31

Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by vladikbr** [comment]
This is actually just mapped into the format specifier.
"multijson" is the default JSON parser which is a strict one.
"json", which only supports JSON lines format (every line is a complete JSON document) is the equivalent of "ignoreformaterrors" option.

**Comment by vladikbr** [comment]
#please-close
