### ISSUE TITLE
Click to run query: Could not connect to cluster (403-Forbidden)

### ISSUE THREAD

**Issue by SteffenZeidler** [MicrosoftDocs/dataexplorer-docs#1403]
The "Click to run query" connection string contains a not accessible Kusto cluster.
There are 9 links with this cluster name - see https://github.com/MicrosoftDocs/dataexplorer-docs/search?q=northeurope

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c844fe93-572f-fcf9-7752-ca8252381e89
* Version Independent ID: 15f828db-95ff-1328-66bf-ddedf6c44865
* Content: [count() (aggregation function) - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/count-aggfunction)
* Content Source: [data-explorer/kusto/query/count-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/count-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YashikaTyagi-MSFT** [comment]
@SteffenZeidler 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by YaelSchuster** [comment]
Hi @SteffenZeidler, make sure you've selected the "help" cluster and the "samples" database to run this query. It may automatically try to run on a different cluster you have access to.

**Comment by SteffenZeidler** [comment]
Hi @YaelSchuster, in the page  "count-aggfunction.md" is the link not correct. It is not an issue at my Kusto configuration.
See raw text:
**\[**[**Click to run query**](https://dataexplorer.azure.com/clusters/kvc6bc487453a064d3c9de.northeurope/databases/NewDatabase1?query=H4sIAAAAAAAAAwsuyS/KdS1LzSsp5uWqUSjPSC1KVQguSSxJVSguSSwqKS7PLMlQUApXAskWl+bmJhZlVqUqOOeX5pXYJoNIDU2FpEqIFgCZCeK+TQAAAA==)**\]**

**Comment by YaelSchuster** [comment]
Ah ok, I see. I've fixed that in the doc.

**Comment by YaelSchuster** [comment]
#sign-off

**Comment by YaelSchuster** [comment]
#please-close
