### ISSUE TITLE
Difference in wording of descriptions for in set of operators

### ISSUE THREAD

**Issue by llavalleytw** [MicrosoftDocs/dataexplorer-docs#1413]
In the Operators on Strings section of this document the wording for the Description column for the operators `in`, `!in`, `in~`, and `!in~` is different. For `in` the description is "Equals to one of the elements" whereas for `in~` the description is "Equals to any of the elements". The key difference here is using the word 'one' vs. the word 'any'. The word 'one' can be interpreted as exactly one or as any one while 'any' must be interpreted as any one. Assuming `in` does not operate differently than the other similarly named operators, this is a suggestion to update the wording to be consistent for this family of operators.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11df65bd-6d46-7a8d-de92-97d933d7f1b1
* Version Independent ID: 51157ab2-6539-8ef8-75aa-89c1ad3026f7
* Content: [String operators - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators)
* Content Source: [data-explorer/kusto/query/datatypes-string-operators.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/datatypes-string-operators.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @llavalleytw, you're absolutely right. Opening a PR now to fix that.

Thanks for helping us improve our documentation!

#please-close
