### ISSUE TITLE
The following command deletes the streaming ingestion policy

### ISSUE THREAD

**Issue by fangzi11** [MicrosoftDocs/dataexplorer-docs#1414]
url: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/show-database-streaming-ingestion-policy-command#example

error: "deletes"

I think is displays command
Please reply，Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8c32733-27fe-4c24-497a-c258a1ac741d
* Version Independent ID: b948cb66-d2e6-4417-521b-0e06bf6768d4
* Content: [.show database streaming ingestion policy command - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/show-database-streaming-ingestion-policy-command#example)
* Content Source: [data-explorer/kusto/management/show-database-streaming-ingestion-policy-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/show-database-streaming-ingestion-policy-command.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by RamanathanChinnappan-MSFT** [comment]
@fangzi11 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Oh dear. @fangzi11 you're definitely correct. Fixing that now. 

Thanks for helping us improve our documentation!

#please-close
