### ISSUE TITLE
Azure Data Explorer > Networking > Managed Private Endpoints configuration panel - wrong sub-resource in Microsoft.Sql/servers

### ISSUE THREAD

**Issue by lucabovo** [MicrosoftDocs/dataexplorer-docs#1415]
Good morning,
I have noticed an issue in Azure Data Explorer configuration web interface, specifically in Managed Private Endpoints configuration tab:
![image](https://user-images.githubusercontent.com/77054756/192542740-3ad5759e-eac0-484c-8c18-ba5ab66b8e6a.png)

The issue is related to SQL Server (Microsoft.Sql/servers resource): in the configuration form, the field "Target sub-resource" has only a value "servers" as you can see in the underlying screenshot:
![image](https://user-images.githubusercontent.com/77054756/192538904-f1e70e4e-8d8a-43fc-bc48-f762ac7cf4ad.png)

The configuration job fails as follows:
![image](https://user-images.githubusercontent.com/77054756/192540771-69f9de24-1952-4bf1-81fe-6ba9e4a9c23c.png)

In the documentation page https://learn.microsoft.com/en-us/azure/data-explorer/security-network-managed-private-endpoint-create , the sub-resource is listed correctly as "sqlServer" as you can see in the screenshot:
![image](https://user-images.githubusercontent.com/77054756/192538642-4013d500-b377-439f-a74c-d4653318324e.png)

Could you please check and fix the Azure Data Explorer > Networking > Managed Private Endpoints configuration panel accordingly to the documentation?

I look forward to hearing from you.
Thanks a lot.
Luca Bovo - beanTech

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb600db3-840e-6395-78ed-65421a1fa0a2
* Version Independent ID: 8d4cccd4-2bd7-8162-f125-19b65fd82d47
* Content: [Create a managed private endpoint for Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/security-network-managed-private-endpoint-create)
* Content Source: [data-explorer/security-network-managed-private-endpoint-create.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/security-network-managed-private-endpoint-create.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by SaibabaBalapur-MSFT** [comment]
@lucabovo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by cosh** [comment]
Hi Luca,

we'll fix it. thanks for reporting.

Cheers, Henning

**Comment by lucabovo** [comment]
Thank you @SaibabaBalapur-MSFT, @YaelSchuster, @cosh for your prompt feedback!

**Comment by YaelSchuster** [comment]
@please-close

**Comment by YaelSchuster** [comment]
#please-close
