### ISSUE TITLE
Mistake in docs

### ISSUE THREAD

**Issue by ivan-zakharchuk** [MicrosoftDocs/dataexplorer-docs#142]
[Enter feedback here]
there is a mistake in docs:

| where 1 == 2 

this makes no sense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cede3d6d-4803-358f-c3b3-11f8c407c878
* Version Independent ID: 9064e163-b02a-6030-dcc4-eddab6fa31cd
* Content: [summarize operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/summarizeoperator)
* Content Source: [data-explorer/kusto/query/summarizeoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/summarizeoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@ivan-zakharchuk  Thanks for the feedback! I have assigned the issue to the content author to review further and update the document as appropriate.

**Comment by orspod** [comment]
@yonileibowitz - will you review @ivan-zakharchuk feedback?

**Comment by yonileibowitz** [comment]
this isn't a mistake - `1 == 2` is a condition that evaluates to false, and the purpose of those examples is to show you how the `summarize` operator acts when the input table includes no records (e.g. they were all filtered out)

that said, we'll update the docs with an example that focuses on the main part, without adding potentially confusing parts in between - thanks for the feedback!

**Comment by yonileibowitz** [comment]
handled in: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/442

**Comment by orspod** [comment]
Thanks @yonileibowitz for updating the docs and answering the question. Closing this issue.
