### ISSUE TITLE
Preparing python dependencies must be done on a Windows machine

### ISSUE THREAD

**Issue by tamirkamara** [MicrosoftDocs/dataexplorer-docs#1427]
The document describes how to prepare python dependencies but doesn't mention it has to be done on a Windows machine. 
This is crucial since some packages also include native/compiled code which pypi fetches according to the os/arch it's run on. So running pypi on a linux will create an issue in runtime in ADX when the package is there but isn't usable since the os is wrong and then we'll get a failure due to missing dependency.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1dc0c9f-5768-5404-426b-64fe17b5c3ff
* Version Independent ID: 8ca6e09c-861d-429b-8957-0bd065902280
* Content: [Python plugin - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/pythonplugin)
* Content Source: [data-explorer/kusto/query/pythonplugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/pythonplugin.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Thanks @tamirkamara for pointing this out. We've added this note to the docs page.
#please-close
