### ISSUE TITLE
Add more information about the connection settings

### ISSUE THREAD

**Issue by tsubasaxZZZ** [MicrosoftDocs/dataexplorer-docs#1429]
When I connected by using Kusto Explorer, I'm not sure about the connection settings.
So, it might better describe settings on Connection screen.
![image](https://user-images.githubusercontent.com/3822284/193180094-d9cfd14d-19f6-45f3-938d-4b4757e9ed58.png)

For example:
1. Select Cloud settings [Public cloud]
2. Put "http://localhost:8080" to [Cluster connection]
3. Open "Advanced: Connection String"
4. Modify from "AAD Federated Security=True" to "AAD Federated Security=False"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcc33778-a87a-8f18-ceef-7e1a6923b676
* Version Independent ID: 2f12c68e-1690-dab7-4a5c-433deb3c0199
* Content: [Install the Azure Data Explorer Kusto emulator](https://learn.microsoft.com/en-us/azure/data-explorer/kusto-emulator-install)
* Content Source: [data-explorer/kusto-emulator-install.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto-emulator-install.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by SaibabaBalapur-MSFT** [comment]
@tsubasaxZZZ 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks, @tsubasaxZZZ for this. We are modifying this guidance now. 

https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/3511

#please-close
