### ISSUE TITLE
Add description about duplicated records in Data Explorer

### ISSUE THREAD

**Issue by shoshii** [MicrosoftDocs/dataexplorer-docs#1430]
[Enter feedback here]
Hello, could you consider add the description that tells us duplicated records could appear even in Data Explorer?
Data Explorer sometimes handles sensitive data such as Security Event logs, and there is cases at which users want to know precise number of security incidents. Duplicated records could end up with incorrect statistics and mislead the judgement of viewers.

I would suggest you can add one sentence at the top of document below.

As of now:
You want to safeguard your analytical databases from malfunctioning devices that resend the cached data and cause data duplication in the analytical database. This topic outlines best practices for handling duplicate data for these types of scenarios.

Suggestion:
 You want to safeguard your analytical databases from malfunctioning devices that resend the cached data and cause data duplication in the analytical database. **Duplicated records could appear even in Azure Data Explorer.** This topic outlines best practices for handling duplicate data for these types of scenarios.

https://learn.microsoft.com/en-us/azure/data-explorer/dealing-with-duplicates

I hope you consider this request.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69d81d6e-8715-ccdc-ba99-ddbb61c7b86e
* Version Independent ID: a051de71-7527-5f6c-718f-ceee739a7756
* Content: [Handle duplicate data in Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/dealing-with-duplicates?source=docs)
* Content Source: [data-explorer/dealing-with-duplicates.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/dealing-with-duplicates.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by SaibabaBalapur-MSFT** [comment]
@shoshii 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @shoshii, thanks for taking the time to reach out and help us improve our docs! I have added a note to this document emphasizing that duplicates can affect the number of records returned by a query. This is relevant when you need a precise count of records, such as when counting events.

#please-close

**Comment by shoshii** [comment]
Hello @SaibabaBalapur-MSFT  @YaelSchuster thank you for quick reply.
I have not found your note but assume I wii be able to see some change after your review process is completed.

**Comment by shoshii** [comment]
@YaelSchuster , I could see the note you have added. Thank you so much!
