### ISSUE TITLE
need more clear guidance how to setup Windows Container to get it work. 

### ISSUE THREAD

**Issue by qliu95114** [MicrosoftDocs/dataexplorer-docs#1431]
need more clear guidance how to setup Windows Container to get it work.

with some test efforts it look to me only 17763  RS5 build Windows Client and Server can do Dock Run, higher windows build won't work
high Windows 11 build 22000 or Windows Server 2022 20348 build cannot load the image with error message 

docker: Error response from daemon: hcsshim::CreateComputeSystem 0440ec7e99152f6a4dbbef51ac77c614f02e0ab4c1f77d3aced2da32e1c59569: The container operating system does not match the host operating system.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcc33778-a87a-8f18-ceef-7e1a6923b676
* Version Independent ID: 2f12c68e-1690-dab7-4a5c-433deb3c0199
* Content: [Install the Azure Data Explorer Kusto emulator](https://learn.microsoft.com/en-us/azure/data-explorer/kusto-emulator-install)
* Content Source: [data-explorer/kusto-emulator-install.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto-emulator-install.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ManoharLakkoju-MSFT** [comment]
@qliu95114 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by grawcho** [comment]
@qliu95114 - can you try to collect docker logs from the image, additionally. can you check which processes are running on the container (with powershell Get-Process)?
everything seems in order, but it looks like the Kusto.Svc or the dotnet process are not running.

**Comment by qliu95114** [comment]
c:\Kusto>dir
 Volume in drive C has no label.
 Volume Serial Number is C008-D78D

 Directory of c:\Kusto

10/03/2022  02:37 AM    <DIR>          .
10/03/2022  02:37 AM    <DIR>          ..
10/03/2022  02:37 AM                 0 dir
09/30/2022  12:52 PM    <DIR>          Packages
09/30/2022  12:52 PM    <DIR>          Running
09/30/2022  12:52 PM               247 StartKusto.cmd
10/03/2022  02:37 AM                 0 tasklist
               3 File(s)            247 bytes
               4 Dir(s)  21,037,412,352 bytes free

c:\Kusto>StartKusto.cmd

c:\Kusto\Running\Kustainer.Svc>tasklist

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
System Idle Process              0                            0          8 K
System                           4                            0        156 K
smss.exe                      8636                            0      1,232 K
csrss.exe                     1904 Services                   4      5,296 K
wininit.exe                   9516 Services                   4      7,236 K
services.exe                  8740 Services                   4      6,544 K
lsass.exe                     8080 Services                   4     27,804 K
fontdrvhost.exe               6624 Services                   4      3,372 K
svchost.exe                   4532 Services                   4     18,760 K
svchost.exe                   9520 Services                   4     29,100 K
svchost.exe                   4888 Services                   4     86,700 K
svchost.exe                   3920 Services                   4     18,900 K
CExecSvc.exe                  4068 Services                   4      5,144 K
svchost.exe                   4800 Services                   4     24,688 K
conhost.exe                   3728 Services                   4      4,844 K
powershell.exe                4228 Services                   4    139,848 K
svchost.exe                   1944 Services                   4     30,948 K
svchost.exe                   5972 Services                   4     14,396 K
cmd.exe                       5284 Services                   4      3,728 K
msdtc.exe                     7312 Services                   4     10,312 K
conhost.exe                   9956 Services                   4      5,820 K
cmd.exe                       8956 Services                   4     14,124 K
notepad.exe                   4112 Services                   4      9,104 K
WmiPrvSE.exe                  3836 Services                   4      8,876 K
cmd.exe                      11012 Services                   4      4,268 K
cmd.exe                      10956 Services                   4      4,516 K
notepad.exe                   3512 Services                   4      9,328 K
WmiPrvSE.exe                  7048 Services                   4      7,400 K
tasklist.exe                  8536 Services                   4      7,764 K

@grawcho

**Comment by grawcho** [comment]
@qliu95114 - i would like to look at the console output (assuming there is any) from docker logs.

**Comment by YaelSchuster** [comment]
Hi @qliu95114 - since there has been no response in 15 days, I'm closing this issue. Please feel free to reopen or @mention us with more information.

#please-close
