### ISSUE TITLE
Typo error at "Plan subnet size in your VNet" section

### ISSUE THREAD

**Issue by Shawngbk** [MicrosoftDocs/dataexplorer-docs#1435]
Typo error at "Plan subnet size in your VNet" section
https://learn.microsoft.com/en-us/azure/data-explorer/vnet-deployment#plan-subnet-size-in-your-vnet
![image](https://user-images.githubusercontent.com/18609174/193962476-1cad2ede-db8c-4fe1-902a-cd8bf64b4233.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 501c33cd-0ac0-685b-0da1-03a269616d08
* Version Independent ID: 67e7428d-9b35-cb0c-7af9-6fc402848b8d
* Content: [Deploy Azure Data Explorer into your Virtual Network](https://learn.microsoft.com/en-us/azure/data-explorer/vnet-deployment#plan-subnet-size-in-your-vnet)
* Content Source: [data-explorer/vnet-deployment.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/vnet-deployment.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by Naveenommi-MSFT** [comment]
@Shawngbk 
Thanks for your feedback! We will investigate and update as appropriate.

Thank you for bringing this to our attention. I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for noticing that, @Shawngbk - I've added a PR to fix the error.

**Comment by YaelSchuster** [comment]
#please-close
