### ISSUE TITLE
No truncation is not working

### ISSUE THREAD

**Issue by wrampazo** [MicrosoftDocs/dataexplorer-docs#1439]
"No truncation" command fails using Kusto.Cli or the Kusto client app.
Failed to execute: set notruncation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 082142f3-9558-d472-c85b-459b956480a1
* Version Independent ID: 3beb35b6-5885-9367-9fc0-2c4fe6b7b824
* Content: [Query limits - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits)
* Content Source: [data-explorer/kusto/concepts/querylimits.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/concepts/querylimits.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ManoharLakkoju-MSFT** [comment]
@wrampazo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by zivcaspi** [comment]
`set notruncation` in itself isn't a valid Kusto query, as it doesn't have any [tabular expression statement](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/tabularexpressionstatements). A valid Kusto query must have at least one such statement.

**Comment by YaelSchuster** [comment]
#please-close
