### ISSUE TITLE
Include instructions for embedded into Teams

### ISSUE THREAD

**Issue by carlo-quinonez** [MicrosoftDocs/dataexplorer-docs#1440]
These docs state the `f-IFrameAuth=true` must be provided to embed the query explorer and provide details on how to handle auth. However, when embedding as a Teams tab, that parameter can be left off and Teams seems to handle authentication just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19a65aa5-0a6b-9916-e201-45fb67154e30
* Version Independent ID: e68aa06e-8811-a52b-8629-ffe7ada9accf
* Content: [Embed the Azure Data Explorer web UI in an **iframe**.](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/monaco/host-web-ux-in-iframe)
* Content Source: [data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ManoharLakkoju-MSFT** [comment]
@carlo-quinonez 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by gil-koifman** [comment]
Hi,
First let me just note that I'm not really familiar with adding tabs for Teams.
A possible reason for why it still works without the `f-IFrameAuth=true` flag, is that you have already a token in your cache.
That can happen if you logged in to Kusto Web Explorer from your browser.
I would suggest that you try to clear your local storage related to the Kusto Web Explorer site, and then see if it works without the feature flag.

IMPORTANT (in case you decide to clear your local storage):
Before clearing your local storage, please export your current settings, so you can import them later without losing anything.
We save your connections and queries in the browser local storage.
This can be done in the settings menu:
![image](https://user-images.githubusercontent.com/110340694/196406749-3b2bc69e-9124-41b2-8973-f6b28a7b6e9f.png)

**Comment by YaelSchuster** [comment]
I'm closing the issue at this time. If you have further questions, please feel free to reopen or @mention one of us.
#please-close
