### ISSUE TITLE
JSON MULTILINE seems not an option in Format now

### ISSUE THREAD

**Issue by javierdve** [MicrosoftDocs/dataexplorer-docs#1445]
[I am not able to see the JSON MULTILINE option, how to select it]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 448ddad1-243c-af54-3395-7d022f83dff7
* Version Independent ID: 09e32c75-831b-876e-c33a-9cd5a83500b3
* Content: [Ingest data from IoT Hub into Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-iot-hub?source=recommendations)
* Content Source: [data-explorer/ingest-data-iot-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/ingest-data-iot-hub.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by Naveenommi-MSFT** [comment]
@javierdve 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

@shsagir 
Could you Please check and add your comments on this and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @javierdve 
Please see this document https://learn.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language#the-json-format

In particular this note:

When ingesting using the [ingestion wizard](https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-wizard), select Ignore data format errors, to ingest data in JSON format. If you leave this check box unselected, the data will be ingested in multijson format. For more information, see [edit the schema in the ingestion wizard](https://learn.microsoft.com/en-us/azure/data-explorer/ingestion-wizard-existing-table#edit-the-schema).

**Comment by YaelSchuster** [comment]
#please-close
