### ISSUE TITLE
command is incorrect:  should be '.clear database cache query_results'

### ISSUE THREAD

**Issue by gacurtin** [MicrosoftDocs/dataexplorer-docs#1447]
command is incorrect: should be '.clear database cache query_results'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd401028-385a-0c9b-aacf-6a4d1ed28b71
* Version Independent ID: 30a1aa22-5e30-9365-9e4b-e73cbd5791f4
* Content: [Clear query results cache - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/clear-query-results-cache-command)
* Content Source: [data-explorer/kusto/management/clear-query-results-cache-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/clear-query-results-cache-command.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by Naveenommi-MSFT** [comment]
@gacurtin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
@gacurtin thanks for pointing that out. I've fixed the example.

#please-close
