### ISSUE TITLE
Docs appear to be using outdated naming

### ISSUE THREAD

**Issue by Fuchio** [MicrosoftDocs/dataexplorer-docs#1452]
Hey,

The docs seem to be using outdated naming for the columns that are returned by the digital twin queries. Also in the examples there is no SourceTimeStamp in the "Example schema" on the page.

How our return schema looks like is:
Id | TimeStamp | SourceTimeStamp | ServiceId | ModelId | Key | Value | RelationshipTarget | RelationshipId

Main differences are:
1. SourceTimeStamp missing
2. twinId seems to have become just Id
3. First characters are now capitalized

This page contains examples which are not directly reproduceable because of these differences. Another page (link below) also uses the what appears to be older naming versions, most other pages seem to be up to date.
https://learn.microsoft.com/en-us/azure/digital-twins/concepts-data-explorer-plugin?source=recommendations

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e10ce0d-f814-ab77-ad91-5ea83e3b1079
* Version Independent ID: c2508f33-65c9-2efa-3436-ded0899f2275
* Content: [azure_digital_twins_query_request plugin - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/azure-digital-twins-query-request-plugin)
* Content Source: [data-explorer/kusto/query/azure-digital-twins-query-request-plugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/azure-digital-twins-query-request-plugin.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by AjayBathini-MSFT** [comment]
@Fuchio 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@Fuchio 

Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
Thanks @Fuchio for letting us know. We are tracking this update here: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2005700

At this time I'll close the GH Issue.

#please-close
