### ISSUE TITLE
arg_min() / arg_max() example descriptions are wrong

### ISSUE THREAD

**Issue by JacopoSitran** [MicrosoftDocs/dataexplorer-docs#1453]
Hey,
seems that the pages on arg_min() and arg_max() suffer from some wrong copy-pasting in the example section. The example descriptions are identical without adjusting "northern" to "southern" in arg_min(),  and "first" to "last" arg_max() 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93336287-fa47-0ca7-4aba-318906afba5c
* Version Independent ID: ce226d9f-108e-d2aa-c5c8-61f50cfadd1a
* Content: [arg_min() (aggregation function) - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-min-aggfunction)
* Content Source: [data-explorer/kusto/query/arg-min-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/arg-min-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by AjayBathini-MSFT** [comment]
@JacopoSitran 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
@JacopoSitran Thanks for pointing that out. I've changed the descriptions.

**Comment by YaelSchuster** [comment]
#please-close
