### ISSUE TITLE
datetime_local_to_utc function not in Azure Monitor Logs

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/dataexplorer-docs#1457]
I see documentation for the Kusto scalar functions for local --> UTC and UTC --> local. However, these functions do not appear be in or work for Azure Monitor logs. 

https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/datetime-local-to-utc-function

![image](https://user-images.githubusercontent.com/13274071/196774150-dba81097-2553-46fd-b92d-b7898f913ea2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3c013d2-791d-2072-6b4c-a07405100e8d
* Version Independent ID: 382d74ad-17a4-e358-2f4b-fd6d45bbe1b9
* Content: [datetime_local_to_utc() - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/datetime-local-to-utc-function)
* Content Source: [data-explorer/kusto/query/datetime-local-to-utc-function.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/datetime-local-to-utc-function.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YashikaTyagi-MSFT** [comment]
@ChristopherMank 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
@ChristopherMank thanks for pointing this out. We've discussed with Azure Monitor, and will be updating the doc to reflect that these functions are not supported in Azure Monitor logs.

#please-close

**Comment by YaelSchuster** [comment]
@christopherMank, on further exploration, we've found out that these functions do work, they just haven't been updated in intellisense.

**Comment by sloutsky** [comment]
The functions are supported in Azure Monitor - the issue here is that IntelliSense of Azure Monitor is not offering them as it is still in old version.  @YaelSchuster : please don't change docs.
