### ISSUE TITLE
Commands index not correct

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/dataexplorer-docs#1466]
It lists `.show failed ingestions` but the command is `.show ingestion failures`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9a9ae0a-eda8-7dce-a0ad-4a595e8177a4
* Version Independent ID: 170d9037-9722-c975-b547-86ed969a8e90
* Content: [System information - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/systeminfo)
* Content Source: [data-explorer/kusto/management/systeminfo.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/systeminfo.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
Have updated accordingly in the docs. Thanks for noticing that!
#please-close

**Comment by AjayBathini-MSFT** [comment]
@andrePKI 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
