### ISSUE TITLE
arg-max

### ISSUE THREAD

**Issue by pdendukuri** [MicrosoftDocs/dataexplorer-docs#1479]
Example 2 in this page https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-max-aggfunction

It should say "Find the **last** time an event with a direct death happened in each state showing all the columns."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80b51337-2793-f005-6f37-31f383ff7f02
* Version Independent ID: 4659f959-2e71-f6fb-5e2c-bba6271dd2cd
* Content: [arg_max() (aggregation function) - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-max-aggfunction)
* Content Source: [data-explorer/kusto/query/arg-max-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/arg-max-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by RamanathanChinnappan-MSFT** [comment]
@pdendukuri 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
I have fixed this issue in the docs. Thanks for letting us know!
#please-close
