### ISSUE TITLE
'syntax' section is a bit confusing

### ISSUE THREAD

**Issue by shanrath** [MicrosoftDocs/dataexplorer-docs#148]
Hello, 

Currently, [the 'syntax' section](https://github.com/MicrosoftDocs/dataexplorer-docs/blame/master/data-explorer/kusto/query/series-fit-2linesfunction.md#L45) is a bit confusing because the query expected results are bunched in with the next example output.

> project series_fit_2lines(x)
> 
> Will return all mentioned above columns with the following names: series_fit_2lines_x_rsquare, series_fit_2lines_x_split_idx etc. project (rs, si, v)=series_fit_2lines(x)
> 

I'd expect something like

**Syntax**

project `series_fit_2lines(`*x*`)`
* Will return all mentioned above columns with the following names: series_fit_2lines_x_rsquare, series_fit_2lines_x_split_idx etc.

project (rs, si, v)=`series_fit_2lines(`*x*`)`
* Will return the following columns: rs (r-square), si (split index), v (variance) and the rest will look like series_fit_2lines_x_rvariance, series_fit_2lines_x_line_fit and etc.

extend (rs, si, v)=`series_fit_2lines(`*x*`)`
* Will return only: rs (r-square), si (split index) and v (variance).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa6fbcc-e5c5-9973-d85d-ecb6e558b010
* Version Independent ID: 51840cae-1d85-d88f-26db-16cf90ed87ce
* Content: [series_fit_2lines() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/series-fit-2linesfunction)
* Content Source: [data-explorer/kusto/query/series-fit-2linesfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/series-fit-2linesfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by MartinJaffer-MSFT** [comment]
@shanrath  Thank you for bringing this to our attention.  I have created a pull request making the helpful changes you proposed.

Please let me know if you have any further questions.  Have a great day!
