### ISSUE TITLE
Make it clear that 'by user <user-name>' only works with .show running queries. 

### ISSUE THREAD

**Issue by shahdevangp** [MicrosoftDocs/dataexplorer-docs#1481]
The way it is written currently, it appears that 'by user <user-name>' can also work with .show queries command. However, it doesn't. It only works with .show running queries command.

This comes due to the way the syntax has been written:

Syntax

.show [running] queries [by * | by user UserPrincipalName]

As per this, a user can construct a command like .show queries by user <user-name>. However, this command will result in an error.

Can we please fix this? May be show different syntax for .show queries and .show running queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78921997-610a-bd56-8c8f-c2172feea868
* Version Independent ID: 5e5ee28a-6f90-96f8-2ddc-9b51f41062f5
* Content: [Queries management - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/queries)
* Content Source: [data-explorer/kusto/management/queries.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/queries.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
Hi @shahdevangp - can  you please either open a PR for this change on the private repo or open a work item? https://aka.ms/ADX-docs-WI
