### ISSUE TITLE
I cannot find "s_connectionString" in  Program.cs file  

### ISSUE THREAD

**Issue by candy5206031** [MicrosoftDocs/dataexplorer-docs#1484]
I cannot find "s_connectionString" in Program.cs file 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 448ddad1-243c-af54-3395-7d022f83dff7
* Version Independent ID: 09e32c75-831b-876e-c33a-9cd5a83500b3
* Content: [Ingest data from IoT Hub into Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-iot-hub#register-a-device-to-the-iot-hub)
* Content Source: [data-explorer/ingest-data-iot-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/ingest-data-iot-hub.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by RamanathanChinnappan-MSFT** [comment]
@candy5206031

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by vladikbr** [comment]
@candy5206031, I am terribly sorry, I cannot find any reference to Program.cs file in this article.
Could you please point me to the article + line number (or provide a screenshot with the page URL visible)?
