### ISSUE TITLE
Completely unclear hot to use parameters

### ISSUE THREAD

**Issue by Marusyk** [MicrosoftDocs/dataexplorer-docs#1496]
First,
![image](https://user-images.githubusercontent.com/9221694/201436407-2c737bab-4e9a-49c9-aea7-76c0d3263bff.png)
what is `PropertyName`? hot the example looks like? 
```
.execute database script [with A="AAA"]  
<|
    .show table Connection ingestion mappings
```
doesn't work - Syntax error!
then how?
The next
![image](https://user-images.githubusercontent.com/9221694/201436704-f2dc8296-5a19-4291-860f-6fe2c823e4ee.png)
How to specify Database scope? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 868b3894-4bd0-f427-468b-b035c87b803a
* Version Independent ID: 73b64711-da63-8c19-a206-5be99503d072
* Content: [.execute database script - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/execute-database-script)
* Content Source: [data-explorer/kusto/management/execute-database-script.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/execute-database-script.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by SaibabaBalapur-MSFT** [comment]
@Marusyk 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@shsagir 
Could you please review this and update as appropriate.

@Marusyk 
Thank you for bringing this to our attention. I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @Marusyk, can you please send an example of the full command you're using that gives an error? The examples shown will not work because you must put in a table name and properties. The properties are shown here: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/execute-database-script#optional-properties

**Comment by Marusyk** [comment]
how? where is the example? how should I know the syntax?

**Comment by YaelSchuster** [comment]
@Marusyk please note that the optional parameters are listed in the Optional properties section. They must be enclosed in parentheses, for example:

.execute database script with (ContinueOnErrors=true)
<|

I will edit the doc to make this more clear.

**Comment by YaelSchuster** [comment]
Since this is resolved, closing the issue now. Please feel free to reach out with further questions.

#please-close
