### ISSUE TITLE
Multiple Join Keys example

### ISSUE THREAD

**Issue by mathaholic** [MicrosoftDocs/dataexplorer-docs#1498]
please add an example of 

let b = table
           |some logic
           |distinct keyB, keyD, col1, col2;
a
| join kind=inner (b) on $left.keyA == $right.keyB, $left.keyC == $right.keyD

I've tried all permutations listed here:
https://stackoverflow.com/questions/58867033/kusto-kql-join-on-multiple-columns
and none of them worked

**Comment by SaibabaBalapur-MSFT** [comment]
@mathaholic 
We are going to close this thread as resolved as duplicate case.
Duplicate of #1498
