### ISSUE TITLE
Need example CSV to go with this

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/dataexplorer-docs#15]
First, it would be more helpful to have a sample CSV file that would be ingested with this mapping.  I find myself reading this and wondering if a rownumber/rowguid are metadata that are ingested with every CSV file, or just the sample data we can't see.  If the latter - if the CSV being ingested has columns called rownumber/rowguid - that's confusing.  Consider changing to a more obvious sample set like "LastName/FirstName".

Second, I've seen online samples showing you can use the mapping to insert const data.  This doc says nothing about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0013a7e-ee3a-6be5-64eb-a38b5f6c03a8
* Version Independent ID: ddaaa167-ce5c-5296-c403-9d3e354f315a
* Content: [.create ingestion mapping - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/create-ingestion-mapping-command#feedback)
* Content Source: [data-explorer/kusto/management/create-ingestion-mapping-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/create-ingestion-mapping-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@sloh-ms - thanks for your feedback
@kerend - please advise re: needed changes to update this doc as requested

**Comment by orspod** [comment]
@kerend - is the information documented elsewhere? please advise if there are needed changes to this doc.

**Comment by kerend** [comment]
Please review [concept document](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings) on mappings: 
rownumber/rowguid are predefined columns on the table. Properties field in mapping tells where to take the column from. For CSV, it's column ordinal in ingested data file.
By default, CSV is not expected to have titles row, if the file has titles, please use ignoreFirstRecord [ingestion property](https://docs.microsoft.com/en-us/azure/data-explorer/ingestion-properties)

**Comment by orspod** [comment]
@sloh-ms please LMK if @kerend comments answered your question.
@sloutsky can you please answer the second question: "Second, I've seen online samples showing you can use the mapping to insert const data. This doc says nothing about that."

**Comment by sloutsky** [comment]
@orspod - you can see that today's document has example how to insert constant data.
Attaching screenshot from https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings#csv-mapping

![image](https://user-images.githubusercontent.com/17802887/80306115-f5309700-87c9-11ea-9cb6-577234adde32.png)

**Comment by orspod** [comment]
@sloutsky - thanks so much for the quick response.
@sloh-ms - I hope this answers both your questions. Please let us know if you require additional assistance or clarification.

**Comment by orspod** [comment]
@sloh-ms - I believe that we've answered both your questions. Please let us know if you require additional assistance.
@KalyanChanumolu-MSFT  - please close the issue.

**Comment by KalyanChanumolu-MSFT** [comment]
@sloh-ms We will proceed to close this issue now. 
If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
