### ISSUE TITLE
Timechart sample query does not work

### ISSUE THREAD

**Issue by maxburs** [MicrosoftDocs/dataexplorer-docs#1502]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/8890312/202306500-adda179b-c406-49fc-b299-b864ccaed1da.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by ManoharLakkoju-MSFT** [comment]
@maxburs 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @maxburs 

Thanks for noticing this. I have updated the example to be one that works. 

#please-close
