### ISSUE TITLE
documenting limitations of free cluster

### ISSUE THREAD

**Issue by kiranpradeep** [MicrosoftDocs/dataexplorer-docs#1508]
It is not clear from docs if free adx cluster support following.

1.  live ingestion from iot hub
2. streaming ingestion is allowed or not
3. ingestion using sdk ([link](https://learn.microsoft.com/en-us/azure/data-explorer/net-sdk-ingest-data)) is allowed or not
4. etc etc

At the moment only documented limitaion ([link](https://techcommunity.microsoft.com/t5/azure-data-explorer-blog/azure-data-explorer-adx-free-cluster-with-upgrade-option/ba-p/3576347)) is 100 GB and 4 vCPUs. Could limitations of free cluster be documented? It might help avoiding questions like [these](https://stackoverflow.com/questions/71785820/problems-accessing-azure-data-explorer-free-cluster) in stackoverflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae82ebd2-f7f6-5068-54f2-69c7532b6b38
* Version Independent ID: 4727dbed-4e17-879b-d494-6ee62d78633a
* Content: [Ingest data with Azure Data Explorer .NET SDK](https://learn.microsoft.com/en-us/azure/data-explorer/net-sdk-ingest-data)
* Content Source: [data-explorer/net-sdk-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/net-sdk-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@kiranpradeep Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YashikaTyagi-MSFT** [comment]
@kiranpradeep 
Thanks for your feedback! We have assigned the issue to author who will provide further updates.

**Comment by avneraa** [comment]
The points raised in the issue are documented here: https://learn.microsoft.com/en-us/azure/data-explorer/start-for-free
