### ISSUE TITLE
parsejson is deprecated according to Azure log analytics portal when used

### ISSUE THREAD

**Issue by sergiosolorzano** [MicrosoftDocs/dataexplorer-docs#1513]
parsejson is deprecated according to Azure log analytics portal when used
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87ceffe2-e518-d7f5-6f1d-99cbf26dce9a
* Version Independent ID: 28ce08eb-3eac-ad19-e11f-a3fd754757ec
* Content: [Samples for Kusto Queries - Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/samples?pivots=azuremonitor)
* Content Source: [data-explorer/kusto/query/samples.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/samples.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by YaelSchuster** [comment]
Hi @sergiosolorzano, thanks for pointing this out. We have an active PR open fixing this documentation. 
Closing the issue at this time, please feel free to reach out with other docs improvements!

#please-close
