### ISSUE TITLE
authority variable in code sample is neither defined or explained

### ISSUE THREAD

**Issue by Brian-Von-Hochgurtel** [MicrosoftDocs/dataexplorer-docs#1516]
The code example has a variable called authority.  It is not defined in the code nor is it explained what it is in the text of the article. It is the unique id of the Azure Active Directory instance that you registered your app with.  It would have save me some headache if this information was in the article. 

Thanks for reading!
Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 266e7eb8-4c41-df4a-1b6e-38730477fdca
* Version Independent ID: 76208613-c17b-e8a1-bdf0-a3dded2746ed
* Content: [Create an Azure AD application in Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/provision-azure-ad-app)
* Content Source: [data-explorer/provision-azure-ad-app.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/provision-azure-ad-app.md)
* Service: **data-explorer**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by Naveenommi-MSFT** [comment]
@Brian-Von-Hochgurtel 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@Brian-Von-Hochgurtel 
I 've assigned this issue to the author who will investigate and update as appropriate.

@shsagir 
Could you please add your inputs on above query.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by cosh** [comment]
Hi Brian,

sorry for the inconveniences. I fixed it in https://github.com/MicrosoftDocs/dataexplorer-docs/pull/1520

KR, Henning.

**Comment by YaelSchuster** [comment]
#please-close
