### ISSUE TITLE
ERROR: datetime_utc_to_local doesn't refer to any know function?

### ISSUE THREAD

**Issue by yigitalparslan** [MicrosoftDocs/dataexplorer-docs#1528]
I get this error in Kusto application insights.
![image](https://user-images.githubusercontent.com/101216744/206282480-24dd7374-628f-41a6-91b6-4b5ef35243d6.png)

Any insights would be appreciated
Thanks

**Comment by AjayBathini-MSFT** [comment]
@yigitalparslan 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by yigitalparslan** [comment]
Sure, I was using this documentation: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/datetime-utc-to-local-function
I used this function to simply convert utc to local in ny application insight logs. The function is not recognized and raises error.

**Comment by AjayBathini-MSFT** [comment]
@elgevork 
Could you please review above document and add you inputs.

Thanks.

**Comment by elgevork** [comment]
Is the question about [this function](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/datetime-utc-to-local-function)?
This is a simple example: **print datetime_utc_to_local(datetime(2022-09-19 23:10:57.9851906),'US/Pacific')**
The example above can be used to test the basic usage.

**Comment by YaelSchuster** [comment]
Hi, since there has been no response from the user I am going to close the issue at this time.

#please-close
