### ISSUE TITLE
Add information on operator coerction in numerical expressions

### ISSUE THREAD

**Issue by cdmihai** [MicrosoftDocs/dataexplorer-docs#153]
It would be helpful if the numerical operations talked about type coercion (or linked to a page with that information). Does `long / long` produce a long or a float / real number?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1947564-176f-46a1-b33b-e04bdfcf502c
* Version Independent ID: 4166dbcc-cbd0-4076-c2ba-1b0498964135
* Content: [Numerical operators - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/numoperators)
* Content Source: [data-explorer/kusto/query/numoperators.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/numoperators.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@cdmihai thanks for your feedback. 
@yonileibowitz are you able to assist?

**Comment by yonileibowitz** [comment]
Hi @cdmihai,

the documentation includes topics for all `to*()` functions, which attempt to cast a given value to the target data type

![image](https://user-images.githubusercontent.com/42423208/84518156-26372f00-ac85-11ea-983d-1ca56f73417d.png)

**Comment by cdmihai** [comment]
@yonileibowitz, thanks for the info. I had also found it with further info. I opened the issue to let you know that the knowledge is not discoverable from the numerical operator doc page I opened the issue on. At the very least, it should have a "Related links" section pointing to details on the numeric type system, coercion rules, etc.

**Comment by yonileibowitz** [comment]
thanks for the feedback @cdmihai .
just in case you're interested - we happily accept contributions.
otherwise - I'll let @orspod consider the right approach regarding your feedback

**Comment by orspod** [comment]
@cdmihai - a WI has been created to deal with your suggestion. I'm closing this as an open issue for now, but feel free to continue to comment here as necessary.
