### ISSUE TITLE
isnotnull() function page shows notempty() as a synonym in the sidebar

### ISSUE THREAD

**Issue by dzsquared** [MicrosoftDocs/dataexplorer-docs#154]
The left sidebar shows "isnotnull(), notempty()" as the title for this article - instead of "isnotnull(), notnull()"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1aec316-04c5-e725-7e61-41abab34055d
* Version Independent ID: f7e8690d-7766-dec1-c41e-ed5657b6166c
* Content: [isnotnull() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/isnotnullfunction)
* Content Source: [data-explorer/kusto/query/isnotnullfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/isnotnullfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@dzsquared Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
@dzsquared 
The PR for the fix has been created & notified doc author. It will be reviewed and merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

Thank you.
