### ISSUE TITLE
CSV on the page should be lower case

### ISSUE THREAD

**Issue by yuanman2016** [MicrosoftDocs/dataexplorer-docs#156]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece17ed4-922c-fad6-8063-f6ba4988bd03
* Version Independent ID: 332cfe88-df27-b4e2-6556-d482b5f7fca2
* Content: [.drop ingestion mapping - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/drop-ingestion-mapping-command)
* Content Source: [data-explorer/kusto/management/drop-ingestion-mapping-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/drop-ingestion-mapping-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@yuanman2016 thanks for your feedback.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@yuanman2016 Thanks for your contribution, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/466](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/466)
The changes should be live EOD or tomorrow. We will now close this issue. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.
