### ISSUE TITLE
Incorrect case for parse_path: Filename instead FileName

### ISSUE THREAD

**Issue by itsnotapt** [MicrosoftDocs/dataexplorer-docs#1561]
https://github.com/MicrosoftDocs/dataexplorer-docs/blob/840809e110b3abf42269f4edd6a6853296934380/data-explorer/kusto/query/parsepathfunction.md?plain=1#L15

The `parse_path` function returns `Filename` instead of `FileName`.

**Comment by Naveenommi-MSFT** [comment]
@itsnotapt 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by shsagir** [comment]
@itsnotapt  Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close

**Comment by Naveenommi-MSFT** [comment]
@shsagir 
Thank you for your response.
