### ISSUE TITLE
KQL - Contributing New Functions

### ISSUE THREAD

**Issue by ltrk2** [MicrosoftDocs/dataexplorer-docs#1580]
Hello,

I'm looking to contribute a couple of functions to the specification and I was wondering if this was the right repository for this purpose. Could you please confirm this?

Specifically, I'd like to produce IPv6 variants of the `has_ipv4`, `has_any_ipv4`, `has_ipv4_prefix` and `has_any_ipv4_prefix` functions.

Thanks!

 I forgot to mention that it's the KQL specification (https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/) I'm looking to extend.

This is the list of functions in general: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/scalarfunctions

**Comment by ltrk2** [comment]
@AjayBathini-MSFT certainly. I forgot to mention that it's the KQL specification (https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/) I'm looking to extend.

This is the list of functions in general: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/scalarfunctions

**Comment by AjayBathini-MSFT** [comment]
@ltrk2 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by shsagir** [comment]
@ltrk2  Thanks for contacting us about wanting to contribute to our product documentation. Your request has been forwarded to the product team for their consideration. It could take from a few business days to a few weeks to look further into your offer. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by sloutsky** [comment]
@ltrk2 - contributing to service code can be done only if you work in Microsoft. If this is a case - please contact us over internal channel.

**Comment by shsagir** [comment]
@ltrk2  Per the previous message, I'm closing this issue. Thx

#please-close
