### ISSUE TITLE
This page should link to the "Mappings" page

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/dataexplorer-docs#16]
It would have been helpful to have a link here.
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0013a7e-ee3a-6be5-64eb-a38b5f6c03a8
* Version Independent ID: ddaaa167-ce5c-5296-c403-9d3e354f315a
* Content: [.create ingestion mapping - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/create-ingestion-mapping-command)
* Content Source: [data-explorer/kusto/management/create-ingestion-mapping-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/create-ingestion-mapping-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@sloh-ms - I added the link as requested. Closing this issue.
