### ISSUE TITLE
Example(s) missing

### ISSUE THREAD

**Issue by MantisTree** [MicrosoftDocs/dataexplorer-docs#162]
Examples of implementation would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c844fe93-572f-fcf9-7752-ca8252381e89
* Version Independent ID: 15f828db-95ff-1328-66bf-ddedf6c44865
* Content: [count() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/count-aggfunction)
* Content Source: [data-explorer/kusto/query/count-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/count-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@MantisTree 
Thanks for the feedback! We have assigned the issue to content author to further review the feedback and update the document as appropriate.

**Comment by orspod** [comment]
@sloutsky - thanks for adding the example.
@MantisTree - thanks for the feedback. I'm closing this issue for now, but feel free to continue to comment here if needed.
