### ISSUE TITLE
Describe behavior with backfilling overriding extent creation time when materialized view has >=2  datetime group-by-keys

### ISSUE THREAD

**Issue by nachoalonsoportillo** [MicrosoftDocs/dataexplorer-docs#1649]
In https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/materialized-views/materialized-view-create.md#backfill-a-materialized-view one paragraph mentions the following:

```If the materialized view includes a datetime group-by key, the backfill process supports overriding the [extent creation time](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/extents-overview#extent-creation-time) based on the datetime column. This can be useful, for example, if you want older records to be dropped before recent ones, because the [retention policy](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/retentionpolicy) is based on the extent creation time. For example, the following backfill will assign creation time based on the Timestamp group-by key:```

However, it doesn't mention which one is used to override extent creation time when there are two or more datetime group-by-keys included in the materialized view.

Would be very convenient to have that information included in that article.

title: Create materialized view - Azure Data Explorer
description: This article describes how to create materialized views in Azure Data Explorer.
ms.reviewer: yifats
ms.topic: reference
ms.date: 02/21/2023

**Comment by YashikaTyagii** [comment]
@nachoalonsoportillo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by yifatsor** [comment]
Thanks for the feedback @nachoalonsoportillo. If there's more than one datetime group by key, it will choose the first one. I will update the documentation accordingly.

**Comment by nachoalonsoportillo** [comment]
@yifatsor Thanks for investigating and for preparing the information to be included in the docs.

**Comment by YaelSchuster** [comment]
Added to active WI:

https://dev.azure.com/msft-skilling/Content/_workitems/edit/51024

#please-close
