### ISSUE TITLE
How to get all matches from extract() if the input matches a given regex pattern more than once

### ISSUE THREAD

**Issue by vamuzumd** [MicrosoftDocs/dataexplorer-docs#165]
[Enter feedback here]
I am trying to use _extract_ to match a given regex pattern from a column. My problem is that the column contains more than 1 value that matches the regex and I want to extract all the values that match the regex, but extract only returns the first matched pattern.

**Sample Input:**
"The following programs consumed the most virtual memory: ServiceHost.exe (4320) consumed 2703261696 bytes, my-service-x64.exe (12340) consumed 23505664 bytes, and w3wp.exe (3864) consumed 23344 bytes."

**Query:**
| Mytable
| extend processMemory = extract("([0-9]+) bytes", 1, EventDescription)
| extend  processName = extract("(\\S+) (\\(\\d+\\)) consumed",1, EventDescription)
| project processName, processMemory

**Expected values:** 

processName	processMemory
ServiceHost.exe	2703261696
my-service-x64.exe 23505664 
w3wp.exe 23344

**Actual value returned:** 

processName	processMemory
ServiceHost.exe	2703261696

 Is there any way I can get all the matching values instead of just the first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278a7ae3-4eba-a252-b4e8-66e04ea280a5
* Version Independent ID: 6812cf36-c5de-eefb-2217-a89d0efe221f
* Content: [extract() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractfunction)
* Content Source: [data-explorer/kusto/query/extractfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/extractfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by vamuzumd** [comment]
Looked into extract_all documentation and it achieves the intended purpose, closing the issue.

**Comment by KranthiPakala-MSFT** [comment]
Hey @  thanks for sharing your findings. :)

extract_all() documentation :https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractallfunction
