### ISSUE TITLE
search "Lab*PC" syntax

### ISSUE THREAD

**Issue by pallxk** [MicrosoftDocs/dataexplorer-docs#166]
It's said that

\# | Syntax | Meaning (equivalent where) | Comments
-- | -- | -- | --
8 | search "Lab*PC" | where * matches regex @"\bLab\w*PC\b" |  

But my test reveals that `search "Lab*PC"` actually equals to `where * matches regex @"\bLab.*PC\b"`

Test it with the following KQL:

```
print "Lab PC" | search "Lab*PC"  // 1 match

print "Lab PC" | where * matches regex @"\bLab.*PC\b"  // 1 match

print "Lab PC" | where * matches regex @"\bLab\w*PC\b"  // 0 matches
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b54882e-831a-64d3-a2e1-9dc8f689ff53
* Version Independent ID: 755ac9e9-796c-bf0c-6f29-c8810cbeca98
* Content: [search operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/searchoperator)
* Content Source: [data-explorer/kusto/query/searchoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/searchoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@pallxk  Thanks for bringing this to our attention. Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@yonileibowitz can you assist with this question? Thanks!

**Comment by yonileibowitz** [comment]
thanks @pallxk for pointing this out - you are correct, the docs are wrong, and we'll have them fixed

**Comment by yonileibowitz** [comment]
resolved by https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/527

**Comment by orspod** [comment]
@yonileibowitz thanks for fixing the docs. @pallxk - hope this answers your question. I am now closing this issue. If you have additional questions, feel free to reach out once again....
