### ISSUE TITLE
Describe effect, if any, of designating a stored function as a view

### ISSUE THREAD

**Issue by nachoalonsoportillo** [MicrosoftDocs/dataexplorer-docs#1668]
Designating a stored function as a stored view through the use of the view=true parameter in the .create function with clause doesn't seem to have any real effect. If it does, it should be explained this the following two articles:

https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/create-function

https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/views

**Comment by AjayBathini-MSFT** [comment]
@nachoalonsoportillo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@nachoalonsoportillo 
I've delegated this to content author @shsagir, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@shsagir 
Could you please review add comments on this, update as appropriate.

**Comment by YaelSchuster** [comment]
WI opened in DevOps
https://dev.azure.com/msft-skilling/Content/_workitems/edit/69796

#please-close
