### ISSUE TITLE
ADX External Table fetches no data

### ISSUE THREAD

**Issue by ashwini-git** [MicrosoftDocs/dataexplorer-docs#17]
i followed the document to create external table in ADX from ADLS 2. But external_table('table_name','mapping') fetches no records. Here are the steps i performed:
Created External Table:

```
.create external table extable (AppId:string) 
kind=blob
dataformat=json
( 
   h@'https://clickstreamstorelake2.blob.core.windows.net/streamout/0_56da70eca49745f8b830da45ff6aba57_1.json;secret_key'
)
with 
(
   docstring = "Docs",
   folder = "ExternalTables",
   namePrefix="Prefix"
)
```
_secret key : taking it from access keys in ADLS._

**JSON Mapping Created:**
`.create external table extable json mapping "map" '[{ "column" : "AppId", "datatype" : "string", "path" : "$.AppId"}]'`

External Table and Json mapping is created without error. But when i query data  - `external_table('extable','map)` it fetches no records.

i have also posted this query at stackoverflow here  - 
[https://stackoverflow.com/q/61228056/10009608](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ad0713-7721-c891-337a-ad08c7af64a0
* Version Independent ID: ecd185db-7a5c-e6e6-ffcf-51657903446c
* Content: [Query data in Azure Data Lake using Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/data-lake-query-data)
* Content Source: [data-explorer/data-lake-query-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/data-lake-query-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ashwini-git** [comment]
i didn't kept the folder structure right , which caused the issue. its resolved closing it.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@ashwini-git  Hope you have self resolved and hence closed the issue. Thanks for the update.
