### ISSUE TITLE
Out of date documentation on power apps connector

### ISSUE THREAD

**Issue by tbelqdx** [MicrosoftDocs/dataexplorer-docs#1734]
It looks like this tutorial is out of date: https://learn.microsoft.com/en-us/azure/data-explorer/power-apps-connector
When an azure data explorer is created, we can't access the "Results" variable we talk about when retriving the data.

I get the first error when adding this code in the ```` OnChange```` of my drop down
````
ClearCollect(
Results,
AzureDataExplorer.listKustoResultsPost(
"https://help.kusto.windows.net",
"Samples",
"StormEvents | where State == '" & Dropdown1.SelectedText.Value & "' | take 15"
).value
)
````

I tried to put directly the ADX source as input of my table but it is still not working

**Comment by SaibabaBalapur-MSFT** [comment]
@tbelqdx 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Converted to work item for tracking. 
https://dev.azure.com/msft-skilling/Content/_workitems/edit/70342

#please-close
