### ISSUE TITLE
Link to Authentication over HTTPS not working

### ISSUE THREAD

**Issue by schultechr** [MicrosoftDocs/dataexplorer-docs#1736]
The link to "Authentication over HTTPS" in the Februar 2023 is not working.

**Comment by SaibabaBalapur-MSFT** [comment]
@
Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team

**Comment by schultechr** [comment]
Sorry I missed the document. 

https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/whats-new.md

**Comment by SaibabaBalapur-MSFT** [comment]
@schultechr 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@shsagir 
please review it.

**Comment by YaelSchuster** [comment]
Thanks for pointing that out, have fixed this link in the following PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/4191

Should be live later today.

#please-close
