### ISSUE TITLE
ADX IotHub Dataconnection enqueuedtime bug with a array in message body

### ISSUE THREAD

**Issue by Ben-Duf** [MicrosoftDocs/dataexplorer-docs#1738]
Hello,
I have a problem in ADX ingesting data with a IoTHub Dataconnection.

in IoT Edge, I have OPCUA publisher module wich batches messages by 10.
in IoT Hub, I see the json message containing an array of OPCUA messages.
in the AdxDataConnection, I added the system property 'iothub-enqueuedtime'.

in ADX table, I dont have the array in one row, but I have many OPCUA message in separate rows ; well ok great.
the problem is : only one of them has the iothub-enqueuedtime property

* I think this array split behavior may be documented 
* is there something I can do for the enqueuedtime ? a property to set in the connector?

thanks for your help

**Comment by SaibabaBalapur-MSFT** [comment]
@Ben-Duf 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by Ben-Duf** [comment]
https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-iot-hub

**Comment by SaibabaBalapur-MSFT** [comment]
@shsagir
please review it.

**Comment by YaelSchuster** [comment]
Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
We've passed this product issue onto the team for further investigation. Closing the issue at this time.
#please-close
