### ISSUE TITLE
Kusto Security Roles Management, please add the example

### ISSUE THREAD

**Issue by PKPublicCode** [MicrosoftDocs/dataexplorer-docs#1742]
Please, add example how to use .show command for any of security roles in page below:
https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/security-roles.md

**Comment by SaibabaBalapur-MSFT** [comment]
@PKPublicCode 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @PKPublicCode, thanks for being in contact.
There are examples in the individual command docs, for example: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/manage-database-security-roles#example

**Comment by YaelSchuster** [comment]
Closing this issue at this time as there is no needed docs update
#Please-close
