### ISSUE TITLE
How to be notified then blob ingestion has completed successfully or failed using Event Grids ADX Ingestion

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/dataexplorer-docs#1745]
Regarding https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-event-grid?tabs=adx
How to be notified then blob ingestion has completed successfully or failed using Event Grid ADX Ingestion.

I would like to rename or move blobs after they have been ingested.

Thanks,

**Comment by SaibabaBalapur-MSFT** [comment]
@pisees 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @pisees, please refer to this document for monitoring batching ingestion: https://learn.microsoft.com/en-us/azure/data-explorer/monitor-batching-ingestion

**Comment by YaelSchuster** [comment]
#please-close
