### ISSUE TITLE
searching for ipv6 addresses within text

### ISSUE THREAD

**Issue by bemitc** [MicrosoftDocs/dataexplorer-docs#1754]
Functions to support searching for ipv6 addresses in text would be really useful to have, modeled after has_ipv4(), has_any_ipv4(), has_ipv4_prefix(), and has_any_ipv4_prefix().

**Comment by v-dkorn** [comment]
I will pass this feedback on to the team. Thank you. 

#please-close

**Comment by v-dkorn** [comment]
@bemitc 
You can [request this feature here](https://feedback.azure.com/d365community/forum/a952add5-eb24-ec11-b6e6-000d3a4f0da0 )
