### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/dataexplorer-docs#18]
This guidance (and tooling) needs to be updated for actualling using DevOps pipelines, not the outdated release pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6cb9693-823a-74c8-4af4-2ad8118256e7
* Version Independent ID: c2e9e58b-75e1-9cde-4fb5-5cd0aad043fd
* Content: [Azure DevOps task for Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/devops#feedback)
* Content Source: [data-explorer/devops.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/devops.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@dciborow - thanks for your feedback and input. I am tagging our content experts for this topic: @ManojRaheja and @grawcho, please advise re: needed changes.
I created a [WI](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1711734) to follow up. Thanks!

**Comment by orspod** [comment]
@dciborow - I am now moving to close this issue.

**Comment by jdiekhoff** [comment]
@orspod what is the status of the work item? That link gives a 403 access denied. Docs are also still out of date (have not been updated since 2019) and are using outdated "Releases" instead of pipelines.

**Comment by orspod** [comment]
@jdiekhoff  - Apologies for the delay. This has been in the docs queue for a while. 
Thanks for reaching out. The doc update is now in progress. @shsagir is currently working on it. It should be live soon.
@shsagir will you update when live?
