### ISSUE TITLE
Needs better documentation on PyPy

### ISSUE THREAD

**Issue by BadrulAlomEY** [MicrosoftDocs/dataexplorer-docs#182]
The link to installing the Python connector is not very useful. This link was a bigger help: 
https://github.com/azure/azure-kusto-python

Or just tell the user to type in 
azure-kusto-data
azure-kusto-ingest

into the PyPy section of the databricks server library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66353133-1b29-fa99-c9bd-e74c4a2f14dc
* Version Independent ID: 5cf9bdf3-207a-ab00-4cb9-4b5e4668f894
* Content: [Connect to Azure Data Explorer from Azure Databricks](https://docs.microsoft.com/en-us/azure/data-explorer/connect-from-databricks)
* Content Source: [data-explorer/connect-from-databricks.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/connect-from-databricks.md)
* Service: **data-explorer**
* GitHub Login: @ManojRaheja
* Microsoft Alias: **maraheja**

**Comment by BharathNimmala-MSFT** [comment]
@BadrulAlomEY Thank you for your feedback, assigned this issue to our Product PM and document author @ManojRaheja to further evaluate the feedback and update the document accordingly.

**Comment by ManojRaheja** [comment]
@BadrulAlomEY - this document is indented for using PySpark using the spark-kusto-connector. Would changing the doc title help?

**Comment by orspod** [comment]
PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/638 created to fix title

**Comment by orspod** [comment]
@BadrulAlomEY - thanks for your feedback. The title of the article was changed accordingly. I am now closing this issue.
