### ISSUE TITLE
ADF Substring length as an optional argument says invalid. 

### ISSUE THREAD

**Issue by iKshitiz** [MicrosoftDocs/dataexplorer-docs#183]
In documentation, It is mentioned that length parameter in substring function is optional and can be left blank. But In adf, It says substring requires 3 arguments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103728d9-415c-551e-ca55-7bd70a0894f0
* Version Independent ID: f88b2b51-a787-585b-708b-6b333fbdfe49
* Content: [substring() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/substringfunction)
* Content Source: [data-explorer/kusto/query/substringfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/substringfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BharathNimmala-MSFT** [comment]
@iKshitiz Thank you for bringing this to our notice, our team will look into it and get back to you at the earliest.

**Comment by KranthiPakala-MSFT** [comment]
@iKshitiz Thanks for reaching out. After reviewing the feedback, it seems that you are referring to Azure Data Factory substring function but this documentation is for Azure Data Explorer. If you have any feedback regarding ADF, please open another issue in ADF document.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thank you.
