### ISSUE TITLE
Ingestion from ADLS

### ISSUE THREAD

**Issue by yoelb** [MicrosoftDocs/dataexplorer-docs#185]
It seems that the ingestion from  Azure Data Lake Storage Gen 2 (ADLSv2) is not correct. It should be:
```
.ingest into table T (
  'abfss://myfilesystem@contoso.dfs.core.windows.net/path/to/file1.csv;...'
)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8367589f-76cb-1a24-37d0-e4355594fb18
* Version Independent ID: 3455ea4f-4ce4-ee0d-007c-d4ca3b7ec89e
* Content: [Kusto .ingest into command (pull data from storage) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-from-storage)
* Content Source: [data-explorer/kusto/management/data-ingestion/ingest-from-storage.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-ingestion/ingest-from-storage.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@yoelb  Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
@yoelb The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with

Thank you..
