### ISSUE TITLE
Data from Event Hub not showing up in Azure Data Explorer

### ISSUE THREAD

**Issue by mansivsaxena** [MicrosoftDocs/dataexplorer-docs#188]
1. I used a sample data generator application written in C# in Visual Studio Code to generate some data in Azure Cosmos DB in a container.
2.  Then wrote an Azure Function to send this data to event hub. 
3. Created an Azure Data Explorer account and a database with a table in it and used a data connection to connect to the created event hub where data was sent. 
4. On running the application and azure function, the data from cosmos DB is sent to event hub which can be seen in the metrics section.
5. The table in azure data explorer has the correct schema and mapping corresponding to the JSON documents in cosmos DB.
6. The data connection is also done successfully.
However **data in Azure Data Explorer table does not show  up**.
**Tutorial followed:** https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub

**Sample Data coming into event hub:**
```
[
  {
    "id": "f59eadd3-5c1d-41cd-b452-18d3d6fd0612",
    "CartId": 32169,
    "Action": "Added",
    "Item": "Unisex Beanie",
    "Price": 10,
    "BuyerState": "DE"
  },
  {
    "id": "d171d342-c0a9-4f95-acec-0707ffa6cdfd",
    "CartId": 58598,
    "Action": "Viewed",
    "Item": "Women's White Sweater",
    "Price": 32,
    "BuyerState": "VT"
  },
  {
    "id": "7193af99-dc9c-47d8-a912-34488802718f",
    "CartId": 68940,
    "Action": "Added",
    "Item": "Women's Green Sweater",
    "Price": 30,
    "BuyerState": "OK"
  }
]
 
```
**Azure Data Explorer Table Schema**

` .create table StoreTable (id: string, CartId: int, Action: string, Item: string, Price: double, BuyerState: string) `

**Table Mapping **

` .create table StoreTable ingestion json mapping "JsonMapping" 
'['
' {"column":"id", "Properties": {"Path": "$.id"}},'
' {"column":"CartId", "Properties": {"Path":"$.CartId"}},'
' {"column":"Action", "Properties": {"Path":"$.Action"}},'
' {"column":"Item", "Properties": {"Path":"$.Item"}},'
' {"column":"Price", "Properties": {"Path": "$.Price"}},'
' {"column":"BuyerState", "Properties": {"Path": "$.BuyerState"}}'
']' `

**Data Connection Settings:**
Target table: StoreTable
Mapping: JsonMapping
Data format: JSON

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5808ed2-5d09-4c56-dc0b-4e3650f8fc16
* Version Independent ID: ba034a8d-d5bb-6ea4-e61b-74ea3a5eb2be
* Content: [Ingest data from Event Hub into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub)
* Content Source: [data-explorer/ingest-data-event-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-hub.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@mansivsaxena Thanks for your feedback! We will investigate and update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
@mansivsaxena Thanks for reaching out. Have you noticed any specific error or warning message?

**Comment by KranthiPakala-MSFT** [comment]
@mansivsaxena We will now proceed to close this thread as we have not heard back from you. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thanks.
