### ISSUE TITLE
I need to some help

### ISSUE THREAD

**Issue by sivanyuegmail** [MicrosoftDocs/dataexplorer-docs#190]
[Enter feedback here]

"Use the bearer token in your request to the query endpoint."
Could you give more comprehensive examples of the last request? I tried for a day and still couldn't get through.

the error message as follow

"error": {
        "code": "Bad request",
        "message": "Query (parameter name: 'csl') cannot be empty.",
        "@context": {
            "clientRequestId": "unspecified;e70cced4-7ede-40b6-bf89-00698f578c3f",
            "activityId": "efc473f6-e15c-40c7-841f-67e4bac45370"
        }
    }

but my parameter csl is not empty!

curl -d '{"db":"testDB","csl":"CPUInfoTable| take 100 ","properties":"{\"Options\":{\"queryconsistency\":\"strongconsistency\"},\"Parameters\":{},\"ClientRequestId\":\"MyApp.Query;e9f884e4-90f0-404a-8e8b-01d883023bf1\"}"}' 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d046c47f-5e33-bff9-51fd-b8fa4905a260
* Version Independent ID: 49509522-8d22-75e4-8dc7-ec78ff83a045
* Content: [Query/management HTTP request - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/request)
* Content Source: [data-explorer/kusto/api/rest/request.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/rest/request.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KrishnaG-MSFT** [comment]
@sivanyuegmail Thanks for your comment! We will review and provide an update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
Hi @sivanyuegmail, 

Thanks for reaching out to us. At this time it does not look like you are referring to a document content, but to a specific scenario. If that's the case we request you to please post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) and other forums - [stackoverflow](https://stackoverflow.com/questions/tagged/azure-data-explorer), we have our engineers and others who are monitoring them and will be happy to help. 

If you have a document which you are following and if you think it needs an update, please let us know about that here.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thanks.
