### ISSUE TITLE
Kusto install link does not work

### ISSUE THREAD

**Issue by abbashus** [MicrosoftDocs/dataexplorer-docs#192]
The link to install Kusto explorer via "Install the Kusto.Explorer tool" does not work. It points to current page url.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba96a1-65dd-5320-6d36-47de50b8403f
* Version Independent ID: deee5b70-9bd5-2bf9-f7b7-12c40200693d
* Content: [Getting started with Kusto.Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer)
* Content Source: [data-explorer/kusto/tools/kusto-explorer.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/kusto-explorer.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by abbashus** [comment]
Closing this one. Similar to #177.

**Comment by grawcho** [comment]
@abbashus the link for installing kusto explorer is https://aka.ms/ke . It should download and open the Kusto. Explorer.application file which is the "click once" installer for the app.
The link seems to work for me both from inside and out side the MSFT network and allows annonimous access.
Can you please try the aka.ms link and share the actual URL you are directed to?
