### ISSUE TITLE
SDK version for .net standard

### ISSUE THREAD

**Issue by dougsi** [MicrosoftDocs/dataexplorer-docs#199]
The SDK version mentioned was in preview, but it's been deprecated. I don't see any new version that supports .net standard. What do you recommend?

This is what it says on the package itself:

> MPORTANT NOTE: This package is deprecated and no longer in active development. It is strongly recommended that new development use the Microsoft.Azure.Kusto.Xxx package which supersedes it

And the version ([Microsoft.Azure.Kusto.Ingest](https://www.nuget.org/packages/Microsoft.Azure.Kusto.Ingest/)) that supersedes it doesn't support .net standard, only .net framework and .net core.

So, how does one use this SDK in a library that is using .net standard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82ebd2-f7f6-5068-54f2-69c7532b6b38
* Version Independent ID: 4727dbed-4e17-879b-d494-6ee62d78633a
* Content: [Ingest data with Azure Data Explorer .NET Standard SDK (Preview)](https://docs.microsoft.com/en-us/azure/data-explorer/net-standard-ingest-data?source=docs)
* Content Source: [data-explorer/net-standard-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/net-standard-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@dougsi 
Thanks for reaching out.  We have assigned the issue to the content author to investigate this and provide an update as appropriate.

**Comment by orspod** [comment]
@vladikbr can you assist?

**Comment by vladikbr** [comment]
The documentation is not correct.
We indeed do not publish .NET Standard package, due to certain limitations we ran across.
So right now we only offer .NET and .NET Core.

Side note: going forward (if and when we shift the baseline requirement for .NET to 4.7.2 or higher) we will be able to go back to publishing .NET Standard packages.

**Comment by orspod** [comment]
@dougsi thanks for your feedback and bringing the incorrect doc to our attention. A WI has been created to update the docs accordingly. I am now closing this issue.

**Comment by orspod** [comment]
@dougsi : PR to fix the docs: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/650
