### ISSUE TITLE
GetIngestionStatusBySourceId always returns the status of Queued

### ISSUE THREAD

**Issue by karthik25** [MicrosoftDocs/dataexplorer-docs#211]
Hello,

I am having trouble getting the `GetIngestionStatusBySourceId` method to work (https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-client-examples#ingest-from-local-files-and-report-status-to-a-table). It always seem to return a status of **Queued**, even after the ingestion is completed as per the data explorer (using `.show operations`). Am I missing anything? I updated the method to break the loop based on previous and current row counts for the table in question and as expected, it works. But its not ideal, since we would be ingesting numerous files and this method won't be reliable. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49e16209-5d32-cebb-cec1-8c5be30a25aa
* Version Independent ID: 781d5ac3-83e4-9aa2-dfd7-35ace0fcd691
* Content: [Kusto.Ingest code examples - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-client-examples#ingest-from-local-files-and-report-status-to-a-table)
* Content Source: [data-explorer/kusto/api/netfx/kusto-ingest-client-examples.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/netfx/kusto-ingest-client-examples.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by karthik25** [comment]
Sorry, it does work perfectly. I missed setting the `ReportLevel` and `ReportMethod` properties for the `KustoQueuedIngestionProperties` instance. Closing this one out. Thanks!

**Comment by KranthiPakala-MSFT** [comment]
@karthik25 Glad that you were unblocked. Thanks for sharing your findings here 😊
