### ISSUE TITLE
The syntax uses sort by

### ISSUE THREAD

**Issue by pengjuntc** [MicrosoftDocs/dataexplorer-docs#218]
Shouldn't it be order by in the syntax?

_T_ | **`sort by`** _column_ [`asc` | `desc`] [`nulls first` | `nulls last`] [, ...]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f01ec0-f05e-3df0-6e70-1089542a03d6
* Version Independent ID: 3cbe9447-afe9-36c5-2bde-09807649973d
* Content: [order operator  - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/orderoperator)
* Content Source: [data-explorer/kusto/query/orderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/orderoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@pengjuntc Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
Hi @pengjuntc , 

I have cross verified withe internal team and confirmed that `sort by` and `order by` are two aliases for the same operator with no difference in functionality. I have provided a feedback to the internal team to make this consistent in docs and it would be improved the near feature. 

If you notice any differences, please feel free to report it to us. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thank you.
