### ISSUE TITLE
ADX best practices: add "don't use decimal when real will work"

### ISSUE THREAD

**Issue by gardnerjr** [MicrosoftDocs/dataexplorer-docs#226]
from random other places, this best practices doc should also include not using decimal unless you *really* need more accuracy than real (64 bit double) provides.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8936d746-8ea8-a5ac-a565-f50befdeb15e
* Version Independent ID: 412e3ef5-53ca-56eb-d3cd-1fb1088132e9
* Content: [Query best practices  - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/best-practices)
* Content Source: [data-explorer/kusto/query/best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@gardnerjr  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@gardnerjr - thanks for your feedback. This information doesn't exactly belong to query best practices. Decimal type should not be used in the beginning (as storage) if it isn't needed. I will look for an alternative location to place this information. I am now closing this issue.
