### ISSUE TITLE
Call ExtendedKustoIngestClient.IngestFromStreamAsync with individual json document 20 times/second is fine or not?

### ISSUE THREAD

**Issue by deyanp** [MicrosoftDocs/dataexplorer-docs#232]
Hi,

The page contains a lot of recommendations in direction of batching the data to be ingested. What I don't understand though is why the client application code should do the batching in case of Queued Ingestion? In that case Azure Data Explorer can itself decide how often (e.g. every 5 minutes) and how many queue messages to read at once, right?

Can I simply ingest individual json documents (for each one call ExtendedKustoIngestClient.IngestFromStreamAsync where the stream will contain only 1 json document), and do this e.g. 10-20/second?

Thanks in advance and best regards,
Deyan Petrov

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47ff6172-c040-65e6-55aa-1e418e5c53b9
* Version Independent ID: 74022ecc-45f6-99dd-873b-2cf6ebfd8676
* Content: [Kusto ingest client library best practices - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-best-practices)
* Content Source: [data-explorer/kusto/api/netfx/kusto-ingest-best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/netfx/kusto-ingest-best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by deyanp** [comment]
It should be actually the same as ingestion from Event Hubs where the client can write individual events to Event Hub at any time, and ADX ingests them every 5 minutes (batching them) ...

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by orspod** [comment]
@deyanp - thanks for the feedback. @vladikbr - can you assist with an answer?

**Comment by vladikbr** [comment]
@deyanp,
First of all, ingesting your data record at a time will incur costs - every IngestFromStream call involves a storage write transaction.
It is true that the ADX ingestion service will batch the incoming data (or more correctly, the blobs containing that data), but the more source data is fragmented, the harder the ingestion service will work and the more storage transactions will be needed.
So, if you are seeking to ingest truly "trickling" data, are better off with Event Hub ingestion or with Streaming Ingestion (https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/streamingingestionpolicy).
In case you wish to stick to the classic queued ingestion, I would recommend to batch the data on the client for as long as your latency requirements allow.

And last, you should be switching away from the ExtendedIngestClient methods (those are there for back compat), and move to IKustoIngestClient.IngestFromStreamAsync (https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-client-reference#interface-ikustoingestclient)

**Comment by deyanp** [comment]
@vladikbr, thanks for the answer and the hints about event hubs and IKustoIngestClient.IngestFromStreamAsync!

I am looking for the easiest (from client code point of view) way to ingest "trickling" data as you called it into ADX ...

Creating Event Hubs just for this sounds like an overkill (and additional costs) ... Do you mean that every call to IKustoIngestClient.IngestFromStreamAsync results in a separate blob written on a storage account? I was thinking you write a queue message only, which sounded equivalent to writing event hub messages, however it seems I am mistaken?

**Comment by vladikbr** [comment]
@deyanp,
Yes, every call to IKustoIngestClient.IngestFromXXX (other than IngestFromBlob) includes a write transaction to Blob storage. A queue message is also written to point to the written blob (or to the existing blob in case of IngestFromBlob).

If your scenario is trickling data, Streaming ingestion is for you. This mechanism was specifically designed for trickling scenarios.

**Comment by orspod** [comment]
@vladikbr thanks for the response.  @deyanp thanks for your feedback. 
I will now close this issue.

**Comment by deyanp** [comment]
Thanks @vladikbr , but are you sure Streaming Ingestion is applicable to my scenario where I have only a few events per second? I see this in the docs:

`"This ingestion method is suitable for ingesting a high volume of data, such as thousands of records per second, spread over thousands of tables. Each table receives a relatively low volume of data, such as a few records per second."`

Which is also a bit controversial, as the first sentence says thousands of records per second, and the second sentence ends with a few records per second ...
