### ISSUE TITLE
Streaming Ingestion with extents tags not work.

### ISSUE THREAD

**Issue by SilentCC** [MicrosoftDocs/dataexplorer-docs#233]
streaming ingest data with extents tags can upload data successfully, but extents tags didn't work!

```
  var kustoIngestionProperties =
                new KustoIngestionProperties(databaseName: "xxx", tableName: "xxx")
                {
                    Format = DataSourceFormat.csv,
                    DropByTags = new List<string> { "xxx" }
                };

            var str = "";
            var ms = new MemoryStream();
            using (var rd = new StreamReader(@"xxxx"))
            {
                str = rd.ReadLine();
                
            }
           // var ms = new MemoryStream();
            using (var tw = new StreamWriter(ms, Encoding.UTF8, 4096, true))
            {
                tw.WriteLine(str);
            }


            client.IngestFromStreamAsync(ms, kustoIngestionProperties).GetAwaiter().GetResult();
```

I can see the new data in Kusto. But I can't see the new extents tags with command: .show table xxx extents.
However when I use client.IngestFromStorageAsync, I can successfully upload with tags.
Maybe there is a bug with IngestFromStreamAsync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 694d3c49-5ee1-91d6-f75c-8bb0602c0433
* Version Independent ID: 72c1b168-0b36-f936-d7c9-a8a7633fd6dd
* Content: [Configure streaming ingestion on your Azure Data Explorer cluster using the Azure portal](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-streaming#limitations)
* Content Source: [data-explorer/ingest-data-streaming.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-streaming.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by NavtejSaini-MSFT** [comment]
@SilentCC Github feedback is for raising issues with Github documentation. Please share the document link for which this feedback is raised

**Comment by orspod** [comment]
@SilentCC  thanks for your feedback.
@alexefro - can you assist with this question?

**Comment by alexefro** [comment]
@SilentCC extent tags are not supported on data sent via streaming ingestion. Please see full list of limitations [here](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-streaming#limitations).

**Comment by SilentCC** [comment]
@alexefro Thanks! I see. But why are extent tags not supported with streaming ingestion? Can this be a new feature？

**Comment by orspod** [comment]
@SilentCC thanks for your question. I see @alexefro addressed it. Since Github feedback is for raising issues with Github documentation, please direct any additional product questions to stackoverflow. I will now close this issue. Happy to assist you in the future with any additional docs questions.
