### ISSUE TITLE
Is soon be available a correct statement? I think it is already there. 

### ISSUE THREAD

**Issue by uribarash-personal** [MicrosoftDocs/dataexplorer-docs#234]
Is soon be available a correct statement? I think it is already there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf34ca1-ff18-d8fb-3e5e-d1a814aef299
* Version Independent ID: 28e39763-a6c7-5e01-2ede-268685419e13
* Content: [Kusto Java SDK - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/java/kusto-java-client-library)
* Content Source: [data-explorer/kusto/api/java/kusto-java-client-library.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/java/kusto-java-client-library.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by NavtejSaini-MSFT** [comment]
@uribarash-personal We are checking this and we will get back to you.

**Comment by orspod** [comment]
Thanks @uribarash-personal for your feedback. @vladikbr - can you assist? Is "and will be soon available from Maven." correct or is it already available?

**Comment by vladikbr** [comment]
Yes, it is long since available on Maven.
I think we should delete all references to Maven and just leave the reference to the GitHub repo (it has library installation guidance pointing at Maven)

**Comment by orspod** [comment]
@vladikbr and @uribarash-personal  - maven has been removed. See PR: 
Is the SDK still called Kusto Java SDK and not Azure Data Explorer Java SDK?

**Comment by orspod** [comment]
@uribarash-personal - since your question has been addressed and doc changes made, I am now closing this issue
