### ISSUE TITLE
Update Policy view must match target table schema in column order

### ISSUE THREAD

**Issue by StenPetrov** [MicrosoftDocs/dataexplorer-docs#238]
I had a view that was used as an update policy for a table.
I added a column to the view, somewhere in the middle of other columns in the last `project`, then I *appended* the same column to the existing table. As a result ingestion into that target table stopped working, until I made the view return that new column *last*

This behavior was unexpected, as there was still an obvious name+type mapping between the view output and table schema.
This should be documented or changed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb3c4ca-b4aa-e3cd-0caf-dc1dea4422fd
* Version Independent ID: f456720e-8e16-ae7f-5bb6-7ecb7b162633
* Content: [Kusto update policy management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/update-policy)
* Content Source: [data-explorer/kusto/management/update-policy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/update-policy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@StenPetrov  Thanks for the feedback!  Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@StenPetrov - Thanks for your feedback! 
The update policy function schema and the target table schema must match – column names, types, and their order.
We will update the document with that information. See PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/613
Now that your question has been addressed, I will close this issue
