### ISSUE TITLE
Missing BadRequest_EmptyArchive

### ISSUE THREAD

**Issue by sloh-ms** [MicrosoftDocs/dataexplorer-docs#239]
I'm hitting "BadRequest_EmptyArchive: Empty zip archive" but that isn't documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4865cc4e-f472-ebe3-c8a7-0be9a9b3d939
* Version Independent ID: 534b2807-65fd-3c55-4e56-56ed29b30dc2
* Content: [Kusto.Ingest errors & exceptions - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-client-errors)
* Content Source: [data-explorer/kusto/api/netfx/kusto-ingest-client-errors.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/netfx/kusto-ingest-client-errors.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@sloh-ms  Thanks for the feedback! . Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@sloh-ms - thanks for your feedback. 
BadRequest_InvalidOrEmptyBlob that appears in the documentation was replaced by 4 errors:
- BadRequest_InvalidBlob – non zip blob that the Engine failed to open and read
- BadRequest_EmptyBlob – empty blob
- BadRequest_EmptyArchive – zip file that doesn’t contain any archived elements
- BadRequest_EmptyBlobUri – the specified blob URI is empty
We will update the docs accordingly. I am closing this issue. If you have additional questions feel free to comment.

**Comment by orspod** [comment]
See PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/743
