### ISSUE TITLE
KustoSourceOptions keys out of date

### ISSUE THREAD

**Issue by thrastarson** [MicrosoftDocs/dataexplorer-docs#241]
Hi,

It looks like the keys KUSTO_AAD_CLIENT_ID and KUSTO_AAD_CLIENT_PASSWORD in KustSourceOptions have been replaced with new names. If I'm correct it should be a breeze to update the docs.

Cheers,
Arni

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa46bfb-17f8-a18d-50a5-eaad4c85ae19
* Version Independent ID: ac1fc513-55d6-203a-ce2c-bae250d126d4
* Content: [Use the Azure Data Explorer connector for Apache Spark to move data between Azure Data Explorer and Spark clusters.](https://docs.microsoft.com/en-us/azure/data-explorer/spark-connector)
* Content Source: [data-explorer/spark-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/spark-connector.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@thrastarson Thank you very much for bringing this to our attention. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@thrastarson You're right in that the Azure AD application authentication property names had been updated recently. AFAIK, that would also affect `KustoSinkOptions` in addition to `KustoSourceOptions`.

I have submitted a PR to fix the issue that's under review. Thanks for letting us know!

**Comment by BhargaviAnnadevara-MSFT** [comment]
@thrastarson Thank you for the feedback! The change is merged internally and will go-live in the public docs shortly.
