### ISSUE TITLE
NOW()/UTCNOW()

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/dataexplorer-docs#246]
I expected to find on this page how could I get NOW/UTC NOW and didn't find

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e96632-ab2c-4c9a-bc5e-4224859e7f4a
* Version Independent ID: b476eea5-5895-39ca-d4ab-b78ad3f39e98
* Content: [Datetime / timespan arithmetic - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datetime-timespan-arithmetic)
* Content Source: [data-explorer/kusto/query/datetime-timespan-arithmetic.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/datetime-timespan-arithmetic.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Hi @yahorsi , Thanks for reaching out. now() function is documented under Scalar functions section. Please refer to this doc: [now()](https://docs.microsoft.com/azure/data-explorer/kusto/query/nowfunction)

Hope this helps. 

We will now proceed to close this thread. Please feel free to comment and tag us in your reply if there are further questions. We will gladly continue the discussion.

Thanks
