### ISSUE TITLE
Countif document needs an example to explain how the predicate works

### ISSUE THREAD

**Issue by bclubbMSFT** [MicrosoftDocs/dataexplorer-docs#248]
This page is difficult to follow without an example of what we can use as a predicate for the countif()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54049329-6d97-b871-d77f-0d9bd3138b72
* Version Independent ID: d744fad1-2b1f-cca3-5cd0-d170d35c7d67
* Content: [countif() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/countif-aggfunction)
* Content Source: [data-explorer/kusto/query/countif-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/countif-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@bclubbMSFT  Thanks for the feedback! Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@bclubbMSFT thanks for your feedback. The following two PRs have been created to clarify how predicate works:
https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/754 , https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/753
These clarifications should answer your question. Closing this issue now.
