### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by shwetalodha** [MicrosoftDocs/dataexplorer-docs#249]
[Enter feedback here]
In last 4th line - 'If you run the query above in Kusto.Explorer, all true values will be **displated** as 1, and all false values will be displayed as 0.'

My suggestion: It should be displayed rather than displated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b8c137-22c6-18b2-d07e-cc9e76e4dabb
* Version Independent ID: 82558980-9bca-1dcf-dba7-b59c94fc22ab
* Content: [Null Values - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/null-values?pivots=azuredataexplorer&source=docs)
* Content Source: [data-explorer/kusto/query/scalar-data-types/null-values.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/scalar-data-types/null-values.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@shwetalodha Thanks for your contribution, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/750](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/750)
The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.

We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
