### ISSUE TITLE
Add footnote or callout for "terms" in has/in string operators

### ISSUE THREAD

**Issue by kylebrandt** [MicrosoftDocs/dataexplorer-docs#250]
I was a little tripped up when a query like the following returned no results, even though there are results like "BA".

```kusto
Covid19
| where CountryCode has "b"
| summarize by CountryCode
| order by CountryCode asc
```

Returning to the documentation, and reading more of :-P, I see that I misunderstood because it matches 'terms' as described in https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators#understanding-string-terms .

I think it might help future users if this distinction was highlighted earlier in the document, or if 'has/in' has a footnote to draw you to the follow up section on understanding terms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11df65bd-6d46-7a8d-de92-97d933d7f1b1
* Version Independent ID: 51157ab2-6539-8ef8-75aa-89c1ad3026f7
* Content: [String operators - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators)
* Content Source: [data-explorer/kusto/query/datatypes-string-operators.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/datatypes-string-operators.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@kylebrandt 
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by MartinJaffer-MSFT** [comment]
@kylebrandt 
Thank you for your feedback. This has been assigned to the content owner and will be updated as appropriate.

**Comment by orspod** [comment]
@kylebrandt - thanks for your feedback. We will rewrite the topic to clarify. I am now closing this issue.

**Comment by YaelSchuster** [comment]
https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/759 was created to address this Issue
