### ISSUE TITLE
issue in ".create external table" using "dataformat=apacheavro "

### ISSUE THREAD

**Issue by SQLDataSide** [MicrosoftDocs/dataexplorer-docs#255]
[Hi
I have used 2 MXCHIPDevKit from Microsoft and generated data using IoT Hub into a Blob storage (Gen2) (Cold Path), my point is that the data is real and stored in a cold storage.

I have tested reading the files using **======>**

.create external table TblNameNew (EnqueuedTimeUtc:datetime, Properties:dynamic, SystemProperties:dynamic, Body:dynamic, filename:string)  
kind=blob  
dataformat=apacheavro 
( 
   h@'https://---------.blob.core.windows.net/' 
)

**======>** they are working with no problem.

Now I am trying to use the .ingest like ======>

.ingest into table TblNameNew2
("https://---------.blob.core.windows.net/") 
with (format="apacheavro", ingestionMapping=
'[\n'
'  {"column": "EnqueuedTimeUtc",    "Properties":{"Field":"EnqueuedTimeUtc"}},\n'
'  {"column": "Properties",    		"Properties":{"Field":"Properties"}},\n'
'  {"column": "SystemProperties",   "Properties":{"Field":"SystemProperties"}},\n'
'  {"column": "Body",     			"Properties":{"Field":"Body"}}'
']\n')

========> it does create the table for me but it does not read the data and insert it into the table
In Kusto.Explorer I get the error .....

Failed to download blob: Argument 'name' is null: at .ctor in C:\source\Src\Common\Kusto.Cloud.Platform.Azure\Storage\PersistentStorage\BlobPersistentStorageFile.cs: line 56
Parameter name: name
Failure Kind: Permanent

....... the link (https://) of the works fine 

maybe I am missing something.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc651bb6-a359-89f1-04ca-fd1a253a3ab0
* Version Independent ID: e5d31e43-6497-243d-0162-319dc9aeb87c
* Content: [Ingest sample data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-sample-data)
* Content Source: [data-explorer/ingest-sample-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-sample-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@SQLDataSide  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@SQLDataSide Thanks for your question! @kerend - can you please assist? Thanks!

**Comment by spektom** [comment]
@SQLDataSide please note that unlike external tables, full file path must be specified in `.ingest into` command connection string. If you need to ingest several files at once, you can separate connection strings with comma.

**Comment by orspod** [comment]
@SQLDataSide - hope that answers your question. Closing the PR. If you have additional comments, feel free to continue the conversation.
