### ISSUE TITLE
Wrong line of code

### ISSUE THREAD

**Issue by amsoffer** [MicrosoftDocs/dataexplorer-docs#256]
The last code snippet is wrong:
ingestClient.IngestFromStorageAsync
should be changed to
ingestClient.IngestFromStorageAsync(blobPath, ingestionProperties: properties).Result;

Because we must await on the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82ebd2-f7f6-5068-54f2-69c7532b6b38
* Version Independent ID: 4727dbed-4e17-879b-d494-6ee62d78633a
* Content: [Ingest data with Azure Data Explorer .NET SDK](https://docs.microsoft.com/en-us/azure/data-explorer/net-sdk-ingest-data)
* Content Source: [data-explorer/net-sdk-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/net-sdk-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by orspod** [comment]
@amsoffer - thanks for your feedback. @vladikbr - please review the requested change.

**Comment by vladikbr** [comment]
@amsoffer, thanks for pointing this out.

@orspod, can we please change line 205 to:
ingestClient.IngestFromStorageAsync(blobPath, ingestionProperties: properties).GetAwaiter().GetResult();

Thanks!

**Comment by orspod** [comment]
@vladikbr - thanks for the fix. Created PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/771 to correct the docs. Closing this issue now.
