### ISSUE TITLE
Cartesian product example makes no sense with current parameters

### ISSUE THREAD

**Issue by SsandmanN** [MicrosoftDocs/dataexplorer-docs#257]
The Cartesian product example makes no sense when the 3rd column is fixed at a single value ([5]).
It should be 2 values for 2nd column and 3 values for 3rd column, as in the previous example, so the difference can be made apparent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec66d4d-34dc-ad45-e456-afaa20947616
* Version Independent ID: 45e221db-2874-b65d-d67a-4bd6ebb203fd
* Content: [mv-expand operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/mvexpandoperator)
* Content Source: [data-explorer/kusto/query/mvexpandoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/mvexpandoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by orspod** [comment]
@SsandmanN - see PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/789 with doc changes that should answer your question. Closing this issue.
