### ISSUE TITLE
No option to restore the tab which got mistakenly closed

### ISSUE THREAD

**Issue by gauravgahlot299** [MicrosoftDocs/dataexplorer-docs#262]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e0fe92a-90be-c666-9d29-fe3d4eb68b27
* Version Independent ID: bfb921ef-c510-a3d4-6d39-d7e7f5fde79f
* Content: [Quickstart: Query data in Azure Data Explorer Web UI](https://docs.microsoft.com/en-us/azure/data-explorer/web-query-data#provide-feedback)
* Content Source: [data-explorer/web-query-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/web-query-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@gauravgahlot299  Thanks for the question! We are investigating and will update you shortly.

**Comment by KranthiPakala-MSFT** [comment]
Hi @gauravgahlot299 , Thanks for reaching out and sharing your feedback. This could be a feature request. 
I would recommend you to please share your feedback in ADX user voice forum: https://feedback.azure.com/forums/915733-azure-data-explorer as well as you can send feedback directly to ADX product team from portal as shown below.

![image](https://user-images.githubusercontent.com/50185738/89571864-35e27800-d7dd-11ea-9ff7-ae9bfeab2b8c.png)

Thank you.

**Comment by KranthiPakala-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thank you
