### ISSUE TITLE
'Let' examples unclear which is for parameterized user-defined or lambda functions

### ISSUE THREAD

**Issue by ZStoner** [MicrosoftDocs/dataexplorer-docs#266]
The issue refers to the docs page for the `let` operator, and in the 2nd to last example: `Use multiple let statements`.

- This example is an example of using the previously mentioned "_lambda_" syntax...
- ...but it's also an example of the also-previously mentioned "_User-defined function_" near the top of the docs page...
    * ...and it's currently the **_ONLY_** example here using **parameters** in any way.
- But the example's description indicates neither of these.
- The example as it stands still has a distinct purpose (_...calling a UDF/lamba from another_)...
    * ...but isn't a good example of more common UDF/Lambda functions that may be called from the body of the main query...
      ...rather than within the context of another `let` statement (_apart from the `materialize` example_).

**Suggestions** to improve the usefulness of the many variants of the `let` operator:
1. It would be useful if the example's description (and/or its title) better reflected that this is currently the only example in this page using **parameters** in any way.
2. Suggest adding examples to help clarify its various usage patterns when using parameters :
    * Add a parameterized **User-Defined Function** example, with at least one operator pipe and returns a **tabular** result.
    * Add a parameterized **Lambda** function example, with at least one operator pipe, but returns a single **scalar** result.
    * Add a parameterized **Lambda** function example with a single **scalar** expression (_i.e. like a `parse` or `trim` of the param_).
        + **Bonus points if this is called from a row context,** and not a simple `print` statement.
            Rows from a `range` statement would suffice.
    * Add a simple working example using the **`view ()` syntax**... **-OR-** at least provide a doc link to the `union` operator 
(_...of which this page currently has no actual link to the `union` page_)

Thanks,
----Z.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 741d0e14-4a3f-af28-1d6e-e6a6dd3dd414
* Version Independent ID: 731bbd4d-10c6-5cc4-741d-7cba31cb0586
* Content: [Let statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/letstatement#feedback)
* Content Source: [data-explorer/kusto/query/letstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/letstatement.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@orspod Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@ZStoner Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by orspod** [comment]
@ZStoner - thanks so much for your detailed feedback.
Here are the examples you requested:
<img width="500" alt="github-issue-266(a)" src="https://user-images.githubusercontent.com/42039150/89726481-b7c3e280-da23-11ea-96bb-6575fc30c01e.PNG">

<img width="573" alt="github-issue-266(b)" src="https://user-images.githubusercontent.com/42039150/89726488-bdb9c380-da23-11ea-9823-2b5438154d87.PNG">
<img width="600" alt="github-issue-266(c)" src="https://user-images.githubusercontent.com/42039150/89726490-c4483b00-da23-11ea-990c-e390e94480e1.PNG">

**Comment by orspod** [comment]
Updated doc in PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/778. Closing this issue now.
