### ISSUE TITLE
(doc/suggestion) need more detail about NSG rule requirement for client access

### ISSUE THREAD

**Issue by tamatsuxyz** [MicrosoftDocs/dataexplorer-docs#273]
**Suggestion**
About VNET deployment scenarios, Inbound NSG rule requirement is described in the following doc.

Deploy Azure Data Explorer cluster into your Virtual Network:
https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment

I suggest to add the client access rule sample to "Inbound NSG configuration" tables.

**Background**
I try to set NSG rule following "Inbound NSG configuration",
but I couldn't use https://dataexplorer.azure.com (also "query" menu in ADX blade).

Finally, I had to add client public IP  allow rule to Inbound rule.

It's hard to imagine dataexplorer.azure.com (also query menu) is based on direct access from browser client to ADX engine.
This is why, I suggest to add the client access rule sample to "Inbound NSG configuration" tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501c33cd-0ac0-685b-0da1-03a269616d08
* Version Independent ID: 67e7428d-9b35-cb0c-7af9-6fc402848b8d
* Content: [Deploy Azure Data Explorer into your Virtual Network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment)
* Content Source: [data-explorer/vnet-deployment.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/vnet-deployment.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@tamatsuxyz  Thanks for the feedback! Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@tamatsuxyz - thanks for your feedback. @basaba - can you assist?

**Comment by basaba** [comment]
@tamatsuxyz Thanks for your feedback.
The inbound rules section are rules that must be added for proper cluster operation, while the optional rules (based on user config) are mentioned earlier, we are concerned that adding another one to the list will be confused with the required dependency

**Comment by orspod** [comment]
@tamatsuxyz - I think that addresses your question. Thanks again for your feedback. I'm now closing this issue.
