### ISSUE TITLE
missing keyword "policy" 

### ISSUE THREAD

**Issue by chshihMSFT** [MicrosoftDocs/dataexplorer-docs#279]
should be
.alter table T1 **policy** streamingingestion '{"IsEnabled": true}'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7868235-6354-d9ae-1c3c-450c4d4133cd
* Version Independent ID: 9b6f6ac8-fa6d-b855-769d-00f04559c4ce
* Content: [Kusto streaming ingestion policy management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/streamingingestion-policy)
* Content Source: [data-explorer/kusto/management/streamingingestion-policy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/streamingingestion-policy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@chshihMSFT Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
@chshihMSFT The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

Thank you
