### ISSUE TITLE
Example of nested let statements is missing

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/dataexplorer-docs#3]
Looks like example of nested let statements is missing even text mentions it. The example is identical with the example of multiple let statements.

Also it should be noted if multiple let statements and access previously defined value or not. (Recursive let statements)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 741d0e14-4a3f-af28-1d6e-e6a6dd3dd414
* Version Independent ID: 731bbd4d-10c6-5cc4-741d-7cba31cb0586
* Content: [Let statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/letstatement)
* Content Source: [data-explorer/kusto/query/letstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/letstatement.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@jikuja - thank you for your contribution
@Mike-Ubezzi-MSFT - note issue in new repo
@yonileibowitz or @sloutsky please advise

**Comment by yonileibowitz** [comment]
@jikuja, thanks for letting us know - we'll update the example to include nested `let` statements

**Comment by orspod** [comment]
@yonileibowitz thanks for your assistance and for updating the docs.
@jikuja thanks for your feedback. Since doc has been updated, I will close the issue.
