### ISSUE TITLE
Issues with NULL values

### ISSUE THREAD

**Issue by rtaylor72** [MicrosoftDocs/dataexplorer-docs#30]
I setup 2 tables (let statements) and did a full outer join.  I then was doing a sort with max_of() between a column in each table of type decimal and getting weird inconsistent results.  When I added the max_of as a projected column, its value was sometimes blank.
This fixed some of the issues:
| sort by max_of(iif(isnotempty(FEDuration),FEDuration,todecimal(0)), APIDuration);
but I had to do this to work around it:
| sort by max_of(iif(isnotempty(FEDuration),FEDuration,todecimal(0)), iif(isnotempty(APIDuration),APIDuration,todecimal(0)));

The documentation says that the types have to be the same, but it appears it is not handling the NULL of the full outer join correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64825e12-4245-bc94-a714-1f8d65cc8541
* Version Independent ID: ecb76ffa-e95d-ae9a-ceda-1a69d5b5312d
* Content: [max_of() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/max-offunction)
* Content Source: [data-explorer/kusto/query/max-offunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/max-offunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@rtaylor72 - thanks for your feedback and question.
@yonileibowitz - can you please assist @rtaylor72 with an answer to this issue?

**Comment by orspod** [comment]
@yonileibowitz - can you please assist @rtaylor72 with an answer to this issue?

**Comment by yonileibowitz** [comment]
@rtaylor72 - would you be able to provide a minimal input data set (using the `datatable` operator) that allows running your query, and the expected result for it? it's currently hard to deduce that from the verbal description.

also - consider posting technical questions to StackOverflow (under the `kusto`, `azure-data-explorer` or `kql` tags) instead of here (as this is not monitored by the Product team)

**Comment by orspod** [comment]
@rtaylor72 - will you provide more information so we can assist you? Thanks!

**Comment by KalyanChanumolu-MSFT** [comment]
@rtaylor72 Its been a while we heard from you.
We will proceed to close this issue now. 
If there are further questions regarding this matter, please comment and we will gladly continue the discussion.

**Comment by rtaylor72** [comment]
I have not had a chance to circle back on this because of a project deadline. Please keep this open until this weekend.

Robert Taylor

________________________________
