### ISSUE TITLE
More examples for JSON

### ISSUE THREAD

**Issue by laughingman42** [MicrosoftDocs/dataexplorer-docs#310]
It would be useful if you can specify examples for JSON format. It would also be useful is there are either sample files to test with, and a writeup on how to handle nested json objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c78088-4289-15ef-3111-8116976124bb
* Version Independent ID: 3c8d8be2-2841-df0a-6c8b-b5a6893bbd1d
* Content: [externaldata operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/externaldata-operator)
* Content Source: [data-explorer/kusto/query/externaldata-operator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/externaldata-operator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@laughingman42 
Thanks for the feedback! We have assigned the issue to the content author to further review this feedback and update the document as appropriate.

**Comment by orspod** [comment]
@laughingman42 - thanks for your feedback. 
There isn't much difference in querying using externaldata() or external_table().
Here's an example of querying JSON file using external_table: https://docs.microsoft.com/en-us/azure/data-explorer/data-lake-query-data#querying-hierarchical-data-formats
Hope this answers your question.

**Comment by orspod** [comment]
PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/883 for fix

**Comment by spektom** [comment]
@laughingman42 Please see the updated documentation that now includes some examples for querying JSON files: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/externaldata-operator

**Comment by laughingman42** [comment]
Thanks @spektom 
Really appreciate it. This will be helpful for everyone.
