### ISSUE TITLE
Datasize limitations for externaldata()

### ISSUE THREAD

**Issue by laughingman42** [MicrosoftDocs/dataexplorer-docs#315]
This page doesn't specify what is the maximum number of records, or maximum filesize that this function can handle. Unless there are no limits.
It might also be a good idea to add a footnote that the ALA query will always limit the resultset to 10,000 rows, though the entire table maybe retrieved from the externaldata source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c78088-4289-15ef-3111-8116976124bb
* Version Independent ID: 3c8d8be2-2841-df0a-6c8b-b5a6893bbd1d
* Content: [externaldata operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/externaldata-operator)
* Content Source: [data-explorer/kusto/query/externaldata-operator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/externaldata-operator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@laughingman42  
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by orspod** [comment]
@laughingman42 - thanks for your feedback. Standard [query limits](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits) apply to external data queries as well.
Fix in PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/909
I will now close this issue. Thanks!
