### ISSUE TITLE
Consider specifying that Filter search shows up only once you have more than a handful of entries 

### ISSUE THREAD

**Issue by mitulmk** [MicrosoftDocs/dataexplorer-docs#318]
Nit: consider specifying that Filter search shows up only once you have more than a handful of entries 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fdcd90e-7d08-39e9-c2e5-888c690c6cbc
* Version Independent ID: 525bd933-5da2-29b5-8d7c-dadfa094c9f0
* Content: [Parameters in Azure Data Explorer dashboards](https://docs.microsoft.com/en-us/azure/data-explorer/dashboard-parameters)
* Content Source: [data-explorer/dashboard-parameters.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/dashboard-parameters.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@mitulmk  
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by orspod** [comment]
@Gabilehner

**Comment by orspod** [comment]
@mitulmk - created a WI to make this update. I'm closing now.

**Comment by orspod** [comment]
@Gabilehner @Mitulmk please review https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/906
