### ISSUE TITLE
"Use time filters first" best practice - what about conjunctions that contain time filters?

### ISSUE THREAD

**Issue by ymost** [MicrosoftDocs/dataexplorer-docs#319]
If the `where` operator contains a conjunction of a time filter with a non-time filter, will Kusto know to apply the time filter first, and benefit from the "use time filters first" best practice? 
Or should the user split the conjunction in two, so the time filter is explicitly first?
Whatever the answer is - I suggest adding this information to the page.

```javascript
// Is this good enough?
| where TimeColumn > ago(7d) and StringColumn contains "text"

// Or should we do this?
| where TimeColumn > ago(7d)
| where StringColumn contains "text"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8936d746-8ea8-a5ac-a565-f50befdeb15e
* Version Independent ID: 412e3ef5-53ca-56eb-d3cd-1fb1088132e9
* Content: [Query best practices  - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/best-practices)
* Content Source: [data-explorer/kusto/query/best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@ymost  
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by sloutsky** [comment]
Both expressions are the same.
(and please try to use 'has' instead of 'contains')

**Comment by ymost** [comment]
@sloutsky - thanks!
I understand from this that given a conjunction, Kusto will apply the time filter first, and benefit from the "use time filters first" best practice.
Short follow-up question: does the order of the expressions in the conjunction matter?

```javascript
// Will Kusto know to apply the time filter first here?
| where StringColumn has "text" and TimeColumn > ago(7d)
// Or do need to have it first in the conjunction like this?
| where TimeColumn > ago(7d) and StringColumn has "text"
```

**Comment by orspod** [comment]
@ymost - re: has/contains see here:
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators#what-is-a-term
"Kusto builds a term index consisting of all terms that are four characters or more, and this index is used by has, !has, and so on. If the query looks for a term that is smaller than four characters, or uses a contains operator, Kusto will revert to scanning the values in the column if it can't determine a match. This method is much slower than looking up the term in the term index."

**Comment by sloutsky** [comment]
The order of filters matters in general. Use time-filters first, and prefer having filter with best selectivity (stronger filter) first.

**Comment by orspod** [comment]
@ymost - thanks for your feedback. I believe your question has been addressed. I will now close this issue. If you have additional questions, feel free to continue the conversation by tagging @sloutsky and @orspod

**Comment by ymost** [comment]
Thanks! 
This is all very useful information, and some of it was not clear to me from the documentation.
Here are the things that were not clear to me from the current documentation, for your consideration:
1. Consecutive "where" filters are equivalent to a single "where" filter with a conjunction.
2. While the `and` operator is theoretically symmetric, in KQL queries it matters which filters come first. I now see that this can be understood from the ["where operator" page](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/whereoperator), but I would be more explicit about it, and also add it to the "best practices" page (it's especially relevant for the "time filters first" best practice).
