### ISSUE TITLE
how to add permission programatically

### ISSUE THREAD

**Issue by smartpcr** [MicrosoftDocs/dataexplorer-docs#32]
[Enter feedback here]

Kusto is using different model for access control, roles such as admin, viewer, injestor, etc cannot be managed via az-cli.

Are there alternative to manage these permissions using code?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbcf6abb-8fab-4656-8e36-0828841c1b11
* Version Independent ID: 310ac6c2-7491-5147-6d55-cd76a08c75b0
* Content: [Kusto Access Control Overview - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/)
* Content Source: [data-explorer/kusto/management/access-control/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/access-control/index.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@smartpcr - thank you for your question.
We have 6 how-to docs that may be helpful to you. They include adding cluster / database principals using C#, Python or ARM. See the following links as examples:
https://docs.microsoft.com/en-us/azure/data-explorer/database-principal-csharp 
https://docs.microsoft.com/en-us/azure/data-explorer/cluster-principal-python

**Comment by orspod** [comment]
@smartpcr - please LMK if your question was addressed.

**Comment by orspod** [comment]
@smartpcr - please LMK if your question was answered to your satisfaction.

**Comment by KalyanChanumolu-MSFT** [comment]
@smartpcr Its been a while we heard from you.
We will proceed to close this issue now. 
If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
