### ISSUE TITLE
There is an error reunning this  page, sample file in code may not be avaiable.

### ISSUE THREAD

**Issue by Nishco** [MicrosoftDocs/dataexplorer-docs#323]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc651bb6-a359-89f1-04ca-fd1a253a3ab0
* Version Independent ID: e5d31e43-6497-243d-0162-319dc9aeb87c
* Content: [Ingest sample data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-sample-data)
* Content Source: [data-explorer/ingest-sample-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-sample-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Nishco  Thanks for your feedback! We will investigate and update as appropriate.
