### ISSUE TITLE
Step 5 needs ( ) as shown below 

### ISSUE THREAD

**Issue by Nishco** [MicrosoftDocs/dataexplorer-docs#324]
Step 5 needs ( ) as shown below 
.ingest into table StormEvents h'https://kustosamplefiles.blob.core.windows.net/samplefiles/StormEvents.csv?st=2018-08-31T22%3A02%3A25Z&se=2020-09-01T22%3A02%3A00Z&sp=r&sv=2018-03-28&sr=b&sig=LQIbomcKI8Ooz425hWtjeq6d61uEaq21UVX7YrM61N4%3D' with (ignoreFirstRecord=true)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc651bb6-a359-89f1-04ca-fd1a253a3ab0
* Version Independent ID: e5d31e43-6497-243d-0162-319dc9aeb87c
* Content: [Ingest sample data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-sample-data)
* Content Source: [data-explorer/ingest-sample-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-sample-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Nishco  Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Nishco, As per my repro, it shows as nothing wrong with step5.  Could you please more details on your feedback.

`.ingest into table StormEvents h'https://kustosamplefiles.blob.core.windows.net/samplefiles/StormEvents.csv?st=2018-08-31T22%3A02%3A25Z&se=2020-09-01T22%3A02%3A00Z&sp=r&sv=2018-03-28&sr=b&sig=LQIbomcKI8Ooz425hWtjeq6d61uEaq21UVX7YrM61N4%3D' with (ignoreFirstRecord=true)`

![image](https://user-images.githubusercontent.com/44426401/92210502-6e44a700-eeac-11ea-8d39-f6f6a0deadfb.png)

**Comment by orspod** [comment]
@Nishco - thanks for your feedback. The SAS token has been extended and doc updated. I am now closing this issue.
