### ISSUE TITLE
WithAadUserPromptAuthentication is not available in SDK

### ISSUE THREAD

**Issue by kiranpradeep** [MicrosoftDocs/dataexplorer-docs#328]
Under section "AAD-based authentication examples", recommended code syntax samples use _WithAadUserPromptAuthentication_  which is not available in SDK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2795f4-802e-754f-f325-00ebe5a2e5e1
* Version Independent ID: 1eee8c82-9f46-764f-429d-228071922d4a
* Content: [Kusto connection strings - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto)
* Content Source: [data-explorer/kusto/api/connection-strings/kusto.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/connection-strings/kusto.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback @kiranpradeep! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by orspod** [comment]
@kiranpradeep thanks for your feedback @vladikbr - can you please assist?

**Comment by KranthiPakala-MSFT** [comment]
HI @kiranpradeep,

Please see below response from @vladikbr in the user voice forum:

```
"ADAL, the authentication library currently in use with ADX, does not support popping up an interactive UI for user authentication in .NET Core, so this is an infrastructure limitation.

Specifically to work around this issue, KustoConnectionStringBuilder can be initialized with the following properties to achieve username/password AAD authentication:
Fed=true
Username=…
Password=…

This approach has two disadvantages:
1. You pass in the password in cleartext
2. The resulting authentication will never be Multi-Factor

We are working to adapt our SDKs to work with the new authentication library (MSAL), but I am not sure this issue is addressed there."

```

Reference user voice link: https://feedback.azure.com/forums/915733-azure-data-explorer/suggestions/36777112-withaaduserpromptauthentication-method-not-availab

Tech Community discussion on the same issue: https://techcommunity.microsoft.com/t5/azure-data-explorer/missing-method-withaaduserpromptauthentication-in-microsoft/m-p/331479

@orspod Could you please create an internal work item to update the doc accordingly? - Thank you

**Comment by KranthiPakala-MSFT** [comment]
Hi @kiranpradeep , We have opened an internal work item (issue# 1769801) and assigned to content author to investigate further on this and update the document as appropriate. 

We will now proceed to close this thread based on this update. If there are further questions regarding this, please feel free to comment and we will gladly continue the discussion.

Thanks much for using Microsoft docs feedback forum for raising this concern and helping us to improve the doc content. 

-Stay safe :)
