### ISSUE TITLE
TotalOriginalDataSize does not mention the Unit of measurement. Is it Bytes ?

### ISSUE THREAD

**Issue by gbmsft** [MicrosoftDocs/dataexplorer-docs#336]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf45cf2-2f81-6063-01eb-6195d2e04054
* Version Independent ID: 5d1e0dd2-d14c-8a59-ce77-1b9f90fbe828
* Content: [Diagnostic information - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/diagnostics)
* Content Source: [data-explorer/kusto/management/diagnostics.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/diagnostics.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by RyanHill-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by KranthiPakala-MSFT** [comment]
Hi @gbmsft, 

Sorry for the delay in response. Yes, the unit of measurement for 'TotalOriginalDataSize' output parameter is 'bytes' .

Hope this answers your query. We will now proceed to close this thread. If there are further questions regarding this matter, please feel free to comment or open a new issue. We will gladly continue the discussion.

Thank you
