### ISSUE TITLE
Limit for string size for parese_xml

### ISSUE THREAD

**Issue by uthsab** [MicrosoftDocs/dataexplorer-docs#340]
[Question]
Is the limit for data size of 128KB still applicable. I have a ~220KB xml content as string in one of the fields and parse_xml seems to work on that field. 
Is it still recommended to stick to the 128KB limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a7851-083f-b4f4-d37a-cdf235101b72
* Version Independent ID: 9601cbfd-8b83-29df-03bf-6e429e317a43
* Content: [parse_xml() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-xmlfunction)
* Content Source: [data-explorer/kusto/query/parse-xmlfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/parse-xmlfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@uthsab  Thanks for the question! We are investigating and will update you shortly.

**Comment by sloutsky** [comment]
The limit was updated to 1MB (1,048,576 bytes). We will update the docs accordingly.

**Comment by uthsab** [comment]
Sure, thanks for the update!

**Comment by orspod** [comment]
Thanks @sloutsky for creating the PR with the fix: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/951
@uthsab thanks for the feedback! I am now closing this issue.
