### ISSUE TITLE
Typo under "Supported formats - ISO 8601" section

### ISSUE THREAD

**Issue by simonsigre** [MicrosoftDocs/dataexplorer-docs#342]
Under the "Supported formats - ISO 8601"  section the following exsts;
```
%Y-%m-%dT%H:%M:%s"
```
Please note the `"` . This trailing `"` should be removed;

This trailing `"` exists in approx 14 places in the document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68211517-a161-eb5b-9456-ec946c20c351
* Version Independent ID: a4d128b1-e602-ce69-a8eb-3ad151791024
* Content: [The datetime data type - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/datetime)
* Content Source: [data-explorer/kusto/query/scalar-data-types/datetime.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/scalar-data-types/datetime.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@simonsigre 
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by orspod** [comment]
@simonsigre - Thanks for your feedback. fix was done and PR was merged. Closing this issue.
