### ISSUE TITLE
Documentation needs to describe how to use advanced connection strings in the web app

### ISSUE THREAD

**Issue by chrisbro-MSFT** [MicrosoftDocs/dataexplorer-docs#344]
In the client app you can specify parameters on connection strings, like https://<cluster>.kusto.windows.net/security_signals_realtime;Authority Id=<guid>;User ID=<something>.

The documentation should also specify the format that you use when specifying these properties for the Data Explorer web app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2795f4-802e-754f-f325-00ebe5a2e5e1
* Version Independent ID: 1eee8c82-9f46-764f-429d-228071922d4a
* Content: [Kusto connection strings - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto)
* Content Source: [data-explorer/kusto/api/connection-strings/kusto.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/connection-strings/kusto.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@chrisbro-MSFT  Thanks for the feedback! We have assigned the issue to the content author to further evaluate this and update the document as appropriate.

**Comment by orspod** [comment]
@chrisbro-MSFT thanks for the feedback.
@lidermanrony - can you assist?
--

**Comment by lidermanrony** [comment]
the web client does not currently support any of these parameters

**Comment by orspod** [comment]
Thanks @lidermanrony for the information. I am now closing this issue. @chrisbro-MSFT, If you have additional questions, feel free to open another issue.
