### ISSUE TITLE
Non-ASCII characters in entity names

### ISSUE THREAD

**Issue by satonaoki** [MicrosoftDocs/dataexplorer-docs#346]
> They may contain letters, digits, underscores (_), spaces, dots (.), and dashes (-).

Entity names (such as column names) don't support non-ASCII characters (such as Japanese or Korean characters).

Could you please clarify what characters are supported as "letters"? (I think they are a-z and A-Z)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85b21a1-258d-b3bf-8c35-51f0e7162f21
* Version Independent ID: 7d58da00-bfa7-9303-8e63-872a65b9bc6a
* Content: [Entity names - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/entity-names)
* Content Source: [data-explorer/kusto/query/schema-entities/entity-names.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/schema-entities/entity-names.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@satonaoki 
Thanks for the question! We are investigating and will update you shortly.

**Comment by sloutsky** [comment]
Any letters supported, including Korean ones (with escaping):

print ['여보세요'] = 's'

**Comment by orspod** [comment]
@satonaoki - thanks for your feedback. @sloutsky - thanks for the response. I am now closing this issue.
