### ISSUE TITLE
The newest azure-kusto-data (pip version 1.0.2) doesn not have "azure.kusto.data.request"

### ISSUE THREAD

**Issue by koheikawata** [MicrosoftDocs/dataexplorer-docs#347]
I found the issues below, and please take a look at it and fix it if it is issues. 

1) This document should be updated because the most recent version of azure-kusto-data does not work for the import below.
```
from azure.kusto.data.request import KustoClient, KustoConnectionStringBuilder
```
Instead, it should be
```
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder
```

2) Another feedback is the example on this page does not use BlockBlobService. So the line below has to be removed.
```
from azure.storage.blob import BlockBlobService
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c010923-e011-6915-e3c4-6265fb997c35
* Version Independent ID: 6b102d99-8aae-bba3-0ddf-d4137c3d6434
* Content: [Ingest data using the Azure Data Explorer Python library](https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data)
* Content Source: [data-explorer/python-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/python-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@koheikawata - thanks for your feedback.
@vladikbr - can you assist?

**Comment by orspod** [comment]
@ArielYehezkely - thanks for your assistance. 
@koheikawata - the doc has been updated according to your feedback PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/964
I am now closing this issue.
