### ISSUE TITLE
hint.strategy = partitioned

### ISSUE THREAD

**Issue by SamZhangQingChuan** [MicrosoftDocs/dataexplorer-docs#349]
Is `hint.strategy = partitioned` valid? I have a piece of legacy code containing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563768b5-021b-9d7a-98cd-a630f67b02fd
* Version Independent ID: 2c0fe763-005d-5532-a7b4-9697e29dd380
* Content: [Shuffle query - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/shufflequery)
* Content Source: [data-explorer/kusto/query/shufflequery.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/shufflequery.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by himanshusinha-msft** [comment]
@SamZhangQingChuan  : I dont see anything mentioned on the document which mentions it deprecated or something . I could say it should work , but I will wait to hear from the content author as the final verdict . @orspod  : Can you please comment on the ask ?

**Comment by SamZhangQingChuan** [comment]
> @SamZhangQingChuan : I dont see anything mentioned on the document which mentions it deprecated or something . I could say it should work , but I will wait to hear from the content author as the final verdict . @orspod : Can you please comment on the ask ?

What I mean is that in the doc it says `Set shuffle query strategy using the query parameter hint.strategy = shuffle or hint.shufflekey = <key>.`. This seems not to mention other possibilities?

**Comment by orspod** [comment]
@SamZhangQingChuan  - Thanks for your feedback.
Hint.strategy=shuffle and hint.strategy=partitioned are quite the same.
In the past it was recognized as partitioned then there was a suggestion to change this to shuffle.
shuffle is now published in the docs and partitioned was removed but both are valid and recognized by the service.

I will now close this issue. Feel free to reply here if you have additional questions on this topic

**Comment by SamZhangQingChuan** [comment]
@orspod Would it be better if it can be mentioned in the doc that `partitioned` has been deprecated?

**Comment by orspod** [comment]
@SamZhangQingChuan - we will place the info in the doc and/or the KE and Web UI intellisense.

**Comment by SamZhangQingChuan** [comment]
@orspod thanks:)

**Comment by vRachelBell** [comment]
This issue was addressed with PR #2647 (https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2647)
