### ISSUE TITLE
Syntax error: Query could not be parsed: . Query: '.show database query results cache'

### ISSUE THREAD

**Issue by benohead** [MicrosoftDocs/dataexplorer-docs#354]
When trying to use this command to show the query result cache, I get the following error: "Syntax error: Query could not be parsed: . Query: '.show database query results cache'"

Does this command still exist ? Or are there any kind of prerequisite in order to be able to execute it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd8b7553-43ea-2351-b91d-040514fd61d3
* Version Independent ID: e2612f2f-0e5d-dcb5-707d-9868ac83e0bc
* Content: [Show query results cache - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-query-results-cache-command)
* Content Source: [data-explorer/kusto/management/show-query-results-cache-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/show-query-results-cache-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@benohead  
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by orspod** [comment]
@benohead - thanks for the feedback. The query syntax has been fixed in PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1003. Closing this issue.
