### ISSUE TITLE
clusterName parameter cannot be a variable

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/dataexplorer-docs#359]
When I attempt this:

```
let AppInsightsResultTable = (clusterName:string)
{
 cluster(clusterName)
};
let AppInsightsResult = materialize(
    AppInsightsResultTable(strcat("https://ade.applicationinsights.io/subscriptions/.../resourcegroups/", basename, "-", env, "/providers/microsoft.insights/components/", basename)).database(basename).requests);
```

I receive this error:
> Error 
>
> cluster(): first argument must be a non-empty string literal

so seems this syntax either isn't allowed or isn't properly documented if there is indeed a way to pull it off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6a7945-dc26-39b3-bec7-1778b7e53958
* Version Independent ID: d59ce2e5-2d13-0ff7-1017-df2bdb35299e
* Content: [cluster() (scope function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/clusterfunction?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/clusterfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/clusterfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@brandonh-msft 
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by MartinJaffer-MSFT** [comment]
Hello @brandonh-msft  I believe you are running into the caveat for the cluster function:

> Argument has to be constant prior to the query's execution, i.e. cannot come from sub-query evaluation.

I was able to run
```
let AppInsightsResultTable = (clusterName:string)
{
 cluster(clusterName)
};
AppInsightsResultTable("help").database('Samples').StormEvents
```
I am seeing if there is a way to make it constant other than hard-coding string literals

**Comment by MartinJaffer-MSFT** [comment]
I am closing this issue, as we connected out-of-channel.  If you would like to use `cluster()` with functions rather than string literals, please upvote/request this feature in the [feedback forum](https://feedback.azure.com/forums/915733-azure-data-explorer).

**Comment by brandonh-msft** [comment]
> I am closing this issue, as we connected out-of-channel. If you would like to use `cluster()` with functions rather than string literals, please upvote/request this feature in the [feedback forum](https://feedback.azure.com/forums/915733-azure-data-explorer).

[done and done](https://feedback.azure.com/forums/915733-azure-data-explorer/suggestions/41528347-allow-cluster-to-take-function-variable-values), thanks!

**Comment by aconkle** [comment]
@brandonh-msft @MartinJaffer-MSFT - How did you work around this? We are currently blocked on this.

**Comment by aconkle** [comment]
We are trying to do:

.show cluster;
let azEnv = $command_results | top 1 by StartTime
| extend azEnvironment = extractjson('$.compute.azEnvironment', EnvironmentDescription)
| project azEnvironment;
let clusterHybrid =
iif('AzureUSGovernmentCloud' in~ (azEnv), 'foo',
iif('AzureChinaCloud' in~ (azEnv), 'bar',
'public'));
cluster(clusterHybrid).database('foo').bar | take 1

**Comment by brandonh-msft** [comment]
> @brandonh-msft @MartinJaffer-MSFT - How did you work around this? We are currently blocked on this.

@aconkle , unfortunately no way to work around this. Suggest upvoting the feedback forum entry.

**Comment by brandonh-msft** [comment]
@masisley indeed; they're transitioning to a new feedback system/site. I can only hope the existing entries aren't lost. If/when it comes back online and my request is still there, I'll update the links.

cc @MartinJaffer-MSFT

**Comment by raegood** [comment]
I found potential partial hacky workaround, depending on your scenario, by unioning the tables in different clusters conditionally, if you have a small number of pre-defined clusters to toggle between. Not sure though if this has perf concerns though. 
For example:
let clusterName = "abc";
union (cluster("xyz").database("MyDB").Table123 | where clusterName  == "xyz"), (cluster("abc").database("MyDB").Table123 | where clusterName  == "abc")
| where ....

**Comment by brandonh-msft** [comment]
> I am closing this issue, as we connected out-of-channel. If you would like to use `cluster()` with functions rather than string literals, please upvote/request this feature in the [feedback forum](https://feedback.azure.com/forums/915733-azure-data-explorer).

@MartinJaffer-MSFT the link you cited here is unfortunately broken now. Where can users go to upvote?

**Comment by JoshBClemons** [comment]
This still isn't supported. I'm amazed you can't at least form the cluster name using only parameters (enum / constant) and other constant strings such as example below. Disappointing.
```
cluster(strcat("raieus", ["Environment"], "adx.eastus"))
```
