### ISSUE TITLE
series_fill_const does not have optional parameter 'constant_value'

### ISSUE THREAD

**Issue by mpdelbuono** [MicrosoftDocs/dataexplorer-docs#360]
When attempting to use the default for constant_value, I get an error: series_fill_const(): function expects [2..3] argument(s).

Based on this error, as best I can tell, series_fill_const does not have a default value for constant_value. If true, the documentation should be updated to reflect that.

I would make the edit myself, but since it's an API definition I would look to the code owners to confirm this behavior before changing the corresponding documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a535e5-9c59-da2a-6301-231c8c65bc6c
* Version Independent ID: a0a0f408-6bbd-c870-d6d9-69584a509581
* Content: [series_fill_const() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/series-fill-constfunction)
* Content Source: [data-explorer/kusto/query/series-fill-constfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/series-fill-constfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@mpdelbuono - thanks for the feedback. We are currently investigating this issue

**Comment by adieldar** [comment]
Thank @mpdelbuono for reporting this. We consider whether default value makes sense for this parameter. Accordingly we will fix either the function or the doc

**Comment by orspod** [comment]
@mpdelbuono the doc has been updated PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/996. 
@adieldar - thanks for the update.
Closing this issue.

**Comment by adieldar** [comment]
The updated doc is already published: [series_fill_const](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/series-fill-constfunction)

thanks,
Adi
