### ISSUE TITLE
Table visualization requests

### ISSUE THREAD

**Issue by adamabdelhamed** [MicrosoftDocs/dataexplorer-docs#364]
Table visualizer in dashboard should remember column size settings (e.g. manual sizes, or auto size options that are present within the column hamburger menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@adamabdelhamed  Thanks for the feedback! We have assigned the issue to the content author to review this and provide an update as appropriate.

@orspod Could you please have a look at this feedback and do the helpful needed. Thanks!

**Comment by orspod** [comment]
@adamabdelhamed - thanks for your request. Since this is a feature request, I am closing this issue.
Adding @Olgagold318 and @lidermanrony for FYI of feature request.
