### ISSUE TITLE
Map visualization improvement

### ISSUE THREAD

**Issue by prashanthmadi** [MicrosoftDocs/dataexplorer-docs#365]
Took me a while to figure this out and thought a good addition to our documentation.. you can do join on externaldata to get long/lat if your data has country code or county name.. while map visualization also requires long/lat

you can find lat/long + country_code+ country_name data from below link
https://developers.google.com/public-data/docs/canonical/countries_csv

| join kind = leftouter (
externaldata(country:string,latitude:real,longitude:real,name:string)[h@"<url>"]
with(format="csv"))
 on $left.AgentCountryCode == $right.country

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acb15859-4558-eb59-5940-f81c54cc475a
* Version Independent ID: 936f49a0-b7c5-5d9d-85a2-7e3d8cf2c788
* Content: [Customize Azure Data Explorer dashboard visuals](https://docs.microsoft.com/en-us/azure/data-explorer/dashboard-customize-visuals)
* Content Source: [data-explorer/dashboard-customize-visuals.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/dashboard-customize-visuals.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by NaveenAkode-MSFT** [comment]
Hello @prashanthmadi, Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by HarithaMaddi-MSFT** [comment]
@prashanthmadi - Thank you for your valuable inputs. It is mentioned in the documentation that lat/long details are needed for rendering map visual. And if they are not available in input data, retrieving them from external data is a specific scenario and we have [documentation ](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/externaldata-operator)on external data and joins as well that would help users to get the input data in required format before using in map visual.
![image](https://user-images.githubusercontent.com/61235246/94394951-2c8de000-017c-11eb-96c9-a9d2d4181c2d.png)
Please feel free to comment for any further questions on the same.

**Comment by prashanthmadi** [comment]
As i mentioned earlier, it took me atleast an hour to figure out that solution. we should be little more clear in this visualization doc on how to do it i guess.

**Comment by orspod** [comment]
Thanks @prashanthmadi for the feedback. I am adding for FYI: @mjsharma and @Gabilehner
