### ISSUE TITLE
Is it possible to ingest from a container using Kusto query language?

### ISSUE THREAD

**Issue by joelverhagen** [MicrosoftDocs/dataexplorer-docs#368]
This guide (https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-one-click) allows you to interactively import up to 1000 blobs into a Kusto table. Is it possible to do this same thing via scripting or the Kusto query language?

I would like to perform this task on a scheduled basic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fe3f579-2262-46b3-549a-12a01f6efaf6
* Version Independent ID: 3580c0ff-81ab-d190-0e41-a5c1f139c8bd
* Content: [Use one-click ingestion to ingest data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-one-click)
* Content Source: [data-explorer/ingest-data-one-click.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-one-click.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@joelverhagen  Thanks for reaching out. We have assigned the issue to the content author to further review the ask and provide an update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
Hi @joelverhagen I just had a conversation with internal source and confirmed that your ask can be achieved by LightIngest Utility.

LightIngest is a command-line utility for ad-hoc data ingestion into Azure Data Explorer. The utility can pull source data from a local folder or from an Azure blob storage container.

For more info please refer to this document: https://docs.microsoft.com/azure/data-explorer/lightingest


Hope this helps
