### ISSUE TITLE
Wrong step and link?

### ISSUE THREAD

**Issue by deyanp** [MicrosoftDocs/dataexplorer-docs#38]
Create public IP addresses -&gt; 2. Search for Network Security Group should be I guess 2. Search for Public IP Address instead ..

Next Steps -&gt; Deploy Azure Data Explorer into your Virtual Network seems to be linked with the current page, but I guess it should be linked to https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68819851-163e-b42d-949e-f20e11731d24
* Version Independent ID: 19cff8ca-b534-2278-f3f9-2eb7b8032abc
* Content: [Create an Azure Data Explorer cluster & DB in your virtual network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-create-cluster-portal)
* Content Source: [data-explorer/vnet-create-cluster-portal.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/vnet-create-cluster-portal.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@deyanp thanks for your feedback. The doc has been updated with the correct link. 
Can you please clarify your first question so @basaba can assist.

**Comment by deyanp** [comment]
My first point was related to the section "Create public IP addresses" in which step 2 says " Search for **Network Security Group**" which may be wrong, I would expect "Search for **Public IP Address**" instead

**Comment by orspod** [comment]
@deyanp - thank you for your feedback. I made the necessary change. Moving to close the issue.
