### ISSUE TITLE
sort and top example contains incorrect column name

### ISSUE THREAD

**Issue by LUKEALDRED** [MicrosoftDocs/dataexplorer-docs#381]
The second example in **sort and top** (https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/tutorial?pivots=azuredataexplorer#sort-and-top) contains the column name **EndLat**. I noticed EndLat doesn't contain any information. Should this be **EndTime**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b32c0bf-08cc-c345-edca-d8fb0e15ffac
* Version Independent ID: 436fb2c0-ada7-e5dc-d6b7-3d2a8b5ea191
* Content: [Tutorial - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/tutorial)
* Content Source: [data-explorer/kusto/query/tutorial.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/tutorial.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Hi @LUKEALDRED , 
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by orspod** [comment]
@himanshusinha-msft  - thanks for the fix. Change was merged and will be live with next publish.
@LUKEALDRED - thanks again for the fix. I will now close this issue.
