### ISSUE TITLE
Connection problems from Notebook

### ISSUE THREAD

**Issue by Craigmeister68** [MicrosoftDocs/dataexplorer-docs#387]
It should be mentioned in the documentation that the successful connection attempt must identify the cluster using the pattern 
'<cluster name>.<region>'

Not including the region produces this error message at the connection cell: 
ConnectionError: HTTPSConnectionPool(host='<cluster name>.kusto.windows.net', port=443): Max retries exceeded with url: /v2/rest/query (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Also, the Azure Notebooks preview has been deprecated as of October 9. Here is the note from the Azure Notebooks page:
The Azure Notebooks preview will be retired on January 15th, 2021, and all user data will be destroyed. Please download your user data before then.
To execute notebooks or create new notebook content, learn about our other notebooks experiences at Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f497838f-e309-f36a-43af-6d58b5e6b1e9
* Version Independent ID: 0cf67eee-4f79-9b23-7ec7-2ed347d68cb4
* Content: [Use a Jupyter Notebook to analyze data in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kqlmagic)
* Content Source: [data-explorer/kqlmagic.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kqlmagic.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Mike-Ubezzi-MSFT** [comment]
Hi, @Craigmeister68. Thank you for bringing this to our attention. I will work with the content team to have an update made as you have suggested. Thank you for taking the time to detail all the minor but important updates needed to this document.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@orspod  Could you please review further and update the document as appropriate.

**Comment by orspod** [comment]
@Craigmeister68  thanks for the feedback.
@ManojRaheja - can you please review user comments on this and Azure Notebooks doc

**Comment by orspod** [comment]
@ManojRaheja and @mbnshtck - please review user comments and assist in clarifications, as needed.

**Comment by orspod** [comment]
@Craigmeister68 Thanks for your feedback. I've created a [WI](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1784650) to deal with your request. I will now close this issue

**Comment by orspod** [comment]
@Craigmeister68 - doc was updated and Azure Notebooks removed in this PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1113
Thanks again for your feedback
