### ISSUE TITLE
Reference docs for a_timespan

### ISSUE THREAD

**Issue by krishnabm** [MicrosoftDocs/dataexplorer-docs#389]
[Enter feedback here]
Can you please provide a reference link to all acceptable values for a_timespan argument?
Valid combinations of month,year etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f89f5099-9596-787c-198e-cc5fcc2eb5aa
* Version Independent ID: 9cbf33f5-0698-131b-f2d5-11433e1d2392
* Content: [ago() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/agofunction)
* Content Source: [data-explorer/kusto/query/agofunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/agofunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@krishnabm  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@krishnabm - see this topic for additional information about timespan format: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/format-timespanfunction

**Comment by orspod** [comment]
@krishnabm - I believe we have answered your question. I will now close this issue. If you have additional questions, please respond here and @mention both @orspod and @CHEEKATLAPRADEEP-MSFT
