### ISSUE TITLE
Example that better shows regex usage

### ISSUE THREAD

**Issue by michael-niemand** [MicrosoftDocs/dataexplorer-docs#391]
It would be great to have an example where the content of the field that's parsed using regex is more like:

`10.242.21.13 [14/Oct/2020:12:48:32 +0000] "GET / HTTP/1.1" `

instead of 

`value01=10.242.21.13 value02=[14/Oct/2020:12:48:32 +0000] value03="GET / HTTP/1.1" `

The 2nd example is trivial and can be solved easily with the text parse alone. Extracting values without column names using regex does not seem to be so straight forward. 
I wasn't able to transform a (working) regex into a working expression

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db18f5b0-f08d-56f6-1045-3fae5577e2f9
* Version Independent ID: a1a2fbbe-12a3-b6bf-b087-9d5c6eb27e4f
* Content: [parse-where operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parsewhereoperator)
* Content Source: [data-explorer/kusto/query/parsewhereoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/parsewhereoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by michael-niemand** [comment]
nevermind, I think I'm using it wrong and use extract() instead

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@michael-niemand  Hope you have self resolved and hence closed the issue. Thanks for the update.
