### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by krepko7** [MicrosoftDocs/dataexplorer-docs#395]
You refer to Always-on configuration in one section title and then in two tables below you refer to it as Active-Active-Active-n.  You may want to update that.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c426719b-43df-8702-a573-9b1698439773
* Version Independent ID: d33d9114-7292-8487-a4c3-a3491b23c212
* Content: [Azure Data Explorer and business continuity disaster recovery](https://docs.microsoft.com/en-us/azure/data-explorer/business-continuity-overview)
* Content Source: [data-explorer/business-continuity-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/business-continuity-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Mike-Ubezzi-MSFT** [comment]
@krepko7 Thank you for bringing this to our attention. I am having the content team review this and have an update made as appropriate.

**Comment by orspod** [comment]
@krepko7 - thanks for your useful feedback. Created a [WI](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1784648) to update doc. I am now closing this issue. Thanks!
