### ISSUE TITLE
Incorrect example for `endswith_cs` operator

### ISSUE THREAD

**Issue by metrognome1** [MicrosoftDocs/dataexplorer-docs#398]
In the __Operators on Strings__ section the example given for the `endswith_cs` operator is shown as `"Fabrikam" endswith "Kam"` is incorrect. That statement when run in Azure Data Explorer resolves as false. The example should be something like `"Fabrikam" endswith "kam"`. The original example was probably copied from the `endswith` operator (non case-sensitive).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11df65bd-6d46-7a8d-de92-97d933d7f1b1
* Version Independent ID: 51157ab2-6539-8ef8-75aa-89c1ad3026f7
* Content: [String operators - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators)
* Content Source: [data-explorer/kusto/query/datatypes-string-operators.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/datatypes-string-operators.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@metrognome1 Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@metrognome1 Yes, it looks like a copy-paste error as `endswith` examples are the same as that of `endswith_cs`. Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.

Meanwhile, here is the updated set of examples:

Operator | Description | Case-Sensitive | Example (yields true)
-- | -- | -- | --
`endswith_cs` | RHS is a closing subsequence of LHS | Yes | `"Fabrikam" endswith_cs "kam"`
`!endswith_cs` | RHS isn't a closing subsequence of LHS | Yes | `"Fabrikam" !endswith_cs "brik"`
