### ISSUE TITLE
Search++ Kusto feature is not working

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/dataexplorer-docs#40]
Hello Team,

Search++ Kusto feature is not working as mentioned in Document - https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer#search-mode
It seems this feature is either deprecated or there is a bug or documentation needs to updated with correct steps.

Regards,
Hina Sharma
Support Escalation Engineer
Microsoft Dynamics 365
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba96a1-65dd-5320-6d36-47de50b8403f
* Version Independent ID: deee5b70-9bd5-2bf9-f7b7-12c40200693d
* Content: [Kusto.Explorer tool - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer#search-mode)
* Content Source: [data-explorer/kusto/tools/kusto-explorer.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/kusto-explorer.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@HinaMS - Thanks for your feedback. There is an open PR on the update for this functionality. 
https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/16 . It should be live early next week

**Comment by HinaMS** [comment]
I can’t access the PR information .
[cid:image001.png@01D61EB4.4B0B59F0]

**Comment by orspod** [comment]
@HinaMS i am attaching the text for the change. Please LMK if this answers your question. 

Search++ mode enables you to search for a term using search syntax across one or more tables.

In the Home tab, in the Query dropdown, select Search++.
Select Multiple tables.
Under Choose tables, define which tables to search.
In the edit box, enter your search phrase and select Go.
A heat-map of the table/time-slot grid shows which terms appear and where they appear.
Select a cell in the grid and select View Details to show the relevant entries in the results pane.

**Comment by orspod** [comment]
@HinaMS - did the information above answer your question?

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@HinaMS  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
