### ISSUE TITLE
Clarify the starting offset for Event Hubs ingestion

### ISSUE THREAD

**Issue by joelw** [MicrosoftDocs/dataexplorer-docs#403]
Hi! Would it be possible for this document to clarify the initial offsets used for Event Hubs ingestion? In my testing it appears that it uses the latest position - that is, it will only start reading events published after the connection is created. Is there any way to set an initial offset / timestamp or to specify that it should read all available events upon creation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48946887-6f4c-9fc9-a3ba-1609b1059cab
* Version Independent ID: 73781e6f-3343-5abf-e483-05c0dac13075
* Content: [Ingest from Event Hub - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub-overview)
* Content Source: [data-explorer/ingest-data-event-hub-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-hub-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by HarithaMaddi-MSFT** [comment]
@joelw - Thanks for posting the question. We are looking into it and will update you shortly.

**Comment by HarithaMaddi-MSFT** [comment]
@orspod - As per my understanding, it is not configurable today. Can you please share your thoughts on the ask.

**Comment by orspod** [comment]
@kerend and @LeaShallev - will you respond re: the question?

**Comment by orspod** [comment]
@kerend and @LeaShallev can you assist with this question? Thanks.

**Comment by kerend** [comment]
![image](https://user-images.githubusercontent.com/20067795/97107918-c640a280-16d2-11eb-820d-4a3e6be798cb.png)

Please see the note on the subject - events are ingested from the moment the connection was created.

**Comment by joelw** [comment]
Ah! You're absolutely correct. I did not see that for some reason. Thank you and sorry for the trouble!

**Comment by orspod** [comment]
@joelw since your questions was answered I will now close your issue.
@kerend thanks for the assistance
