### ISSUE TITLE
Understand Azure Data Explorer Dashboard Usage (Number of Users, etc.)

### ISSUE THREAD

**Issue by gibron** [MicrosoftDocs/dataexplorer-docs#408]
Is there a way to find out what the usage of Azure Data Explorer Dashboards by users by Subscription? 
Would like to provide a usage report to influence the ongoing use of this feature across the broader team. 

Some metrics we would be after: 
* number of dashboards created
* number of users w/ dashboards (by time period [day, month])
* daily users of dashboards (by time period)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1640-3699-8fdf-07a2-c9b922499c90
* Version Independent ID: 55027537-6af4-541d-da8d-e2cdc2b5fa92
* Content: [Visualize data with the Azure Data Explorer dashboard](https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards)
* Content Source: [data-explorer/azure-data-explorer-dashboards.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/azure-data-explorer-dashboards.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by thisisnish** [comment]
+1

**Comment by Svijay-msft** [comment]
Thanks for the question! We are taking a look into this and will get back to you soon.

**Comment by orspod** [comment]
@Gabilehner - can you assist with this question?

**Comment by Gabilehner** [comment]
Hi, unfortunately we don't have a trivial way to offer this today.
As workaround, assuming you have admin permissions on the DB where the data of the dashboards is stored, you can use .show queries command to extract all the data about the queries that were sent to the relevant DB. Assuming you have a way to identify the queries sent from the dashboard (in the query text column) you'll be able to find data on users, apps, etc.
The issue with building a dashboard that is built on a control command (like .show queries) is that you cannot use parameters with it.
Please vote for it on our user-voice.

Thanks,
Gabi

**Comment by HarithaMaddi-MSFT** [comment]
@Gabilehner - Thanks for sharing the details along with workaround and limitation. 

@gibron - As recommended, kindly post an idea in[ feedback forum](https://feedback.azure.com/forums/915733-azure-data-explorer) which is closely monitored by our product team to implement in future releases. I will proceed with closing the issue now, please feel free to post for any queries.
