### ISSUE TITLE
Json Array Doesn't Work

### ISSUE THREAD

**Issue by AC740** [MicrosoftDocs/dataexplorer-docs#416]
[Enter feedback here]

I made same process and it works with one record but it doesn't work with multiple records.

This works
{"TimeStamp": "1987-11-16 12:00","Value": "two array World","Source": "TestSource"}

but this doesn't work
[{"TimeStamp": "1987-11-16 12:00","Value": "two array World","Source": "TestSource"},{"TimeStamp": "1987-11-16 12:00","Value": "twotwo array World","Source": "TestSource"}]

Could you advice me why multiple records doesn't work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf4599f-0e80-47fc-c919-be4434dcdffd
* Version Independent ID: 8ef468be-2c25-d37c-be11-23f0ad8d5c3c
* Content: [Ingest Azure Blobs into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-grid)
* Content Source: [data-explorer/ingest-data-event-grid.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-grid.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by AC740** [comment]
Found, there is multiline json option. (I had the same problem 5 years and I did again.)

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@AC740  Hope you have self resolved and hence closed the issue. Thanks for the update.
