### ISSUE TITLE
Text references "table below" which doesn't exist

### ISSUE THREAD

**Issue by dellch** [MicrosoftDocs/dataexplorer-docs#42]
On page `Azure  / Azure Data Explorer / Kusto / Query Language / Reference material for Kusto Query Language / RE2 syntax`, the second paragraph has the statement:
> ... matches the beginning of a line (see the table below), ...

But the page contains no table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4453d290-493e-74a0-3ada-1bd39bfbd587
* Version Independent ID: 275a219c-9449-bc07-ceec-8f3b765fa2a7
* Content: [Regular expressions - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/re2#feedback)
* Content Source: [data-explorer/kusto/query/re2.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/re2.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@dellch thanks for your feedback. I am investigating the matter further and will update.

**Comment by YaelSchuster** [comment]
@dellch thanks for your feedback. Created a PR to fix this reference. Closing issue now.
