### ISSUE TITLE
COGS term unclear / undefined

### ISSUE THREAD

**Issue by hugovoerman** [MicrosoftDocs/dataexplorer-docs#427]
Hi, 

Also in https://github.com/orspod/azure-docs/commit/21e10d60f7d2d71b3378f5a8e4405069ba6de24f
the term COGs was used and created confusion and not clearity.

In this page it even has a heading. "Optimizing for COGS" 
What is meant by that?

Thank you for the clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47ff6172-c040-65e6-55aa-1e418e5c53b9
* Version Independent ID: 74022ecc-45f6-99dd-873b-2cf6ebfd8676
* Content: [Kusto ingest client library best practices - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-best-practices#optimizing-for-throughput)
* Content Source: [data-explorer/kusto/api/netfx/kusto-ingest-best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/netfx/kusto-ingest-best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@hugovoerman  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
Thanks @hugovoerman for the feedback
Adding explanation of COGs to text in various places in repo: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1182
Will now close this issue.
