### ISSUE TITLE
Cannot compare dynamic values without explicit cast

### ISSUE THREAD

**Issue by evilches** [MicrosoftDocs/dataexplorer-docs#43]
The main example: 
print extract_all(@"(\d+)", "a set of numbers: 123, 567 and 789") == dynamic(["123", "567", "789"])
throws the error: Cannot compare dynamic values without explicit cast

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df27c2b2-99c9-ed18-5b94-85e506132632
* Version Independent ID: d77fe688-fe1d-1c4f-eacc-d5d52b2d130f
* Content: [extract_all() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractallfunction#feedback)
* Content Source: [data-explorer/kusto/query/extractallfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/extractallfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@evilches thanks for your feedback.
@yonileibowitz - can you assist re: this question?

**Comment by yonileibowitz** [comment]
thanks @evilches, we'll have the example in the docs updated

**Comment by yonileibowitz** [comment]
resolved by https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/125

**Comment by orspod** [comment]
@yonileibowitz thanks for the super quick fix.
@evilches hope this resolves the issue. I am closing the issue. Feel free to reach out with any additional questions.
