### ISSUE TITLE
Parquet data ingest inconsistency

### ISSUE THREAD

**Issue by thec0dewriter** [MicrosoftDocs/dataexplorer-docs#430]
Hello,
The description under: https://docs.microsoft.com/en-us/azure/data-explorer/lightingest#how-to-ingest-data-using-creationtime mentions that the blob name contains parquet but the the Kusto ingest command says that the format and pattern is CSV:
 
ingest-{Cluster name and region}.kusto.windows.net;AAD Federated Security=True -db:{Database} -table:Trips -source:"https://{Account}.blob.core.windows.net/{ROOT_CONTAINER};{StorageAccountKey}" -creationTimePattern:"'**historicalvalues'yyyyMMdd'.parquet**'"
 -pattern:"*.csv.gz" -format:csv -limit:2 -ignoreFirst:true -cr:10.0 -dontWait:true

This is quite misleading.  Is it supposed to work for csv or for parquet?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b60b016-b2b8-7c45-be03-4df69ef9d696
* Version Independent ID: 17fc1c4b-f6c6-4c1f-e377-c204fad6b107
* Content: [Use LightIngest to ingest data to Azure Data Explorer.](https://docs.microsoft.com/en-us/azure/data-explorer/lightingest#azure-blob-specific-capabilities)
* Content Source: [data-explorer/lightingest.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/lightingest.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@thec0dewriter thanks for your feedback.
@vladikbr - please advise.

**Comment by vladikbr** [comment]
this is a typo, we need to change "-pattern:"*.csv.gz"" to "-pattern:"*.parquet""

**Comment by YaelSchuster** [comment]
Addressed in PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1198

**Comment by orspod** [comment]
Thanks all for the fix. @thec0dewriter thanks again for your feedback. Since issue is resolved, I'm now closing this issue.
