### ISSUE TITLE
Count should have many more examples

### ISSUE THREAD

**Issue by stowen-msft** [MicrosoftDocs/dataexplorer-docs#432]
The Count() command is very powerful and has a lot of usages. The example given is very basic and should be expanded with other scenarios, like the role of count in aggregate statements.  Since KQL is so new, these docs are still a top result and this page doesn't provide much meat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218abeeb-18ff-cf1d-21c4-3605a8fe0e4a
* Version Independent ID: 4704d7a4-a73a-b480-1139-d6a8d09d009f
* Content: [count operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/countoperator)
* Content Source: [data-explorer/kusto/query/countoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/countoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your feedback, @stowen-msft . This has been assigned to the content owner, @orspod , and will be updated as appropriate.

Documentation rich with examples, are often the most helpful documentation.

**Comment by orspod** [comment]
@stowen-msft thanks for your feedback.

The count operator usage is very simple and therefore doesn't require more text.
I think you are referring to the count() - aggregation function. There is additional documentation on this page https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/count-aggfunction with links to other option:
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/countif-aggfunction

You can also search for count() for additional examples within our docset

**Comment by stowen-msft** [comment]
You are right :)

Maybe adding a link to the other aggregation function would help similarly confused people, like me :)

Thanks.

**Comment by orspod** [comment]
Thanks @stowen-msft. We will add that link. Closing the issue.
