### ISSUE TITLE
all data ingest links(https://kustosamplefiles.blob.core.windows.net/jsonsamplefiles/simple.json) are expired.

### ISSUE THREAD

**Issue by akashlkendre** [MicrosoftDocs/dataexplorer-docs#435]
can you please also mention if we can fetch data drom an API which gives JSON as output...?

---
#### Document Details

https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d5f8ab-85c7-19bf-d91a-e76e81c76d7b
* Version Independent ID: 161a10d8-fc7f-97e8-b13e-0ddc7dd4f3c6
* Content: [Ingest JSON formatted data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language)
* Content Source: [data-explorer/ingest-json-formats.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-json-formats.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by HarithaMaddi-MSFT** [comment]
@akashlkendre - Thanks for posting the query. I am looking into it and will update you shortly.

**Comment by HarithaMaddi-MSFT** [comment]
@orspod - Can you please take a look and share your thoughts.

**Comment by orspod** [comment]
@akashlkendre - thanks so much for the feedback. We have a WI to fix these links. I will expedite the process. Closing this issue now.

**Comment by orspod** [comment]
@akashlkendre - there are new links to the files. Please lmk if you have any issues...
