### ISSUE TITLE
Complex regex examples are missing. Just typing them in quotes doesn't work

### ISSUE THREAD

**Issue by sergiopaim** [MicrosoftDocs/dataexplorer-docs#436]
There should be more elaborated regex examples like this one:
`indexof_regex(cloud_RoleInstance, @'-[\da-z]*-[\da-z]*\.\(none\)')`

I have lost 1h hour trying to figure out that single quotes should be used along with @... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed06035-d345-6258-e782-247623d25b3f
* Version Independent ID: 5411245b-cb3f-310f-b21a-bffb55bec2fe
* Content: [indexof_regex() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/indexofregexfunction)
* Content Source: [data-explorer/kusto/query/indexofregexfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/indexofregexfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@sergiopaim Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by orspod** [comment]
Thanks @sergiopaim for your feedback.
@sloutsky - can you assist?

**Comment by orspod** [comment]
@sergiopaim - thanks for your feedback. PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1212 was created to address your issue. I am now closing this issue. Thanks
