### ISSUE TITLE
Examples on this page are broken

### ISSUE THREAD

**Issue by zurdev** [MicrosoftDocs/dataexplorer-docs#438]
The query clause below appears in multiple examples and is incorrect:
`extend series_decompose_anomalies_y_ad_flag = series_multiply(10, series_decompose_anomalies_y_ad_flag) // multiply by 10 for visualization purposes`
1. series_multiply doesn't take scalar value as first argument
1. the second argument has a typo, it's currently pointing to undefined variable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfc3cde5-a7b3-9fa0-5266-2be49ff9821c
* Version Independent ID: 4ea789b4-2943-ee03-776a-c9a63366c49f
* Content: [series_decompose_anomalies() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/series-decompose-anomaliesfunction)
* Content Source: [data-explorer/kusto/query/series-decompose-anomaliesfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/series-decompose-anomaliesfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@zurdev thanks for your feedback.
@adieldar - will you take a look?

**Comment by adieldar** [comment]
Hi @zurdev,

All samples are working as is

1. series_multiply can take scalar value as one of its argument and it's extended into a constant vector of the same size as that of the other argument

2. There is no typo. When you call extend with some function, but without specifying explicitly the name of the variable (or tuple of variables) then the variable names are generated  based on the output name, the function name and the input name. This is mention in [extend](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extendoperator) doc

Still, I agree that both items should be better documented - we will fix that. Thanks for reporting

**Comment by zurdev** [comment]
@orspod - thanks for the quick response
@adieldar - thanks for the elaborated answer
Nothing is broken with the current examples, I'm closing this issue.
Since Kusto.Explorer's intellisense is showing red squiggly and Kusto's documentation doesn't mention series_multiple can take scalar input, it might be a good idea to add a comment.
