### ISSUE TITLE
Import a ntebook.

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/dataexplorer-docs#44]
In addition (I'd say in place of) the provided notebook. I would link to here. This is what you will want to use on DataBricks with Spark, not the regular python client. I knew something was fishy when it was a pip install here and not a maven install. Get the Spark Connector from Maven, "com.microsoft.azure.kusto:spark-kusto-connector:1.1.2"
https://github.com/Azure/azure-kusto-spark/blob/master/samples/src/main/python/pyKusto.py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66353133-1b29-fa99-c9bd-e74c4a2f14dc
* Version Independent ID: 5cf9bdf3-207a-ab00-4cb9-4b5e4668f894
* Content: [Connect to Azure Data Explorer from Azure Databricks using Python](https://docs.microsoft.com/en-us/azure/data-explorer/connect-from-databricks#feedback)
* Content Source: [data-explorer/connect-from-databricks.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/connect-from-databricks.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@dciborow - thanks for your feedback. 
@ManojRaheja - please assist with the question and LMK if doc changes are necessary?

**Comment by ManojRaheja** [comment]
Hi Dan,

Thanks for your feedback. We do have some customers wanted to use Kusto Python SDK on Azure Databricks, will update to the doc to reflect both the options.

Thanks,
Manoj

**Comment by orspod** [comment]
@dciborow - thanks for your feedback. I am moving to close this issue. WI has been created to update the doc as per your suggestion: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1721614
