### ISSUE TITLE
activity_counts_metrics not aggregating distinct count + dcount also incorrect. 

### ISSUE THREAD

**Issue by Utsav37** [MicrosoftDocs/dataexplorer-docs#440]
As mentioned activity_counts_metrics is not correctly calculating dcount and its not correctly counting Aggregating distinct Count. 

PFA image for proof of aggregating not working. 2nd Image is proof that dcount itself is incorrect!!
![image](https://user-images.githubusercontent.com/25278093/98880180-06768380-243c-11eb-8296-b88e711bf560.png)

![image](https://user-images.githubusercontent.com/25278093/98881634-53a82480-243f-11eb-99f0-eb8ba2622344.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb85f6ca-ac14-2a52-e5b9-0034e116cd5a
* Version Independent ID: 30e5fbc3-5257-d073-0a5a-9131c04a4a48
* Content: [activity_counts_metrics plugin - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/activity-counts-metrics-plugin)
* Content Source: [data-explorer/kusto/query/activity-counts-metrics-plugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/activity-counts-metrics-plugin.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Utsav37** [comment]
Should I confirm all plugins that we use in Kusto before using it? I am worried now as its the first time I started using plugin and it had bugs.

**Comment by HarithaMaddi-MSFT** [comment]
@Utsav37 - Thanks for posting the query. I am looking into it and will get back to you soon.

**Comment by HarithaMaddi-MSFT** [comment]
@orspod - Can you please take a look and share your thoughts.

**Comment by yifatsor** [comment]
@Utsav37, it's hard to tell from the images what exactly is not working correctly. Are you referring to the record of Nov 1st in the first image (in which the aggregated_dcount is lower than previous row)? Or is it something else? 
It would also greatly help if you can provide a request id for these queries.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Utsav37  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
