### ISSUE TITLE
How does this sample related with the description

### ISSUE THREAD

**Issue by bingbing8** [MicrosoftDocs/dataexplorer-docs#441]
[Enter feedback here]
The following command ingests data into a table (Purchases) with two columns, SKU (of type string) and Quantity (of type long).

Kusto

Copy
.ingest inline into table Purchases <|
Shoes,1000
Wide Shoes,50
"Coats, black",20
"Coats with ""quotes""",5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff753b0-334b-fda1-453a-71cda7e44737
* Version Independent ID: 9a8628fe-b8be-80d5-5029-766f335a5648
* Content: [The ingest inline command (push) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-inline)
* Content Source: [data-explorer/kusto/management/data-ingestion/ingest-inline.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-ingestion/ingest-inline.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by HarithaMaddi-MSFT** [comment]
@bingbing8 - Thanks for posting the query. I can see that the sample is associated to .ingest inline command as covered in the article. Can you please share more details on unrelated content here as that will help us in assisting you better.

**Comment by bingbing8** [comment]
@HarithaMaddi-MSFT , I did not link "Shoes" "Wide Shoes" with column name SKU when I read the description and sample code.

**Comment by HarithaMaddi-MSFT** [comment]
@bingbing8 - Thanks for confirming. I will proceed with closing this issue now, please feel free to comment for further queries.
