### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by vivere-dally** [MicrosoftDocs/dataexplorer-docs#442]
Hello,

By following this documentation you can create an application that can only view/read resources. I believe you should also point to some documentation with which you can make an admin application.

In cases of creation of let's say IotHubDataConnection from C#, you encounter an error due to roles and permissions.

Besides everything mentioned here, the application also needs to be added for a certain database as Admin, and besides that, the application needs to have the Contributor role inside the subscription as per this documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

I believe mentioning the link above would spare other users of scratching their heads for a couple of hours.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 266e7eb8-4c41-df4a-1b6e-38730477fdca
* Version Independent ID: 76208613-c17b-e8a1-bdf0-a3dded2746ed
* Content: [Create an Azure AD application in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/provision-azure-ad-app)
* Content Source: [data-explorer/provision-azure-ad-app.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/provision-azure-ad-app.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your feedback @vivere-dally . This has been assigned to the content owner, @orspod , and will be updated as appropriate.

**Comment by orspod** [comment]
@vladikbr - please advise.

**Comment by orspod** [comment]
@vivere-dally - thanks for your feedback. Created a WI to add link to the documentation. Closing this issue now.
