### ISSUE TITLE
Which version of Excel is needed for the Kusto connector

### ISSUE THREAD

**Issue by hugovoerman** [MicrosoftDocs/dataexplorer-docs#447]
In this page there is no reference to which version of Excel is needed to have the Azure Data Explorer connector.

On my company laptop, I do not have this connector. Is there something to install?

Please elaborate on how to enable this in Excel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab47fc29-e55f-b6f8-4904-ff531c49feac
* Version Independent ID: c46ee3de-cfdf-4e54-a375-088e389866d0
* Content: [Visualize data using the Azure Data Explorer connector for Microsoft Excel](https://docs.microsoft.com/en-us/azure/data-explorer/excel-connector)
* Content Source: [data-explorer/excel-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/excel-connector.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@hugovoerman Could you please share the Excel version installed on your company laptop and also please do share the screenshot where it doesn't show Azure Data Explorer connector?

You can find the excel version in the Account section => About Excel.

**Comment by hugovoerman** [comment]
Hi,

Please see the requested screenshots below.

Hope this helps to enable me to use the Azure Data Explorer connector.

Best regards,

Hugo Voerman
Priva

[cid:image001.png@01D6BCC8.21F47BC0]


[cid:image002.png@01D6BCC8.21F47BC0]

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@hugovoerman Unable to find the requested screenshot, Could you please upload it again?

**Comment by hugovoerman** [comment]
Here they are again.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@hugovoerman Could you please reshare the screenshot?

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@HugoDurana  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.

**Comment by hugovoerman** [comment]
@CHEEKATLAPRADEEP-MSFT 

Hi, I did mail the requested screenshots twice. I think the mailhandler you use is not capable of correctly handing the mail (send by outlook btw).

Hopefully you find them now as a zip file attached to this 

And thus I think the line:

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe. 

should be altered. This can be used but apparently when sending embedded screenshots (which outlook perfectly supports), things get a bit messy on the github side.

[RE_ _MicrosoftDocs_dataexplorer-docs_ Which version of Excel is needed for the Kusto connector (#447).zip](https://github.com/MicrosoftDocs/dataexplorer-docs/files/5582036/RE_._MicrosoftDocs_dataexplorer-docs_.Which.version.of.Excel.is.needed.for.the.Kusto.connector.447.zip)

Hopefully we can finally solve this issue.
