### ISSUE TITLE
This doc should include databricks in title

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/dataexplorer-docs#45]
The "Connect from Databricks using Python" document is a trap. This is what anyone going to databricks should be using... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa46bfb-17f8-a18d-50a5-eaad4c85ae19
* Version Independent ID: ac1fc513-55d6-203a-ce2c-bae250d126d4
* Content: [Use the Azure Data Explorer connector for Apache Spark to move data between Azure Data Explorer and Spark clusters.](https://docs.microsoft.com/en-us/azure/data-explorer/spark-connector)
* Content Source: [data-explorer/spark-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/spark-connector.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@dciborow - thanks for your feedback. I believe it is connected to your other issue: https://github.com/MicrosoftDocs/dataexplorer-docs/issues/44 
@ManojRaheja - please assist with the request.

**Comment by ManojRaheja** [comment]
Thanks Dan for your feedback. We will update the doc based on your feedback.

**Comment by orspod** [comment]
@dciborow - thanks for your feedback. I believe it is connected to your other issue: https://github.com/MicrosoftDocs/dataexplorer-docs/issues/44. We created a WI to fix the doc. I am therefore closing this issue.
