### ISSUE TITLE
Missing documentation on how to select the engine version of Azure Data Explorer when deploying via ARM template

### ISSUE THREAD

**Issue by tedvanderveen** [MicrosoftDocs/dataexplorer-docs#453]
When creating a new Azure Data Explorer cluster using the Portal UI, there is a checkbox available that allows to select version 3 of the ADX engine, see [Screenshot](https://docs.microsoft.com/en-us/azure/data-explorer/media/engine-v3/create-new-cluster-v3.png).
How can we create a new Azure Data Explorer cluster with that same setting (engine version 3) enabled via ARM template deployment (or other automation deployment mechanisms like Powershell or AZ CLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9c4d32-fdd8-6ce4-4237-fb0f34b56c7f
* Version Independent ID: d2045be8-bc75-aeef-249d-2b95d73e4841
* Content: [Create an Azure Data Explorer cluster and database by using an Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-resource-manager)
* Content Source: [data-explorer/create-cluster-database-resource-manager.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/create-cluster-database-resource-manager.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SumanthMarigowda-MSFT** [comment]
@tedvanderveen Thanks for your question. We are checking on this and will respond to you soon.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@tedvanderveen  Thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

@orspod Could you please review and update the document with the template that allows selecting version 3 of the ADX engine?

**Comment by orspod** [comment]
@tedvanderveen - thanks for your feedback. I have created a [WI](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1796697/?triage=true) to update this doc. 
@AssafTaubenfeldMSFT - FYI
I am now closing this issue. I will follow up when doc is updated

**Comment by astauben** [comment]
Hi, @tedvanderveen I'm updating our files to include the engine-type property. In the meanwhile, to create cluster with engine-type using CLI please see these CLI docs: https://docs.microsoft.com/en-us/cli/azure/ext/kusto/kusto/cluster?view=azure-cli-latest#ext_kusto_az_kusto_cluster_create
