### ISSUE TITLE
Looking for first() and last() aggregation functions like in Time Series Insights

### ISSUE THREAD

**Issue by hugovoerman** [MicrosoftDocs/dataexplorer-docs#459]
In Time Series Insights the aggregation functions first and last are also available. Where are they in ADX?

See https://docs.microsoft.com/en-us/rest/api/time-series-insights/gen1-query-syntax#aggregate-expressions for  a TSI description.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e79e226-f1e1-b6ec-f4aa-1a66818190b4
* Version Independent ID: 49dba61b-3968-ac88-e2b2-49fd27942f61
* Content: [make-series operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/make-seriesoperator)
* Content Source: [data-explorer/kusto/query/make-seriesoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/make-seriesoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@hugovoerman thanks for the feedback
@adieldar - please review and respond

**Comment by adieldar** [comment]
@royoMS to answer

**Comment by royoMS** [comment]
@hugovoerman you could use [arg_max](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-max-aggfunction) and [arg_min](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-min-aggfunction) aggregation functions inside a [summarize operator](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/summarizeoperator) to find the first/last values of a given property.

**Comment by hugovoerman** [comment]
Thank you very much.

This (a little bit generalized) seems to do the job.

Can you confirm that this is the right way to do this?

T
| where DateTime > ago(1d)
| where Identifier == <blablabla>
| where reading matches regex ‘<nice regex to get the readings we want>'
| summarize last_value=arg_max(DateTime, v1=tostring(Value)), first_value=arg_min(DateTime, v2=tostring(Value)) by bin(DateTime, 1800s), reading

Thank for the pointer!

**Comment by royoMS** [comment]
@hugovoerman yes that seems right

**Comment by orspod** [comment]
@royoMS - thanks for your assistance with this question.
@hugovoerman - Now that your question has been addressed, I will close this issue.
