### ISSUE TITLE
Storage Account Requirements for Ingestion

### ISSUE THREAD

**Issue by Craigmeister68** [MicrosoftDocs/dataexplorer-docs#462]
Greetings,
It would be helpful to have a statement on this page that states that storage account type General Purpose v1 is not supported for use with blob ingestion. The error message that occurs when you try to target this kind of account in a data connection from the Azure  Portal points to this doc - https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview. But putting 2 and 2 together for the customer at the start will save time and frustration. 

And come to think of it, checking for a Gen Purpose v1 storage account from the UI and not allowing it  would help also. 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf4599f-0e80-47fc-c919-be4434dcdffd
* Version Independent ID: 8ef468be-2c25-d37c-be11-23f0ad8d5c3c
* Content: [Ingest Azure Blobs into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-grid)
* Content Source: [data-explorer/ingest-data-event-grid.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-grid.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MonikaReddy-MSFT** [comment]
@Craigmeister68 - 
- Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by orspod** [comment]
@Craigmeister68 - thanks for your feedback.
@kerend and @LeaShallev - can you please review the feedback?

**Comment by orspod** [comment]
@Craigmeister68 - thanks again for the feedback.
The following statement was added as prerequisite for article: "*Event Grid notification subscription can be set on Azure Storage accounts for `BlobStorage`, `StorageV2`, or [Data Lake Storage Gen2](/azure/storage/blobs/data-lake-storage-introduction)."

@orhasban will be addressing your suggestion: "checking for a Gen Purpose v1 storage account from the UI and not allowing it would help also."

I will now close this issue. Feel free to reach out by @mention me with any additional questions.
