### ISSUE TITLE
delimiting let statements

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#463]
This statement is incomplete
_Multiple let statements can be used with the semicolon, ;, delimiter between them_

I am finding it that the semicolon needs to be even in this situation
```
let p = perf_tests_CL | project started_at=TimeGenerated;
p
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 741d0e14-4a3f-af28-1d6e-e6a6dd3dd414
* Version Independent ID: 731bbd4d-10c6-5cc4-741d-7cba31cb0586
* Content: [Let statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/letstatement)
* Content Source: [data-explorer/kusto/query/letstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/letstatement.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@ciufudean  Thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by orspod** [comment]
@ciufudean - can you please clarify why your example is contradicting that let statements can be delimited ‘;’? Please lmk how we can make the docs more clear.
@sloutsky - FYI

**Comment by ciufudean** [comment]
The semicolon _must_ be put even with a single `let` statement. Before a tabular data query.

I cannot find the semicolon where the `let` syntax is defined.

**Comment by orspod** [comment]
@sloutsky - can you please clarify - Must a semicolon be used with a single let statement, before a tabular expression? as described by @ciufudean ?

**Comment by orspod** [comment]
@ciufudean - Semicolon separates all statements (let statements, set statements, tabular expressions, etc). I created a [WI](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1797180/?triage=true) to add clarification in the docs. I am now closing this issue.
