### ISSUE TITLE
code does not run

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#464]
This code will not run as `Text `is incorrectly cased.

```
.set MyTable <|
let text="Hello, World!";
print str=Text
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7273ba66-9fda-51e5-1f6b-46cb610f6c33
* Version Independent ID: 12a79f6f-223f-3940-29dd-69d9dbc9f370
* Content: [Management (control commands) overview - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/)
* Content Source: [data-explorer/kusto/management/index.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/index.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@ciufudean  Thanks for your contribution, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1267 ](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1267) 
The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.
