### ISSUE TITLE
Where to report bugs on .NET Data SDK?

### ISSUE THREAD

**Issue by dg-eparizzi** [MicrosoftDocs/dataexplorer-docs#465]
I've been searching around and I cannot seem to find any place to report bugs on the [Microsoft.Azure.Kusto.Data library](https://www.nuget.org/packages/Microsoft.Azure.Kusto.Data/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82ebd2-f7f6-5068-54f2-69c7532b6b38
* Version Independent ID: 4727dbed-4e17-879b-d494-6ee62d78633a
* Content: [Ingest data with Azure Data Explorer .NET SDK](https://docs.microsoft.com/en-us/azure/data-explorer/net-sdk-ingest-data)
* Content Source: [data-explorer/net-sdk-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/net-sdk-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MonikaReddy-MSFT** [comment]
@dg-eparizzi - 
- Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by vladikbr** [comment]
@dg-eparizzi, you can reach us at nugetkusto@microsoft.com

**Comment by orspod** [comment]
@vladikbr - thanks for your response.
@dg-eparizzi thanks for your feedback. You can also select "contact owners" in right-hand menu to report a bug.
I am now closing this issue
