### ISSUE TITLE
Incorrect definition for database cursor function `cursor_before_or_at`

### ISSUE THREAD

**Issue by chintanr97** [MicrosoftDocs/dataexplorer-docs#468]
The `cursor_before_or_at(rhs:string)` terminology definition on the documentation page [here](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/databasecursor#cursor-functions) should be modified to have following explanation:

[cursor_before_or_at(rhs:string)](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/cursorbeforeoratfunction?pivots=azuredataexplorer): This special function can be used on the table records that have the IngestionTime policy enabled. It returns a scalar value of type `bool` indicating whether the record's `ingestion_time()` database cursor value comes **before or at** the `rhs` database cursor value.

**Instead of current definition as:**
[cursor_before_or_at(rhs:string)](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/cursorbeforeoratfunction?pivots=azuredataexplorer): This special function can be used on the table records that have the IngestionTime policy enabled. It returns a scalar value of type `bool` indicating whether the record's `ingestion_time()` database cursor value comes **after** the rhs database cursor value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a570ec9e-deaa-d4d1-f193-75b67280a286
* Version Independent ID: 276ed116-24be-60f9-573f-28cd8a85fe2b
* Content: [Database cursors - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/databasecursor)
* Content Source: [data-explorer/kusto/management/databasecursor.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/databasecursor.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@chintanr97  Thanks for your contribution, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1269](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1269).

The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.
