### ISSUE TITLE
Best Practices for Schema Design???

### ISSUE THREAD

**Issue by DavidBerg-MSFT** [MicrosoftDocs/dataexplorer-docs#470]
The page "Best Practices for Schema Design" feels mislabeled.  I read it expecting to get tips on **designing** Data Explorer Schemas.  Instead I got a bunch of tips on manipulating and querying schemas, **not** designing them.

(If you have any tips on **designing** Data Explorer Schemas, I'd love to read them.  In the meantime, please consider retitling the page.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e54dce-472a-ac8a-e8e0-d31c25602f71
* Version Independent ID: 91cb215e-e203-5ff1-dae7-08eda1250375
* Content: [Best practices for schema design - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/management-best-practices)
* Content Source: [data-explorer/kusto/management/management-best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/management-best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by krish-gh** [comment]
@DavidBerg-MSFT Thanks for the suggestion. Assigning to the author to have a look.

**Comment by orspod** [comment]
@DavidBerg-MSFT thanks for your feedback. We will change the page title as requested.
I created a [WI](https://mseng.visualstudio.com/TechnicalContent/_queries/query/977d69dc-a57d-4219-8f3c-fba78447ccf4/) re: your request for "tips on designing Data Explorer Schemas"
I will now close this issue.

**Comment by DavidBerg-MSFT** [comment]
Thanks.  Glad you found the suggestion helpful.
