### ISSUE TITLE
Is it correct to say that, to delete a database, the user needs Contributor or Owner role at the **subscription** level?

### ISSUE THREAD

**Issue by riserrad** [MicrosoftDocs/dataexplorer-docs#472]
When reading through this document, I see the following statement:

_To delete or rename a database, you must be a member of the Contributor or Owner role for the **Azure subscription**._

Shouldn't it be for the **Azure Data Explorer cluster** instead?

I see this is also mentioned for database creation. And I think it should be the same case.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb8afe2-3457-df7f-3ee5-18084f31163e
* Version Independent ID: f01c68bd-c6c3-5759-e497-97b4ff52b2c3
* Content: [Failure to create or delete DB or table in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/troubleshoot-database-table)
* Content Source: [data-explorer/troubleshoot-database-table.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/troubleshoot-database-table.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@riserrad  Thanks for the feedback! I have assigned the issue to the content author to review further and update the document as appropriate.

**Comment by orspod** [comment]
@riserrad thanks for your feedback.
The docs are correct for database creation and deletion. There aren't cluster-level permissions. 
You can ALSO delete a database if you have database admin permissions. I will update the doc.

I will now close this issue. If you have additional questions, feel free to @mention me in this issue or open a new issue.
