### ISSUE TITLE
Please provide the documentation for running management queries from Spark Databricks Notebook. We need run the adx mangement queries like renaming and droping the adx tables from spark code.

### ISSUE THREAD

**Issue by lohithrvce** [MicrosoftDocs/dataexplorer-docs#473]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66353133-1b29-fa99-c9bd-e74c4a2f14dc
* Version Independent ID: 5cf9bdf3-207a-ab00-4cb9-4b5e4668f894
* Content: [Connect to Azure Data Explorer from Azure Databricks](https://docs.microsoft.com/en-us/azure/data-explorer/connect-from-databricks)
* Content Source: [data-explorer/connect-from-databricks.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/connect-from-databricks.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BharathNimmala-MSFT** [comment]
@lohithrvce Thank you for reaching out, our team will review your request and get back to you at the earliest

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by orspod** [comment]
@lohithrvce thanks for your feedback.
@ohadbitt or @ManojRaheja can you please assist.

**Comment by ohadbitt** [comment]
The spark connector is for querying and ingesting data. In order to use management queries (called control commands) one need to use the java or python sdk depend on the environment he is using

**Comment by orspod** [comment]
@ohadbitt thanks for the clarification. @lohithrvce - I hope this answers your question. I am now closing this issue. If you have follow-up questions, feel free to comment here.
