### ISSUE TITLE
Maximum number of records that can be ingested this way?

### ISSUE THREAD

**Issue by dwhathaway** [MicrosoftDocs/dataexplorer-docs#478]
I see there's a mention of `For example, the command can retrieve 1000 CSV-formatted blobs from Azure Blob Storage`.  Is 1000 the max number of records that a statement can contain?  It would be good to note that on the page explicitly if that's the case, or whatever the actual limit is along with any recommendations on best practices on how many files to include.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8367589f-76cb-1a24-37d0-e4355594fb18
* Version Independent ID: 3455ea4f-4ce4-ee0d-007c-d4ca3b7ec89e
* Content: [Kusto .ingest into command (pull data from storage) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-from-storage)
* Content Source: [data-explorer/kusto/management/data-ingestion/ingest-from-storage.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-ingestion/ingest-from-storage.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@dwhathaway  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@dwhathaway thanks for the feedback. The text you quoted is just an example and not a limit.
We created a [WI](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1799178/?triage=true) to clarify this statement in the doc.
I will now close this issue. If you need more information on product limitations, feel free to
create a thread on the forums - [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) or [stackoverflow](https://stackoverflow.com/).
I am now closing this issue.
