### ISSUE TITLE
render ignores the "with" properties in Azure Monitor

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#486]
I am running the same query in Log Analytics and Data Explorer.
```
range x from -2 to 2 step 0.1
| extend sin = sin(x), cos = cos(x)
| extend x_sign = iif(x > 0, "x_pos", "x_neg")
| extend sum_sign = iif(sin + cos > 0, "sum_pos", "sum_neg")
| render columnchart with (ycolumns = sin, cos, series = x_sign, sum_sign)
```
The Data Explorer chart displays six series, while the one in Log Analytics only two.
Moreover, the chart in Log Analytics displays the same chart even if I remove all `with` properties

Another problem is with the samples provided for Azure Monitor, they use `render linechart` which is not supported in this product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MayankBargali-MSFT** [comment]
@ciufudean Thank you for your feedback! We will review and update as appropriate.

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your feedback @ciufudean . This has been assigned to the content owner, @orspod , and will be updated as appropriate.

**Comment by orspod** [comment]
@bwren can you assist the customer?

**Comment by bwren** [comment]
@ciufudean Thanks for noticing this. Obviously, we copied over the content for Azure Monitor and failed to update the sample. The render operator tells the UI how to present the results, and ADX and Log Analytics work different with charts. Log Analytics lets you select which series to display, while the ADX web UI has to display the series together. I'll get the example changed. We really should have an example that uses a table in a Log Analytics workspace anyway. I'll also update the series explanation. 

#please-close

**Comment by orspod** [comment]
Thanks @bwren 
@ciufudean - [PR](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1307) was created with fix. See changes in the doc.
