### ISSUE TITLE
What is the syntax for the bin size for time

### ISSUE THREAD

**Issue by JasonWHowell** [MicrosoftDocs/dataexplorer-docs#489]
Hi @orspod 

I see examples like 14d in the bin function. 

Could we add a link for whatever syntax the time span is? 

I am searching for several minutes to find what the syntax is called but haven't figured it out yet. I need to figure out what to put in there for 1 month bins, and `1m` seems to be minutes, and `1M` doesn't do months. 

Thanks! Jason
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86e8e8e7-acca-7eaf-1c13-90b49bef3963
* Version Independent ID: 2b95cdd0-dd5b-d6ac-bdcf-688c0d476705
* Content: [bin() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/binfunction)
* Content Source: [data-explorer/kusto/query/binfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/binfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by JasonWHowell** [comment]
Found out a timespan is a data type for the bin roundsto parameters, but maybe it doesn't support months or years. 
I'm not really sure yet. 
https://docs.microsoft.com/azure/data-explorer/kusto/query/scalar-data-types/timespan

**Comment by BharathNimmala-MSFT** [comment]
@JasonWHowell Thanks a lot for your query, assigned this issue to our document author @orspod to further review you and circle back accordingly.

**Comment by orspod** [comment]
@JasonWHowell - thanks for your feedback. 

The argument type of the 2nd param of the bin() function is [timespan](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan). 
I created a [WI](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1799204/?triage=true) to update the doc.
Regarding the fact that timespan doesn't support months/years, feel free to request it on [user voice](https://feedback.azure.com/forums/915733-azure-data-explorer).

I hope your query has been addressed. I will now close this issue. Feel free to respond or create a new issue with additional questions.

**Comment by JasonWHowell** [comment]
The alternative syntax to group by month or year rather than by bin() is to use this kind of syntax:

| summarize ... by Month = startofmonth(DateTimeColumn)
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/startofmonthfunction

| summarize ... by Year = startofyear(DateTimeColumn)
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/startofyearfunction
