### ISSUE TITLE
How to check if a value exists in an array, where the array is a dynamic column?

### ISSUE THREAD

**Issue by ymost** [MicrosoftDocs/dataexplorer-docs#494]
Minimal example:
```C
datatable (foo:dynamic)
    [dynamic(["A", "B", "C"]),
     dynamic(["A B", "C", "D"]),
     dynamic(["AB", "C", "D"])]
| where  ????  // Keep only lines where 'foo' contains an element which equals "A" (i.e. only the first line)
```

Here are things I tried which don't work exactly as required:
```C
| where "A" in foo      // recognition error
| where "A" in (foo)      // failed to cast argument 2 to scalar constant
| where foo has_cs "A"     // keeps the second line as well
| where foo contains_cs "A"     // keeps the second and third lines as well
```

**Comment by NavtejSaini-MSFT** [comment]
@ymost We are checking this and we will get back to you.

**Comment by sloutsky** [comment]
Use: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/sethaselementfunction

**Comment by YaelSchuster** [comment]
Thanks @sloutsky for your response. @ymost I am closing this issue at this time. Please feel free to reach out with any further questions.

#please-close

**Comment by ymost** [comment]
@sloutsky Thanks!
I want to point out a mistake in [this](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/dynamic#operators-and-functions-over-dynamic-types) documentation page:
1. It says that "in" can be used for this purpose, but that doesn't work for dynamic columns
2. The function "set_has_element" doesn't appear under "Operators and functions over dynamic types"
