### ISSUE TITLE
Wrong feature is suggested in "Effective Slicers" section

### ISSUE THREAD

**Issue by HymieHo** [MicrosoftDocs/dataexplorer-docs#495]
"Effective slicers – Use **sync slicers** to prevent reports from loading data before you're ready."

This should say "Use **Query Reduction** to prevent reports from loading data before you're ready." and "Query Reduction" should be linked to https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec5fb9d-8962-7e64-2768-b04b498f2db4
* Version Independent ID: f82bc4a7-476c-20e6-71cb-5406a3577a74
* Content: [Best practices for using Power BI to query and visualize Azure Data Explorer data](https://docs.microsoft.com/en-us/azure/data-explorer/power-bi-best-practices)
* Content Source: [data-explorer/power-bi-best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/power-bi-best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by NavtejSaini-MSFT** [comment]
@HymieHo We are checking this and will get back to you.

**Comment by NavtejSaini-MSFT** [comment]
@orspod Please check and verify and let us know if we can make this change.

**Comment by orspod** [comment]
@Gabilehner and @saguiitay - can you please verify the feedback from @HymieHo

**Comment by orspod** [comment]
@HymieHo - thanks for your feedback. Sync Slicers is a different feature than the Query Reduction feature. We will link to that DQ best practice page as suggested. I am now closing this issue.
