### ISSUE TITLE
ADE Dashboard documentation needs more optimization tips

### ISSUE THREAD

**Issue by daviw-git** [MicrosoftDocs/dataexplorer-docs#504]
I am concerned about cluster load caused by the Azure Data Explorer dashboards. While there were a couple of tips on reducing load in this document, I don't have a good sense of how often these queries are run, if the result of the queries are cached somewhere or are run again each time they are viewed by each user, etc...

I am looking for more information on how refresh works so that I can be sure to optimize my design to reduce cluster load.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1640-3699-8fdf-07a2-c9b922499c90
* Version Independent ID: 55027537-6af4-541d-da8d-e2cdc2b5fa92
* Content: [Visualize data with the Azure Data Explorer dashboard](https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards)
* Content Source: [data-explorer/azure-data-explorer-dashboards.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/azure-data-explorer-dashboards.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by femsulu** [comment]
@daviw-git Thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by Gabilehner** [comment]
Hi @daviw-git,
In general, all of the performance optimization rules are applicable to ADX dashboards.
Specifically, we do plan to add performance optimizations during 2021for ADX dashboards.
For now, the main recommendation is not to overload the cluster with dashboard queries using the auto refresh capability of dashboards. That's the purpose of allowing the dashboard owner to control the minimal time interval for refreshing the dashboard.
https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards#enable-auto-refresh

**Comment by YaelSchuster** [comment]
Thanks @Gabilehner for your detailed response.

@daviw-git We will now proceed to close this issue. Feel free to reach out with any additional questions.

**Comment by YaelSchuster** [comment]
#please-close
