### ISSUE TITLE
Load balancer of outbound settings(Create Private Link service)

### ISSUE THREAD

**Issue by jiyongseong** [MicrosoftDocs/dataexplorer-docs#508]
[Enter feedback here]
Load balancer of outbound settings(Create Private Link service) should be an **internal load balancer**, not external load balancer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af34f52-e08b-55b0-bfdd-6081b808e585
* Version Independent ID: 4e61b826-27ab-67be-e921-1656ec7f2777
* Content: [Using Private Endpoint in your Azure Data Explorer cluster in your virtual network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-create-private-endpoint)
* Content Source: [data-explorer/vnet-create-private-endpoint.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/vnet-create-private-endpoint.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @jiyongseong , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by eladbi** [comment]
Hi @jiyongseong 

Thanks for the feedback, this could be the external and the internal load balancer, I will update the documentation.

**Comment by YaelSchuster** [comment]
Thanks @eladbi for your response. I have created a WI to followup on this issue in the docs. https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1802476 

@jiyongseong thanks for your input. Please feel free to reach out with any further questions. I am closing this issue at this time.

#please-close

**Comment by jiyongseong** [comment]
@eladbi  
I think the suggested value of "Load balancer frontend IP address"  needs to be changed also.
| Load balancer frontend IP address | Your engine or data management public/private IP. | Select the Load Balancer public/private IP address. |
https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1351/files

**Comment by eladbi** [comment]
@jiyongseong Thanks for the feedback, I will remove the need for public IP, just need to select the load balancer IP address.

**Comment by jiyongseong** [comment]
@eladbi  thank you for letting me know.
