### ISSUE TITLE
Performance Considerations

### ISSUE THREAD

**Issue by nigarfin** [MicrosoftDocs/dataexplorer-docs#517]
It would be helpful to include performance considerations for unions similar to what we see for joins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdae741d-890b-0d72-8873-1b5be2a72d74
* Version Independent ID: 4845e524-c60d-ebbd-94c7-05c075e5a177
* Content: [union operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/unionoperator)
* Content Source: [data-explorer/kusto/query/unionoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/unionoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by YaelSchuster** [comment]
Hi @nigarfin, thank you for your feedback. I have opened a work item to address this issue. I am closing this issue at this time. If you have any further questions, please feel free to reach out.

#please-close
