### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by jacobwbutler** [MicrosoftDocs/dataexplorer-docs#52]
"The above will restrict the query access to the following entites:" -&gt; "entities:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9edad54-ecb5-dc20-970d-214cce195a6f
* Version Independent ID: 9db1a075-410f-2933-6414-b92e5efd6385
* Content: [Cross-database and cross-cluster queries - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/cross-cluster-or-database-queries?pivots=azuredataexplorer#feedback)
* Content Source: [data-explorer/kusto/query/cross-cluster-or-database-queries.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/cross-cluster-or-database-queries.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@jacobwbutler - thanks for your feedback. Created a PR to fix the typo. Closing the issue now
