### ISSUE TITLE
Required permissions info is missing from this and other ingestion docs.

### ISSUE THREAD

**Issue by Craigmeister68** [MicrosoftDocs/dataexplorer-docs#536]
Greetings, 
It would seem there are required permissions on the ingestion sources for ADX to access the blob, event message, etc. Based on lack of mention in the documentation, it would seem ADX is using the permissions of the logged in user which is creating the objects. However, this is not explicit and there does not seem to be guidance for security settings necessary in the ingestion sources in general. Production environments do not want to have a connection be based on a user who might leave and the account be deactivated, which will break the connection. Also, ADX and the source may be managed by different people/teams such that the ADX admin doesn't have access to the Event Hub or blob. 

Is my assumption correct? Are the connections in the ingestion documentation relying on the logged in user credentials? 
Where do I find further information regarding permission requirements for ingestion in the documentation?

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48946887-6f4c-9fc9-a3ba-1609b1059cab
* Version Independent ID: 73781e6f-3343-5abf-e483-05c0dac13075
* Content: [Ingest from Event Hub - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub-overview)
* Content Source: [data-explorer/ingest-data-event-hub-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-hub-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@Craigmeister68 
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
@Craigmeister68 Thanks for reaching out.

The answer I've received from @orhasban is as follows:

We don’t use the caller permission, we have special permissions to fetch data from that data source (S2S). 
We just verify that the caller that set the data connection has listKeys permission on the EH / Storage – which practically means that they owns the data source.

Soon we’ll introduce more secure type of data connection that is based on Managed Identity. 
It gives the customer much more control on the permissions, and they can cut the permission whenever they want.

@Craigmeister68 does this answer your question?

**Comment by orspod** [comment]
@Craigmeister68 - I hope your question was addressed. I am now closing this issue.
If you have additional questions, feel free to reach out.
