### ISSUE TITLE
Please refresh the screenshots in this doc.

### ISSUE THREAD

**Issue by ManojRaheja** [MicrosoftDocs/dataexplorer-docs#537]
Please refresh the screenshots in this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469b31a6-10e1-1460-b20e-8f2c72561675
* Version Independent ID: 50da61e1-e28a-63f2-2450-0ec5350b5c20
* Content: [Manage cluster vertical scaling (scale up) to match demand in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/manage-cluster-vertical-scaling)
* Content Source: [data-explorer/manage-cluster-vertical-scaling.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/manage-cluster-vertical-scaling.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@ManojRaheja  
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
A [work item](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1807007) has been created for this task.

**Comment by YaelSchuster** [comment]
#please-close
