### ISSUE TITLE
One-click ingest from adls gen2 where data was stored from event hubs capture feature

### ISSUE THREAD

**Issue by darivuki** [MicrosoftDocs/dataexplorer-docs#54]
Hi,

I wanted to One-click ingest data from adls gen2. The data in the datalake was ingested using the event hubs capture feature. When I try to configure the One-click ingestion for the data from the datalake, I get an error saying: 

Error loading file content - selected file: my-eventhubs-namespace/my-eventhub error: File is empty. 

However, the files are there, but they are stored deep into a folder structure that the One-click ingestion is not able to locate i presume. Is this even supported? Is it possible to One-click ingest data from adls gen2 with the event hubs capture data model?

Thanks!   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fe3f579-2262-46b3-549a-12a01f6efaf6
* Version Independent ID: 3580c0ff-81ab-d190-0e41-a5c1f139c8bd
* Content: [Use one-click ingestion to ingest data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-one-click)
* Content Source: [data-explorer/ingest-data-one-click.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-one-click.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@darivuki thanks for your question.
@TzviaGT can you please assist?

**Comment by ArielYehezkely** [comment]
Hi @darivuki,

Thanks for bringing it to our attention, looks like enumerating the blobs in the container counts also directories as files with size 0 when using ADLS. We will open a task to solve this.
Meanwhile, do you see other files in the blob list?
Can you please set the file prefix to the path where the files are located?

Thanks, 
Ariel

**Comment by darivuki** [comment]
Hi @ArielYehezkely ,

thank you for opening a task for this. I will test this out in the next few days and come back with the results.

Best Regards,
Davor

**Comment by ArielYehezkely** [comment]
Hi @darivuki,

The fix was deployed. Please try again now and update so we could close this.

Thanks,
Ariel

**Comment by darivuki** [comment]
Hello @ArielYehezkely 

the One-click ingestion is now able to list the container blob files which I have in my adls gen2. However, I am not sure how to proceed further. Do I need to ingest file by file or will the One-click ingest all of the files from the container? Another problem that I am seeing is in the next step where I need to configure the Schema. The files are in AVRO format (exported from EventHubs into the adls gen2 using Capture feature). When I try to configure the schema, I do not have the option of choosing the AVRO format as the Data Format thus not being able to ingest that data into ADX. 

How can I achieve this?

Thanks!
Davor

**Comment by ArielYehezkely** [comment]
Hi @darivuki, 

1. When using "From container" ingestion type, all the blobs that meets the filters criteria in the container will be ingested up to 10,000 blobs. the list in the source tab shows which blobs will be ingested.
2. Unfortunately One-Click doesn't support AVRO format yet, it's in our backlog though. 

Thanks, 
Ariel

**Comment by darivuki** [comment]
Hello @ArielYehezkely ,

thanks for the info. I'm looking forward to this feature. At this point, my questions have been answered and this ticket can be closed.

Best,
Davor
