### ISSUE TITLE
from azure.kusto.ingest import- ImportError: cannot import name 'KustoIngestClient'

### ISSUE THREAD

**Issue by docast** [MicrosoftDocs/dataexplorer-docs#544]
I am ingesting formatted json into ADX using Python SDK:  I have installed the Kusto libraries using below commands:
pip3 install azure-kusto-data
pip3 install azure-kusto-ingest

I have also ensured that the above libraries are present by following Option 2 mentioned in https://github.com/Azure/azure-kusto-python#install

However, whenever I am referencing azure.kusto.ingest module to import "KustoIngestClient" package, running into error:
    from azure.kusto.ingest import (
ImportError: cannot import name 'KustoIngestClient'

I am successfully able to import other packages like (IngestionProperties, FileDescriptor, BlobDescriptor,DataFormat,ReportLevel,ReportMethod,QueuedIngestClient,StreamDescriptor,KustoStreamingIngestClient) but the issue is only when I am importing "KustoIngestClient" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c010923-e011-6915-e3c4-6265fb997c35
* Version Independent ID: 6b102d99-8aae-bba3-0ddf-d4137c3d6434
* Content: [Ingest data using the Azure Data Explorer Python library](https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data)
* Content Source: [data-explorer/python-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/python-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@docast Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaurabhSharma-MSFT** [comment]
@docast I am able to reproduce this issue when I used option 2 like you mentioned.  
![image](https://user-images.githubusercontent.com/38112130/104764384-2f591480-571c-11eb-997f-36ed09308beb.png)

@orspod Can you please help engaging right people for this issue.

**Comment by docast** [comment]
Hi Saurabh,

As per the Github WIKI: https://github.com/Azure/azure-kusto-python/tree/master/azure-kusto-ingest

KustoIngestClient is renamed to QueuedIngestClient ( 10 days ago), however, this change is not yet reflected on docs page:
Ingest data using the Azure Data Explorer Python library | Microsoft Docs<https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data>

So the above docs.microsoft document need to be updated for the latest change.

[cid:image001.jpg@01D6EBA0.15304CF0]

Regards,
Don Rohan Castelino

**Comment by YaelSchuster** [comment]
A PR has been opened to make this update in the docs. Thanks @docast for your feedback! I am closing this issue now, but please feel free to reach out with any other comments or questions.

#please-close
