### ISSUE TITLE
Table Name need to be updated on python code 

### ISSUE THREAD

**Issue by docast** [MicrosoftDocs/dataexplorer-docs#546]
In the article: https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=python
under "Ingest mapped JSON records"
Python code is creating "TABLE = "RawEvents" whereas KQL/C# code is creating "Events" table. Hence when the document is viewed from python code point of view, the table name created in python code and the table name referrenced in the document is different and causing confusion ( Events Vs RawEvents) which need to be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d5f8ab-85c7-19bf-d91a-e76e81c76d7b
* Version Independent ID: 161a10d8-fc7f-97e8-b13e-0ddc7dd4f3c6
* Content: [Ingest JSON formatted data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=python)
* Content Source: [data-explorer/ingest-json-formats.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-json-formats.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by HarithaMaddi-MSFT** [comment]
@docast - Thanks for your contribution, I've addressed this issue in this [PR](https://github.com/MicrosoftDocs/dataexplorer-docs/pull/547). The changes should be live once the content author approves them.

**Comment by docast** [comment]
Hi Haritha,

I am looking at the article:
Ingest JSON formatted data into Azure Data Explorer | Microsoft Docs<https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=c-sharp>

Under Ingest mapped JSON records section:

KQL : code snippet creates Events table
[cid:image001.jpg@01D6E9F9.0B260D60]


C#: code snippet creates "Events" table.,
[cid:image002.jpg@01D6E9F9.0B260D60]


Python code snippet creates : "RawEvents" table.
[cid:image003.jpg@01D6E9F9.0B260D60]

Because in KQL and C#, table created is "Events" everywhere in the documentation refers to "Events" table. However python is creating "RawEvents" table which is creating confusion.

Regards,
Don Rohan Castelino
