### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by nakah** [MicrosoftDocs/dataexplorer-docs#548]
On the percentiles section:
5% of storms lasted at least two hours and 50 minutes should be:
95% of storms lasted at least two hours and 50 minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b32c0bf-08cc-c345-edca-d8fb0e15ffac
* Version Independent ID: 436fb2c0-ada7-e5dc-d6b7-3d2a8b5ea191
* Content: [Tutorial: Kusto queries in Azure Data Explorer & Azure Monitor](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/tutorial?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/tutorial.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/tutorial.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@nakah  
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
@nakah  
The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
