### ISSUE TITLE
Inconsistency between documentation pages

### ISSUE THREAD

**Issue by roehrijn** [MicrosoftDocs/dataexplorer-docs#560]
You mention the following on this page: 
![image](https://user-images.githubusercontent.com/2474078/105052862-a110c580-5a70-11eb-813b-328b392f1000.png)

But the term "Access Kusto" mentioned here can not be found at all on the linked target page called "Kusto guide to AAD applications provisioning". Neither in the text nor on any screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee89d0d7-becd-83f4-b862-f39b1c1ad6d4
* Version Independent ID: d40d3446-9677-dbdc-faa9-f04a30ffb042
* Content: [Kusto authenticate with AAD for access - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad)
* Content Source: [data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by YaelSchuster** [comment]
@vladikbr @cosh Please advise

**Comment by YaelSchuster** [comment]
Hi @roehrijn, thanks for reaching out. 

@vladikbr has responded that this text should read:

If your application is intended to serve as front-end and authenticate users for Azure Data Explorer cluster, it has to be granted delegated permissions on Azure Data Explorer.
The full step by step process for that is described at [Configure delegated permissions for the application registration](https://docs.microsoft.com/en-us/azure/data-explorer/provision-azure-ad-app#configure-delegated-permissions-for-the-application-registration).

I have opened a PR to update the documentation. I'll close the issue at this point. Feel free to reach out with any further questions or issues. Thanks for being a part of our contributor community!

#sign-off
