### ISSUE TITLE
Error on percentiles spotted

### ISSUE THREAD

**Issue by atrichet** [MicrosoftDocs/dataexplorer-docs#562]
text found in "https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/tutorial?pivots=azuredataexplorer":
vvvvv
We can see from the output that:

5% of storms have a duration of less than 5 minutes.
50% of storms lasted less than one hour and 25 minutes.
95% of storms lasted at least two hours and 50 minutes.
^^^^^
This is inconsistent: If 50% lasted LESS than 1h25, you can't have have 95% lasting MORE than 2h50. The last phrase should be "95% of storms lasted less than two hours and 50 minutes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b32c0bf-08cc-c345-edca-d8fb0e15ffac
* Version Independent ID: 436fb2c0-ada7-e5dc-d6b7-3d2a8b5ea191
* Content: [Tutorial: Kusto queries in Azure Data Explorer & Azure Monitor](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/tutorial?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/tutorial.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/tutorial.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@atrichet  
Thank you for reaching out and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @atrichet. Thanks for noticing that mistake! The doc has been updated accordingly. I am now closing this issue.
#please-close
