### ISSUE TITLE
There isn't any example

### ISSUE THREAD

**Issue by MLwolter** [MicrosoftDocs/dataexplorer-docs#563]
Please add examples. For example when exporting parameters it's recommended to use todynamic, but there isn't any example and when I come to this article there isn't any either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0bdf325-a459-1c3e-f445-452b0c21d6ec
* Version Independent ID: d9317182-7957-acdf-8837-5597d24e7fcf
* Content: [todynamic(), toobject() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/todynamicfunction)
* Content Source: [data-explorer/kusto/query/todynamicfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/todynamicfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @MLwolter , Thanks for the feedback! I have assigned the issue to the content author to evaluate and update this doc as appropriate.

**Comment by YaelSchuster** [comment]
Hi @MLwolter, thanks for your feedback. The todynamic() function is an alias of the [parse_json() function](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parsejsonfunction) , which has several examples. I've opened a PR to consolidate this documentation, and will now close this issue. Thanks for your help!

#please-close
