### ISSUE TITLE
Specify retentio period of ".show ingestion failures"

### ISSUE THREAD

**Issue by Marco-Santoni** [MicrosoftDocs/dataexplorer-docs#566]
In the documentation it is not specified that the command `.show ingestion failures` has a retention period for the ingestion failures is **14 days**. Is it possible to add a note?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e92070-d041-ea43-b0ee-577e61727302
* Version Independent ID: 4fcfa11f-f1a3-d27f-0674-2a4ea87623ef
* Content: [Ingestion failures - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/ingestionfailures)
* Content Source: [data-explorer/kusto/management/ingestionfailures.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/ingestionfailures.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@Marco-Santoni Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
@Marco-Santoni thanks for your input. A PR has been opened to update this in the docs. I will now close this issue.

#please-close
