### ISSUE TITLE
Availability Zones for two nodes ADX cluster

### ISSUE THREAD

**Issue by TechieWorld** [MicrosoftDocs/dataexplorer-docs#57]
Hello Team,

I have created two nodes azure data explorer cluster. I want to use azure availability zones settings to ensure improved reliability (both availability and resiliency). Since, I am having two nodes cluster, can I choose to place them in 3 zones? Also, how these nodes will be placed from Fault Domain and Update Domain Perspective? What will be the impact/down side when placed in 3 different zones?

To achieve 99.99% VMs up time, shall I choose more than 3 nodes or 2 nodes cluster would suffice the need?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0eae58-9545-b31d-19c3-8c5ad4ebc5bf
* Version Independent ID: 8c0ba522-cad6-bd73-9691-92e154d4c0f5
* Content: [Quickstart: Create an Azure Data Explorer cluster & DB](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-portal)
* Content Source: [data-explorer/create-cluster-database-portal.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/create-cluster-database-portal.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by cosh** [comment]
"Deployment to availability zones is possible only during cluster creation and can't be modified at a later date." -> you have to decide about AZs earlier.
drawback: atm you can't deploy ADX into a vnet if you choose AZs

you are able to deploy a 2 node ADX cluster into 3 AZs. However only 2AZs will be used. Once you scale out the cluster we will make sure that the nodes are distributed across all chosen AZs.

if you would like to increase availabilty you should create at least 3 nodes and pick 3 AZs.

**Comment by orspod** [comment]
@cosh thanks for your answer @TechieWorld - thanks for your question. I hope that your question has been addressed to your satisfaction.

**Comment by TechieWorld** [comment]
> "Deployment to availability zones is possible only during cluster creation and can't be modified at a later date." -> you have to decide about AZs earlier.
> drawback: atm you can't deploy ADX into a vnet if you choose AZs
> 
> you are able to deploy a 2 node ADX cluster into 3 AZs. However only 2AZs will be used. Once you scale out the cluster we will make sure that the nodes are distributed across all chosen AZs.
> 
> if you would like to increase availabilty you should create at least 3 nodes and pick

Thank you for prompt reply. BTW, is there any plan to support the VNET along with Zones since this feature is supported when we are creating VMs. Also, can you please let me know how to create the ADX cluster more than 2 Nodes by default, it's creating a two nodes cluster.

**Comment by orspod** [comment]
@cosh - will you please respond to the additional questions?

**Comment by cosh** [comment]
we are evaluating the VNet + Zones feature. I can't provide a date.
You can scale out the cluster after deployment or use an ARM template to provide this spec: https://docs.microsoft.com/en-us/azure/templates/microsoft.kusto/2020-02-15/clusters#azuresku-object

**Comment by orspod** [comment]
@TechieWorld - thanks again for your feedback. I hope we were able to address all your questions.
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
