### ISSUE TITLE
Sample code syntax error?

### ISSUE THREAD

**Issue by eanders-MS** [MicrosoftDocs/dataexplorer-docs#574]
When I copy/paste this sample code into data explorer, I see an error for `count`:
```
X
| mv-expand samples = range(bin(StartTime, 1m), StopTime , 1m)
| summarize count(SessionId) by bin(todatetime(samples),1m)
```

I get the error: `The function 'count' expects no arguments.`

Indeed, the docs for `count` does not list any parameters: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/count-aggfunction

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ceffe2-e518-d7f5-6f1d-99cbf26dce9a
* Version Independent ID: 28ce08eb-3eac-ad19-e11f-a3fd754757ec
* Content: [Samples for queries in Azure Data Explorer and Azure Monitor](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/samples?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/samples.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/samples.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@eanders-MS Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaurabhSharma-MSFT** [comment]
@eanders-MS The PR for the fix has been created and it will be merged after author's review. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
