### ISSUE TITLE
Examples on how to query using an ORM.

### ISSUE THREAD

**Issue by vivere-dally** [MicrosoftDocs/dataexplorer-docs#578]
Hello,

I want to query my cluster from .Net but I could only using the query provider given by KustoClientFactory.CreateCslQueryProvider(). Is there a way to query using ORMs like Entity Framework, Dapper, or something like that? If so are there any samples? What do you recommend using?

I only found these samples which are insufficient and haven't been updated in two years: `https://github.com/Azure/azure-kusto-samples-dotnet`. In there there is a project named HelloKusto which has some comments:
```
            // Important note: For demonstration purposes we show how to read the data
            // using the "bare bones" IDataReader interface. In a production environment
            // one would normally use some ORM library to automatically map the data from
            // IDataReader into a strongly-typed record type (e.g. Dapper.Net, AutoMapper, etc.)
```
You mention using Dapper, AutoMapper but there is no samples provided for this. Nor any resources that I can find.
How to use Dapper when I couldn't find a way to extract an IDataConnection from anywhere in the SDK.

I'm interested in querying, nothing else at the moment and I found it hard to start developing something on this side. There is a lack of resources. I also asked a question on stack and didn't get much help: `https://stackoverflow.com/questions/65917746/azure-data-explorer-c-sharp-qurying-and-orm`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b0560f-8a4c-c829-7307-c18a7710f0fc
* Version Independent ID: 61dcd20a-7a61-88af-ca40-e9922fbb86a1
* Content: [Kusto client library - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/about-kusto-data)
* Content Source: [data-explorer/kusto/api/netfx/about-kusto-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/netfx/about-kusto-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@vivere-dally Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaurabhSharma-MSFT** [comment]
@vivere-dally Can you please look into [this](https://github.com/AutoMapper/AutoMapper.Data) Automapper repository if this helps. Please check for test folder for any examples.  Also, [here](https://stackoverflow.com/questions/39441168/get-poco-object-from-idatareader-using-dapper) is a SO thread which can provide some pointers to use Dapper.

**Comment by vivere-dally** [comment]
I succeeded in making it work with both Dapper and AutoMapper. Thank you for your help. I suggest you update that sample, or somehow make a link between ADX Documentation and Dapper/AutoMapper resources. I really had a though time finding something.

**Comment by SaurabhSharma-MSFT** [comment]
@vivere-dally Good to hear.  Thanks for your feedback.  I will check internally on the same. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
