### ISSUE TITLE
Tables not selectable in Pivot Mode

### ISSUE THREAD

**Issue by sabatlive** [MicrosoftDocs/dataexplorer-docs#582]
As shown here, I cannot select tables to drag and drop for pivot exercise.

![image](https://user-images.githubusercontent.com/77139452/106392450-c245b000-63a6-11eb-8e7a-76e08ec81f47.png)

 I followed all the steps. I should see all tables to drag and drop if filter checkbox is on.

Thanks,

Sunil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237a4a12-fa3d-9ea2-8167-a57ab1d7a2c1
* Version Independent ID: aa9c6cfc-885a-db3b-5828-7af561f116af
* Content: [Quickstart: Query data in Azure Data Explorer Web UI](https://docs.microsoft.com/en-us/azure/data-explorer/web-query-data)
* Content Source: [data-explorer/web-query-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/web-query-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SatishBoddu-MSFT** [comment]
@sabatlive 
Thanks for the feedback! We are currently investigating and will update you shortly.
Cc: @CHEEKATLAPRADEEP-MSFT

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@sabatlive You may follow the step6 & step7 under Work with the table grid, to Select Pivot Mode, then drag columns as follows:

![ADX-PivotMode](https://user-images.githubusercontent.com/44426401/106419600-d0ff9600-647e-11eb-93ab-118d86ca6351.gif)

Hope this helps.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@sabatlive  We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
