### ISSUE TITLE
Fix for the explanation on how to connect to your own ADX cluster

### ISSUE THREAD

**Issue by yildizba** [MicrosoftDocs/dataexplorer-docs#590]
[There is a part (purple box) in this document where it says: 'If you are using your own ADX cluster, you must include the region in the connection string as follows:
%kql azuredataexplorer://tenant="youecompany.com";code;cluster='mycluster.westus';database='mykustodb'
However, i think the **tenant part** should be removed in order to connect to one's own cluster, otherwise it gives error. This can also be verified through this link as there is not tenant specified when connecting to one's own adx cluster <https://docs.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-kqlmagic?view=sql-server-ver15> ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f497838f-e309-f36a-43af-6d58b5e6b1e9
* Version Independent ID: 0cf67eee-4f79-9b23-7ec7-2ed347d68cb4
* Content: [Use a Jupyter Notebook to analyze data in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kqlmagic#connect-to-the-azure-data-explorer-help-cluster)
* Content Source: [data-explorer/kqlmagic.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kqlmagic.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@yildizba  Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@yildizba As per my testing, both the codes works perfectly without any issues.

If you are using your own ADX cluster, you must include the region in the connection string as follows:
`%kql azuredataexplorer://tenant="yourcompany.com";code;cluster='mycluster.westus';database='mykustodb'`

![image](https://user-images.githubusercontent.com/44426401/106997610-33bb9f00-67a9-11eb-9480-f3dc88580bc9.png)

If you are using your own ADX cluster, you must include the region in the connection string as follows:
`%kql azuredataexplorer://code;cluster='mycluster.westus';database='mykustodb'`

![image](https://user-images.githubusercontent.com/44426401/106997676-4c2bb980-67a9-11eb-90a6-8ec6b7f00c4a.png)

Hope this helps.

**Comment by yildizba** [comment]
Hi

Thank you for the response. This works for me as well when trying to connect to Microsoft’s help cluster but when trying to connect to my own cluster & db, I had to remove the tenant section. (I am aware of the region detail for the cluster part).

Could you please let me know what the ‘tenant’ should be for an ADX cluster that I have under our university account (UNSW).

Than you

Best Regards
Baran Yildiz, M.Sc., Ph.D.
Senior Research Associate
UNSW School of Photovoltaics & Renewable Energy Engineering
UNSW SYDNEY NSW 2052 AUSTRALIA
T: (+61) 2 9385 7120
M: (+61) 423 657 780
E: baran.yildiz@unsw.edu.au<mailto:baran.yildiz@unsw.edu.au>
W: ResearchGate<https://www.researchgate.net/profile/Baran_Yildiz>
CRICOS Provider Code 00098G
[cid:image001.png@01D6FE09.BAE503E0]<http://www.unsw.edu.au/>
I acknowledge the Gadigal people of the Eora Nation as the traditional custodians of the land on which I live and work, and pay my respects to their Elders past and present.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@yildizba  A tenant represents an organization in Azure Active Directory. It's a dedicated Azure AD service instance that an organization receives and owns when it signs up for a Microsoft cloud service such as Azure, Microsoft Intune, or Microsoft 365. Each Azure AD tenant is distinct and separate from other Azure AD tenants.

![image](https://user-images.githubusercontent.com/44426401/107176303-fc413280-69f4-11eb-988d-0c9a9f907a09.png)

Hope this helps.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@yildizba  We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
