### ISSUE TITLE
arg_min() default NameExprToReturn value

### ISSUE THREAD

**Issue by adingler711** [MicrosoftDocs/dataexplorer-docs#594]
When we are using arg_min(NameExprToMinimize , NameExprToReturn ) there should be a default value of * for NameExprToReturn. It does not make sense that there always needs to be two arguments especially if the user is using *. When using * it is returns all the columns after the by statement.

```kusto
Supplies | summarize arg_min(Price, *) by Product
```

should also be able to use

```kusto
Supplies | summarize arg_min(Price) by Product
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93336287-fa47-0ca7-4aba-318906afba5c
* Version Independent ID: ce226d9f-108e-d2aa-c5c8-61f50cfadd1a
* Content: [arg_min() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-min-aggfunction#feedback)
* Content Source: [data-explorer/kusto/query/arg-min-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/arg-min-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@adingler711  Thanks for bringing this to our attention. Your feedback  has been shared with the content owner for further review.

**Comment by YaelSchuster** [comment]
Hi @adingler711, thanks for being in touch! For product requests, please add requests and vote on what's important to you here: https://aka.ms/adx.uservoice 

I'm going to close this issue now, but please feel free to reach out with any other docs requests. 
#please-close
