### ISSUE TITLE
.create materialized-view using dimensionTables

### ISSUE THREAD

**Issue by adingler711** [MicrosoftDocs/dataexplorer-docs#595]
The document is a little miss leading.

In the example section there is an example of using a dimension table on number 6.

```kusto
.create materialized-view EnrichedArgMax on table T with (dimensionTables = ['DimUsers'])
{
    T
    | lookup DimUsers on User  
    | summarize arg_max(Timestamp, *) by User 
}

.create materialized-view EnrichedArgMax on table T with (dimensionTables = ['DimUsers'])
{
    DimUsers | project User, Age, Address
    | join kind=rightouter hint.strategy=broadcast T on User
    | summarize arg_max(Timestamp, *) by User 
}
```

and then in the tips section it mentions that dimension tables should not be used
> Don't include transformations, normalizations, lookups in dimension tables, and other heavy computations that can be moved to an update policy as part of the materialized view definition. Instead, do all those processes in an update policy, and perform the aggregation only in the materialized view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a80bf02-94d1-8ba9-87d5-7eb879b3f193
* Version Independent ID: 775199fd-18a8-c173-27f1-c44d533e4697
* Content: [Create materialized view - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/materialized-views/materialized-view-create)
* Content Source: [data-explorer/kusto/management/materialized-views/materialized-view-create.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/materialized-views/materialized-view-create.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@adingler711 
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
@yifatsor Please advise.

**Comment by yifatsor** [comment]
@adingler711 - I'll try to clarify (here and in the docs) - although dimension tables _are_ supported with materialized views, it is generally recommended to perform enrichments (lookups) and transformations in update policies. This is not set in stone - both may work, depending on clusters available resources / ingestion rate and so on. So both options are possible, but the recommendation still stands. I'll try to clarify this in the docs as well.

**Comment by adingler711** [comment]
@YaelSchuster, @yifatsor thank you. I was able to get around it by creating an update policy instead of using the dimension table.

When I was using the dimension table, it worked when I only had 1 dimension table but it would break when I had 2 dimension tables.

**Comment by YaelSchuster** [comment]
Thanks for your response, @yifatsor. 
@adingler711 I am going to proceed to close this issue. If you have any other feedback, problems, or improvements, please feel free to reach out! 

#please-close
