### ISSUE TITLE
Is there https://dataexplorer.azure.com/clusters/ support for query parameters?

### ISSUE THREAD

**Issue by jason-ha** [MicrosoftDocs/dataexplorer-docs#598]
There are notes on specifying parameters for several interfaces, but no notes for https://dataexplorer.azure.com/clusters/. Is there support? If the feature is missing it would still be useful to call that out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f989c5-4b98-697a-7db0-95e77ad43402
* Version Independent ID: e919ef27-4304-bb33-3eea-7264f885ca76
* Content: [Query parameters declaration statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/queryparametersstatement)
* Content Source: [data-explorer/kusto/query/queryparametersstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/queryparametersstatement.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@jason-ha  Thanks for the feedback!  Your feedback  has been shared with the content owner for further review.

**Comment by izikl** [comment]
Unfortunately, there is no such option. 

As a workaround you can try passing the full query with [deep links](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/deeplink): 
```
https://dataexplorer.azure.com/clusters/<cluster>/databases/<database>?query=<URL Encodeded Query>
```
For example: 
to run this query:
```
let ['takeParam']=10;
Covid19_flat | take takeParam
```

You can run this deep-link:
https://dataexplorer.azure.com/clusters/help/databases/Samples?query=let%20%5B%27takeParam%27%5D%3D10%3B%0ACovid19_flat%20%7C%20take%20takeParam%0A

For the feature request, can you please add it to [user voice](https://feedback.azure.com/forums/915733-azure-data-explorer)?

**Comment by YaelSchuster** [comment]
Hi @izikl, thanks for responding.

@jason-ha please feel free to open a feature request on the user voice link above. I am going to proceed to close this issue. Please feel free to reach out with any further questions or issues.
#please-close

**Comment by jason-ha** [comment]
I still think it could be useful to note that it is not supported.

**Comment by jason-ha** [comment]
@izikl Don't see that as workaround for scenario of trying to explore with ease. But I did file suggestion https://feedback.azure.com/forums/915733-azure-data-explorer/suggestions/42696005-support-query-parameters-specification.
