### ISSUE TITLE
Clarify if IngestionTime is guaranteed to be monotonic

### ISSUE THREAD

**Issue by Spoonbender** [MicrosoftDocs/dataexplorer-docs#613]
The page says `$IngestionTime` can be used to retrieve only the data ingested since the last query.
However, the page doesn't explicitly state if `$IngestionTime` is **guaranteed** to be monotonic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5dcc08f-5459-e456-0812-d724c735b92d
* Version Independent ID: c05f8646-afd1-45f4-a37f-8f71c9397f6b
* Content: [IngestionTime policy - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/ingestiontimepolicy)
* Content Source: [data-explorer/kusto/management/ingestiontimepolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/ingestiontimepolicy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@Spoonbender  - Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @Spoonbender, thanks for reaching out. Can you please clarify your question? The section you reference of $IngestionTime retrieving only the data ingested since the last query is in combination with supporting Database Cursors and is not general to use of $IngestionTime. 

"To support Database Cursors that let users issue consecutive queries, the query is limited to the data that was ingested since the previous query."

**Comment by Spoonbender** [comment]
Hi,
First, thank you for clarifying that `$IngestionTime` is only meant to be used for exactly-once queries via the Database Cursors feature. 
It might be worth adding a relevant note about this intention and/or about the monotonicity guarantees to the documentation, since the document does point at the [ingestion_time() function](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/ingestiontimefunction?pivots=azuredataexplorer) - this document does note that database cursors should be used for exactly-once queries, but I imagined that I would be able to have an at-least-once queries by using the `ingestion_time()` function alone (assuming it is monotonic).

Now I see that my question is more about the internal implementation of $IngestionTime and database cursors.
I wanted to know if the cursor is guaranteed to never miss records due to changes in the ingestion server's clock (e.g. if it goes back due to NTP sync) or server failovers. 
I've read the Database Cursors document again and it seems the guarantee holds, so, I guess this issue can be closed.
Thanks!

**Comment by YaelSchuster** [comment]
@Spoonbender thanks for your detailed response. I will look into clarifying that in the docs. In the mean time, I'm going to close this issue. Please feel free to reach out by @mention my GitHub alias, or opening new issues where necessary.
Have a great day!

#please-close

**Comment by YaelSchuster** [comment]
One more note from @alexans:

The only thing that we guarantee – is that when using cursors – the data can be queried “only once”.
We can’t guarantee that ingestion time is monotonically increases (at least not in all scenarios: streaming, followers, streaming+followers in the future).
