### ISSUE TITLE
Clarify the guarantees of strongly consistent queries

### ISSUE THREAD

**Issue by Spoonbender** [MicrosoftDocs/dataexplorer-docs#614]
Please clarify if the strongly consistent queries mode provides only a "[read-your-write](https://jepsen.io/consistency/models/read-your-writes)" guarantee for a specific client session, or a stronger guarantee such that a write performed by some session is immediately visible to all other sessions.

The current documentation uses the term "you", which is ambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93aec2dc-c6c4-766d-421f-50e4905b4e8b
* Version Independent ID: 92192f5c-e7cc-5d6a-adcb-1b4969dfe113
* Content: [Query consistency - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/queryconsistency)
* Content Source: [data-explorer/kusto/concepts/queryconsistency.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/concepts/queryconsistency.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@Spoonbender - 
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Thanks @Spoonbender for reaching out.

Response from @zivcaspi:

There are no “sessions” as such in Kusto today. Once a “write” transaction completes successfully, any subsequent strongly-consistent “read” transaction will “see” its results.

**Comment by Spoonbender** [comment]
@YaelSchuster thank you for the clarification!
I suggest clarifying in the document itself as well, since the doc uses the term "read-my-changes" which resembles the well-known "read your write" (a.k.a "read my write") consistency model, which provides _weaker_ consistency than what Kusto provides (See https://jepsen.io/consistency/models/read-your-writes and https://en.wikipedia.org/wiki/Consistency_model#Read-your-writes_consistency )... for your consideration.
Either way this issue can be closed as far as I'm concerned :-)

**Comment by YaelSchuster** [comment]
@Spoonbender thanks for the references. I'm going to close the issue at this time. 

#please-close
