### ISSUE TITLE
Explain the enforcement of concurrency limit

### ISSUE THREAD

**Issue by Spoonbender** [MicrosoftDocs/dataexplorer-docs#615]
The document explains that the concurrency limit exists and how the limit is defined, but it doesn't say what happens when the limit is reached (request rejected? throttled? etc.)
Do notice that this behavior **is** explained at the ["Request limit policy" document](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/request-rate-limit-policy)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082142f3-9558-d472-c85b-459b956480a1
* Version Independent ID: 3beb35b6-5885-9367-9fc0-2c4fe6b7b824
* Content: [Query limits - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits)
* Content Source: [data-explorer/kusto/concepts/querylimits.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/concepts/querylimits.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@Spoonbender - 
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @Spoonbender thanks for your input! A PR has been opened to address this request. As such, I'm closing the issue. Please feel free to reach out with more docs improvements!

#please-close
