### ISSUE TITLE
How to use a connection string with @azure/data-tables

### ISSUE THREAD

**Issue by vincesp** [MicrosoftDocs/dataexplorer-docs#618]
Add example how to use a connection string with NPM package `@azure/data-tables` in Azure functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6548247e-f52f-8a4d-9ca5-b15314a7bb33
* Version Independent ID: f671c75c-8275-4e9a-7c4d-1508691139f7
* Content: [Storage connection strings - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/storage)
* Content Source: [data-explorer/kusto/api/connection-strings/storage.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/connection-strings/storage.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@vincesp Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @vincesp, thanks for reaching out.

Response from @ArielYehezkely: 
This document lists the storage connection strings supported by Kusto. 
Kusto doesn’t support connection strings of tables.

**Comment by YaelSchuster** [comment]
@vincesp thanks for being part of our contributor community! Please feel free to @mention me with any further questions or open up a new issue if needed. Since this issue has been answered, I'm going to proceed to close it at this time.

#please-close
