### ISSUE TITLE
Add hint to use top operator instead when no groupExpression is used

### ISSUE THREAD

**Issue by avosdewael** [MicrosoftDocs/dataexplorer-docs#620]
A mistake I have made was using the:

- `| summarize arg_min(scalar, *)` and 
- `| summarize arg_max(scalar, *)`

syntax patterns without a _groupExpression_ to reduce the table to a single output row. While this works, it seems that the alternative `| top 1 by scalar` pattern is functionally equivalent yet offers better performance. 

I suggest adding a hint to the arg_min() and arg_max() pages to use the top operator when no grouping is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93336287-fa47-0ca7-4aba-318906afba5c
* Version Independent ID: ce226d9f-108e-d2aa-c5c8-61f50cfadd1a
* Content: [arg_min() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/arg-min-aggfunction)
* Content Source: [data-explorer/kusto/query/arg-min-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/arg-min-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KalyanChanumolu-MSFT** [comment]
@avosdewael Thank you for the detailed feedback. 
This is being assigned to the content author to evaluate and update the documentation as appropriate.

**Comment by YaelSchuster** [comment]
Hi @avosdewael thanks for reaching out with your suggestion. As per @sloutsky, actual perf results depend on the data, and implementation which may change in future.  

I am going to close this issue at this time, but please feel free to reach out with future improvements!
#please-close
