### ISSUE TITLE
Clarify RPO and RTO of Active-Active configuration

### ISSUE THREAD

**Issue by Spoonbender** [MicrosoftDocs/dataexplorer-docs#628]
Please clarify the RPO and RTO of the Active-Active configuration:

The "Active-Active-Active" configuration specifies RTO and RPO of `0 hours`, which I believe means that the recovery time is zero and the data loss is also zero.
However, the "Active-Active" configuration specified RTO and RPO of `None`, which seems to imply... that there is no objective at all? (?!)
This is confusing with regards to the other, lower-cost options which provide _some_ RTO and RPO.

Current summary table looks as follows:

![image](https://user-images.githubusercontent.com/6010433/108622045-fd378280-743e-11eb-8252-0449c1f1840f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c426719b-43df-8702-a573-9b1698439773
* Version Independent ID: d33d9114-7292-8487-a4c3-a3491b23c212
* Content: [Azure Data Explorer and business continuity disaster recovery](https://docs.microsoft.com/en-us/azure/data-explorer/business-continuity-overview#feedback)
* Content Source: [data-explorer/business-continuity-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/business-continuity-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by JamesTran-MSFT** [comment]
@Spoonbender 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by himanshusinha-msft** [comment]
Hello @Spoonbender  ,
As mentioned in the same article ( i am pasting the text below ) that Active- Active is very similar to Active-active-active configuration with the exception that we have only two regions participating in Active- Active . I think for Active- Active also the RTO and RPO should be 0  , but i will let @orspod comment on the same . 

[Active-Active configuration](https://docs.microsoft.com/en-us/azure/data-explorer/business-continuity-overview#active-active-configuration)
This configuration is identical to the active-active-active configuration, but only involves two Azure paired regions. Configure dual ingestion, processing, and curation. Users are routed to the nearest region. The cluster SKU must be the same across regions

**Comment by YaelSchuster** [comment]
Hi @Spoonbender thanks as usual for your excellent questions about our docs. 
I've checked with @cosh and the RTO and RPO for the Active-Active configuration is indeed 0 hours. This is now being changed in the documentation.

Closing this issue now, please let me know if you have further questions.
#please-close
