### ISSUE TITLE
Minor fix: GO API -> Go SDK

### ISSUE THREAD

**Issue by Spoonbender** [MicrosoftDocs/dataexplorer-docs#629]
Under "Programmatic ingestion using SDKs", the list specifies the "GO API", but this is actually a "Go SDK" and not an API (as the linked document specifies)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c758ab8-a66a-0d9d-af7a-a0fbe43ec6f4
* Version Independent ID: 62e4d091-8261-eb79-0f50-92a302487dd0
* Content: [Azure Data Explorer data ingestion overview](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-overview)
* Content Source: [data-explorer/ingest-data-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
Hi @Spoonbender, thank you for noticing. This has been updated in the docs.

#please-close
