### ISSUE TITLE
Azure Log Analytics

### ISSUE THREAD

**Issue by haritrichy** [MicrosoftDocs/dataexplorer-docs#632]
I'd like to know if Spark Connector for data explorer can be used to interface with Azure Log Analytics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa46bfb-17f8-a18d-50a5-eaad4c85ae19
* Version Independent ID: ac1fc513-55d6-203a-ce2c-bae250d126d4
* Content: [Use the Azure Data Explorer connector for Apache Spark to move data between Azure Data Explorer and Spark clusters.](https://docs.microsoft.com/en-us/azure/data-explorer/spark-connector)
* Content Source: [data-explorer/spark-connector.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/spark-connector.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the question! We will review and get back to you shortly.

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author to comment on this .

**Comment by ohadbitt** [comment]
If by interface you mean to query from Azure Log Analytics with the log analytics credentials and urls then the answer is no.
If you really want to use it for that you will need to find the Kusto cluster, dtabase and table supporting this Log analytics

**Comment by YaelSchuster** [comment]
Thanks, @ohadbitt, for your response.
@haritrichy thanks for reaching out with your question. Since it has been answered, I am going to proceed to close this issue. If you have further questions or comments, please feel free to open a new issue or @ mention myself or Ohad.

#please-close
