### ISSUE TITLE
About NSG settings when deploying an Azure Data Explorer Cluster in a Virtual Network

### ISSUE THREAD

**Issue by kogesaka** [MicrosoftDocs/dataexplorer-docs#633]
In step 9 of "Create Network Security Group (NSG)" section, the content of the "Outbound security rules" in the figure and the content in the link (https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment#dependencies-for-vnet-deployment) appear to be different.

It seems that the content of the link ("Outbound NSG configuration" section) is correct, not the figure, but would you prealse check it.

If possible, would you please also tell us about the "AllowADXMonitoringConfigurationDownload" shown in the figure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68819851-163e-b42d-949e-f20e11731d24
* Version Independent ID: 19cff8ca-b534-2278-f3f9-2eb7b8032abc
* Content: [Create an Azure Data Explorer cluster & DB in your virtual network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-create-cluster-portal)
* Content Source: [data-explorer/vnet-create-cluster-portal.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/vnet-create-cluster-portal.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by AshokPeddakotla-MSFT** [comment]
@kogesaka Thanks for the feedback! I have assigned the issue to the content author @orspod to evaluate and update as appropriate.

**Comment by basaba** [comment]
Hi @kogesaka,
The figure shows inbound security rules and not outbound

**Comment by kogesaka** [comment]
Hi @basaba,

Is what you are saying true?

This document's in figure looks like both inbound and outbound settings. 

> 9. Repeat the previous two steps for all inbound and outbound dependencies according to dependencies for VNet deployment. Alternatively, outbound rules can be replaced with single rule to allow Internet for ports 443 and 80.  
>The NSG rules for inbound and outbound dependencies should look like this:
>![figure](https://docs.microsoft.com/en-us/azure/data-explorer/media/vnet-create-cluster-portal/nsg-rules.png)
>

Which content is correct infomation?

**Comment by YaelSchuster** [comment]
@kogesaka - the image you show describes the specific settings for inbound and outbound network security group rules. The document you refer to discusses general dependencies. Can you elaborate as to which particular rule you find a discrepancy in? @basaba

**Comment by kogesaka** [comment]
@YaelSchuster,

"Outbound security rules" Priority 104 (AllowADXMonitoringConfigurationDownload, 443, TCP, Any, 40.78.70.148) in figure that is not included in the "Outbound NSG configuration" section of the document "Deploy Azure Data Explorer cluster into your Virtual Network" (https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment#dependencies-for-vnet-deployment).

**Comment by basaba** [comment]
@kogesaka AllowADXMonitoringConfigurationDownload specifically is not needed anymore it's included in AzureMonitor now, I'll  remove it from the diagram

**Comment by YaelSchuster** [comment]
@basaba thanks for your response.
@kogesaka It seems you have an answer to your question. As such, I'm going to proceed to close this issue. If you have any further questions, please feel free to reach out. Thanks for being a part of our contributor community!

#please-close
