### ISSUE TITLE
delete command description must be wrong

### ISSUE THREAD

**Issue by nbfowler** [MicrosoftDocs/dataexplorer-docs#638]
<img width="722" alt="Screen Shot 2021-03-05 at 1 20 09 PM" src="https://user-images.githubusercontent.com/245593/110174892-b722dd00-7db5-11eb-9bb5-7b8be202948d.png">

> `.delete table *TableName* policy update` appends to the current update policy of a table.

Really?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26bac25c-c168-fadc-2491-651d35361512
* Version Independent ID: 608aa328-7799-1597-0940-4edec0b93e08
* Content: [Kusto update policy for data added to a source - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/updatepolicy)
* Content Source: [data-explorer/kusto/management/updatepolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/updatepolicy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by shashishailaj** [comment]
@nbfowler Thank you for your feedback . We will investigate and update the thread.

**Comment by YaelSchuster** [comment]
Hi @nbfowler, thanks for catching that! You are correct. I've opened a PR to fix this error. 
Thanks for being part of our contributor community and please continue to send issues our way!

#please-close
