### ISSUE TITLE
External Table for Parquet or Avro data format throws error.

### ISSUE THREAD

**Issue by ashwini-git** [MicrosoftDocs/dataexplorer-docs#64]
Hi , 
i created an external table to fetch Parquet data from ADLS which throws below error. 

`Query execution has resulted in error (0x80131500): Partial query failure: 0x80131500 (message: 'Input parquet file is ill-formed and cannot be processed: 'not a Parquet file (size too small)'.: ', details: 'Source: Kusto.Common.Svc
[0]Kusto.Common.Svc.Exceptions.IngestionSourceParquetReaderException: Input parquet file is ill-formed and cannot be processed: 'not a Parquet file (size too small)'.
Timestamp=2020-05-07T11:22:42.0340199Z`

**Folder structure at ADLS:-**
logs / {AppId}/ 2020 / 05 / 07

External Table definition : 

```
.alter external table ExTParquet (AppId:string,UserId:string,Email:string,RoleName:string,Operation:string,EntityId:string,EntityType:string,EntityName:string,TargetTitle:string,Params:string,EventProcessedUtcTime:datetime,PartitionId:string,EventEnqueuedUtcTime:datetime) 
kind=blob
partition by 
   AppId,
   bin(EventProcessedUtcTime,1d)
dataformat=parquet
( 
   h@'https://streamoutalds2.blob.core.windows.net/stream-api-raw-parquet/logs;secret_key'
)
with 
(
   folder = "ExternalTables"   
)
```

**Note : if i provide full file path and remove source directory partitioning from External Table definition  , it works well. **

Please look into it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 467fa023-f317-e4d7-50a9-0061c48c1a4d
* Version Independent ID: efc9cf7d-454e-c3f0-92dc-038ac93796f2
* Content: [External table management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/externaltables)
* Content Source: [data-explorer/kusto/management/externaltables.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/externaltables.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@ashwini-git thank you for your feedback.
@yifatsor - can you please assist with the question?

**Comment by yifatsor** [comment]
@ashwini-git this looks like a recent regression we had which was already fixed but perhaps not deployed to your cluster. Can you provide cluster details and a client request id for the failure (and an approximate timestamp)? It would be better if you can move the question to stackoverflow, as we normally don't track product related issues in the docs repository (tag the question with Azure Data Explorer / Kusto). Thanks!

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@ashwini-git  Since this issue is not related directly to the doc, I would recommend you to create a thread on the forums - [MSDN ](https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureKusto) or [StackOverflow](https://stackoverflow.com/questions/tagged/azure-data-explorer)
Once you post your issue on forums, it will have visibility across the community which is a better suited audience for such types of issues.
