### ISSUE TITLE
How do we run the commands instead of the queries?

### ISSUE THREAD

**Issue by haivercarrillo** [MicrosoftDocs/dataexplorer-docs#640]
Hi,

Could you please add how do we run the .drop, . alter, .clear commands from powershell?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2df80c7-1cca-9c8d-0ed5-05b387e1850f
* Version Independent ID: d3f5e3ed-dc62-ca1a-c821-4ca25453fa0f
* Content: [Kusto .NET Client Libraries from PowerShell - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell)
* Content Source: [data-explorer/kusto/api/powershell/powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/powershell/powershell.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@haivercarrillo  Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by YaelSchuster** [comment]
@yonileibowitz can you help with this question?

**Comment by yonileibowitz** [comment]
there's a `Example: Running an admin command` section in this document, it shows how to run control commands from powershell

**Comment by YaelSchuster** [comment]
Thanks, @yonileibowitz 
@haviercarrillo please see https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell#example-running-an-admin-command

Please let us know if you have any further questions.

Closing this Issue at this time.
#please-close
