### ISSUE TITLE
The LET query does not work in resources manager to query Resources

### ISSUE THREAD

**Issue by robertdudus-shell** [MicrosoftDocs/dataexplorer-docs#641]
Here's a prove:
![image](https://user-images.githubusercontent.com/76438250/111033569-cdf6ae80-8409-11eb-90d8-85c8b8f53bc4.png)
Or:
![image](https://user-images.githubusercontent.com/76438250/111033649-2f1e8200-840a-11eb-9671-8dcd9065561e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b32c0bf-08cc-c345-edca-d8fb0e15ffac
* Version Independent ID: 436fb2c0-ada7-e5dc-d6b7-3d2a8b5ea191
* Content: [Tutorial: Kusto queries in Azure Data Explorer & Azure Monitor](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/tutorial?pivots=azuremonitor)
* Content Source: [data-explorer/kusto/query/tutorial.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/tutorial.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@robertdudus-shell Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@robertdudus-shell VMComputer is a table that Azure Monitor uses for VMs to store details about virtual machines that it monitors. [InsightsMetrics](https://docs.microsoft.com/en-us/azure/azure-monitor/reference/tables/insightsmetrics) contains performance data that's collected from those virtual machines. One value collected in InsightsMetrics is available memory, but not the percentage memory that's available. To calculate the percentage, we need the physical memory for each virtual machine. That value is in VMComputer.

I'm able to run the query without any issue.

![image](https://user-images.githubusercontent.com/79183421/111111717-db847380-8584-11eb-9606-b7dba414c8c7.png)

Hope this helps.

**Comment by robertdudus-shell** [comment]
They work on Logs and in other places, they don't work for Resource based queries like here (I should have clarified it):
![image](https://user-images.githubusercontent.com/76438250/111133993-1087ca80-8573-11eb-9418-af05690af331.png)

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@orspod Could you please look into this issue?

**Comment by YaelSchuster** [comment]
Hi @robertdudus-shell,
Thanks for reaching out. The Azure Resource Manager supports a subset of KQL (Kusto Query Language) for querying resources. The let statement is not part of this subset. For more information, see https://docs.microsoft.com/en-us/azure/governance/resource-graph/concepts/query-language#supported-kql-language-elements

As this question is not related to the Azure Data Explorer product or documentation, I am closing it at this time. Please feel free to reach out with any other questions!

#please-close
