### ISSUE TITLE
Finish.

### ISSUE THREAD

**Issue by doangeh** [MicrosoftDocs/dataexplorer-docs#643]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c758ab8-a66a-0d9d-af7a-a0fbe43ec6f4
* Version Independent ID: 62e4d091-8261-eb79-0f50-92a302487dd0
* Content: [Azure Data Explorer data ingestion overview](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-overview)
* Content Source: [data-explorer/ingest-data-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by doangeh** [comment]
Rms InternationalL*

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@doangeh Could you share your feedback on the document or any questions related to the document?

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@doangeh  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
