### ISSUE TITLE
Unable to convert a dynamic type to a datetime in KQL

### ISSUE THREAD

**Issue by fgheysels** [MicrosoftDocs/dataexplorer-docs#644]
I have an issue where I try to convert a _dynamic_ value to a datetime value.

I'm logging custom events in Application Insights where each custom event has some custom properties.  One of these custom properties (custom dimensions), is a datetime value.
Something like this:

![image](https://user-images.githubusercontent.com/3605786/111767106-9cb52d00-88a6-11eb-833e-ef719f4429de.png)

Now, I want to retrieve from every VesselId the latest value in the Timestamp custom dimension, so I write a query like this, but this one fails because the values in the customDimensions are returned as dynamic:

![image](https://user-images.githubusercontent.com/3605786/111767304-d8e88d80-88a6-11eb-8b7f-e7d7e6f1c879.png)

This is not a problem, you can simply convert them like this:

![image](https://user-images.githubusercontent.com/3605786/111767405-f9184c80-88a6-11eb-8c1d-3e891ad66ef8.png)

However, as you can see, the value of the datetime is null.

Also, when I execute this query, the results are null:

![image](https://user-images.githubusercontent.com/3605786/111767532-236a0a00-88a7-11eb-961a-70d797c542e9.png)

But, when I just to a `print todatetime("2021/03/18 10:31:26") for instance, I get the correct results back:

![image](https://user-images.githubusercontent.com/3605786/111767695-501e2180-88a7-11eb-83d0-aada0b7fc2f7.png)

I also tried to convert the dynamic value to a string first, and then to a datetime, but here, also null is returned.

![image](https://user-images.githubusercontent.com/3605786/111767949-983d4400-88a7-11eb-8f38-c38219be36b2.png)

I tried the above steps with multiple datetime formats (also yyyy-MM-ddTHH:mm:ss), but all have the same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b9c57fc-5fd0-14dd-15f5-7254e48d680f
* Version Independent ID: d2afa3b1-757a-9146-908a-8cabf7aad10b
* Content: [todatetime() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/todatetimefunction)
* Content Source: [data-explorer/kusto/query/todatetimefunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/todatetimefunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@fgheysels  Thanks for the question! We are investigating and will update you shortly.

**Comment by YaelSchuster** [comment]
@fgheysels 
Hi, thanks for reaching out! It seems you're using unsupported datetime representation, that’s why conversion fails.
Supported datetime string types are listed here:
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/datetime

The reason why the same string works when it is used as constant – is due to historical/backward compatibility issues (it was never supported fully – only in constants). The way to resolve it is to write a custom parsing function, based on the custom datetime format being used.

**Comment by YaelSchuster** [comment]
At this time, I am closing the issue. Please feel free to reach out with any further questions.
#please-close

**Comment by YaelSchuster** [comment]
Hi @fgheysels, the todatetime function only works on some non-supported formats when used as constants. It seems you are still not using one of the supported datetime formats. https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/datetime

**Comment by fgheysels** [comment]
Hi @YaelSchuster  Please read my answer :)

I am using a supported format, and the `todatetime` function works on that.

However, when I use `print todatetime` with an unsupported format, it also works, but when I retrieve that same unsupported answer from log analytics, it doesn't work.

**Comment by YaelSchuster** [comment]
@fgheysels yes, the `print todatetime()` on certain unsupported formats only works because of some legacy backwards compatibility, but does not actually work anywhere else.

**Comment by fgheysels** [comment]
Thanks for clarifying.
