### ISSUE TITLE
KQL pattern query from docs not working

### ISSUE THREAD

**Issue by darivuki** [MicrosoftDocs/dataexplorer-docs#649]
This code snippet/query, does not seem to be working. I haven't seen another example in the docs similar to this one to try to out. The problem here is that the passed-in parameters in the second pattern-expression are not working. I get this error "'where' operator: Failed to resolve table or scalar expression named 'applicationId'", which means that the applicationId:string parameter could not be read by the second expression - in our case, the applicationId parameter was set using the "ApplicationX" argument below.
 
declare pattern app = (applicationId:string)[eventType:string]
{
    ("ApplicationX").["StopEvents"] = { database("AppX").Events | where EventType == "StopEvent" };
    ("ApplicationX").["StartEvents"] = { database(applicationId).Events | where EventType == eventType } ;
};
app("ApplicationX").StartEvents
| join kind=inner app("ApplicationX").StopEvents on CorrelationId
| count

Is this scenario supported at all, or was this an error in the docs. This is the only place where I saw this type of syntax and the pattern statement being used like that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 195f90c9-ed7f-109b-6f6d-66793eb97776
* Version Independent ID: d64067d0-c043-ee43-8fa4-d6ae2db22228
* Content: [pattern statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/patternstatement)
* Content Source: [data-explorer/kusto/query/patternstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/patternstatement.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@darivuki  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @darivuki thanks for reaching out. You are correct, this scenario is not supported. We've opened a PR to correct this in the docs.

The example should read:

declare pattern app = (applicationId:string)[eventType:string]
{
    ("ApplicationX").["StopEvents"] = { database("AppX").Events | where EventType == "StopEvent" };
    ("ApplicationX").["StartEvents"] = { database("AppX").Events | where EventType == "StartEvents" } ;
};
app("ApplicationX").StartEvents
| join kind=inner app("ApplicationX").StopEvents on CorrelationId
| count

**Comment by YaelSchuster** [comment]
Since this problem has been resolved in the docs, I'm going to close it now. Please feel free to reach out with any more questions or problems.

#please-close
