### ISSUE TITLE
Should include a reference to the underlying data source

### ISSUE THREAD

**Issue by 1RedOne** [MicrosoftDocs/dataexplorer-docs#650]
It is difficult to understand what this command on this page is meant to do.  Since it doesn't show the underlying data source, and references an opaque 'EpsidoeNarrative` property.

```
StormEvents     
| where EventNarrative != "" and monthofyear(StartTime) > 1 and monthofyear(StartTime) < 9
| where EventType == "Drought" or EventType == "Extreme Cold/Wind Chill"
| evaluate diffpatterns_text(EpisodeNarrative, EventType == "Extreme Cold/Wind Chill", 2)
```

It would be easier to understand if this article included a link to what kind of events would be found in the `StormEvents` table, or had a screenshot of them.  Then the functionality of what the command is doing could be explained in better detail.  I think someone would need to be a data scientist already to be able to read this and understand the use of the command. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c243efeb-d13e-4f45-1cf0-262dd2613b69
* Version Independent ID: 1e4781bf-5041-f799-7d01-c30a1be83b8c
* Content: [diffpatterns_text plugin - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/diffpatterns-textplugin)
* Content Source: [data-explorer/kusto/query/diffpatterns-textplugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/diffpatterns-textplugin.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@1RedOne  
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @1RedOne, thanks for reaching out with your question. 
I've updated the docs with a link to the table in the help cluster that is referenced in this example.

This example uses data from the StormEvents table in the help cluster. To access this data, sign in to [https://dataexplorer.azure.com/clusters/help/databases/Samples](https://dataexplorer.azure.com/clusters/help/databases/Samples). In the left menu, browse to **help** > **Samples** > **Tables** > **Storm_Events**.

Your feedback helps us make the docs more accessible to all users, so thank you! Please feel free to reach out with any other questions or concerns.

#please-close

**Comment by 1RedOne** [comment]
This looks great, excellent 👍
