### ISSUE TITLE
This note on the page is cryptic "Time of ingestion"

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#651]
The consideration next to ingesting using ADF is cryptic "Time of ingestion"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c758ab8-a66a-0d9d-af7a-a0fbe43ec6f4
* Version Independent ID: 62e4d091-8261-eb79-0f50-92a302487dd0
* Content: [Azure Data Explorer data ingestion overview](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-overview)
* Content Source: [data-explorer/ingest-data-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@ciufudean Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Thanks for the feedback, @ciufudean. You're definitely not wrong here.  @TzviaGT can you help clarify this consideration?

**Comment by YaelSchuster** [comment]
@ciufudean The article in question has now been updated to clarify the following regarding ingestion with Azure Data Factory (ADF):
This method takes relatively more time until data is ingested. ADF uploads all data to memory and then begins ingestion.

**Comment by YaelSchuster** [comment]
#please-close
