### ISSUE TITLE
Commands not working for linux powershell

### ISSUE THREAD

**Issue by nisinha** [MicrosoftDocs/dataexplorer-docs#655]
From windows powershell the commands are working properly but not from Linux powershell where unblock-file is not recognized and I am getting type Initialization error while calling 
$kcsb = New-Object Kusto.Data.KustoConnectionStringBuilder($clusterUrl, $databaseName)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2df80c7-1cca-9c8d-0ed5-05b387e1850f
* Version Independent ID: d3f5e3ed-dc62-ca1a-c821-4ca25453fa0f
* Content: [Kusto .NET Client Libraries from PowerShell - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell)
* Content Source: [data-explorer/kusto/api/powershell/powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/powershell/powershell.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@nisinha Thanks for your feedback! We will investigate and update as appropriate.

**Comment by grawcho** [comment]
@nisinha - can you please share the $PSVersionTable output (since support for posix systems for Unblock-file was added in pwsh 7)?

**Comment by nisinha** [comment]
@grawcho . This is output of the below command.


Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by SaurabhSharma-MSFT** [comment]
@grawcho - Did you get a chance to look into this.

**Comment by orspod** [comment]
@shsagir  - FYI

**Comment by shsagir** [comment]
Thx. We are currently investigating the issue.

**Comment by grawcho** [comment]
I provided a workaround for @nisinha when we spoke, essentially use native powershell script query without the SDK, i'm still investigating the issue.

**Comment by shsagir** [comment]
@nisinha, @grawcho Thanks for the update. Since there is not doc change at this time I'm closing the issue. Please open a PR if your investigation required a docs change.

#please-close
