### ISSUE TITLE
The Render page should have examples of rendering each chart.

### ISSUE THREAD

**Issue by 1RedOne** [MicrosoftDocs/dataexplorer-docs#658]
For instance, the `linechart` type is only listed in the example, and isn't mentioned as a valid option in the body of this document at all.  

It would be super cool if each option where there, with one or two examples of each.  Maybe even make those subpages?  Rendering charts is very powerful, so people will get lost and need help, IMHO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your feedback, @1RedOne  . This has been assigned to the content owner, @orspod , and will be updated as appropriate.

**Comment by YaelSchuster** [comment]
Thanks, @1RedOne for your feedback. I agree that this would help users greatly. I've created a work item to follow up on this in our next sprint. https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1834229
As such, I'm going to close the issue at this time. Please continue to reach out with ideas and improvements!

**Comment by YaelSchuster** [comment]
#please-close
