### ISSUE TITLE
Add section on how Data Explorer authorizes against Event Hub

### ISSUE THREAD

**Issue by m2000ank** [MicrosoftDocs/dataexplorer-docs#66]
In the "Connect to the event hub" section above, nothing is said about how the Data Explorer cluster gets authorization to read from the event hub. Testing a simple setup, I have found that ingestion seems to work without having assigned a managed identity to Data Explorer (to be able to assign to it the "Azure Event Hubs Data Receiver" role) and without having created "Listen" authorization rules on the event hubs. Unless there is some internal magic going on, I can only assume that the "RootManageSharedAccessKey" from the event hub name space is used, but I would very much like to know with certainty how this actually works. Could you please add a little about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5808ed2-5d09-4c56-dc0b-4e3650f8fc16
* Version Independent ID: ba034a8d-d5bb-6ea4-e61b-74ea3a5eb2be
* Content: [Ingest data from Event Hub into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub#feedback)
* Content Source: [data-explorer/ingest-data-event-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-hub.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@m2000ank thanks for your feedback.
@kerend are you able to assist?

**Comment by basaba** [comment]
Yes it is using "RootManageSharedAccessKey"

**Comment by orspod** [comment]
@basaba - thanks for your assistance. @m2000ank - does that answer your question?

**Comment by m2000ank** [comment]
Yes it does, thank you @orspod and @basaba. However, since this is a very implicit dependency, I would appreciate it being mentioned in the documentation as well. What happens if that key is rotated, for instance? Is intervention necessary on the Data Explorer side, or will it sort itself out in some way?

**Comment by orhasban** [comment]
Hi @m2000ank ,
In case of key rotation, the best practice is to update the data connection (using ARM template for example) with the exact same properties (actually you don't update any property but to process trigger re-fetching of the new keys).
In addition, we plan to support managed identity based data connection for better security of our customers' data sources (we wouldn't hold EH keys in that scenario). The customer would grand the managed identity Read permission.
Unfortunately, there is no ETA yet.

**Comment by orspod** [comment]
@m2000ank hope this answers your question

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@m2000ank  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.

**Comment by kerend** [comment]
Hi @m2000ank, In case of key rotation, you should rotate in 2 steps, with interval of few hours in between. Our service will pickup the first rotation and will auto update the connection and fetch the new keys. During this time the connection works with the secondary key.
After the second rotation, same process is done and we end up with 2 fresh keys.
I will add this explanation to the docs.

**Comment by m2000ank** [comment]
Hi, everyone. Sorry for the late reply, and thanks for the details on key rotation. Looking forward to be able to use managed identity for this.
