### ISSUE TITLE
Kusto code analyzer doesn't show anything even when pressing ctrl + f6 as mentioned in document

### ISSUE THREAD

**Issue by msft-edluo** [MicrosoftDocs/dataexplorer-docs#661]
I tried using ctrl+F6 to run a query analysis on my Kusto code but it didn't seem to do anything. Is there a specific version I need to run this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2774c8d6-b082-154c-31eb-4341d8884b52
* Version Independent ID: abdcdbb0-f34d-61d6-6d22-262f262aaee8
* Content: [Kusto Explorer Code Analyzer - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer-code-analyzer)
* Content Source: [data-explorer/kusto/tools/kusto-explorer-code-analyzer.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/kusto-explorer-code-analyzer.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@msft-edluo 
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by KranthiPakala-MSFT** [comment]
@msft-edluo I have escalated this to Product team and awaiting response. Will keep you posted once we have a response. 

Thanks for bringing this to our notice.

**Comment by KranthiPakala-MSFT** [comment]
Hi @msft-edluo I have escalated this to ADX product team and below is the update

"We have made a change in KE that now Code Analysis is “called” Issues – and the tab is constantly present on the screen.
We will return Ctrl+F6 hot-key to make Issues tab active + change docs to reflect the change."

As product is working on a doc fix, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thank you
