### ISSUE TITLE
limitations of .show not clear

### ISSUE THREAD

**Issue by nbfowler** [MicrosoftDocs/dataexplorer-docs#664]
Your doc makes it clear that 

> `principals`	Can appear only as part of a `.show` verb; returns the list of principals that can affect the securable object

What it does not make clear is that `principals` is the _only_ role that seems to work with `.show` verb. This is a basic omission that is _not_ at all inferable from the above.

A → B does not equate to B → A.

Please make it clear what can or can't be used with the `.show` verb and any other limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4526aa53-827b-abf4-d419-cea51c79c71b
* Version Independent ID: 73682729-2e9a-216f-5fb5-8e887ef93df2
* Content: [Security roles management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/security-roles)
* Content Source: [data-explorer/kusto/management/security-roles.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/security-roles.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@nbfowler 
Thanks for the feedback! We have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @nbfowler you are correct. the `.show` command can only be used with principals. Principals can only be used in the `.show` command, as it is not really a role. I have added a work item to update this document accordingly.

**Comment by YaelSchuster** [comment]
I'm going to close this Issue at this time. Please feel free to reach out with any other questions and/or doc improvements. Thanks for being part of our community!

#please-close
