### ISSUE TITLE
Database user role doesn't seem to have permissions to create functions

### ISSUE THREAD

**Issue by noellelc** [MicrosoftDocs/dataexplorer-docs#667]
When attempting to execute `.create-or-merge function` commands using a service principal with the Database User role, I got a 403 permission denied; when I granted that same principal the Database Admin role, the function creation was executed successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143622e5-86cc-6eeb-f9b8-c53336867149
* Version Independent ID: ddda3c76-6945-5c73-6acd-c0d8b4a64c75
* Content: [Manage database permissions in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/manage-database-permissions)
* Content Source: [data-explorer/manage-database-permissions.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/manage-database-permissions.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by YaelSchuster** [comment]
@himanshusinha-msft this seems to be a product question, not a docs question.

**Comment by YaelSchuster** [comment]
@noellelc do you mean the `.create-merge` function? Are you trying to merge an existing table? If you do not have permissions on an existing table, you will not be able to execute this command.

**Comment by noellelc** [comment]
No, I am referring to the `.create-or-alter function` function to be able to actually create or update functions on a Kusto database (I don't believe functions are associated with tables). The "Roles and permissions" table on the docs page suggests that a Database User role would have the ability to create functions, but I believe a principal should actually be assigned to the Database Admin role to actually be able to create or update functions on the database.

**Comment by YaelSchuster** [comment]
@noellelc Ah, ok now I understand your question. I've checked with product, and creating functions should work with database user, as documented. If this isn't working for you, you'll need to [create a support ticket](https://ms.portal.azure.com/#create/Microsoft.Support).

If you have any further docs issues, please feel free to reach out!

#please-close
