### ISSUE TITLE
Where does  ```new UserAssertion(customerAadWebApplicationToken)).GetAwaiter().GetResult();``` come from?

### ISSUE THREAD

**Issue by bobbytreed** [MicrosoftDocs/dataexplorer-docs#673]
I cannot see where the variable  **customerAadWebApplicationToken** comes from in:
```
new UserAssertion(customerAadWebApplicationToken)).GetAwaiter().GetResult();
```

Could you please elaborate, or am I missing something obvious? If so, apologies.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee89d0d7-becd-83f4-b862-f39b1c1ad6d4
* Version Independent ID: d40d3446-9677-dbdc-faa9-f04a30ffb042
* Content: [Kusto authenticate with AAD for access - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad?source=docs)
* Content Source: [data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by vladikbr** [comment]
The sample has a title "Step 2: Perform token exchange in your server code", which indicates this is the token your web app receives for the logged in user.

**Comment by shsagir** [comment]
@vladikbr Thanks for responding. We've submitted a documentation change based on your information, and the updated article should be live by tomorrow.
@bobbytreed If you need to follow up on this issue, leave us a comment with an @mention

#please-close
