### ISSUE TITLE
No more option for "File Begin With"

### ISSUE THREAD

**Issue by dckfnuance** [MicrosoftDocs/dataexplorer-docs#674]
For one-click ingestion from ADLS gen2 container, we used to be able to specify what the filename begins with. It was working fine 2 weeks ago. Now the option to specify "File begins with" is no longer there. Why was the option removed??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567e6ac5-f63b-e3a8-6a57-763563436ae5
* Version Independent ID: 438ba708-c111-a69e-2d57-21afe53413a4
* Content: [Use one click to ingest data from a container or Azure Data Lake Storage into Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/one-click-ingestion-new-table)
* Content Source: [data-explorer/one-click-ingestion-new-table.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/one-click-ingestion-new-table.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Hi @dckfnuance, 

Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by KranthiPakala-MSFT** [comment]
Hi @dckfnuance, I have reached out to product team to double check on this change in behavior. Will get back to you as soon as we have an update from the team. 

Thank you

**Comment by KranthiPakala-MSFT** [comment]
Hi @dckfnuance Product team confirmed that there has a been a recent change made to UX which is why there is no more option for "File Begin With". Product and content team are working on an internal work item to update the document with updated functionality.

Hope this info helps. Do let us know if you have further query.

**Comment by YaelSchuster** [comment]
@dckfnuance I'll sync with the product team to update the docs according to the new UI. I'm going to close this PR at this time, @KranthiPakala-MSFT thanks for your work tracking down this problem!

**Comment by YaelSchuster** [comment]
#please-close
