### ISSUE TITLE
The plug-in function 'ipv4_lookup' is not defined.

### ISSUE THREAD

**Issue by hugovoerman** [MicrosoftDocs/dataexplorer-docs#676]
When I try to do the examples on this page, in the Azure Data Explorer website as well as in Kusto Explorer I get the message: "The plug-in function 'ipv4_lookup' is not defined."

How do I define this plugin?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da5e53c6-7e59-9af7-9b2d-83de3f299fa3
* Version Independent ID: 5610b619-82ae-963e-71a6-c8cffc42a495
* Content: [ipv4_lookup plugin - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/ipv4-lookup-plugin)
* Content Source: [data-explorer/kusto/query/ipv4-lookup-plugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/ipv4-lookup-plugin.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@hugovoerman Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaurabhSharma-MSFT** [comment]
@hugovoerman Are getting this error while executing the function ?  I am able to execute it both on Kusto Explorer and on web versions.
![image](https://user-images.githubusercontent.com/38112130/116598058-3d9dfb80-a8db-11eb-9e04-908dcaf4318e.png)

**Comment by SaurabhSharma-MSFT** [comment]
@hugovoerman ok, I see it but I agree it is confusing.  I will internally provide this information to products team. Thanks for your feedback.

**Comment by SaurabhSharma-MSFT** [comment]
@hugovoerman We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by rstanilewicz** [comment]
It's still not fixed, and it's still confusing...
