### ISSUE TITLE
Syntactically wrong Kusto example

### ISSUE THREAD

**Issue by chriswue** [MicrosoftDocs/dataexplorer-docs#680]
The example code

    set query_datascope="hotcache";
    T | union U | join (T datascope=all | where Timestamp < ago(365d) on X

Is either missing the closing bracket - closing the one opened in `join (` - or the opening bracket after `join` is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e81a2cf-15af-04b4-f09b-1ffdda66e4f9
* Version Independent ID: f1eeb141-cffa-3d81-3ff7-c586fda1a00f
* Content: [Cache policy (hot and cold cache) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/cachepolicy)
* Content Source: [data-explorer/kusto/management/cachepolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/cachepolicy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@chriswue  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
@chriswue, thanks for noticing this. You are correct, it is missing the closing bracket before the word "on". I have opened a PR to fix this in the docs.

**Comment by YaelSchuster** [comment]
#please-close
