### ISSUE TITLE
Elaborate on allowable column syntax

### ISSUE THREAD

**Issue by mmannion** [MicrosoftDocs/dataexplorer-docs#685]
I'm just learning Kusto for the first time, and in the context of the Azure Resource Graph Explorer.

From what I can tell so far, most of the useful queries for me will include some sort of "special" column syntax. For example, for the `project` operator, I may have something like:

`project ['MyProperty'] = properties['someProperty']`

I can't seem to figure out the proper syntax sorting by a column like this. I've tried:

`order by MyProperty`
`order by properties['someProperty']`
`order by properties.someProperty`
`order by 4`

(where "4" is the column position in the project operator)

None have worked (although the column alias does work with the `where` operator).

It would be helpful for this doc page to elaborate on what is and isn't allowed for the `order by` operator's `column` argument.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f01ec0-f05e-3df0-6e70-1089542a03d6
* Version Independent ID: 3cbe9447-afe9-36c5-2bde-09807649973d
* Content: [order operator  - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/orderoperator)
* Content Source: [data-explorer/kusto/query/orderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/orderoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@mmannion 
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
Hi @mmannion, I haven't heard back from you in two days. I'm going to close this issue at this time. If you have any further questions, please feel free to @mention me.

#please-close
