### ISSUE TITLE
Unhelpful example

### ISSUE THREAD

**Issue by joel74** [MicrosoftDocs/dataexplorer-docs#686]
This page has the exact same sample as the stdev() and stdevif() pages. It would be beneficial to have more relevant examples and/or explain more about these variants. It's not clear at all how adding a population alters the output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b731fd3c-718f-6048-6ee6-84122f353522
* Version Independent ID: 23210036-8261-ede0-80fa-2c816d30686d
* Content: [stdevp() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/stdevp-aggfunction)
* Content Source: [data-explorer/kusto/query/stdevp-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/stdevp-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@joel74 
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by YaelSchuster** [comment]
@joel74 You'd want to use whichever standard deviation is relevant for your data. Is your data set just a small sample of the population or is it the entire population? I'll add a work item to clarify this in the docs. 

Feel free to reach out with any further questions!
I'm going to close this issue at this time. 
#please-close

**Comment by joel74** [comment]
I think you've completely missed the point. I want an example that's useful for anyone.
