### ISSUE TITLE
trouble import with .import data that I exported with .export

### ISSUE THREAD

**Issue by GeorgeJoy** [MicrosoftDocs/dataexplorer-docs#687]
I am trying to use .export to export a table to Azure blob and then .import to import the table into a table. 
This seems like it should work easily but I'm not having success. There should be a simple example to show how to do this.
The errors are vague like 'Invalid Blob'. In one case I get a 'stream too long' error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4cba9e-9d0a-0650-317a-09806b9bb29e
* Version Independent ID: f7fa7b58-5735-96e2-ce45-1659232579dd
* Content: [Export data to storage - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-export/export-data-to-storage?source=docs)
* Content Source: [data-explorer/kusto/management/data-export/export-data-to-storage.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-export/export-data-to-storage.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
Hi @GeorgeJoy, thanks for reaching out. Can you please clarify, are you trying to then ingest data back into an Azure Data Explorer cluster? What ingestion method are you using? There is no `.import` command for ingesting data in Azure Data Explorer. Perhaps do you mean the `.ingest` [ingest from storage](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-from-storage)?

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@GeorgeJoy Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by GeorgeJoy** [comment]
Hi @CHEEKATLAPRADEEP-MSFT,
I returned back to this again. The code snippet is below:
.export async compressed to parquet 'https://stn.blob.core.windows.net/kustobackup?sv=2020-04-08&st=2021-05-31T06%3A11%3A19Z&se=2021-07-01T06%3A11%3A00Z&sr=c&sp=racwl&sig=XXX'
with (namePrefix=parquetpatients, fileExtension=parquet) <|phidocument

.ingest into table tempdocs 'https://stn.blob.core.windows.net/kustobackup/parquetpatients_1_88c60187376a4374be30f6fa0a7c6119.gz.parquet?sv=2020-04-08&st=2021-05-31T06%3A34%3A11Z&se=2021-06-01T06%3A34%3A11Z&sr=b&sp=r&sig=YYY'

The export succeeds and creates a blob file which I then proceed to try and import in the second line into a separate table called tempdocs (which already exists).

I get the following errors:

"OperationId": c3af2c8a-f109-4172-94be-75d0b40e073f,
"Database": deidpatientsm1,
"Table": tempdocs,
"FailedOn": 2021-05-31T06:51:26.9248833Z,
"IngestionSourcePath": https://stn.blob.core.windows.net/kustobackup/parquetpatients_1_88c60187376a4374be30f6fa0a7c6119.gz.parquet,
"Details": BadRequest_InvalidBlob: OS Error -2146233088 (FormatMessageW() returned error 15105) (os error -2146233088),
"FailureKind": Permanent,
"RootActivityId": c2662e75-cd59-43bd-bc71-e14598a7f6c8,
"OperationKind": DataIngestPull,
"OriginatesFromUpdatePolicy": 0,
"ErrorCode": BadRequest_InvalidBlob,
"Principal": aaduser=xxx,
"ShouldRetry": 0,
"User": ,
"IngestionProperties": [Format=Csv/not-mandatory, IngestionMapping=[ToStringEmpty], ValidationPolicy=[Options=ValidateCsvInputConstantColumns, Implications=BestEffort, IsDetailedErrorReportingEnabled=False], Tags=[ToStringEmpty], IngestIfNotExists=[ToStringEmpty], ZipPattern=[null]],

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@YaelSchuster Could you please look into this issue?

**Comment by GeorgeJoy** [comment]
Let me know if you prefer creating as a new issue.

**Comment by GeorgeJoy** [comment]
Opened #701 
You can ignore this one
