### ISSUE TITLE
Missing await for IngestFromStorageAsync

### ISSUE THREAD

**Issue by grik001** [MicrosoftDocs/dataexplorer-docs#689]
Hi you are missing **await** in your IngestFromStorageAsync example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d5f8ab-85c7-19bf-d91a-e76e81c76d7b
* Version Independent ID: 161a10d8-fc7f-97e8-b13e-0ddc7dd4f3c6
* Content: [Ingest JSON formatted data into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language)
* Content Source: [data-explorer/ingest-json-formats.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-json-formats.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
This has been addressed by the Issue author by opening a public PR https://github.com/MicrosoftDocs/dataexplorer-docs/pull/690

#please-close
