### ISSUE TITLE
clarification on external-tables

### ISSUE THREAD

**Issue by ldayananda** [MicrosoftDocs/dataexplorer-docs#692]
One of the limitations of external-tables are mentioned as:

> Data purge isn't applied on external tables. Records are never deleted from external tables

Does this mean `.purge` commands specifically or does this apply to the blobs that the external-table is referencing also? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: defaea13-e35e-6b8f-7c7a-f876ff50aea5
* Version Independent ID: f249e415-a2ff-c8d7-3ee0-09fc00b5ae08
* Content: [External tables - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/externaltables)
* Content Source: [data-explorer/kusto/query/schema-entities/externaltables.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/schema-entities/externaltables.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@ldayananda 
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by MartinJaffer-MSFT** [comment]
The way I understand it, an External Table, is a mapping that connects the concept of a Table in Kusto, to a data store outside Kusto / Data Explorer.

Hypothetically, if we wanted to purge a record from an external table, one of two things would need to happen.
- The blob / file / SQL table would need to be edited.  Data erased and re-written.
- If the blob is not edited, then Data Explorer would need to manage a record of rows to pretend do not exist.

Given the statement:
> Unlike tables, data is stored and managed outside the cluster. Most commonly the data is stored in some standard format such as CSV, Parquet, Avro, and isn't ingested by Azure Data Explorer.

Neither of the two hypotheticals is the case.  The original blob is not edited by Data Explorer.  Data Explorer does not manage the data.  Ingestion would be required to keep a record of rows to ignore.

So my answer is that `.purge` commands do not edit the blobs the external table references.  They also do not change the external table that looks at them.

Does this answer your question @ldayananda ?

**Comment by MartinJaffer-MSFT** [comment]
We will now proceed to close this thread as we have not heard back from you. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

**Comment by ldayananda** [comment]
Thank you for your response! That answers my question.
