### ISSUE TITLE
Typo on this page: deafults should be defaults

### ISSUE THREAD

**Issue by Leybl** [MicrosoftDocs/dataexplorer-docs#7]
Typo on this page: deafults should be defaults

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19a65aa5-0a6b-9916-e201-45fb67154e30
* Version Independent ID: e68aa06e-8811-a52b-8629-ffe7ada9accf
* Content: [Embed Web UI in an iframe - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/monaco/host-web-ux-in-iframe#feedback)
* Content Source: [data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by orspod** [comment]
@Leybl - thanks for your feedback. The following PR was created to fix the issue: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/25 
I will now close the issue.
