### ISSUE TITLE
Unclear how to ingest an exported table from Azure Blob Storage

### ISSUE THREAD

**Issue by GeorgeJoy** [MicrosoftDocs/dataexplorer-docs#701]
Are there some missing steps in the process I am following?

The code snippet is below:
.export async compressed to parquet 'https://stn.blob.core.windows.net/kustobackup?sv=2020-04-08&st=2021-05-31T06%3A11%3A19Z&se=2021-07-01T06%3A11%3A00Z&sr=c&sp=racwl&sig=XXX'
with (namePrefix=parquetpatients, fileExtension=parquet) <|phidocument

.ingest into table tempdocs 'https://stn.blob.core.windows.net/kustobackup/parquetpatients_1_88c60187376a4374be30f6fa0a7c6119.gz.parquet?sv=2020-04-08&st=2021-05-31T06%3A34%3A11Z&se=2021-06-01T06%3A34%3A11Z&sr=b&sp=r&sig=YYY'

The export succeeds and creates a blob file which I then proceed to try and import in the second line into a separate table called tempdocs (which already exists).

I get the following errors:

"OperationId": c3af2c8a-f109-4172-94be-75d0b40e073f,
"Database": deidpatientsm1,
"Table": tempdocs,
"FailedOn": 2021-05-31T06:51:26.9248833Z,
"IngestionSourcePath": https://stn.blob.core.windows.net/kustobackup/parquetpatients_1_88c60187376a4374be30f6fa0a7c6119.gz.parquet,
"Details": BadRequest_InvalidBlob: OS Error -2146233088 (FormatMessageW() returned error 15105) (os error -2146233088),
"FailureKind": Permanent,
"RootActivityId": c2662e75-cd59-43bd-bc71-e14598a7f6c8,
"OperationKind": DataIngestPull,
"OriginatesFromUpdatePolicy": 0,
"ErrorCode": BadRequest_InvalidBlob,
"Principal": aaduser=xxx,
"ShouldRetry": 0,
"User": ,
"IngestionProperties": [Format=Csv/not-mandatory, IngestionMapping=[ToStringEmpty], ValidationPolicy=[Options=ValidateCsvInputConstantColumns, Implications=BestEffort, IsDetailedErrorReportingEnabled=False], Tags=[ToStringEmpty], IngestIfNotExists=[ToStringEmpty], ZipPattern=[null]],

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae4cba9e-9d0a-0650-317a-09806b9bb29e
* Version Independent ID: f7fa7b58-5735-96e2-ce45-1659232579dd
* Content: [Export data to storage - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-export/export-data-to-storage?source=docs)
* Content Source: [data-explorer/kusto/management/data-export/export-data-to-storage.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-export/export-data-to-storage.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@GeorgeJoy Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

@YaelSchuster Could you please look into this issue?

**Comment by vladikbr** [comment]
@GeorgeJoy , the article you reference only talks about export to storage.
Ingest from storage is explained in https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-from-storage and this article mentions and links to the document covering "ingestion properties".
In your case what's missing is format specification. Please let us know if you think the article on ingestion from storage is not informative enough

**Comment by GeorgeJoy** [comment]
thanks for the response. I tried creating an ingestion mapping and using that and also specifying format="parquet" as below. I am still getting error BadRequest_InvalidBlob. I guess I'm looking for a way to serialize a table1 into Azure Blob and later ingest it into another table2. I expect table2 to be identical to table1.
```
.ingest async into table tempdocs 
h'https://stdxx.blob.core.windows.net/kustobackup/parquetpatients_1_88c60187376a4374be30f6fa0a7c6119.gz.parquet?sv=2020-04-08&st=2021-06-05T12%3A16%3A02Z&se=2021-07-06T12%3A16%3A00Z&sr=b&sp=r&sig=xxx'
with ( format="parquet", ingestionMappingReference = "ParquetMapping")
```

**Comment by ohadbitt** [comment]
hi
can you try naming the files *.parquet.gz 
and try again?

**Comment by GeorgeJoy** [comment]
@ohadbitt , tried that and got similar error. Reported full errror from _.show ingestion failures_ below (xx modified for privacy):
```
"OperationId": 587df0e8-fd64-48e9-9577-85d015b519b5,
"Database": deidpatientsm1,
"Table": tempdocs,
"FailedOn": 2021-06-08T12:03:07.308657Z,
"IngestionSourcePath": https://stxx.blob.core.windows.net/kustobackup/parquetpatients_1_8xx.parquet.gz,
"Details": BadRequest_InvalidBlob: HResult: 0x80131501, source: (OS Error -2146233088 (FormatMessageW() returned error 15100) (os error -2146233088)),
"FailureKind": Permanent,
"RootActivityId": 96bd7814-7704-49d6-a0a3-9fc7cbeb96f1,
"OperationKind": DataIngestPull,
"OriginatesFromUpdatePolicy": 0,
"ErrorCode": BadRequest_InvalidBlob,
"Principal": aaduser=xxx,
"ShouldRetry": 0,
"User": ,
"IngestionProperties": [Format=Parquet/mandatory, IngestionMapping=[{"column":"PatientId","datatype":"","Path":"$.PatientId"},{"column":"SourceHCSName","datatype":"","Path":"$.SourceHCSName"},{"column":"InstanceId","datatype":"","Path":"$.InstanceId"},{"column":"lastModified","datatype":"","Path":"$.LastModified"},{"column":"Birth","datatype":"","Path":"$.Birth"},{"column":"PersonDetailChange","datatype":"","Path":"$.PersonDetailChange"},{"column":"Diagnosis","datatype":"","Path":"$.Diagnosis"},{"column":"RiskAssessment","datatype":"","Path":"$.RiskAssessment"},{"column":"MedicationExposure","datatype":"","Path":"$.MedicationExposure"}], ValidationPolicy=[Options=ValidateCsvInputConstantColumns, Implications=BestEffort, IsDetailedErrorReportingEnabled=False], Tags=[ToStringEmpty], IngestIfNotExists=[ToStringEmpty], ZipPattern=[null]],
```

**Comment by yogilad** [comment]
The server side reports the gzip stream is invalid:
```
Error GZIP header, first magic byte doesn't match
ICSharpCode.SharpZipLib.GZip.GZipException: Error GZIP header, first magic byte doesn't match
```

Are you sure the parquet zip stream is valid?
Can you get the file and decompress it?

**Comment by GeorgeJoy** [comment]
@yogilad - the last experiment suggested by @ohadbitt renamed the file from *.gz.parquet to *.parquet.gz. I am guessing that's why the GZIP exception resulted.  (By the way, are you getting that extended error by looking up the operationId on the ADX back-end?)

**Comment by ohadbitt** [comment]
Hello
Could you please provide us with a sample file failing ingestion

**Comment by YaelSchuster** [comment]
@georgejoy ping on the above question from Ohad

**Comment by GeorgeJoy** [comment]
> Hello
> Could you please provide us with a sample file failing ingestion

I will try to reproduce with a non-sensitive workload

**Comment by GeorgeJoy** [comment]
While doing some more experiments to extract a sample file, I found that a parquet file exported from a smaller data set (20K rows instead of the full 42K rows) can be successfully imported.
.```
export async compressed to parquet 
with (namePrefix=phisample10k, fileExtension=parquet) <| phidocument take 20000
```

So maybe if the blob is over a certain size ADX cannot import it using .ingest? It would be good if this threshold was documented.

**Comment by ohadbitt** [comment]
hi 
can you still provide us with a file that fails ingestion ?

**Comment by ohadbitt** [comment]
The error doesnt indicates it was an issue with the size - therefore we are asking for the file for more investigation.
Anyway you can limit the size of an exported file (sizeLimit):
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-export/export-data-to-storage

Read here the answer and referred docs for more info on size limitation
https://stackoverflow.com/questions/61276069/increase-the-maximum-file-size-to-be-ingested-in-the-azure-data-explorer-adx-k

**Comment by YaelSchuster** [comment]
We have not heard back from the customer in 6 days. This is clearly a product question, not a docs issue.
#please-close
