### ISSUE TITLE
validationpolicy not documented

### ISSUE THREAD

**Issue by GeorgeJoy** [MicrosoftDocs/dataexplorer-docs#705]
https://docs.microsoft.com/en-us/azure/data-explorer/ingestion-properties describes validationpolicy as one of the ingestion properties but I couldn't find the documentation for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24976a2-7a69-d602-31b4-30edf29aa03d
* Version Independent ID: 54a01e38-ce8c-dc77-bc88-e89237dd8308
* Content: [Data ingestion properties for Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingestion-properties)
* Content Source: [data-explorer/ingestion-properties.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingestion-properties.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by GiftA-MSFT** [comment]
@GeorgeJoy we'll review your feedback and get back to you shortly. Thanks.

**Comment by shsagir** [comment]
@GeorgeJoy Thanks for your feedback. This property is in the process of being deprecated and will the topic will be updated when it's done. In the meantime, I'm closing this issue.
Thanks again for bringing this to our attention.
#close

**Comment by YaelSchuster** [comment]
#please-close
