### ISSUE TITLE
How do I set the query_parameters when using the Kusto Web Explorer?

### ISSUE THREAD

**Issue by johnib** [MicrosoftDocs/dataexplorer-docs#710]
I'm looking for a way to use `declare query_parameters` in KWE, and still be able to provide the parameters' values.
In Kusto Explorer it is possible via ALT+P -- I'm wondering if it's possible via KWE as well somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f989c5-4b98-697a-7db0-95e77ad43402
* Version Independent ID: e919ef27-4304-bb33-3eea-7264f885ca76
* Content: [Query parameters declaration statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/queryparametersstatement)
* Content Source: [data-explorer/kusto/query/queryparametersstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/queryparametersstatement.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Svijay-msft** [comment]
Thanks for the question! We are looking into this and will get back to you soon.

**Comment by izikl** [comment]
@johnib Unfortunately, at the moment, this is not supported in Kusto.WebExplorer.

**Comment by KranthiPakala-MSFT** [comment]
Thank you @izakl for the update. 

@johnib As it is not supported currently, we request you to please log a feature request item in User voice forum - https://feedback.azure.com/forums/915733-azure-data-explorer

We will now proceed to close this thread as we have not heard back from you. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.

Thank you
