### ISSUE TITLE
Cannot Add-Type for Kusto.Data.dll with Powershell

### ISSUE THREAD

**Issue by ShakeySnake** [MicrosoftDocs/dataexplorer-docs#713]
Problem with running the steps here for Add-Type. Getting an error for missing dependencies that are not installed with the package.

```
PS C:\Users> Add-Type -LiteralPath "C:\Program Files\PackageManagement\NuGet\Packages\Microsoft.Azure.Kusto.Tools.5.2.0\tools\Kusto.Data.dll"
Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. 
At line:1 char:1 
+ Add-Type -LiteralPath "C:\Program Files\PackageManagement\NuGet\Packa ... 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
   + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException     
   + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeCommand

PS C:\Users> $error[0].Exception.GetBaseException().LoaderExceptions
Could not load file or assembly '**Microsoft.WindowsAzure.Security.Authentication**, 
Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The system cannot find the file specified.

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2df80c7-1cca-9c8d-0ed5-05b387e1850f
* Version Independent ID: d3f5e3ed-dc62-ca1a-c821-4ca25453fa0f
* Content: [Kusto .NET Client Libraries from PowerShell - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell)
* Content Source: [data-explorer/kusto/api/powershell/powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/powershell/powershell.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by YaelSchuster** [comment]
Hi @ShakeySnake 
Response from product team:
Are you trying to do dSTS authentication?

dSTS authentication using Kusto.Tools requires manual download of the dSTS binaries as we are not allowed to ship them with the package.

Please try this and let me know if it solves your problem.

**Comment by YaelSchuster** [comment]
Hi @ShakeySnake - ping on the above question

**Comment by YaelSchuster** [comment]
Since we haven't heard from the customer in over 3 days, I'm going to proceed to close this issue.
@shakeysnake if you have further questions or problems, please feel free to reach out to us by @ mention my alias on this issue, or open a new issue. Thanks!

#please-close

**Comment by ShakeySnake** [comment]
@YaelSchuster Could we have 3 business days to respond before closing things out. I'm not sure what the product team wants me to try here. The steps I'm asking about are simply trying to get the Add-Type step to work. If they would provide a pointer to the binaries or nugets required I could try that. 

Also, I'm not the only person having problems with this https://stackoverflow.microsoft.com/questions/262079.

**Comment by YaelSchuster** [comment]
#please-open
I will check and get back to you.

**Comment by vladikbr** [comment]
You need to retrieve the dSTS binaries yourself from dSTS feed (https://aka,ms/dsts)

**Comment by vladikbr** [comment]
#please_close
