### ISSUE TITLE
Note box on Authentication page is vague, need more info

### ISSUE THREAD

**Issue by mattboothman** [MicrosoftDocs/dataexplorer-docs#718]
Please elaborate the `Note` box at the bottom of the page. Documentation on `AadAuthorityUri` is almost non-existent.

For example, we have had major issues with executing deployment scripts that automate setting up Kusto. We want to add a Service Principal as a database admin. This randomly fails for no apparent reason. Kusto responds with 400 bad request - `entity is not valid and could not be retrieved from AAD. Entity ID '_correct SP App ID_' of type 'AAD Application Id' was not found in AAD tenant '_Correct AD Tenant ID_'.

Sometimes it succeeds, sometimes it doesn't.

We've tried adding a retry loop, every 30 seconds for 10 minutes. When it fails, it fails for 10 minutes, every time.

Could this environment variable be related?

What could be added:

- What behaviour to expect if `AadAuthorityUri` is not correctly set.
- Where to find documentation relating to `AadAuthorityUri`
- What is meant by "The Azure AD service endpoint changes when it runs in national clouds"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbfb57cf-cf3e-4f15-6a02-6dd9a95a7186
* Version Independent ID: 211c73fe-da11-64bd-3429-490fa310cce9
* Content: [Authentication over HTTPS - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/authentication)
* Content Source: [data-explorer/kusto/api/rest/authentication.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/rest/authentication.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@mattboothman  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by vladikbr** [comment]
1. We will improve the documentation.
2. Can you provide more details on the specific action that failed?
Were you really crafting REST requests or were you just trying to grant some principal access to your ADX resource?
3. 10 minutes cool-down is a service internal "negative cache" that is protecting the service from malicious DoS style attacks.
And if you create an SP, it takes some time for it to be resolveable in the directory.
So when you try to add permissions for a just added SP and get "unresolved/not found" error, it will get "locked" for 10 minutes.

**Comment by mattboothman** [comment]
> * We will improve the documentation.
Thank you
> * Can you provide more details on the specific action that failed?
It was a valid request:

Request Body:
```
{ "db": "ASA-Data-Explorer-DB-01", "csl": ".add database ['ASA-Data-Explorer-DB-01'] admins ('aadapp=53c329c5-0e54-4045-b3bf-1faca02bb916;example.com')" }
```
Request URI: `https://abc123xyz.eastus.kusto.windows.net/v1/rest/mgmt`

Request method is `POST` and valid Authorization header and value set.

>   Were you really crafting REST requests or were you just trying to grant some principal access to your ADX resource?

REST request, as above

> 10 minutes cool-down is a service internal "negative cache" that is protecting the service from malicious DoS style attacks.
> And if you create an SP, it takes some time for it to be resolveable in the directory.
> So when you try to add permissions for a just added SP and get "unresolved/not found" error, it will get "locked" for 10 minutes.

We must've misunderstood eachother.

I'm making valid requests to Kusto, with a valid access token. If I understand you correctly, Kusto will process the initial request but if it fails to resolve the AD object, it initiates a lock out for further requests for a period of 10 minutes but continue to respond to subsequent requests in the same way as the first, which is what we're seeing?

**Comment by vladikbr** [comment]
To execute the command .add database ['ASA-Data-Explorer-DB-01'] admins ('aadapp=53c329c5-0e54-4045-b3bf-1faca02bb916;example.com') ADX needs (after the command itself is authorized) to resolve the AAD entity that is the subject of the operation (not the actor). We cache failed resolutions in order to protect ourselves against attack by unresolved entities.

**Comment by shsagir** [comment]
@mattboothman Seems like your issue is resolved and therefore I'm closing it. To follow up on this issue, leave us a comment with an @mention. Please let us know if there's anything more we can do for you.

#please-close

**Comment by mattboothman** [comment]
@shsagir Apologies for the additional comment. I'm hoping this doesn't re-open the issue. I've worked around it.

@vladikbr that is a bonkers, paranoid, and irrational pattern, in all honesty. The caching mechanism wasted a huge amount of time. Kusto should be properly handling failures and responding with the appropriate HTTP status code and error message.

Make it property rate limit requests and return the correct error message so it doesn't waste anyone else's time.

## First request (failure)

Responds as normal with the addition of Retry-After header including the number of seconds the user needs to wait.

## Requests after failure but before retry-after expiry

- Respond with HTTP 429 Too Many Requests
- Respond with new error message describing the reson for rate-limit
- Include Retry-After header
- Reset timeout if required
