### ISSUE TITLE
Adicional information for TableFragmentType and "progressive frames"

### ISSUE THREAD

**Issue by cmasantos** [MicrosoftDocs/dataexplorer-docs#719]
Hi,

It would be good to have more information about the **TableFragmentType** **_DataReplace_** option, I couldn't find what does it mean. 

Also, I'm not sure what "**progressive frames**" really mean, is It all rows in a singles "dataFrame"? It would be really helpful to have aditional information here.

Thank you,
Carlos 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d40d9b6-61de-4770-b84d-f783c1cd3bae
* Version Independent ID: 8856d9e9-c57d-642e-4437-c10be83ca15b
* Content: [Query V2 HTTP response - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/response2)
* Content Source: [data-explorer/kusto/api/rest/response2.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/rest/response2.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by shsagir** [comment]
@cmasantos Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you.

Documentation change: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1967

#please-close
