### ISSUE TITLE
Best Practices on Setting TimeOut between PowerBI and Kusto

### ISSUE THREAD

**Issue by MRBreen** [MicrosoftDocs/dataexplorer-docs#72]
I've been struggling with the best way to increase Kusto's 4 minute default timeout and so far I have not been successful.

I've tried a few different ways...so I thought I'd ask for "Best practices of increasing the Kusto default timeout"  to be included in "Best Practices"

I have successfully increased the timeout in Kusto Explorer to 59 minutes and received data from a query that ran for 30 minutes.  I followed these instructions:
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits  
I use this "Query to PowerBI" button to move query from Kusto to PowerBI
https://docs.microsoft.com/en-us/azure/data-explorer/power-bi-imported-query
After pasting in PowerBI,  I see this in the Advanced Query window (note the two(2) instances of 59 representing 59 minutes)

",#"x-ms-app"="PowerQuery",#"properties"="{""Options"":{""servertimeout"":""00:59:00"",""query_language"":""csl""},""Parameters"":{},""ClientRequestId"":null,""Application"":null,""User"":null,""PrincipalIdentity"":null,""SecurityToken"":null,""AuthorizationScheme"":null,""RequestHostName"":null,""LocalClusterName"":null,""OriginClusterName"":null}"], Timeout=#duration(0,0,59,0)])),
    TypeMap = #table(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082142f3-9558-d472-c85b-459b956480a1
* Version Independent ID: 3beb35b6-5885-9367-9fc0-2c4fe6b7b824
* Content: [Query limits - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits)
* Content Source: [data-explorer/kusto/concepts/querylimits.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/concepts/querylimits.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ChiragMishra-MSFT** [comment]
@orspod Can you please review this ask?

**Comment by orspod** [comment]
@MRBreen thanks for your feedback.
@Gabilehner and @saguiitay can you assist with this question.

**Comment by orspod** [comment]
@Gabilehner and @saguiitay can you assist with this question.

**Comment by Gabilehner** [comment]
Hi MRBreen,

First I would recommend you move to Azure Data Explorer native connector to Power BI - https://docs.microsoft.com/en-us/azure/data-explorer/power-bi-connector
The native connector provides more flexibility as it allows also creating DirectQuery datasets and not just import datasets.
In addition, it is the main way to connect which means it is constantly updated and maintained.
The query you've pasted above should work, so we would like to take a closer look at it.
Please contact me directly with more details - gabil@microsoft.com

Thanks,
Gabi

**Comment by orspod** [comment]
@MRBreen - thanks for your feedback. I hope this resolves your issue.

**Comment by MRBreen** [comment]
@orspod Thanks.  I followed up with an email to @Gabilehner.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@MRBreen  We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.

**Comment by natasha-tahariya** [comment]
@MRBreen - were you able to resolve the issue ? and how ?
