### ISSUE TITLE
MSAL scopes and tokens

### ISSUE THREAD

**Issue by prbans** [MicrosoftDocs/dataexplorer-docs#721]
[Enter feedback here]

Hey Kusto team,
 
I am trying to use msal (@azure/identity) to do authentication in our NodeJS services
 
But I noticed in order to get a token, we need to provide scopes to the new API:

https://docs.microsoft.com/en-us/javascript/api/@azure/identity/chainedtokencredential?view=azure-node-latest
 
function getToken(scopes: string | string[], options?: GetTokenOptions)
 
Does anyone know what scopes I need to provide in order to do data-plane operations on Kusto? (Execute queries)
 
I tried looking online and found a few docs, but none refer to which scopes I need to provide:
https://stackoverflow.com/questions/67896084/generate-an-access-token-in-the-browser-that-is-scoped-to-kusto-azure-data-explo
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/authentication
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/
 
I reached out to the internal kusto help team, and they said I should use this as the scope:

```
You should provide {clusterUrl}/.default

For example: https://help.kusto.windows.net/.default
```

Could your team please update the REST documentation to say this is the scope users should provide if they are building REST api's using MSAL auth?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbfb57cf-cf3e-4f15-6a02-6dd9a95a7186
* Version Independent ID: 211c73fe-da11-64bd-3429-490fa310cce9
* Content: [Authentication over HTTPS - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/authentication)
* Content Source: [data-explorer/kusto/api/rest/authentication.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/rest/authentication.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by AjayKumar-MSFT** [comment]
@prbans, Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by yogilad** [comment]
Kusto is a V1 resource, so we accept the scope `URL/.default`

**Comment by vladikbr** [comment]
#close

**Comment by YaelSchuster** [comment]
#please-close
