### ISSUE TITLE
Please provide example calculating percentages by a field value

### ISSUE THREAD

**Issue by lygasch** [MicrosoftDocs/dataexplorer-docs#723]
Thank you for providing these examples, they are very helpful. 

I am trying to follow how to extend the data to report percentages, as in [this example](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/samples?pivots=azuredataexplorer#extend-a-table-by-a-percentage-of-the-total-calculation) but I have a further need to do that in hierarchy by another column value. 

Following along, I have a query like this

```kql
Table 
| where StartTime >= ago(5d)
| where Id == "myId" 
| project Col_1, Result
| where Col_1 in ("val 1", "val 2", "val 3")
| where Result in ("succeeded","failed")
| summarize count() by Col_1, Result
| as TheResults
| extend total = toscalar(TheResults | summarize sum(count_))
```
That gives me a result like:

| Col_1 | Result	 | count_	| total |
|-|-|-|-|
| val 1 |	succeeded	| 6 |	30 |
| val 2 |	succeeded | 16 | 30 |
| val 2 | failed | 2 |	30 |
| val 3 | succeeded	| 2 |	30 |
| val 1 |	failed	| 4	| 30 |

But what I want is more like
```kql 
| extend total = toscalar(TheResults | summarize sum(count_) by Col_1, Result)
```
I want output like

| Col_1 | Result	 | count_	| total |
|-|-|-|-|
| val 1 |	succeeded	| 6 |	(6+4=) 10 |
| val 2 |	succeeded | 16 | (16+2=) 18 |
| val 2 | failed | 2 |	(16+2=) 18 |
| val 3 | succeeded	| 2 |	2 |
| val 1 |	failed	| 4	| (6+4=) 10 |

But what I get under `total` is "val 1" for all rows.

What I really want to get is the percentage succeeded for each, val 1, val2 , val 3 so this is an intermediate attempt to get that figured out. And then what I really, really want is to be able to [bin them](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/samples?pivots=azuredataexplorer#perform-aggregations-over-a-sliding-window) so that I can see the success rate trend over time by week or month.

Can one of your experts provide such an example?
thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87ceffe2-e518-d7f5-6f1d-99cbf26dce9a
* Version Independent ID: 28ce08eb-3eac-ad19-e11f-a3fd754757ec
* Content: [Samples for queries in Azure Data Explorer and Azure Monitor](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/samples)
* Content Source: [data-explorer/kusto/query/samples.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/samples.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@lygasch Thank you for feedback. We are actively validating it. We will get back to you soon.

**Comment by ShaikMaheer-MSFT** [comment]
@Iygasch Thanks for the question. Github forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilise Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html)
