### ISSUE TITLE
kql queries for http and https traffic

### ISSUE THREAD

**Issue by ktom123** [MicrosoftDocs/dataexplorer-docs#725]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d046c47f-5e33-bff9-51fd-b8fa4905a260
* Version Independent ID: 49509522-8d22-75e4-8dc7-ec78ff83a045
* Content: [Query/management HTTP request - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/request)
* Content Source: [data-explorer/kusto/api/rest/request.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/rest/request.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@ktom123 
Thanks for reaching out. To better assist on your query, could you please elaborate a bit on your feedback/query?

**Comment by KranthiPakala-MSFT** [comment]
@ktom123 - Could you please provide few additional details about your feedback on this document so that we can further review and do necessary enhancements accordingly?

**Comment by KranthiPakala-MSFT** [comment]
We will now proceed to close this thread as we have not heard back from you. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.
