### ISSUE TITLE
'See also extend' does not have a link to the 'extend' operator section

### ISSUE THREAD

**Issue by searleser97** [MicrosoftDocs/dataexplorer-docs#726]
[Enter feedback here]

`See also extend` does not have a link to the 'extend' operator section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d21a5c6-ae80-52d0-7d06-43191081b656
* Version Independent ID: 799a41ab-2353-1bbc-8132-69eeb4678154
* Content: [Project operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/projectoperator)
* Content Source: [data-explorer/kusto/query/projectoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/projectoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
@searleser97  Thanks for noticing that! I've updated this link in the docs, and this change should go live in a few hours. 
https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/1995

#please-close
