### ISSUE TITLE
Zero retention period on source table when using update policy

### ISSUE THREAD

**Issue by fgheysels** [MicrosoftDocs/dataexplorer-docs#732]
I'm using an update-policy to ingest data to a table in Data Explorer (let's call it `table2`.   The source of this data is a table (`table1`) which gets it's data from an event-hub.
I only want to keep the data that exists in `table2`, so I specify a soft-delete period on `table1` as is told [here](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/updatepolicy#zero-retention-on-source-table) in the documentation.

It is stated:
> Set a soft-delete period of 0 in the source table's retention policy, and set the update policy as transactional.

However, when setting the soft-delete-period, you need to specify a time-unit as well.  Is it OK to set the soft-delete-period to `0s` in this case ? 

```kql
.alter-merge table table1 policy retention softdelete = 0s
```

I think this should be clarified in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26bac25c-c168-fadc-2491-651d35361512
* Version Independent ID: 608aa328-7799-1597-0940-4edec0b93e08
* Content: [Kusto update policy for data added to a source - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/updatepolicy#zero-retention-on-source-table)
* Content Source: [data-explorer/kusto/management/updatepolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/updatepolicy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@fgheysels  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by yonileibowitz** [comment]
> Is it OK to set the soft-delete-period to `0s` in this case ?
yes. any time unit would be fine.

**Comment by YaelSchuster** [comment]
A doc update has been made to reflect this change. Thanks @fgheysels for your contribution!
#please-close
