### ISSUE TITLE
ValidationError: Parameter 'Identity.type' can not be None.

### ISSUE THREAD

**Issue by Munyasya** [MicrosoftDocs/dataexplorer-docs#733]
Getting the above error when running the CLI
az kusto cluster create --cluster-name mycuster --sku name="Standard_D13_v2" tier="Standard" --resource-group AML-rg --location westeurope

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d75797a-c3c0-34e0-981e-8cc3b9f7d0f2
* Version Independent ID: 94c113bd-7fc8-1588-cb06-1e4471a863db
* Content: [Create an Azure Data Explorer cluster & DB with Azure CLI](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-cli)
* Content Source: [data-explorer/create-cluster-database-cli.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/create-cluster-database-cli.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@Munyasya  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

![image](https://user-images.githubusercontent.com/79183421/124454502-31845d80-dda6-11eb-8f9e-32bbf2e7c7fe.png)


@orspod Could you please review and update the cmdlet to create the Azure Data Explorer cluster?

**Comment by astauben** [comment]
Hi @Munyasya, 
We are working on fixing this issue. 
For now, may you please add '--type="None"' to your command? this should solve the issue. 

Thanks,
Assaf.

**Comment by shsagir** [comment]
@astauben Thx for responding.
@Munyasya Thanks for your feedback. As we understand it, you're describing a problem with the product itself and not with the product documentation. Therefore I am closing this issue.

Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention
#please-close
