### ISSUE TITLE
Average is not defined.

### ISSUE THREAD

**Issue by wandyezj** [MicrosoftDocs/dataexplorer-docs#735]
Average is a measure of central tendency. https://en.wikipedia.org/wiki/Average

What measure of central tendency is used for the `avg` formula?

Is this the mean? median? mode? A combination based on 'best fit'? Each measure of central tendency has it's own strengths and weaknesses, so it's important to know which is used.

Perhaps, this is a poor name for this method, and a more descriptive name could be used. In the mean time the documentation needs to make up for ambiguity caused by the name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29539902-bafe-e576-c61c-904d97521a75
* Version Independent ID: 995be722-d19d-562f-4797-345f5db43574
* Content: [avg() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/avg-aggfunction)
* Content Source: [data-explorer/kusto/query/avg-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/avg-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SatishBoddu-MSFT** [comment]
Hello @wandyezj 
I have assigned the issue to the content author for further review and update the doc as appropriate.

**Comment by YaelSchuster** [comment]
Hi @SatishBoddu-MSFT - Thanks for your question. The word 'average' as used here refers to the arithmetic mean, which has been updated in the docs.

#please-close
