### ISSUE TITLE
Incorrect property TraceUserName specified in the doc

### ISSUE THREAD

**Issue by dhnilang** [MicrosoftDocs/dataexplorer-docs#739]
In this document incorrect property (programmatic name of it) **TraceUserName** is specified , while the correct programmatic name is **UserNameForTracing**. This appears in '**User authentication properties**' section of the page. I have tested it with **Kusto.Data SDK 9.2.0**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2795f4-802e-754f-f325-00ebe5a2e5e1
* Version Independent ID: 1eee8c82-9f46-764f-429d-228071922d4a
* Content: [Kusto connection strings - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto)
* Content Source: [data-explorer/kusto/api/connection-strings/kusto.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/connection-strings/kusto.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MonikaReddy-MSFT** [comment]
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@dhnilang -  Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
