### ISSUE TITLE
ADX Cluster - Resiliency to failures

### ISSUE THREAD

**Issue by TechieWorld** [MicrosoftDocs/dataexplorer-docs#74]
Hi Team,

We have setup a two node cluster with AZs. We would like to know what else we can to make our design more resilient to failures?

Also, In case of failures, how long it would take to switch over the traffic from old node (current) to new node? Also, I want to know where data will be stored and would data store have any impact due to outage?

What will be the MTTR, MTBF, RTO and RPO in case of failures or incident?

Also, we have not seen any out of box support for BCDR scenario in the current ADX GA. Can you please suggest some design which might be followed by other folks.

Thanks,
Deepak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6bba86f-f473-368c-e517-c02e4635119c
* Version Independent ID: 66be4c19-ccf8-a0e2-31b1-95a9d677ba12
* Content: [What is Azure Data Explorer?](https://docs.microsoft.com/en-us/azure/data-explorer/data-explorer-overview)
* Content Source: [data-explorer/data-explorer-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/data-explorer-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ChiragMishra-MSFT** [comment]
@orspod Can you please have a look at this?

**Comment by orspod** [comment]
@TechieWorld - thanks for your feedback
@cosh will you assist with this question?

**Comment by cosh** [comment]
Hi Deepak,

BCDR: https://techcommunity.microsoft.com/t5/azure-data-explorer/azure-data-explorer-and-business-continuity/ba-p/1332767
RTP/RPO depends on the scenario you chose.
Some more detailled information: https://azure.microsoft.com/de-de/resources/azure-data-explorer/ (in a nutshell: data is always stored on underlying storage accounts and some of it is cached on the engine local disks. In case of a failure of an engine node another one will come up, cache the data from storage and will be ready to respond)

Cheers, Henning

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@TechieWorld  We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
