### ISSUE TITLE
Error in exemple

### ISSUE THREAD

**Issue by csmathon** [MicrosoftDocs/dataexplorer-docs#741]
the command "Add-Type -LiteralPath "$packagesRoot\Kusto.Data.dll"" fails all the time with the following error:
Could not load file or assembly 'Microsoft.WindowsAzure.Security.Authentication, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364
e35' or one of its dependencies. The system cannot find the file specified.

After contacting support, they told me to use:
[System.Reflection.Assembly]::LoadFrom("$packagesRoot\Kusto.Data.dll")

tested and it works (^_^)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2df80c7-1cca-9c8d-0ed5-05b387e1850f
* Version Independent ID: d3f5e3ed-dc62-ca1a-c821-4ca25453fa0f
* Content: [Kusto .NET Client Libraries from PowerShell - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/powershell/powershell)
* Content Source: [data-explorer/kusto/api/powershell/powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/powershell/powershell.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@csmathon  Thanks for the feedback! We are investigating and will update you shortly.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@orspod Could you please evaluate and update the document?

**Comment by vladikbr** [comment]
We are re-evaluating the PS integration documentation and will update the docs once we have a better version

**Comment by vladikbr** [comment]
#please-close
