### ISSUE TITLE
Is there a github link to this example?

### ISSUE THREAD

**Issue by algorithmlover2016** [MicrosoftDocs/dataexplorer-docs#742]
[Enter feedback here]
I find a problem that the codes are not incomplete on this page. Can we offer a github link to the complete  example codes?
For example, the response link of go version is https://github.com/Azure-Samples/Azure-Data-Explorer-Go-SDK-example-to-ingest-data.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae82ebd2-f7f6-5068-54f2-69c7532b6b38
* Version Independent ID: 4727dbed-4e17-879b-d494-6ee62d78633a
* Content: [Ingest data with Azure Data Explorer .NET SDK](https://docs.microsoft.com/en-us/azure/data-explorer/net-sdk-ingest-data)
* Content Source: [data-explorer/net-sdk-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/net-sdk-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@algorithmlover2016 You may checkout this article: [Ingest data using the Azure Data Explorer Go SDK](https://docs.microsoft.com/en-us/azure/data-explorer/go-ingest-data).

Hope this helps.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@algorithmlover2016  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by algorithmlover2016** [comment]
https://github.com/Azure/azure-kusto-samples-dotnet/blob/master/client/StreamingIngestionSample/Program.cs
https://github.com/Azure/azure-kusto-samples-dotnet
I think this is the answer that I'm looking for. I want get the complete examples codes. Thank you very much.
