### ISSUE TITLE
--type argument needed to launch cluster

### ISSUE THREAD

**Issue by jjadta** [MicrosoftDocs/dataexplorer-docs#743]
Hi,

I tried running the following CLI command to create a cluster based on the example command in the doc doc, but got the following error:

az kusto cluster create --cluster-name dataHistoryAdxCluster --sku name="Standard_D13_v2" tier="Standard" --resource-group dataHistoryTest --location westcentralus
Command group 'kusto' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Parameter 'Identity.type' can not be None.

I added 

--type SystemAssigned to the command and it worked.

Taylor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d75797a-c3c0-34e0-981e-8cc3b9f7d0f2
* Version Independent ID: 94c113bd-7fc8-1588-cb06-1e4471a863db
* Content: [Create an Azure Data Explorer cluster & DB with Azure CLI](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-cli)
* Content Source: [data-explorer/create-cluster-database-cli.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/create-cluster-database-cli.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@jjadta - 
Thank you for reaching out and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by shsagir** [comment]
Hi @jjadta ,
Thanks for your reporting the issue. We are working on a fix for this issue but in the meantime, you can resolve your immediate issue by adding **--type="None"** to your command.

As this is not an issue with the product documentation, I am closing this issue but please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention
#please-close
