### ISSUE TITLE
Link to timespan syntax

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/dataexplorer-docs#744]
This doc says that the argument to `ago(..)` is of type `a_timespan`, but it doesn't link to any docs to say what the syntax is.  The examples us `1d` and `1h`, but I want to know how to specify minutes and months. Only one of them can be `1m`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f89f5099-9596-787c-198e-cc5fcc2eb5aa
* Version Independent ID: 9cbf33f5-0698-131b-f2d5-11433e1d2392
* Content: [ago() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/agofunction)
* Content Source: [data-explorer/kusto/query/agofunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/agofunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@zivkan 
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by zivkan** [comment]
In the end, using the ToC search, I found that the docs for the timespan data type is: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan


The `ago()` function docs page should have a link to this page which is easy to find.  I suggest making the `a_timespan` work a link to the page.

**Comment by KranthiPakala-MSFT** [comment]
Hi @zivkan - I have submitted a PR to add link to the `timespan` doc reference. The changes should reflect within 24 hours. 
Appreciate much for the feedback and helping us to improve the doc content.

**Comment by KranthiPakala-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and reopen the issue. We will gladly continue the discussion.
