### ISSUE TITLE
Incorrect table header

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#748]
Incorrect table header at example _Using the 'by' clause_
The column headers must be swapped, make the first one be `isEvenSideCount `and the second `mylist`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa4efbc-144d-88d8-7032-20e8700e1725
* Version Independent ID: a693b1d8-ec33-971d-dc77-235cceae8481
* Content: [make_list() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/makelist-aggfunction)
* Content Source: [data-explorer/kusto/query/makelist-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/makelist-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
Have added this change to other changes to makelist-aggfunction.md
Thanks @ciufudean, this doc clearly needs a lot of work.

#sign-off

**Comment by YaelSchuster** [comment]
#please-close
