### ISSUE TITLE
English mistakes

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#749]
1. _Aggregation that multiple columns or non-numeric results are not supported._ - _Aggregation over ..._?
2. _The last column in the output of the range function with all AxisColumn values._ - no predicate
3. _Due to the fill missing bins by default value, the resulting pivot table has the same number of bins (that is, aggregated values) for all series_ - did you mean _filling of the missing bins_? the sentence does not end with a punctuation mark.
4. typo _MakeSeriesParamters_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e79e226-f1e1-b6ec-f4aa-1a66818190b4
* Version Independent ID: 49dba61b-3968-ac88-e2b2-49fd27942f61
* Content: [make-series operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/make-seriesoperator)
* Content Source: [data-explorer/kusto/query/make-seriesoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/make-seriesoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
Hi @ciufudean, thanks for the heads up. I've opened a PR to address these and other issues in the document. 
At this time, I'm going to close this issue and we will work with product team on the PR.

#please-close
