### ISSUE TITLE
The syntax is not describing the optional list name

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/dataexplorer-docs#750]
The syntax is missing the optional list name that can be assigned with the list value, something like 
`summarize [list_name = ] make_list(Expr [, MaxSize])`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa4efbc-144d-88d8-7032-20e8700e1725
* Version Independent ID: a693b1d8-ec33-971d-dc77-235cceae8481
* Content: [make_list() (aggregation function) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/makelist-aggfunction)
* Content Source: [data-explorer/kusto/query/makelist-aggfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/makelist-aggfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
Hi @ciufudean thanks for pointing that out. I've created a PR to update this in the docs.
Thanks for contributing!

#please-close
