### ISSUE TITLE
Parser flags example variable as an error but query runs without error

### ISSUE THREAD

**Issue by jayallen** [MicrosoftDocs/dataexplorer-docs#751]
In the section ["Use the view keyword in a let statement"](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/letstatement#use-the-view-keyword-in-a-let-statement), the example runs successfully but Intellisense parses it as an error.

![image](https://user-images.githubusercontent.com/40180/126284344-34c98283-576f-41e9-8b17-459da22f370d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 741d0e14-4a3f-af28-1d6e-e6a6dd3dd414
* Version Independent ID: 731bbd4d-10c6-5cc4-741d-7cba31cb0586
* Content: [Let statement - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/letstatement)
* Content Source: [data-explorer/kusto/query/letstatement.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/letstatement.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by SaurabhSharma-MSFT** [comment]
@jayallen Products team has identified this as a bug and provided a fix for the same.  Please let me know if you still see any issues.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@jayallen We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
