### ISSUE TITLE
Should be semi-colon instead of comma in code regarding Laguage option in ODBC

### ISSUE THREAD

**Issue by robert4os** [MicrosoftDocs/dataexplorer-docs#752]
Hi,

the code example under 'For example, the following connection string will instruct Azure Data Explorer to encode strings as NVARCHAR(8000).'

Should read 

"Driver={ODBC Driver 17 for SQL Server};Server=mykustocluster.kusto.windows.net;Database=mykustodatabase;Authentication=ActiveDirectoryIntegra**ted;Lang**uage=any@MaxStringSize:8000"

Note highlighting around semi-colon.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6149ce-1c3c-d2a2-79a9-cb181240ce90
* Version Independent ID: 372e6191-af44-ba93-bf59-c3bcc236c270
* Content: [MS-TDS clients and Kusto - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/tds/clients)
* Content Source: [data-explorer/kusto/api/tds/clients.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/tds/clients.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by shsagir** [comment]
@robert4os Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
@please-close

**Comment by robert4os** [comment]
Hi,

the code sample still uses ',' instead of ';' before 'Language' in
`"Driver={ODBC Driver 17 for SQL Server};Server=mykustocluster.kusto.windows.net;Database=mykustodatabase;Authentication=ActiveDirectoryIntegrated,Language=any@MaxStringSize:8000"`

Best regards, Robert

**Comment by shsagir** [comment]
Fixed in PR: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2127
