### ISSUE TITLE
kusto mapping parameter error

### ISSUE THREAD

**Issue by ottodeng** [MicrosoftDocs/dataexplorer-docs#753]
[ERROR] 2021-07-26 06:09:40.284 [Converge PipelineAction::Create<main>] kusto - Missing a required setting for the kusto output plugin:

  output {
    kusto {
      json_mapping => # SETTING MISSING
      ...
    }
  }

"mapping" need change to "json_mapping"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ca34fa-96ef-e2f3-4758-667c8d1c21da
* Version Independent ID: 816b41a3-3fe6-19fd-8194-42d6e96089f2
* Content: [Ingest data from Logstash to Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-logstash)
* Content Source: [data-explorer/ingest-data-logstash.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-logstash.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@ottodeng Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.
