### ISSUE TITLE
The column 'ShouldRetry' skipped from the result of .show ingestion failure command

### ISSUE THREAD

**Issue by dhnilang** [MicrosoftDocs/dataexplorer-docs#755]
[Enter feedback here]

The column 'ShouldRetry' is not mentioned in the result of .show ingestion failures command. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e92070-d041-ea43-b0ee-577e61727302
* Version Independent ID: 4fcfa11f-f1a3-d27f-0674-2a4ea87623ef
* Content: [Ingestion failures - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/ingestionfailures)
* Content Source: [data-explorer/kusto/management/ingestionfailures.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/ingestionfailures.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by AshokPeddakotla-MSFT** [comment]
@dhnilang Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by YaelSchuster** [comment]
Hi @dhnilang, thanks for reaching out. This is an internally used metric. I will update the docs to reflect this.

#please-close
