### ISSUE TITLE
demo data result is not right.

### ISSUE THREAD

**Issue by linglingruyu** [MicrosoftDocs/dataexplorer-docs#757]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e79e226-f1e1-b6ec-f4aa-1a66818190b4
* Version Independent ID: 49dba61b-3968-ac88-e2b2-49fd27942f61
* Content: [make-series operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/make-seriesoperator)
* Content Source: [data-explorer/kusto/query/make-seriesoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/make-seriesoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the doc author to update appropriately.

**Comment by YaelSchuster** [comment]
Hi @linglingruyu can you please be more specific? There are several examples on this page.

**Comment by YaelSchuster** [comment]
Hi @linglingruyu since I have not heard back from you, I am going to close this issue. If you would like to add more information, please feel free to @meniton me and we will reopen and try to address your question.

#please-close
