### ISSUE TITLE
What is docString, how do I use it, what are the parameters?

### ISSUE THREAD

**Issue by gorygregory** [MicrosoftDocs/dataexplorer-docs#762]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69e5ba4-3bd0-cf52-ab4c-08153545c7cd
* Version Independent ID: ad158cd4-8163-1b55-2374-a00139a679cf
* Content: [.alter table docstring - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-table-docstring-command)
* Content Source: [data-explorer/kusto/management/alter-table-docstring-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/alter-table-docstring-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by AshokPeddakotla-MSFT** [comment]
@gorygregory Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by YaelSchuster** [comment]
Hi @gorygregory, thanks for your question. DocString is a free text you can attach to table/function/column that will describe the entity. This string is presented in various UX settings next to the entity names.
