### ISSUE TITLE
Add basic role assignment for a single database or cluster then point to robust docs

### ISSUE THREAD

**Issue by dc995** [MicrosoftDocs/dataexplorer-docs#769]
It would be great to add one more thing to this article which is assignment of an AAD user to a role as dbadmin, or database reader access.   The current article assumes that access is granted because the creator obviously has full rights.  After a simple add, point to https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/security-roles for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd3c7f85-0e89-8515-bc13-0ee18398652d
* Version Independent ID: 0ffa4cab-f9b4-e05c-16ae-b622eaa3f21c
* Content: [Create an Azure Data Explorer cluster & DB using Powershell](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-powershell)
* Content Source: [data-explorer/create-cluster-database-powershell.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/create-cluster-database-powershell.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@dc995 
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@dc995 Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
