### ISSUE TITLE
References to 'Azure Kusto' action may be out of date?

### ISSUE THREAD

**Issue by jonathanrelf** [MicrosoftDocs/dataexplorer-docs#772]
The instructions show a Logic Apps Action called 'Azure Kusto'. When searching for this in Logic Apps, it appears to now be called 'Azure Data Explorer' and supports similar 'Run query and list results' actions but has (preview) suffixed on them. 

Do the screenshots and instructions need updating to support this new naming?

![image](https://user-images.githubusercontent.com/584662/129372151-46b000ae-04e3-4cf9-8213-01606e0168ab.png)

Many thanks, Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17290e89-e30a-e258-7f7a-77294e884c65
* Version Independent ID: 498e3bb5-92da-dac9-2967-62d85318ff13
* Content: [Use Logic Apps to run Kusto queries automatically in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/logicapps)
* Content Source: [data-explorer/kusto/tools/logicapps.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/logicapps.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by jonathanrelf** [comment]
Searching for 'Kusto' in the 'Choose an operation' search box returns the same options in the attached screenshot. 👍🏼

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by YaelSchuster** [comment]
Hi @jonathanrelf thanks so much for the kind words and pointing that out! I've added a work item so that we can follow up and update these screenshots.

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1867879

#please-close
