### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by ushaq** [MicrosoftDocs/dataexplorer-docs#779]
[Enter feedback here]
 The documentation for using managed identity is out of date. When I used the SDK I get a warning for it being obsolete and to use a newer API call without parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2795f4-802e-754f-f325-00ebe5a2e5e1
* Version Independent ID: 1eee8c82-9f46-764f-429d-228071922d4a
* Content: [Kusto connection strings - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto)
* Content Source: [data-explorer/kusto/api/connection-strings/kusto.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/connection-strings/kusto.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@ushaq Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
