### ISSUE TITLE
many adx plugins are not documented - method to extract how to test those in order to make missing documentation?

### ISSUE THREAD

**Issue by zama202** [MicrosoftDocs/dataexplorer-docs#780]
There are many plugins that are not activated by default and not documented yet. 
Is there a ADX/Kusto method to have "plugin command list, command list options, ecc. in order to test (and to make missing documentation)? example "Show autocluster options"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dedfda0a-cdb4-8db2-b274-78ce54005c05
* Version Independent ID: 0b328d08-f173-4b0c-7e07-40d24d6fd1e2
* Content: [Plugins command show plugins - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-plugins)
* Content Source: [data-explorer/kusto/management/show-plugins.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/show-plugins.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@zama202  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by YaelSchuster** [comment]
Hi @zama202, since it looks like all available plugins are documented, I'm going to proceed to close this issue. If you have further questions, please feel free to reopen by @mention myself, or opening a new issue.
#please-close
