### ISSUE TITLE
Property key with dot

### ISSUE THREAD

**Issue by idigra** [MicrosoftDocs/dataexplorer-docs#783]
Is there a way to use extractjson function with property key that contains dot? i.e. is there a way to escape dots in property key, so it won't be captured as the special character of JSON path?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01a9498f-3bba-5479-e7d7-32cc4d96c15a
* Version Independent ID: 198ef7fc-f118-3f0d-0c9b-366d3e008be0
* Content: [extractjson() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractjsonfunction)
* Content Source: [data-explorer/kusto/query/extractjsonfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/extractjsonfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@idigra  Thanks for the question! We are investigating and will update you shortly.

**Comment by natinimni** [comment]
Hi @idigra, you may use _['<property_name>']_ notation for property names with special characters. 
For example, the following JSON string has a property name that contains dots ("a.g.e"):
~~~
print json='{ "name":"contoso", "a.g.e":56 }'
| project extractjson("$.['a.g.e']", json, typeof(int)) 
~~~ 

I hope this answer your question.

**Comment by idigra** [comment]
Thanks! That's what I need, I'll try it.
I would consider explicitly mentioning in the documentation that escaping can be done using the [' syntax.
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractjsonfunction
