### ISSUE TITLE
Aks.ms links aren't working

### ISSUE THREAD

**Issue by msangapu-msft** [MicrosoftDocs/dataexplorer-docs#797]
The links to kusto explorer aren't working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba96a1-65dd-5320-6d36-47de50b8403f
* Version Independent ID: deee5b70-9bd5-2bf9-f7b7-12c40200693d
* Content: [Kusto.Explorer installation and user interface](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer)
* Content Source: [data-explorer/kusto/tools/kusto-explorer.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/tools/kusto-explorer.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. We are actively investigating and will get back to you soon.

**Comment by YaelSchuster** [comment]
![image](https://user-images.githubusercontent.com/62833511/131453962-559cf233-6e4e-41ef-8dad-1f1c8680ff5d.png)
The links are working ok for me (see image).

**Comment by msangapu-msft** [comment]
Thanks for taking a look. I've tracked the culprit to this Chrome extension mentioned here: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer#using-chrome-and-kustoexplorer

If I disable the extension, the link works. When the extension is enabled, the links don't work. Not sure if that's limited to my machine/experience, but wanted to share. I think we're good to close this issue. Thanks again.
