### ISSUE TITLE
dayofyear() syntax section shows dayofweek()

### ISSUE THREAD

**Issue by Clex19** [MicrosoftDocs/dataexplorer-docs#798]
![image](https://user-images.githubusercontent.com/8637208/131361196-ef1811a3-18d9-4b79-bc4d-fd6923a8614d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c061cab9-a03a-c3f1-b8a3-1e9139f8f573
* Version Independent ID: 3673fc3b-53be-0dea-9538-15292425f306
* Content: [dayofyear() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/dayofyearfunction#feedback)
* Content Source: [data-explorer/kusto/query/dayofyearfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/dayofyearfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by femsulu** [comment]
Thanks for bringing this to our attention. We are actively investigating and will get back to you soon.

**Comment by femsulu** [comment]
created a PR to resolve this doc-isssue. 
FYI @orspod

**Comment by femsulu** [comment]
Thanks again for bringing this to our attention, @Clex19. The fix will be live shortly.
We will now close this issue. If there are further questions regarding this matter, please reply and we will gladly continue the discussion.
