### ISSUE TITLE
Automate Table creation

### ISSUE THREAD

**Issue by raghuvamsi-disys** [MicrosoftDocs/dataexplorer-docs#802]
[Enter feedback here]

I have created Data Explorer Cluster, Database using Terraform. Looks like there is no option to create Tables using Terraform.

Wanted to check is it possible to create the table using ARM template atleast?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a64f727-eca9-25a5-5350-bae37aeb79e9
* Version Independent ID: 759fa56e-81fe-c719-6cd2-d12f907b759e
* Content: [Create a table in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/one-click-table)
* Content Source: [data-explorer/one-click-table.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/one-click-table.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for reaching out to us , but at this time it does not look like you are referring to a document but to a specific scenario . If that's the case we request you to please post your question on Microsoft Q&A and other forums , we have our engineers and others who are monitoring them and will be happy to help .
If you have a document which you are following and if you think it needs  an update , please let us know about that here .
