### ISSUE TITLE
Broken link when deploy event hub namespace

### ISSUE THREAD

**Issue by angie4u** [MicrosoftDocs/dataexplorer-docs#808]
[Broken link when deploy event hub namespace]

When create a event hub namespace by following the docs(https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-no-code?tabs=diagnostic-metrics#create-an-azure-event-hubs-namespace), this azure deploy button doesn't work due to the invalid url.
![image](https://user-images.githubusercontent.com/16282358/132147051-b9ea3383-5a3c-4810-8ca6-124b5adc4ee2.png)

## Error page
![image](https://user-images.githubusercontent.com/16282358/132146809-88867250-a2f6-4ccf-8847-f5e1f622e945.png)
Custom deployment error cause this url 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-event-hubs-create-event-hub-and-consumer-group/azuredeploy.json' is not valid anymore.

## How to fix error

Change url from
 https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-event-hubs-create-event-hub-and-consumer-group/azuredeploy.json 
to https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.eventhub/event-hubs-create-event-hub-and-consumer-group/azuredeploy.json

## After fix the url
![image](https://user-images.githubusercontent.com/16282358/132146966-7304e0e0-3645-4386-a09a-20208b02f778.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe49562-852d-db87-a190-8e6f267951fc
* Version Independent ID: 08c75879-50de-cf95-ecac-226e93285a66
* Content: [Tutorial: Ingest monitoring data in Azure Data Explorer without code](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-no-code?tabs=diagnostic-metrics)
* Content Source: [data-explorer/ingest-data-no-code.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-no-code.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@angie4u Thanks for pointing out the issue, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2279](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2279) 
The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.
