### ISSUE TITLE
Wrong spelling for "results"

### ISSUE THREAD

**Issue by why39** [MicrosoftDocs/dataexplorer-docs#809]
There seems a wrong spelling for "results"
![image](https://user-images.githubusercontent.com/38268442/132151528-24a4f188-d3ab-446e-87da-5aad9d6b1ebe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c750ffa-07a3-6247-b5d2-89c43f8aacd6
* Version Independent ID: 33f23cad-20a0-c0bb-0622-6272a7c5f9c2
* Content: [Capacity policy - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/capacitypolicy#feedback)
* Content Source: [data-explorer/kusto/management/capacitypolicy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/capacitypolicy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@why39 Thanks for pointing out the issue, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2278](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2278) 
The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.
