### ISSUE TITLE
Add section on how Data Explorer handles Event hubs in a disaster recovery setup 

### ISSUE THREAD

**Issue by m2000ank** [MicrosoftDocs/dataexplorer-docs#81]
Event hubs can be set up with multi-region disaster recovery, and I would like to understand how failing over an event hub namespace from primary to secondary region would affect the data connections. Will they need to be manually recreated after failover, for instance, or does Data Explorer handle such situations automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5808ed2-5d09-4c56-dc0b-4e3650f8fc16
* Version Independent ID: ba034a8d-d5bb-6ea4-e61b-74ea3a5eb2be
* Content: [Ingest data from Event Hub into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub#feedback)
* Content Source: [data-explorer/ingest-data-event-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-hub.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@m2000ank  Thanks for the feedback! Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@m2000ank Thanks for the feedback! A BCDR doc is in progress.
@cosh will you assist with this question.

**Comment by cosh** [comment]
Hi,

please go to https://techcommunity.microsoft.com/t5/azure-data-explorer/azure-data-explorer-and-business-continuity/ba-p/1332767 . You need to connect to the alias. The rest is handled by ADX with checkpointing.

Cheers

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@m2000ank  We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.

**Comment by m2000ank** [comment]
Sorry for the late answer, and thanks for providing the documentation.
