### ISSUE TITLE
Import Dashboard via JSON?

### ISSUE THREAD

**Issue by wangyuantao** [MicrosoftDocs/dataexplorer-docs#810]
In the Dashboard view, there is a button "Export to JSON". How to "Import" it back to ADX Dashboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1640-3699-8fdf-07a2-c9b922499c90
* Version Independent ID: 55027537-6af4-541d-da8d-e2cdc2b5fa92
* Content: [Visualize data with the Azure Data Explorer dashboard](https://docs.microsoft.com/en-us/azure/data-explorer/azure-data-explorer-dashboards)
* Content Source: [data-explorer/azure-data-explorer-dashboards.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/azure-data-explorer-dashboards.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the ask  . At this time we are reviewing the ask and we will reply back as soon as we can .

**Comment by MartinJaffer-MSFT** [comment]
That's a great question @wangyuantao .  So far I have not found the import dashboard button either.  Escalating to @orspod .

**Comment by Gabilehner** [comment]
Thank you for your question!
Import json file is not supported today, but it is on our backlog for the mid term.

**Comment by YaelSchuster** [comment]
Thanks @Gabilehner 
Closing this issue now.
@wangyuantao thanks for reaching out, we're always here for questions.

**Comment by YaelSchuster** [comment]
#please-close
