### ISSUE TITLE
Render Chart Title Type String

### ISSUE THREAD

**Issue by Stuart-Wilcox** [MicrosoftDocs/dataexplorer-docs#816]
[Enter feedback here]
In the docs for `render` it says an attribute called `title` is type string, but I have seen that this is not exactly true.

This works:
```
SomeData
| render barchart title='My Graph Title'
```

This does not:
```
let MyGraphTitle = 'My Graph Title';
SomeData
| render barchart title=MyGraphTitle
```
![image](https://user-images.githubusercontent.com/22772721/132876427-0a669ba3-5003-48fe-87f2-829375f5a3f7.png)

This also does not:
```
let GetMyGraphTitle = () {
  strcat('My ', 'Graph ', 'Title')
};
SomeData
| render barchart title=GetMyGraphTitle()
```

Even though both of those resolve to string/are of type string. If this is expected behaviour (I don't think it should) it should be clarified in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f766314-2d79-147e-728c-cd661ab29939
* Version Independent ID: 0f1b5a73-c5ac-1505-bc62-5361eeaedbb7
* Content: [render operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator)
* Content Source: [data-explorer/kusto/query/renderoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/renderoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the ask  . At this time we are reviewing the ask and we will reply back as soon as we can .

**Comment by SaurabhSharma-MSFT** [comment]
@Stuart-Wilcox I see the same behavior but it works using `with` operator. 
 `render barchart with(xcolumn=x,title=MyGraphTitle)`
![image](https://user-images.githubusercontent.com/38112130/133184113-f9b0ba0a-5f45-4e61-a14b-09cc95327d46.png)
![image](https://user-images.githubusercontent.com/38112130/133184173-6bd1aa8d-f756-4ca7-bde2-0ec4040526e5.png)

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@Stuart-Wilcox We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
