### ISSUE TITLE
Why does kusto have getyear and getmonth but no getday?

### ISSUE THREAD

**Issue by WaterWan** [MicrosoftDocs/dataexplorer-docs#82]
[Enter feedback here]
When I tried to get the beginning of a day, I would use query like this:
```
let beginningOfToday = make_datetime(getyear(now()), getmonth(now()), dayofmonth(now()));
```

I need to use two kind of functions to calculate. Why does not Kusto provide getday? Also, could you please show a more elegant way to get the beginnning of a day?

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5308a69-9b73-afb9-4038-a07b9cc75a2e
* Version Independent ID: ccf13517-7e1a-0930-4a8e-0c5ce019b5fe
* Content: [getyear() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/getyearfunction)
* Content Source: [data-explorer/kusto/query/getyearfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/getyearfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@WaterWan  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@yonileibowitz will you please assist with @WaterWan 's question?

**Comment by yonileibowitz** [comment]
you can use `bin(timestamp, 1d)` or `startofday(timestamp)` to get the beginning of a day.

you can request/vote new features at https://aka.ms/adx.uservoice.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@WaterWan 
We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
