### ISSUE TITLE
"Deploy to Azure" bottom linked to ARM template that can not be found.

### ISSUE THREAD

**Issue by mlevin19** [MicrosoftDocs/dataexplorer-docs#824]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5808ed2-5d09-4c56-dc0b-4e3650f8fc16
* Version Independent ID: ba034a8d-d5bb-6ea4-e61b-74ea3a5eb2be
* Content: [Ingest data from Event Hub into Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub)
* Content Source: [data-explorer/ingest-data-event-hub.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/ingest-data-event-hub.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@mlevin19 Thanks for pointing out the issue, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2311](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2311) 

The changes should be live soon. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.

@orspod Could you please review the PR and approve?

**Comment by YaelSchuster** [comment]
Have approved and merged the PR, thanks @CHEEKATLAPRADEEP-MSFT 

At this time, I'm closing the Issue. 
@mlevin19 thanks for reaching out and helping us improve the docs!

#please-close
