### ISSUE TITLE
steps in order

### ISSUE THREAD

**Issue by smedegaard** [MicrosoftDocs/dataexplorer-docs#831]
> For example, you can expose the service as a Load Balancer service. To do so, add the --set service.type=LoadBalancer parameter to the earlier Kibana Helm install command.

## Step 3 F
`helm install k2bridge charts/k2bridge -n k2bridge --set image.repository=$REPOSITORY_NAME/$CONTAINER_NAME --set settings.adxClusterUrl="$ADX_URL" --set settings.adxDefaultDatabaseName="$ADX_DATABASE" --set settings.aadClientId="$ADX_CLIENT_ID" --set settings.aadClientSecret="$ADX_CLIENT_SECRET" --set settings.aadTenantId="$ADX_TENANT_ID" [--set image.tag=latest] [--set privateRegistry="$IMAGE_PULL_SECRET_NAME"] [--set settings.collectTelemetry=$COLLECT_TELEMETRY]`

should have ` --create-namespace` since the namespace will not exist in a fresh install:

``helm install k2bridge charts/k2bridge -n k2bridge --create-namespace --set image.repository=$REPOSITORY_NAME/$CONTAINER_NAME --set settings.adxClusterUrl="$ADX_URL" --set settings.adxDefaultDatabaseName="$ADX_DATABASE" --set settings.aadClientId="$ADX_CLIENT_ID" --set settings.aadClientSecret="$ADX_CLIENT_SECRET" --set settings.aadTenantId="$ADX_TENANT_ID" [--set image.tag=latest] [--set privateRegistry="$IMAGE_PULL_SECRET_NAME"] [--set settings.collectTelemetry=$COLLECT_TELEMETRY]``

## Step 3 G
> --set service.type=LoadBalancer 
should not come after the install command, since it messes the install up if you follow the natural sequence of the steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db70b14-6793-154e-d8f3-157d2ecf6a5a
* Version Independent ID: 6bdfb13b-cdf4-31a7-c987-7b26e1e024ca
* Content: [Visualize data from Azure Data Explorer using Kibana](https://docs.microsoft.com/en-us/azure/data-explorer/k2bridge)
* Content Source: [data-explorer/k2bridge.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/k2bridge.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by guregini** [comment]
Thanks @smedegaard for sharing this important feedback!
 We will add the 'create namespace' part.
Regarding the "set service.type=LoadBalancer", you said "should not come after the install command" - do you mean that it **should** be **placed** after the install command in the document?

**Comment by YaelSchuster** [comment]
@smedegaard ping on the above question.

**Comment by YaelSchuster** [comment]
@smedegaard, since we haven't heard anything further, I'm going to close this issue. If you have further issues or questions, please feel free to @mention me or open a new issue. @guregini please let me know if you need my help with docs changes as a result. 
#please-close
