### ISSUE TITLE
Show Table Schema as json

### ISSUE THREAD

**Issue by PaulieC1972** [MicrosoftDocs/dataexplorer-docs#84]
example command syntax is incorrect - .show table TableName schema as JSON

Should be ".show table TableName schema as json"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c27ecef-9569-8659-af19-53a454b846ae
* Version Independent ID: 10203dc7-0f0c-7a09-7308-9755fdb805ba
* Content: [.show table schema - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-table-schema-command#feedback)
* Content Source: [data-explorer/kusto/management/show-table-schema-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/show-table-schema-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
@PaulieC1972 Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by PaulieC1972** [comment]
Obviously it's not super hi pri 😉

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KranthiPakala-MSFT** [comment]
@PaulieC1972 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
