### ISSUE TITLE
What are the units of these columns?

### ISSUE THREAD

**Issue by jcsclement** [MicrosoftDocs/dataexplorer-docs#85]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663dd48a-e82c-39b7-979a-dbf7103dd94f
* Version Independent ID: 4bba448f-c9c6-6bce-c694-35c9f0777e6b
* Content: [.show table details - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-table-details-command)
* Content Source: [data-explorer/kusto/management/show-table-details-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/show-table-details-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SumanthMarigowda-MSFT** [comment]
@jcsclement Thanks for the question! We are investigating and will update you shortly.

**Comment by himanshusinha-msft** [comment]
@jcsclement : Many of the columns are counts only  . I beleive that the extentsize will be in bytes .
@orspod  : Can you please confirm ?

**Comment by orspod** [comment]
@kerend - can you confirm?

**Comment by kerend** [comment]
Size is in bytes.

**Comment by orspod** [comment]
@jcsclement I believe we addressed your question. Moving to close this issue.
