### ISSUE TITLE
Add examples for "File begins with"

### ISSUE THREAD

**Issue by jmiddleton** [MicrosoftDocs/dataexplorer-docs#86]
It would be good to have more examples on how to use the filters. Application Insights stores files with a specific folder structure apiinsight[randomId]/Requests, apiinsight[randomId]/Avaliability, etc. You can filter files which are under specific folder in Blob storage so they can be stored in one table. For example, you can define "File begins with"  apiinsight[randomId]/Requests to ingest only Requests logs into a Azure Data Explorer table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567e6ac5-f63b-e3a8-6a57-763563436ae5
* Version Independent ID: 438ba708-c111-a69e-2d57-21afe53413a4
* Content: [Use one-click ingestion to ingest data into a new Azure Data Explorer table](https://docs.microsoft.com/en-us/azure///data-explorer/one-click-ingestion-new-table#feedback)
* Content Source: [data-explorer/one-click-ingestion-new-table.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/one-click-ingestion-new-table.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BharathNimmala-MSFT** [comment]
@jmiddleton Thank you for your query, our team will look into it and get back to you at the earliest.

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by orspod** [comment]
@jmiddleton thanks for your feedback. We are currently working on updating the doc and will incorporate your sugestion.  @ArielYehezkely can you assist with this question?

**Comment by ArielYehezkely** [comment]
Hi @jmiddleton, 

The file filters are simple prefix/suffix.
As of efficiency considerations we use Azure Storage blob API to provide the functionality of filtering by prefix, and Azure storage doesn't support other kinds of filters (regex for example).
For your scenario, you might want to take a look at [Light Ingest tool](https://docs.microsoft.com/en-us/azure/data-explorer/lightingest) which supports regex.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@jmiddleton  We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
