### ISSUE TITLE
How to query ADX from SSIS?

### ISSUE THREAD

**Issue by chribben** [MicrosoftDocs/dataexplorer-docs#869]
The article states that "For example, you can create SSIS jobs to query Kusto with a KQL query." but who would one do this in practice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eed42031-4dbf-b3d2-7488-cf202c7a2722
* Version Independent ID: af054c90-d722-d422-a5f2-41bef3ad2f40
* Content: [KQL over TDS - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/tds/tdskql)
* Content Source: [data-explorer/kusto/api/tds/tdskql.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/tds/tdskql.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by shsagir** [comment]
@chribben Thanks for your patience. We are still looking into this and hope to get back to you soon.

**Comment by shsagir** [comment]
@chribben Thanks for your feedback. Our investigation shows that the SSIS reference in this topic is a mistake. We'll be submitting a documentation change based on your suggestion. Please let us know if there's anything more we can do for you.

**Comment by shsagir** [comment]
#please-close
