### ISSUE TITLE
KQL Command missing ticks

### ISSUE THREAD

**Issue by KhaoticMind** [MicrosoftDocs/dataexplorer-docs#882]
The KQL commands provided on this page are incorrect, as they are missing the ticks for the function name, as an argument to the RLS policy.
Other pages (as https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/rowlevelsecuritypolicy) have the syntax correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd45a3a-f480-8edb-6a39-4c681aa1ce61
* Version Independent ID: fb1b11ca-40c5-2343-7d69-c388a2a458af
* Content: [.alter table row level security policy command- Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-table-row-level-security-policy-command)
* Content Source: [data-explorer/kusto/management/alter-table-row-level-security-policy-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/alter-table-row-level-security-policy-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@KhaoticMind Thank you for sharing your feedback. We are validating it. We will get back with updates soon.

**Comment by YaelSchuster** [comment]
Hi @KhaoticMind Thanks for pointing that out to us and helping us to continually improve the docs. 
Fixing that now.

**Comment by YaelSchuster** [comment]
#please-close
