### ISSUE TITLE
Make term details more explicit on the has operator kusto documentation page

### ISSUE THREAD

**Issue by szimmerMicrosoft** [MicrosoftDocs/dataexplorer-docs#884]
The kusto documentation page on the "has" operator makes no reference to terms or the terms index discussed here.
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators

This is vital information about the has operator which is not on the has operator documentation page in an explicit form, or even include a direct link to explain terms explicilty.

This led me to not understand the has operator (or has_any) operator for years thinking they were just a broken contains operator. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54a3e89-5278-6712-42b8-146c4f6c57dd
* Version Independent ID: 6d773e2a-596d-5c8f-28d1-9b61389f1089
* Content: [The case-insensitive has string operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/has-operator)
* Content Source: [data-explorer/kusto/query/has-operator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/has-operator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by YaelSchuster** [comment]
@szimmerMicrosoft thanks for bringing this to our attention. Will add specific links to indexing discussion. A work item has been created for this task: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1891100 
As such, closing this issue. Thanks for your help!

#please-close
