### ISSUE TITLE
Please add an example of how to parse without losing all of your columns

### ISSUE THREAD

**Issue by justinmchase** [MicrosoftDocs/dataexplorer-docs#886]
How can you use the parse step in conjuction with an extend? Syntactically it doesn't seem to work but when you add a `| parse` step to your query it drops all of the other columns.

I'm trying to do this query for example:
```
ContainerLog
| where ContainerID == "624954045a2e31bda1646d7f209b876f43fc7af606be07f3059f8628dd182ca1"
| join kind=inner KubePodInventory on $left.ContainerID == $right.ContainerID
| project TimeGenerated, Image, ImageTag, LogEntry
| parse LogEntry with StatusCode:long " " Method:string " " Path:string " " Data:string)
| limit 1
```

But the parse step removes all of the fields projected on the step before. I can't seem to use the parse in a join or in an extend or in a project step, so how on earth can I do an extend where the value of the new column is a parse? This documentation only shows a single kind of example which is fine but its not clear how else the parse can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1e5ee0d-f964-d0a8-8574-3ea4eb3c1e76
* Version Independent ID: 3915be89-d297-8423-238e-96e94f5f3f81
* Content: [parse operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parseoperator)
* Content Source: [data-explorer/kusto/query/parseoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/parseoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@justinmchase Thank you for sharing your valuable feedback. We are actively validating it. We will get back with updates soon.

**Comment by YaelSchuster** [comment]
Hi @Justinmchase - to begin to answer your question, 
the Parse operator adds additional columns, and doesn’t remove any. It's unclear what your question is in light of the behavior of the operator.

 If you're having problems with your query, please post your question to StackOverflow.
When posting question in StackOverflow – provide an input example using datatable() and expected output.

#please-close

**Comment by justinmchase** [comment]
You're right somehow it wasnt' working for me but I think I had a bad query that was doing something I wasn't expecting. Please disregard.
