### ISSUE TITLE
Specify allowed values for step (bin size)

### ISSUE THREAD

**Issue by ghogen** [MicrosoftDocs/dataexplorer-docs#889]
By trial and error, I found out that `step 1m` means 1 minute, not 1 month, but this page doesn't list the possible step syntax
1d means 1 day, that's the only example available

Please list all possible syntax for "step"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e79e226-f1e1-b6ec-f4aa-1a66818190b4
* Version Independent ID: 49dba61b-3968-ac88-e2b2-49fd27942f61
* Content: [make-series operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/make-seriesoperator)
* Content Source: [data-explorer/kusto/query/make-seriesoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/make-seriesoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ghogen** [comment]
Apparently this is described in the timespan article. https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan

**Comment by ShaikMaheer-MSFT** [comment]
@ghogen Thank you for sharing your feedback. We are actively validating it. We will get back with updates soon.

**Comment by YaelSchuster** [comment]
Hi @ghogen, sorry to hear that was confusing for you. I've added a link to this document: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan which lists all the available timespan intervals. Hope that helps you and future customers! Thanks for contributing.

#please-close
