### ISSUE TITLE
On-behalf-of authentication using App Service Authentication

### ISSUE THREAD

**Issue by MertUssakliMSFT** [MicrosoftDocs/dataexplorer-docs#890]
Hi,

I am working on building a serverless web application hosted on Azure Functions. This application requires querying a Kusto database as its backend to display data for the users. To ensure that the users have proper access to the said Kusto database, I want to implement an on-behalf-of authentication flow. I am leveraging [App Service Authentication](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) directly to authenticate users and generate tokens. 

To do this, I am following both these Data Explorer docs, and [these docs](https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=azure-resource-explorer%2Cprogramming-language-csharp) for guidance on App Service Authentication.

I have set up my authentication with an AAD app, where the authentication provider is Microsoft: 

![image](https://user-images.githubusercontent.com/94049942/141118150-6c9ccd62-165a-4800-8422-6f98de9a3d5d.png)

and I granted this AAD application delegated permissions for Azure Data Explorer `user_impersonation` scope: 

![image](https://user-images.githubusercontent.com/94049942/141118271-efb20aed-27cd-42c2-9ce0-3e855de0c325.png)

With just these set up, App Service Authentication does not issue access tokens for the proper audience for me. The consent dialog that pops up on `https://myapp.azurewebsites.net/.auth/login/aad` asks only for Microsoft Graph audience consent, and I can validate this by later checking on `https://stackviewer.azurewebsites.net/.auth/me` and looking at the `access_token`, which has audience scoped only to Graph. This value cannot be used for `customerAadWebApplicationToken` value, as it will yield an invalid signature error.

This sort of makes sense, because the App Service Authentication documentation for OBO auth for Microsoft graph [does instruct](https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=azure-resource-explorer%2Cprogramming-language-csharp#configure-app-service-to-return-a-usable-access-token) the user to modify your Azure resource to generate access tokens specifically for the Microsoft Graph scope that is needed.

I simulated this same process, but for Azure Data Explorer. I modified my authSettingsV2 to contain the following: 

```
"identityProviders": {
      "azureActiveDirectory": {
        "enabled": true,
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
          "clientId": "b03493a7-9ef0-4daf-9b43-c3f8f5898fdb",
          "clientSecretSettingName": "MICROSOFT_PROVIDER_AUTHENTICATION_SECRET"
        },
        "login": {
          "loginParameters": [
            "scope=openid profile email offline_access https://help.kusto.windows.net/user_impersonation"
          ],
          "disableWWWAuthenticate": false
        },
        "validation": {
          "jwtClaimChecks": {},
          "allowedAudiences": [],
          "defaultAuthorizationPolicy": {
            "allowedPrincipals": {}
          }
        },
        "isAutoProvisioned": true
      },
```

This unfortunately doesn't work, as I'm led to a consent screen that says I need admin approval to request these tokens: 
![image](https://user-images.githubusercontent.com/94049942/141119496-71d97e2c-373d-4251-ada1-d7e706002668.png)

I have also tried this with using my own cluster name in the scope string, as `https://clusetername.kusto.windows.net/user_impersonation`, yielding the same result. 

I'd like to have some guidance about how to generate the correct access token for OBO auth into Kusto, while using App Service Authentication. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee89d0d7-becd-83f4-b862-f39b1c1ad6d4
* Version Independent ID: d40d3446-9677-dbdc-faa9-f04a30ffb042
* Content: [Kusto authenticate with AAD for access - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad#on-behalf-of-authentication)
* Content Source: [data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@MertUssakliMSFT Thanks for the question. GitHub forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilize Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html).
