### ISSUE TITLE
add column  transformation example

### ISSUE THREAD

**Issue by mathaholic** [MicrosoftDocs/dataexplorer-docs#893]
This page could give more clarity if it added a cheat sheet item for column transformations that do not require a group by.
For example:
SELECT
idColumn,
CAST(timestamp AS date) AS rowDate
FROM table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f392719-bd91-a626-7176-a95297e4ca99
* Version Independent ID: 362cb089-c767-ed2c-6c00-16068b68cbbd
* Content: [SQL to Kusto query translation - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/sqlcheatsheet)
* Content Source: [data-explorer/kusto/query/sqlcheatsheet.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/sqlcheatsheet.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@mathaholic  Thanks for the feedback! I have assigned the issue to the content author to evaluate and add the column transformation details.

**Comment by YaelSchuster** [comment]
Hi @mathaholic, thanks for the suggestion. I've added this to our backlog of work items, where we will track here: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1893956

At this time, I'm going to close the issue. Please do continue to suggest ways to make our docs more useful!

#please-close
