### ISSUE TITLE
Hardcoded value in example function code

### ISSUE THREAD

**Issue by jovanroy** [MicrosoftDocs/dataexplorer-docs#897]
Hi,

An example function Test1 is included. While the example code is not incorrect, the function has a call to Test4 with a fixed value of 10, while it looks like the parameter id should be used in the call to Test4 instead of the fixed value 10. Otherwise, the output would always be 70, no matter which input value is provided as the id parameter. (See line 8 in the code underneath.)

```
let Test1 = (id: int) {
  let Test2 = 10;
  let Test3 = 10 + Test2 + id;
  let Test4 = (arg: int) {
      let Test5 = 20;
      Test2 + Test3 + Test5 + arg
  };
  Test4(10)
};
range x from 1 to Test1(10) step 1
| count
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5958aeff-6cae-d186-b3b4-47925c42f4dd
* Version Independent ID: ba7d8197-6ec5-e730-9b1a-4fba51680289
* Content: [User-defined functions - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/functions/user-defined-functions)
* Content Source: [data-explorer/kusto/query/functions/user-defined-functions.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/functions/user-defined-functions.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@jovanroy Thank you for sharing your valuable feedback. We are actively investigating it. We will share updates soon.

**Comment by shsagir** [comment]
@jovanroy Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
