### ISSUE TITLE
Blob's SAS token maybe be expired.

### ISSUE THREAD

**Issue by yuharucan** [MicrosoftDocs/dataexplorer-docs#899]
[Enter feedback here]
Blob's SAS token maybe be expired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c010923-e011-6915-e3c4-6265fb997c35
* Version Independent ID: 6b102d99-8aae-bba3-0ddf-d4137c3d6434
* Content: [Ingest data using the Azure Data Explorer Python library](https://docs.microsoft.com/en-us/azure/data-explorer/python-ingest-data)
* Content Source: [data-explorer/python-ingest-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/python-ingest-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@yuharucan Thanks for pointing out the issue, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs/pull/900](https://github.com/MicrosoftDocs/dataexplorer-docs/pull/900)

![image](https://user-images.githubusercontent.com/79183421/141963203-2515313d-4415-43ae-b31d-627640bbb141.png)

The changes should be live EOD or tomorrow. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.

**Comment by shsagir** [comment]
Content is live.

#please-close
