### ISSUE TITLE
Data Explorer with vnet deployment using Terraform 

### ISSUE THREAD

**Issue by raghuvamsi-disys** [MicrosoftDocs/dataexplorer-docs#903]
Is there Terraform support to deploy Azure Data Explorer into vnet?

https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501c33cd-0ac0-685b-0da1-03a269616d08
* Version Independent ID: 67e7428d-9b35-cb0c-7af9-6fc402848b8d
* Content: [Deploy Azure Data Explorer into your Virtual Network](https://docs.microsoft.com/en-us/azure/data-explorer/vnet-deployment)
* Content Source: [data-explorer/vnet-deployment.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/vnet-deployment.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the ask  . At this time we are reviewing the ask and we will reply back as soon as we can .

**Comment by YaelSchuster** [comment]
Hi @raghuvamsi-disys please ask product questions on StackOverflow. Tag with Kusto and/or Azure Data Explorer. This forum is for docs-related issues only.

#Please-close
