### ISSUE TITLE
How to cancel async ingest query?

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/dataexplorer-docs#91]
I started a ingest query without distributed=true by mistake. .cancel does not seem to help... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dde8b71-b1d9-ddef-1879-7358813b16ab
* Version Independent ID: db750929-3467-bbe3-b753-8953070900dc
* Content: [Kusto query ingestion (set, append, replace) - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-from-query#feedback)
* Content Source: [data-explorer/kusto/management/data-ingestion/ingest-from-query.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/data-ingestion/ingest-from-query.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@dciborow 
Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@dciborow thanks for the question. @kerend can you assist?

**Comment by yonileibowitz** [comment]
`.cancel query` is meant for cancelling queries, not control commands.

in cases where the control commands runs a query (e.g. `.export` or `.set-or-append`), then using `.cancel query` may be able to cancel the query, and have the command fail, but that depends on the current phase of the command's execution.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@dciborow  We will now proceed to close this thread. If there are further questions regarding this matter, please comment and we will gladly continue the discussion.
