### ISSUE TITLE
decision tree has 2 redundant entries

### ISSUE THREAD

**Issue by Holger1968** [MicrosoftDocs/dataexplorer-docs#910]
2 and 4 is the same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6bba86f-f473-368c-e517-c02e4635119c
* Version Independent ID: 66be4c19-ccf8-a0e2-31b1-95a9d677ba12
* Content: [What is Azure Data Explorer?](https://docs.microsoft.com/en-us/azure/data-explorer/data-explorer-overview)
* Content Source: [data-explorer/data-explorer-overview.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/data-explorer-overview.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by YaelSchuster** [comment]
Thanks @Holger1968 for noticing that. Have opened WI to track this fix. https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1896675

#please-close
