### ISSUE TITLE
The example is missing the "database" keyword.

### ISSUE THREAD

**Issue by asafnadler** [MicrosoftDocs/dataexplorer-docs#912]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c73c8b-48be-e8eb-0860-05f0e36d7e07
* Version Independent ID: a1213bb3-6969-5390-6e78-6f7851869666
* Content: [.show database ingestion batching policy command- Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-database-ingestion-batching-policy)
* Content Source: [data-explorer/kusto/management/show-database-ingestion-batching-policy.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/show-database-ingestion-batching-policy.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by YaelSchuster** [comment]
Hi @asafnadler thanks for noticing that. I've fixed this in the docs and the changes will be live later today.
#please-close
