### ISSUE TITLE
Undocumented behavior : parse_json reformats strings that look like datetime assuming UTC

### ISSUE THREAD

**Issue by egoward** [MicrosoftDocs/dataexplorer-docs#914]
parse_json is doing undocumented processing of string tokens that can be parsed as datetime

Test case:
  print parse_json('{"t":"2021-11-18T00:03:35"}');
Expected result:
  {"t":"2021-11-18T00:03:35"}
Actual result:
  {"t":"2021-11-18T00:03:35.0000000Z"}

This wasn't expected behavior for a JSON parser and is problematic for my use case which involves manipulating dates with business logic that will determine the timezone.  Suggest we document it ahead of a backwards compatible fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0bdf325-a459-1c3e-f445-452b0c21d6ec
* Version Independent ID: d9317182-7957-acdf-8837-5597d24e7fcf
* Content: [todynamic(), parse_json() functions - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parsejsonfunction)
* Content Source: [data-explorer/kusto/query/parsejsonfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/parsejsonfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @egoward, thanks for your feedback! We will review and update this doc accordingly.

**Comment by YaelSchuster** [comment]
Hi @egoward, parse_json converts json string into dynamic objects, with possible type conversions into Kusto types involved. 
You're correct- this wasn't clear from the documentation. I'm adding such a note now.

For the case where a strict parsing required, it's possible to use extract() or extractjson() functions.

**Comment by YaelSchuster** [comment]
#please-close
