### ISSUE TITLE
ParseUrl does not handle multiple query params with same key

### ISSUE THREAD

**Issue by miqm** [MicrosoftDocs/dataexplorer-docs#917]
Hello,

I'm using parse_url function to get query params. However, if query is like `https://domain.com/a/b?c=1&c=2&c=3` and I call `parse_url(Url)["Query Parameters"]["c"]` I get as a result value `3` while it should be an array of all values: `[1,2,3]`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25ef5c77-e818-8bfd-690e-e01088a65a48
* Version Independent ID: 1b956b47-af36-30fb-b4f6-f9f5467298b3
* Content: [parse_url() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parseurlfunction)
* Content Source: [data-explorer/kusto/query/parseurlfunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/parseurlfunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@miqm Thanks for the question. GitHub forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilize Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html).

**Comment by miqm** [comment]
@ShaikMaheer-MSFT I do realise that, but this kind of limitation should be reflected in docs. Can you update the relevant section and clearly describe that parse_url returns only one query parameter - and which one - when multiple ones are supplied?

**Comment by ShaikMaheer-MSFT** [comment]
@orspod Could you please validate feedback and update document as appropriate to reflect limitation in docs. Thank you.

**Comment by YaelSchuster** [comment]
Hi @miqm thanks for reaching out with your question. I've checked with the product team, and learned the following:

If there are multiple parameters with the same key, the last one is returned. 

I've opened a PR to change this in the docs.

At this time I'm going to close the PR, but please feel free to reach out with other docs questions and issues!

#please-close
