### ISSUE TITLE
Log Analytics Endpoint is wrong

### ISSUE THREAD

**Issue by hajekj** [MicrosoftDocs/dataexplorer-docs#920]
In the section [Add a Log Analytics/Application Insights workspace to Azure Data Explorer client tools](https://docs.microsoft.com/en-us/azure/data-explorer/query-monitor-data#add-a-log-analyticsapplication-insights-workspace-to-azure-data-explorer-client-tools) docs say to use `https://adx.monitor.azure.com/` but the address doesn't seem to work. I end up with `Failed to connect to cluster. Please verify the URI` error. The correct hostname seems to be `https://ade.loganalytics.io/` instead. Is this a bug or documentation issue? Happy to submit PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6c8fe3-d9a3-f11b-cfe7-f0f67f44b0d5
* Version Independent ID: 418e6ed4-24b4-689b-50fc-490441dc393c
* Content: [Query data in Azure Monitor with Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/query-monitor-data)
* Content Source: [data-explorer/query-monitor-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/query-monitor-data.md)
* Service: **data-explorer**
* GitHub Login: @osalzberg
* Microsoft Alias: **orspodek**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @hajekj , thank you for the detailed question. We are currently investigating and will update you when we have accurate information to provide.

**Comment by osalzberg** [comment]
Hi @hajekj , there was an issue with one of my clusters. I am investigating it. at the meanwhile, I have updated the docs to a woking endpoint.

thanks

**Comment by YaelSchuster** [comment]
#please-close
