### ISSUE TITLE
Bug in 50M data query

### ISSUE THREAD

**Issue by e4ch** [MicrosoftDocs/dataexplorer-docs#931]
The sample query "50M data query" in that article seems to have a bug:
* The first line "EventType = rand(3)" creates a random integer between 0...2
* The "extend EventType=case(EventType..." indicates that it wants to convert these three numbers into letters A, B, C. This does not work; only letters A and B are generated.
The reason is that the numbers are integers, not float. So "EventType <= 1" matches both numbers 0 and 1. And the character 'C' is never matched.

For the rest of the query or the example, this doesn‘t matter, as 'C' is never used, but it screws up the probabilities of the expected result.

Second bug/problem:
With the example given, I would expect the following number of results (Count):
50m * 2/3 * 60*100 / 10m * 1/3 = 6667
* 50m numbers to start with
* 2/3 probability of an 'A'
* 60*100 number of samples within one minute
* 1/10m probability of matching SessionId
* 1/3 probability of 'B'

This gives an expected Count of 6667 on an average run. Running the query confirms that and I get indeed numbers in that range.
But the page says 'Count=1276' for your sample run. Even if the results are random, to have such a low number sounds unbelievable. That number is probably the result of an earlier version or something. So please also update that number to a realistic one. Preferably after you fix the code bug mentioned above.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99176c38-a637-d4d8-fe78-70463e6a689f
* Version Independent ID: 7b0d0207-0859-ab2e-8f5a-09f2a8fc84c7
* Content: [Joining within time window - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/join-timewindow)
* Content Source: [data-explorer/kusto/query/join-timewindow.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/join-timewindow.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by shsagir** [comment]
@e4ch Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
