### ISSUE TITLE
Wrap kql code into a python function

### ISSUE THREAD

**Issue by slowlyswimming** [MicrosoftDocs/dataexplorer-docs#938]
Hi,

Is it possible to wrap a piece of kql code into a python function in a notebook cell? Like this:

def func(a):
    %%kql
    let _a = a;
    DB
    | where cname == _a
    
    df = _kql_raw_result_.to_dataframe()
    return df

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f497838f-e309-f36a-43af-6d58b5e6b1e9
* Version Independent ID: 0cf67eee-4f79-9b23-7ec7-2ed347d68cb4
* Content: [Use a Jupyter Notebook to analyze data in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kqlmagic)
* Content Source: [data-explorer/kqlmagic.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kqlmagic.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@slowlyswimming Thank you for sharing your feedback. We are actively validating it. We will share updates soon.

**Comment by ShaikMaheer-MSFT** [comment]
@slowlyswimming As explained in below link. Using Python variables in your KQL Query is possible.
https://docs.microsoft.com/en-us/azure/data-explorer/kqlmagic#use-a-python-variable-in-your-kql-query

Converting Query results to Pandas data frame is also possible.
https://docs.microsoft.com/en-us/azure/data-explorer/kqlmagic#convert-query-results-to-pandas-dataframe

So, its feasible i feel. Are you facing any issue or error while trying same? If yes, I would encourage to raise issue on [Microsoft Q&A Portal](https://docs.microsoft.com/en-us/answers/index.html).

Please Note, GitHub forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilize Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html)

**Comment by shsagir** [comment]
@ShaikMaheer-MSFT Thanks for responding to the question.

#please-close
