### ISSUE TITLE
ChunkedEncodingError: Connection broken

### ISSUE THREAD

**Issue by slowlyswimming** [MicrosoftDocs/dataexplorer-docs#939]
Hi,

When I query by using %%kql code, I have the following error message:

ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

But when I limit the results in few rows,e.g., 
| limit 2

The execution of code is success. 

Is this error caused by Kusto side restriction? Anything that I can do in my notebook?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f497838f-e309-f36a-43af-6d58b5e6b1e9
* Version Independent ID: 0cf67eee-4f79-9b23-7ec7-2ed347d68cb4
* Content: [Use a Jupyter Notebook to analyze data in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kqlmagic)
* Content Source: [data-explorer/kqlmagic.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kqlmagic.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@slowlyswimming Thanks for the question. Github forum is dedicated for docs related issues. For any technical queries or clarifications, we encourage to utilise Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html)

**Comment by slowlyswimming** [comment]
Thanks @ShaikMaheer-MSFT for sharing me the correct place. I will close this ask and post there.
