### ISSUE TITLE
How to apply a "what-if" parameter in the advanced query editor for a query copied in from kusto?

### ISSUE THREAD

**Issue by hasridha** [MicrosoftDocs/dataexplorer-docs#94]
So I added a what-if parameter("Last N Days") from the ribbon and it gave me a slider that I can happily drag between 1 and 30 (for number of days ago to use in the query). Problem is - I don't know how to connect the user-supplied value from this slider into the Kusto query I am using for a funnel chart on the side. Using  this in the query - & #"Last N Days" & - doesn't work because the advanced query editor doesn't recognize the what-if parameter as it would a vanilla parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec5fb9d-8962-7e64-2768-b04b498f2db4
* Version Independent ID: f82bc4a7-476c-20e6-71cb-5406a3577a74
* Content: [Best practices for using Power BI to query and visualize Azure Data Explorer data](https://docs.microsoft.com/en-us/azure/data-explorer/power-bi-best-practices#best-practices-for-using-power-bi)
* Content Source: [data-explorer/power-bi-best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/power-bi-best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@hasridha  Thanks for the question! We are investigating and will update you shortly.

**Comment by orspod** [comment]
@Gabilehner can you assist with this question?

**Comment by orspod** [comment]
@Gabilehner can you assist with this question?

**Comment by saguiitay** [comment]
You currently can't use WhatIf parameters in the Power Query Editor, as you've found out.
We are working on improving these kind of scenarios with the PBI team, but don't have anything to share yet.

Depending on what you are trying to do, you might be able to just use a filter on a column of your dataset.

**Comment by orspod** [comment]
@saguiitay - thanks for the answer
@hasridha hope this answered your question. Please let us know if you have additional questions

**Comment by orspod** [comment]
@hasridha I am closing this issue. If you have additional questions feel free to comment.
