### ISSUE TITLE
Add a link to the case statement

### ISSUE THREAD

**Issue by garybusheyWork** [MicrosoftDocs/dataexplorer-docs#940]
This page should have a link to the case statement under the Recommended Content as that is the next logical step if you have multiple iif statements.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5887c53-5505-7e1b-4592-c1d74d405c23
* Version Independent ID: c7a8a32a-7906-b341-f88a-b552d39ac8df
* Content: [iif() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/iiffunction)
* Content Source: [data-explorer/kusto/query/iiffunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/iiffunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@garybusheyWork Thank you for sharing feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@ShaikMaheer-MSFT Thanks for the suggestion. The recommended content is autogenerated by the build system and, as such, cannot be updated manually.

#please-close
