### ISSUE TITLE
Microsoft Azure  Data kemas kini

### ISSUE THREAD

**Issue by Ashikin8888ckin** [MicrosoftDocs/dataexplorer-docs#942]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ccc4c6-423a-bab8-e5b9-6c05c75a6773
* Version Independent ID: 0be88948-94c9-3d05-0032-5bb0de9ae8f8
* Content: [.show workload group command - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/show-workload-group-command)
* Content Source: [data-explorer/kusto/management/show-workload-group-command.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/show-workload-group-command.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by shsagir** [comment]
@Ashikin8888ckin Please can you provide a little more detail on the issue you raised, @mention me, and then reopen it. Thanks.
No information is provided, so closing the issue for now.

#please-close
