### ISSUE TITLE
KQL 'has_any' operator does not capture all values

### ISSUE THREAD

**Issue by nischai-vinesh** [MicrosoftDocs/dataexplorer-docs#947]
Hi,
I am trying to match a set a keywords for filtering purposes and it seems that "contains" and "has_any" operators work differently. My assumption was "contains" is used to search for a single value and has_any / has_all can be used to check if multiple keywords are present in the data values. To explain this, I creates a dataset and filter queries as below:

"Contians" returns **8 records**:

<img width="595" alt="MS bug - contains" src="https://user-images.githubusercontent.com/92090121/146004316-4d87d7aa-e987-40f4-a11c-2b1a57861576.png">

"has_any" (and has_all) returns only **5 records**:

<img width="571" alt="MS bug - has_any" src="https://user-images.githubusercontent.com/92090121/146004345-8fad1e31-ef25-48f8-93ad-7b0c9c1e48ae.png">

And "in" operator returns **zero** records. I guess "in" looks for exact matches with the keywords
<img width="566" alt="MS bug - in" src="https://user-images.githubusercontent.com/92090121/146004365-dadf33bf-c523-4f5b-b7f5-46854b36a8f1.png">

I would expect "contains" and "has_any" returns same result if there are only one keyword / filter criteria. Or at least "has_any" captures all instances of the keywords from the data.

**Comment by SatishBoddu-MSFT** [comment]
Hello [@nischai-vinesh](https://github.com/nischai-vinesh)

Our SME will review your feedback soon.

**Comment by slavikn84** [comment]
Hi,

`contains` and `has` operators indeed work differently. While `contains` matches substrings in a string, `has` matches full [terms](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatypes-string-operators#what-is-a-term) in a string.

So:
* `"ManagerGeneral" contains "General"` will return `true`
* `"ManagerGeneral" has "General"` will return `false`
* `"Manager-General" has "General"` will return `true`

Regards,
Slavik

**Comment by nischai-vinesh** [comment]
Hi @slavikn84,

Thanks for the reply and understands the logic of "has" now. But is there a way to filter data/strings based on multiple keywords, need not be "terms"? I know I can use multiple "contains" along with "or/and" operators. I am looking for a solution where I can define a set of keywords into a list and use it in the code. If required in future, change only that list rather than changing the conditions in the code every time.

Kind regards
Nischai

**Comment by slavikn84** [comment]
Because `contains` looks for any substring, it doesn't take advantage of the bloomfilters, so it's much slower than `has`. That's why we implemented `has_any` and `has_all`, but didn't implement `contains_any` and `contains_all`. To do multiple lookups with `contains` you have no choice but to write something like `(Col1 contains "xx") or (Col1 contains "yy") or (Col1 contains "zz")`. But as I wrote, it's much more optimal to look for whole terms, if your data allows this.

**Comment by shsagir** [comment]
@slavikn84 Thanks for responding
@nischai-vinesh Thanks for your question. I believe your query has been answered and am closing this issue.

To follow up on this issue, please check if the answer is on the [Azure Data Explorer Q & A](https://docs.microsoft.com/en-us/answers/topics/azure-data-explorer.html) or ask a question there.

@please-close

**Comment by williamtwar** [comment]
Thanks for sharing the workaround (contains "xx")
The bloomfilters allow the SOC team to check if the file's name is a legitimate remote admin tool.
If it is, then the SOC team will proceed to send the email to user for removing the remote admin tool file.
