### ISSUE TITLE
Operation state missing "Throttled" as a valid option

### ISSUE THREAD

**Issue by abenisek** [MicrosoftDocs/dataexplorer-docs#950]
![image](https://user-images.githubusercontent.com/32983397/146239970-a11f28d8-6a14-4a92-b6d7-b6fa6eba76c7.png)

Documentation states that azure data explorer can only have 3 states, however, I see a 4th state of "Throttled" when running ".show commands-and-queries."

![image](https://user-images.githubusercontent.com/32983397/146240528-fd6f9005-a9b5-46b9-8b2b-e5e5d8de498a.png)

Can this documentation be updated to reflect the "Throttled" state with details on best practices to handle this state. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab27c89-ec79-23c7-f216-7364944ed1fd
* Version Independent ID: d72d702a-2f62-2e89-7b44-c0ec64bb926a
* Content: [Operations management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/operations)
* Content Source: [data-explorer/kusto/management/operations.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/operations.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by shsagir** [comment]
@abenisek Thanks for your feedback. We've submitted a documentation change based on your suggestion, and updated the article. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
