### ISSUE TITLE
Would be nice to have examples on how to do this using azure-cli

### ISSUE THREAD

**Issue by jumacabo** [MicrosoftDocs/dataexplorer-docs#951]
Azure cli is one of the prefered tools for many people for provisioning and configuring azure resources.

Would be great to have some example on how to do it with "az cli" too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0641250b-48bc-c32c-2c87-51fdc8bfd6d7
* Version Independent ID: 9a7e16a5-b138-dcb1-6fed-aedeb683a0bd
* Content: [Configure managed identities for your Azure Data Explorer cluster](https://docs.microsoft.com/en-us/azure/data-explorer/configure-managed-identities-cluster?tabs=portal)
* Content Source: [data-explorer/configure-managed-identities-cluster.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/configure-managed-identities-cluster.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by ShaikMaheer-MSFT** [comment]
@jumacabo Thank you for sharing your valuable feedback. We are actively validating it. We will share updates soon.

**Comment by shsagir** [comment]
@jumacabo Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by ShaikMaheer-MSFT** [comment]
@orspod Customer is looking for adding CLI details also in the doc to work with identities for your Azure data explorer cluster. Could you please validate feedback and enhance document as appropriate. Thank you.

**Comment by shsagir** [comment]
@jumacabo Thanks for your feedback. We’ll be submitting a documentation change based on your suggestion, though it may take a little while as people are on vacation. When the change is ready, we'll add the pull request to this issue, but in the meantime, we're closing the issue. Please let us know if there’s anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
