### ISSUE TITLE
Mention that Path property in JSON ingestion mappings uses JSONPath format

### ISSUE THREAD

**Issue by astafan8** [MicrosoftDocs/dataexplorer-docs#953]
It would be great if for JSON mapping definition, for the Path property specifically, it would be stated explicitly that the format of that is JSONPath (https://restfulapi.net/json-jsonpath/). I could not bing/google this fact online, hence had to do a little investigation. Thankfully the one-click json ingestion doc page https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language#ingest-json-records-containing-dictionaries comes with an interesting example of a mapping where `?(` query is used: ``"path":"$.event[?(@.Key == \'timestamp\')].Value"``. Thanks to that I learned that JSONPath exists and it's likely that the json mappings in ADX are using it. I think other documentation readers who are not familiar with JSONPath, would be very grateful to be able to learn about this from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c88dc391-7ece-09d6-64c7-20a5b9879f74
* Version Independent ID: 383769d2-9c23-9ec9-1575-d1541fef941a
* Content: [Data mappings - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings)
* Content Source: [data-explorer/kusto/management/mappings.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/management/mappings.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SatishBoddu-MSFT** [comment]
[@astafan8](https://github.com/astafan8)
I have assigned the issue to the content author for further review.

**Comment by sigorbor** [comment]
@astafan8 ADX indeed uses a JsonPath notation (JsonPath doesn't have an official RFC, BTW), but only a subset is supported. Currently, we don't implement wildcards/recursion/union/slices/current node/script expressions. Our documentation on that definitely needs improvement, thanks for pointing this issue out!

**Comment by astafan8** [comment]
@sigorbor thank you for the response and these details! i'll be looking forward to adding even your response to the docs :)

**Comment by sigorbor** [comment]
@astafan8 we added JSONPath documentation to the docs

https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language#ingest-json-records-containing-dictionaries
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/jsonpath

Thanks again for letting us know

**Comment by astafan8** [comment]
@sigorbor this is great! thank you so much!

the only little detail: the example in https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language#ingest-json-records-containing-dictionaries uses ``"$.event[?(@.Key == \'timestamp\')].Value"`` while it is not specified in the table here https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/jsonpath, but perhaps it's just me not realizing what category of queries ("Wildcards, recursion, union, slices and current object are not supported") the `?(..)` together with `@.` belongs to?

**Comment by shsagir** [comment]
@astafan8 Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
