### ISSUE TITLE
Add "Errors and Exceptions" page for Kusto.Data .NET SDK

### ISSUE THREAD

**Issue by gholliday** [MicrosoftDocs/dataexplorer-docs#956]
There is a [Errors and Exceptions](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/kusto-ingest-client-errors) page for the `Kusto.Ingest` SDK. Would it be possible to create a similar page relating to the `Kusto.Data` SDK?

For example, it would be useful to know that `KustoRequestThrottledException` is the exception type that a client will hit when their requests are throttled so that they can add an appropriate backoff policy.

Also, that exceptions with `KustoException.IsPermanent = true` should not be retried.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b0560f-8a4c-c829-7307-c18a7710f0fc
* Version Independent ID: 61dcd20a-7a61-88af-ca40-e9922fbb86a1
* Content: [Kusto client library - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/about-kusto-data)
* Content Source: [data-explorer/kusto/api/netfx/about-kusto-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/api/netfx/about-kusto-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SatishBoddu-MSFT** [comment]
[@gholliday](https://github.com/gholliday)
I have assigned the issue to the content author for further review.

**Comment by shsagir** [comment]
@gholliday Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@gholliday Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close
