### ISSUE TITLE
sc vs cs

### ISSUE THREAD

**Issue by iwafula025** [MicrosoftDocs/dataexplorer-docs#979]
is the sc here supposed to be cs ?
String matching extensions: String literals that appear as terms in the SearchPredicate indicate a term match between all columns and the literal using has, hasprefix, hassuffix, and the inverted (!) or case-sensitive **(sc)** versions of these operators. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b54882e-831a-64d3-a2e1-9dc8f689ff53
* Version Independent ID: 755ac9e9-796c-bf0c-6f29-c8810cbeca98
* Content: [search operator - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/searchoperator)
* Content Source: [data-explorer/kusto/query/searchoperator.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/searchoperator.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SnehaAgrawal-MSFT** [comment]
@iwafula025 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
Thanks for pointing out the issue, I've addressed this issue in PR: [https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2691](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2691) 
The changes should be live soon. In future, if you see any minor bug fixes in the doc, feel free to click on the edit button and submit a PR to update. we love to take community contributions.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@iwafula025 Now the changes are live.

![image](https://user-images.githubusercontent.com/79183421/149085875-8885c5b1-e880-4337-9b87-0c29273e2354.png)

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
