### ISSUE TITLE
Azure Data Explorer format_datetime() Day Partitioning Bug

### ISSUE THREAD

**Issue by kosylon** [MicrosoftDocs/dataexplorer-docs#98]
We are trying to partition an external table (ADLS Gen2 blog storage) to be viewable in Azure Data Explorer using `partition by format_datetime="'Day='d"`. Performing a partition with the 'd' format element only returns data for single-digit partitions (Day=1 to Day=9). The documentation clearly states it should handle days 1-31. Alternatively partitioning with the 'dd' format element only returns double-digit dates (Day=10+), since our single-digit date partitions do not lead with '0'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e39113-7646-84ba-4e88-a35ccec723be
* Version Independent ID: e14b969a-3c1a-edfc-77b3-617ff008dc83
* Content: [format_datetime() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/format-datetimefunction#supported-formats)
* Content Source: [data-explorer/kusto/query/format-datetimefunction.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/kusto/query/format-datetimefunction.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@kosylon  Thanks for bringing this to our attention. Your feedback  has been shared with the content owner for further review.

**Comment by orspod** [comment]
@yifatsor and @spektom can you assist with this question?

**Comment by spektom** [comment]
Hi @kosylon !

This is bug, and it will be fixed in the next release.
Thank you for reporting!

Sincerely,
Michael

**Comment by orspod** [comment]
@kosylon - thanks for your feedback. @spektom thanks for investigating and fixing the product bug.
Closing this issue.

**Comment by kosylon** [comment]
@spektom - Thank you for the reply. Where can I be notified about Data Explorer releases? And when do you anticipate this bug will be fixed? We are using this service to expose data to partners and will need to perform an interim workaround depending on the timeline.

-Nathan

**Comment by spektom** [comment]
@kosylon it usually takes less than two weeks to rollout a fix. I'll notify you on email when the fix is out.
