### ISSUE TITLE
parse_ipv6 example query incorrect (copy-paste typo from parse_ipv4_mask)

### ISSUE THREAD

**Issue by helderpinto** [MicrosoftDocs/dataexplorer-docs#983]
The example query for the `parse_ipv6` function is unrelated with the function as it is using content that should have been used in the `parse_ipv4_mask` function example. This seems a copy-paste typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081657b6-f5c0-42c4-d360-8fb00887fa61
* Version Independent ID: ecf247ab-0c30-8774-df2e-1854ddb7dd5b
* Content: [parse_ipv6() - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-ipv6function)
* Content Source: [data-explorer/kusto/query/parse-ipv6function.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/parse-ipv6function.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by shsagir** [comment]
@helderpinto Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
