### ISSUE TITLE
Best practices regarding the usage of the `in` operator against the `join` operator?

### ISSUE THREAD

**Issue by 0xThiebaut** [MicrosoftDocs/dataexplorer-docs#985]
Would it be possible to provide best practices regarding the usage of the `in` operator against the `join kind=leftsemi` operator when the outer table is large with a single column?

#### Using the `join` operator.
```kusto
let SHA256s = externaldata (SHA256: string)[
    '...'
    ] with (format='txt');
EmailAttachmentInfo 
| join kind=leftsemi hint.strategy=shuffle hint.shufflekey=SHA256 SHA256s on SHA256
```

#### Using the `in` operator.
```kusto
let SHA256s = externaldata (SHA256: string)[
    '...'
    ] with (format='txt');
EmailAttachmentInfo 
| where SHA256 in (SHA256s)
```

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8936d746-8ea8-a5ac-a565-f50befdeb15e
* Version Independent ID: 412e3ef5-53ca-56eb-d3cd-1fb1088132e9
* Content: [Query best practices  - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/best-practices)
* Content Source: [data-explorer/kusto/query/best-practices.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/best-practices.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@0xThiebaut  Thanks for the feedback! I have assigned the issue to the content author to evaluate and add the above details.

**Comment by shsagir** [comment]
@0xThiebaut Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@name Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
