### ISSUE TITLE
Security role called monitors is not explained

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/dataexplorer-docs#989]
The table for Security Roles covers all roles but `monitors`:

|*Role*      |Description|
|------------|-----------|
| admins |Have control over the securable object, including the ability to view, modify it, and remove the object and all sub-objects.|
| users | Can view the securable object, and create new objects underneath it.|
| viewers |Can view the securable object.|
| unrestrictedviewers |At the database level only, allows viewing of restricted tables (which are not exposed to "normal" `viewers` and `users`).|
| ingestors |At the database level only, allow data ingestion into all tables.|
| **monitors** |  **???** |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4526aa53-827b-abf4-d419-cea51c79c71b
* Version Independent ID: 73682729-2e9a-216f-5fb5-8e887ef93df2
* Content: [Security roles management - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/security-roles)
* Content Source: [data-explorer/kusto/management/security-roles.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/management/security-roles.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for bringing this to our attention.  We will let you know when we have more information.

**Comment by shsagir** [comment]
@abatishchev Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@abatishchev Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
