### ISSUE TITLE
Screenshots are out of data for Manage language extensions

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/dataexplorer-docs#990]
Current blade in the Azure Portal looks like differently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb051ac3-09cc-a84b-cd03-68e0a7ba6f72
* Version Independent ID: 23d8320d-3e59-14c7-de2f-433b85b32129
* Content: [Manage language extensions in your Azure Data Explorer cluster.](https://docs.microsoft.com/en-us/azure/data-explorer/language-extensions)
* Content Source: [data-explorer/language-extensions.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/language-extensions.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for bringing this to our attention.  We will let you know when we have more information.

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by shsagir** [comment]
@abatishchev Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close

**Comment by abatishchev** [comment]
Please close issue after it has been addressed, not before.

#please-open #pleaese-reopen

**Comment by shsagir** [comment]
@abatishchev You can track the progress on this in the WI I sent you in Teams. In the meantime, I'm closing this issue. Tx

#please-close
