### ISSUE TITLE
Examples has reference to wrong plugin

### ISSUE THREAD

**Issue by SudheeshGH** [MicrosoftDocs/dataexplorer-docs#992]
Page is for mysql_request but the examples has sql_request referred. 

evaluate **sql_request(**
    'Server=contoso.mysql.database.azure.com; Port = 3306;'
    'Database=Fabrikam;'
    h'UID=USERNAME;'
    h'Pwd=PASSWORD;', 
  'select * from [dbo].[Table]')
| where Id > 0
| project Name

evaluate **sql_request(**
   'Server=contoso.mysql.database.azure.com; Port = 3306;'
    'Database=Fabrikam;'
    h'UID=USERNAME;'
    h'Pwd=PASSWORD;', 
  'select * from [dbo].[Table]')
| where Id > 0
| project Name
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29012c32-2298-5f5a-aa99-92bc8526a2ed
* Version Independent ID: a3cd1b63-eba2-fd0b-f434-5df88d9c074b
* Content: [mysql_request plugin - Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/mysqlrequest-plugin?pivots=azuredataexplorer)
* Content Source: [data-explorer/kusto/query/mysqlrequest-plugin.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/query/mysqlrequest-plugin.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by vipulsparsh** [comment]
@SudheeshGH Thanks for reaching out. We will investigate and update the thread accordingly.

**Comment by shsagir** [comment]
@SudheeshGH Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close

**Comment by SudheeshGH** [comment]
@shsagir  Thank you. There were also few other reference of SQLDB instead of  MySQLDB in few places on same page , Hope that also will be addressed.
"The following example sends a SQL query to an Azure SQL DB database retrieving all records from "
"SQL authentication with username and password" : I think it is Passport Authentication.
