### ISSUE TITLE
Missing more detailed information about .clear table data command

### ISSUE THREAD

**Issue by dariuszdbr** [MicrosoftDocs/dataexplorer-docs#994]
Hi, based on documentation [here](https://docs.microsoft.com/en-us/azure/data-explorer/delete-data), Azure Data Explorer offers different ways of deleting data. It is described that we can:

1. Delete data using the retention policy
2. Delete data by dropping extents
3. Delete individual rows with [.purge](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/data-purge) or [.soft-delete](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/data-soft-delete)

Information about `.clear table data` is not present, so I wonder how it differs from the above options. [Documentation](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/clear-table-data-command) about that command says only:
> Clears the data of an existing table, including streaming ingestion data.

Can you clarify how it works, how it differs from other options, what are the use cases, is the deletion immediately, and what might be the performance impact over the table that is queried frequently and when the data in that table is cleared and re-ingested also frequently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6dc9cc9-7277-b802-798b-4267d800548f
* Version Independent ID: 82cd5f5b-5513-a955-5428-c949ffbda211
* Content: [Delete data from Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/delete-data)
* Content Source: [data-explorer/delete-data.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/delete-data.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by BryanTrach-MSFT** [comment]
@dariuszdbr Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by himanshusinha-msft** [comment]
We have assigned the issue to the content author . They will evaluate & update the document as appropriate

**Comment by shsagir** [comment]
@BryanTrach-MSFT Thanks so much for taking the time to leave us your comment on our documentation. We're working on an [update ](https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/2718) for the page based on your suggestions which will be published as soon as possible.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

#please-close

**Comment by shsagir** [comment]
@BryanTrach-MSFT Thanks again for your feedback. We've updated the topic based on your feedback.
