### ISSUE TITLE
ARM template does not pass validation

### ISSUE THREAD

**Issue by lmjeremias** [MicrosoftDocs/dataexplorer-docs#999]
I have tried to use the ARM template to create a Kusto cluster, but it doesn't deploy:

Failed to start deployment to resource group 'lujeremi-rg'.
Additional details from the underlying API that might be helpful: Code: 'templateLinkAndJson'. 
Parameters: MyGalleryItem,,. 

(I have removed VNET and Keyvault parameters)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9c4d32-fdd8-6ce4-4237-fb0f34b56c7f
* Version Independent ID: d2045be8-bc75-aeef-249d-2b95d73e4841
* Content: [Create an Azure Data Explorer cluster and database by using an Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-resource-manager#azure-resource-manager-template-for-cluster-and-database-creation)
* Content Source: [data-explorer/create-cluster-database-resource-manager.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/create-cluster-database-resource-manager.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by MartinJaffer-MSFT** [comment]
This appears to be a request for troubleshooting, not a documentation issue.  For assistance, please post your question in [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/).




[@lmjeremias](https://github.com/lmjeremias)
